### ISSUE TITLE
Update check fails

### ISSUE THREAD

**Issue by ovizii** [goauthentik/authentik#10013]
**Describe the bug**
Running a self-hosted version for my local needs and when I noticed your blog entry talking about the newest 2024.4 version I wondered why I wasn't getting notified about the update by my setup as it used to do.

I notice `Temporary failure in name resolution` in the error log, so I thought I'd enter the container with `docker exec -ti ` but it seems there's no ping, curl or wget command present in the container, so I am unsure how to check what is wrong. 

**To Reproduce**

1. Go to admin interface => dashboards check version
![image](https://github.com/goauthentik/authentik/assets/837902/01cdf330-5c8a-4218-9efe-8f78a08ff51e)
2. Go to System Tasks 
![image](https://github.com/goauthentik/authentik/assets/837902/263e764c-fb44-4e5f-
8477-9c62dad34b2c)

**Expected behavior**
I expect authentik to successfully check for new versions.

**Logs**
`Traceback (most recent call last): File "/authentik/admin/tasks.py", line 62, in update_latest_version response = get_http_session().get( ^^^^^^^^^^^^^^^^^^^^^^^ File "/ak-root/venv/lib/python3.12/site-packages/requests/sessions.py", line 602, in get return self.request("GET", url, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/ak-root/venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/ak-root/venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send r = adapter.send(request, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/ak-root/venv/lib/python3.12/site-packages/requests/adapters.py", line 519, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPSConnectionPool(host='version.goauthentik.io', port=443): Max retries exceeded with url: /version.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7e48a1961700>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))`

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.2.3
-   Deployment: docker-compose

**Comment by ovizii** [comment]
Hm, should I have reported this here: https://github.com/goauthentik/version/issues instead?

**Comment by ovizii** [comment]
I'm asking just out of curiosity: what is not planned?
