### ISSUE TITLE
Notification-transport error

### ISSUE THREAD

**Issue by szinn** [goauthentik/authentik#10257]
**Describe the bug**
Getting notification-transport error

**To Reproduce**
No actual steps

**Expected behavior**
System task should run successfully

**Screenshots**

**Logs**
```
Traceback (most recent call last): File "/authentik/events/tasks.py", line 120, in notification_transport transport.send(notification) File "/authentik/events/models.py", line 357, in send return self.send_email(notification) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/authentik/events/models.py", line 512, in send_email raise NotificationTransportError(exc) from exc authentik.events.models.NotificationTransportError: [Errno 111] Connection refused
```
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.6.0
-   Deployment: helm

**Additional context**

**Comment by szinn** [comment]
That system task seems to have been removed and all system tasks are now happy
