### ISSUE TITLE
Can't send emails with SMTP - Getting Authentication Failed

### ISSUE THREAD

**Issue by EmilianoEscobedo** [goauthentik/authentik#10342]
**Describe the bug**
Can't send emails with SMTP using zoho as mail provider, with Authentik deployed in docker-compose. I'm using SSL port 465. Getting Authentication Failed. 

**To Reproduce**
1. Use the environment variables to configure SMTP as documentation says.
2. Complete those environment variables in .env file.
3. Try to send a mail with ak test_mail, executing docker compose exec authentik-worker ak test_email <my_mail>

**Expected behavior**
Test mail sent.

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/83373185/f1a928aa-fb85-43f5-b0a2-8b6234c34a43)
![image](https://github.com/goauthentik/authentik/assets/83373185/0cbe34fb-13cc-429e-be72-09001f4fce5b)

**Logs**
![image](https://github.com/goauthentik/authentik/assets/83373185/8b2c16d4-3c15-4a3e-802b-b32998706589)

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.6.0
-   Deployment: docker-compose

**Additional context**

This instance of Authentik is hosted in a VM of a cloud provider and its restricted in port 80/443 to be only accessible thru a VPN.

Tried from an external online SMTP tester and is working as expected with the exact same server, port, and credentials.

![image](https://github.com/goauthentik/authentik/assets/83373185/8449e5a9-fd1a-475a-a2bd-7fbdec175fe7)

**Comment by EmilianoEscobedo** [comment]
Hey all, I just downgraded to 2024.4.0 and everything is working as expected, so this seems to be a bug in this last release.

**Comment by flece** [comment]
same Version and deploymentmethod for me and i got this errormessage for testing E-Mail

ak-root/venv/lib/python3.12/site-packages/django/core/mail/backends/smtp.py", line 95, in open self.connection.login(self.username, self.password)
    File "/usr/local/lib/python3.12/smtplib.py", line 739, in login
        (code, resp) = self.auth(
                           ^^^^^^^^^^
                             File "/usr/local/lib/python3.12/smtplib.py", line 641, in auth
                               response = encode_base64(initial_response.encode('ascii'), eol='')
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                            builtins.UnicodeEncodeError: 'ascii' codec can't encode characters in position 21-22: ordinal not in range(128)"

**Comment by pXius** [comment]
Same issue, works on server, worker errors out.

```shell
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/manage.py", line 52, in <module>
    execute_from_command_line(sys.argv)
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/tenants/management/__init__.py", line 38, in handle
    self.handle_per_tenant(*args, **options)
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/email/management/commands/test_email.py", line 38, in handle_per_tenant
    send_mail(message.__dict__, stage.pk)
  File "/ak-root/venv/lib/python3.12/site-packages/celery/local.py", line 182, in __call__
    return self._get_current_object()(*a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/celery/app/task.py", line 411, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/celery/app/autoretry.py", line 60, in run
    ret = task.retry(exc=exc, **retry_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/celery/app/task.py", line 720, in retry
    raise_with_context(exc or Retry('Task can be retried', None))
  File "/ak-root/venv/lib/python3.12/site-packages/celery/app/autoretry.py", line 38, in run
    return task._orig_run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/email/tasks.py", line 105, in send_mail
    raise exc
  File "/authentik/stages/email/tasks.py", line 73, in send_mail
    backend.open()
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/mail/backends/smtp.py", line 86, in open
    self.connection = self.connection_class(
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 1022, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout,
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 1028, in _get_socket
    new_socket = super()._get_socket(host, port, timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/sentry_sdk/integrations/socket.py", line 63, in create_connection
    return real_create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 852, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 837, in create_connection
    sock.connect(sa)
TimeoutError: timed out
```

**Comment by BeryJu** [comment]
@flece could it be that in your .env file, the password entry has an invisible unicode character in it?

could both of you run dump_config to ensure authentik reads the .env file correctly? https://docs.goauthentik.io/docs/installation/configuration#verify-your-configuration-settings

**Comment by flece** [comment]
@BeryJu 

i have the characters "ü" and "ß" in my password
if i dump the config it is represented as: "\u00fc" and "\u00df"

if i change to a password without this characters it worked.

**Comment by nicoduck** [comment]
Hi,

anything new? Complex passwords cause issues with some characters, is there another way to save them to config without the scripts breaking?

**Comment by nicoduck** [comment]
Ignoring issues doesn't fix them.
What are you even expecting from stale-bot besides pissing off the community?
