### ISSUE TITLE
IP Address not filled in during login to authentik_policies_reputation_reputation table

### ISSUE THREAD

**Issue by dgaiero** [goauthentik/authentik#10666]
**Describe the bug**
When I try to login to authentik, I get an exception that the IP column in the table `authentik_policies_reputation_reputation` must be not null. I manually set this table to allow NULL for now and that is a work-around, but when I look at the admin dashboard,I do see that logins do not have an IP address associated with it.

**To Reproduce**
Attempt to login to Authentik

**Expected behavior**
IP address to be added to the `authentik_policies_reputation_reputation` table

**Screenshots**

**Logs**
<details>
    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
  File "/authentik/flows/views/executor.py", line 290, in get
    stage_response = self.current_stage_view.dispatch(request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/user_login/stage.py", line 59, in dispatch
    return self.do_login(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/user_login/stage.py", line 102, in do_login
    login(
  File "/ak-root/venv/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 152, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "/ak-root/venv/lib/python3.12/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/policies/reputation/signals.py", line 58, in handle_successful_login
    update_score(request, user.username, 1)
  File "/authentik/policies/reputation/signals.py", line 25, in update_score
    reputation, created = Reputation.objects.select_for_update().get_or_create(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/query.py", line 955, in get_or_create
    return self.create(**params), True
           ^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/base.py", line 1071, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/base.py", line 1112, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
django.db.utils.IntegrityError: null value in column "ip" of relation "authentik_policies_reputation_reputation" violates not-null constraint
DETAIL:  Failing row contains (dbea4d63-a950-4427-8d5d-b2b015240d63, jbob, null, {}, 1, 2024-07-28 18:28:21.399182+00, 2024-07-29 18:28:21.397072+00, t, {}).
```
</details>

**Version and Deployment (please complete the following information):**
- authentik version: 2024.6.1
- Deployment: docker-compose

**Additional context**

**Comment by aaw3** [comment]
I am also getting this error. I just added the traefik-real-ip plugin and noticed in my requests that on the local network the real IP will resolve to "" resulting in the null error and now I also get the same issue.

**Comment by BeryJu** [comment]
2024.8.3 should fix this error (and return a placeholder), however the root cause is that the x-forwarded-for header from your reverse proxy is empty
