### ISSUE TITLE
Kubernetes Helm deployment gives "PermissionError: [Errno 13] Permission denied: '/media/public'"

### ISSUE THREAD

**Issue by crazyelectron-io** [goauthentik/authentik#11041]
**Describe the bug**
Installed Authentik on a 6-node Kubernetes cluster (1.30.1) and specified a media volume in the Helm values file:
```yaml
## authentik worker
worker:
  # -- authentik worker name
  name: authworker
  # -- The number of worker pods to run
  replicas: 1
  # -- Additional volumeMounts to the authentik worker main container
  volumeMounts:
    - name: authentik-media
      mountPath: /media
  volumes:
    - name: authentik-media
      persistentVolumeClaim:
        claimName: authentik-media
```
The PVC is created as:
```yaml
      kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: authentik-media
        namespace: "{{authentik_namespace}}"
      spec:
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 200Mi
```
The `authentik-atuhworker` pod goes into `CrashLoopBackoff` with:
```shell
"event": "Not running as root, disabling permission fixes", "level": "info", "logger": "bootstrap"}
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1724403227.57191, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1724403227.5723202, "count": 48}
{"event": "Starting authentik bootstrap", "level": "info", "logger": "authentik.lib.config", "timestamp": 1724403227.7518}
{"event": "PostgreSQL connection successful", "level": "info", "logger": "authentik.lib.config", "timestamp": 1724403227.7716477}
{"event": "Redis Connection successful", "level": "info", "logger": "authentik.lib.config", "timestamp": 1724403227.7756853}
{"event": "Finished authentik bootstrap", "level": "info", "logger": "authentik.lib.config", "timestamp": 1724403227.7757645}
2024-08-23 08:53:47 [info     ] waiting to acquire database lock
2024-08-23 08:53:47 [info     ] Migration needs to be applied  migration=tenant_files.py
2024-08-23 08:53:47 [info     ] releasing database lock
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/manage.py", line 37, in <module>
    run_migrations()
  File "/lifecycle/migrate.py", line 99, in run_migrations
    migration.run()
  File "/lifecycle/system_migrations/tenant_files.py", line 15, in run
    TENANT_MEDIA_ROOT.mkdir(parents=True)
  File "/usr/local/lib/python3.12/pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/media/public'
```

**Version and Deployment (please complete the following information):**
k3s v1.30.1
Longhorn 1.6.1
Authentik Helm chart 2024.4.2

When running Authentik withoutvthe PVC attached, it works fine.

How can I fix this (preferably without an initContainer...)?

EDIT: Updated to 2024.6.4 with the same result.

**Comment by ednxzu** [comment]
```
global:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
```
You can add this bit to your values.yml, tho it should be globally a default since it will not work without.

**Comment by crazyelectron-io** [comment]
Thanks. Will test this.

**Comment by crazyelectron-io** [comment]
Finally found the time to test it and it works. Thanks!

**Comment by sunmetis** [comment]
Hi same error for me .. Even with fsgroup etc .. permission error . The volume and the repo are mounted but stil have permission denied
