### ISSUE TITLE
SCIM sync fails with exception

### ISSUE THREAD

**Issue by kuzaxak** [goauthentik/authentik#11165]
**Describe the bug**

After an upgrade from 2023 SCIM stops reporting an errors in a readable way, now it is a giant stacktrace.

**To Reproduce**
1. Run SCIM provider sync.

**Expected behavior**
SCIM sync should work, or at least print out what user\group cause a failure.

**Screenshots**
<img width="820" alt="image" src="https://github.com/user-attachments/assets/8ea84ace-5c16-4594-aca7-b126fd7ce00d">

**Logs**
Output of docker-compose logs or kubectl logs respectively

Traceback (most recent call last): File "/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task R = retval = fun(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^ File "/ak-root/venv/lib/python3.12/site-packages/sentry_sdk/utils.py", line 1711, in runner return sentry_patched_function(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/ak-root/venv/lib/python3.12/site-packages/sentry_sdk/integrations/celery/__init__.py", line 380, in _inner reraise(*exc_info) File "/ak-root/venv/lib/python3.12/site-packages/sentry_sdk/utils.py", line 1640, in reraise raise value File "/ak-root/venv/lib/python3.12/site-packages/sentry_sdk/integrations/celery/__init__.py", line 375, in _inner return f(*args, **kwargs) ^^^^^^^^^^^^^^^^^^ File "/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__ return self.run(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/ak-root/venv/lib/python3.12/site-packages/celery/app/autoretry.py", line 38, in run return task._orig_run(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/authentik/providers/scim/tasks.py", line 22, in scim_sync return sync_tasks.sync_single(self, provider_pk, scim_sync_objects) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/authentik/lib/sync/outgoing/tasks.py", line 90, in sync_single ).get(): ^^^^^ File "/ak-root/venv/lib/python3.12/site-packages/celery/result.py", line 251, in get return self.backend.wait_for_pending( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/ak-root/venv/lib/python3.12/site-packages/celery/backends/asynchronous.py", line 223, in wait_for_pending return result.maybe_throw(callback=callback, propagate=propagate) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/ak-root/venv/lib/python3.12/site-packages/celery/result.py", line 365, in maybe_throw self.throw(value, self._to_remote_traceback(tb)) File "/ak-root/venv/lib/python3.12/site-packages/celery/result.py", line 358, in throw self.on_ready.throw(*args, **kwargs) File "/ak-root/venv/lib/python3.12/site-packages/vine/promises.py", line 235, in throw reraise(type(exc), exc, tb) File "/ak-root/venv/lib/python3.12/site-packages/vine/utils.py", line 27, in reraise raise value authentik.lib.sync.outgoing.exceptions.ObjectExistsSyncException: <Response [409]>

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.6.4
-   Deployment: helm

**Additional context**

**Comment by kpodp0ra** [comment]
Can reproduce on 2024.8.3
```
Traceback (most recent call last):
  File "/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/celery/app/autoretry.py", line 38, in run
    return task._orig_run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/providers/scim/tasks.py", line 22, in scim_sync
    return sync_tasks.sync_single(self, provider_pk, scim_sync_objects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/lib/sync/outgoing/tasks.py", line 90, in sync_single
    ).get():
      ^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/celery/result.py", line 251, in get
    return self.backend.wait_for_pending(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/celery/backends/asynchronous.py", line 223, in wait_for_pending
    return result.maybe_throw(callback=callback, propagate=propagate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/celery/result.py", line 365, in maybe_throw
    self.throw(value, self._to_remote_traceback(tb))
  File "/ak-root/venv/lib/python3.12/site-packages/celery/result.py", line 358, in throw
    self.on_ready.throw(*args, **kwargs)
  File "/ak-root/venv/lib/python3.12/site-packages/vine/promises.py", line 235, in throw
    reraise(type(exc), exc, tb)
  File "/ak-root/venv/lib/python3.12/site-packages/vine/utils.py", line 27, in reraise
    raise value
authentik.lib.sync.outgoing.exceptions.ObjectExistsSyncException: <Response [409]>
```

**Comment by jorhett** [comment]
FYI I saw this error when I was trying to tweak the property mappings for groups https://github.com/goauthentik/authentik/issues/12827#issuecomment-2708439808

Might want to try resetting the group property mapping to default and see if it disappears, then start adding your changes back.

**Comment by compuguy** [comment]
> FYI I saw this error when I was trying to tweak the property mappings for groups [#12827 (comment)](https://github.com/goauthentik/authentik/issues/12827#issuecomment-2708439808)
> 
> Might want to try resetting the group property mapping to default and see if it disappears, then start adding your changes back.

Already had it configured like that, still getting the same error as OP:

`Traceback (most recent call last): File "/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task R = retval = fun(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^ File "/ak-root/venv/lib/python3.12/site-packages/sentry_sdk/utils.py", line 1783, in runner return sentry_patched_function(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/ak-root/venv/lib/python3.12/site-packages/sentry_sdk/integrations/celery/__init__.py", line 415, in _inner reraise(*exc_info) File "/ak-root/venv/lib/python3.12/site-packages/sentry_sdk/utils.py", line 1718, in reraise raise value File "/ak-root/venv/lib/python3.12/site-packages/sentry_sdk/integrations/celery/__init__.py", line 410, in _inner return f(*args, **kwargs) ^^^^^^^^^^^^^^^^^^ File "/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__ return self.run(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/ak-root/venv/lib/python3.12/site-packages/celery/app/autoretry.py", line 38, in run return task._orig_run(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/authentik/providers/scim/tasks.py", line 22, in scim_sync return sync_tasks.sync_single(self, provider_pk, scim_sync_objects) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/authentik/lib/sync/outgoing/tasks.py", line 90, in sync_single ).get(): ^^^^^ File "/ak-root/venv/lib/python3.12/site-packages/celery/result.py", line 251, in get return self.backend.wait_for_pending( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/ak-root/venv/lib/python3.12/site-packages/celery/backends/asynchronous.py", line 223, in wait_for_pending return result.maybe_throw(callback=callback, propagate=propagate) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/ak-root/venv/lib/python3.12/site-packages/celery/result.py", line 365, in maybe_throw self.throw(value, self._to_remote_traceback(tb)) File "/ak-root/venv/lib/python3.12/site-packages/celery/result.py", line 358, in throw self.on_ready.throw(*args, **kwargs) File "/ak-root/venv/lib/python3.12/site-packages/vine/promises.py", line 235, in throw reraise(type(exc), exc, tb) File "/ak-root/venv/lib/python3.12/site-packages/vine/utils.py", line 27, in reraise raise value authentik.lib.sync.outgoing.exceptions.ObjectExistsSyncException: <Response [409]>`
