### ISSUE TITLE
Fresh Install of Authentik - Unable to login or complete Initial-setup using FQDN

### ISSUE THREAD

**Issue by flexyneat** [goauthentik/authentik#11254]
**Describe the bug**

Hi Everyone, Just recently encountered this issue described below, and would very much appreciate any help:

I have a dockerized fresh Install of authentik behind traefik proxy and it fails to complete initial-setup flow. All other work-arounds as seen on reddit and github fail. The only work around is to use internal IP/URL with port number - https://172.20.124.122:9443/if/flow/initial-setup/. 
But all attempts to initiate the initial setup flow from FQDN (https://auth.domain.com/if/flow/initial-setup/) fails with the below screenshot:

![image](https://github.com/user-attachments/assets/05147613-02a5-4fc3-bef3-93865731d5bb)

Secondly, After completing initial-setup flow from internal URL and port number, when i try to login with akadmin from the FQDN, i get the below HTML output error without being logged in. Once again, I am only able to successfully login with internal IP/URL and port number
![image](https://github.com/user-attachments/assets/0cec1030-a0d3-44a3-aed4-3716bd274265)

**To Reproduce**

**Expected behavior**
To be able to complete initial-setup flow using FQDN - auth.domain.com/if/flow/initial-setup/ and subsequently be able to login from FQDN without errors.

**Screenshots**
screenshots attached

**Logs**
Output of docker-compose logs or kubectl logs respectively

```
2024-09-06T15:02:01.378352832Z warning | auth_via=unauthenticated domain_url=auth.domain.com event=Policy failed to run exc=Traceback (most recent call last):
  File "/authentik/policies/process.py", line 145, in run
    self.connection.send(self.profiling_wrapper())
                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/policies/process.py", line 140, in profiling_wrapper
    return self.execute()
           ^^^^^^^^^^^^^^
  File "/authentik/policies/process.py", line 85, in execute
    policy_result = self.binding.passes(self.request)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/policies/models.py", line 102, in passes
    return self.policy.passes(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/policies/expression/models.py", line 31, in passes
    evaluator.set_policy_request(request)
  File "/authentik/policies/expression/evaluator.py", line 45, in set_policy_request
    self.set_http_request(request.http_request)
  File "/authentik/policies/expression/evaluator.py", line 53, in set_http_request
    self._context["ak_client_ip"] = ip_address(ClientIPMiddleware.get_client_ip(request))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
builtins.ValueError: 'https' does not appear to be an IPv4 or IPv6 address host=auth.domain.com logger=authentik.policies.process pid=256 request_id=a53e3043d1e84496aa695c554b6187da schema_name=public timestamp=2024-09-06T15:02:01.378127 
2024-09-06T15:02:01.379177347Z warning | auth_via=unauthenticated domain_url=auth.domain.com event=f(exec): Flow not applicable to current user exc=FlowNonApplicableException() flow_slug=initial-setup host=auth.domain.com logger=authentik.flows.views.executor pid=256 request_id=a53e3043d1e84496aa695c554b6187da schema_name=public timestamp=2024-09-06T15:02:01.379001 
2024-09-06T15:02:01.382543107Z INF | auth_via=unauthenticated domain_url=auth.domain.com event=/api/v3/flows/executor/initial-setup/?query= host=auth.domain.com logger=authentik.asgi method=GET pid=256 remote=https request_id=a53e3043d1e84496aa695c554b6187da runtime=26 schema_name=public scheme=https status=200 timestamp=2024-09-06T15:02:01.382381 user= user_agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15 
2024-09-06T15:02:01.621322872Z INF | domain_url=null event=/ws/client/ logger=authentik.asgi pid=258 remote=https, 102.164.36.86 schema_name=public scheme=ws timestamp=2024-09-06T15:02:01.621099 user_agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15 
2024-09-06T15:02:12.095146858Z INF | auth_via=unauthenticated domain_url=localhost event=/-/health/live/ host=localhost:8000 logger=authentik.asgi method=GET pid=258 remote=255.255.255.255 request_id=f2102dfcc1824ac99bfea4dafedf4d8e runtime=7 schema_name=public scheme=http status=204 timestamp=2024-09-06T15:02:12.094862 user= user_agent=goauthentik.io/router/healthcheck 

```
**Version and Deployment (please complete the following information):**

-   authentik version: [Initial test with 2024.8 and got this issue, so tried with 2024.2 and same issue persists]
-   Deployment: [docker-compose]

**Additional context**

**Comment by BeryJu** [comment]
From the logs above it is most likely that your reverse proxy is sending an incorrect X-Forwarded-For header; this header should only contain IP Addresses (separated by a comma if there are multiple) and not any protocol like https
