### ISSUE TITLE
Test Property Mapping for SCIM Source fails with "name 'data' is not defined"

### ISSUE THREAD

**Issue by aichert** [goauthentik/authentik#11294]
**Describe the bug**
First of all, thank you for the fast fix of #11230, I retested the bug and it's definitely closed.
Unfortunately I stumbled upon another bug, which I couldn't test before.

the source Python dictionary `data` is not defined.

This only happens with the test property mapping feature, a sync between IdP and authentik works.

**To Reproduce**

1. open property mappings
2. Click on test of the source property mapping you want to test
3. fill out user and context
4. click test

**Expected behavior**
I can see attributes based on the property mapping

**Logs**
context:
```yaml
schemas:
  - urn:scim:schemas:core:2.0
  - urn:scim:schemas:extension:enterprise:2.0
userName: AAA Test  User 01
name:
  familyName: " User 01"
  givenName: AAA Test
  formatted: onelogin-test-user01
emails:
  - value: onelogin-test-user01@tdtest.com
    type: work
    primary: true
title: ""
urn:scim:schemas:extension:enterprise:2.0:
  department: ""
  oneloginid: "12345678"
  manager:
    value: ""
    displayName: " "
active: true
```
Trace
```
Traceback (most recent call last):
  File "/authentik/core/models.py", line 900, in evaluate
    return evaluator.evaluate(self.expression)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/core/expression/evaluator.py", line 88, in evaluate
    return super().evaluate(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/lib/expression/evaluator.py", line 227, in evaluate
    raise exc
  File "onelogin_user_mapping", line 11, in <module>
  File "onelogin_user_mapping", line 4, in handler
builtins.NameError: name 'data' is not defined
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.8.1
-   Deployment: docker-compose

**Comment by BeryJu** [comment]
The root cause of the issue stems from the fact that in the actual SCIM source, the data is passed in as a single `data` attribute to the mapping that contains all of the request data, however in the tester this is not wrapped into a `data` object automatically. So if you prepend `data:` do your input data and indent the rest of it, it will work correctly.

**Comment by dominic-r** [comment]
We're closing this in favor of this parent issue: #25276
