### ISSUE TITLE
Provide docs for django allauth?

### ISSUE THREAD

**Issue by Akruidenberg** [goauthentik/authentik#1179]
**Describe your question/**
I would like to intergrate Authentik with Tandoor (a recipe manager, using django all-auth for openid/oauth2)

**Relevant infos**
Tandoor 0.16.7 (using django all-auth)

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/18529293/126872636-b09ebcb0-f29a-45e4-8c21-3805d47a8f63.png)

**Version and Deployment (please complete the following information):**
 - Authentik version: 2021.6.4
 - Deployment: Docker compose

When adding the env `SOCIAL_PROVIDERS=allauth.socialaccount.providers.openid` to the tandoor container, some options appears in the admin panel of Tandoor. However, not all options are available, like the token and userinfo URL. Only the secret key and the client id are visible.
I don't a have a lot of experiences with such applications, that's the reason why i posted a question here. How to add the additional fields here?
Some docs for django all-auth:

[https://django-allauth.readthedocs.io/en/latest/providers.html#openid](url)

**Comment by BeryJu** [comment]
After you've created an Application with an OAuth2 Provider in authentik, add this to the config:

```python
SOCIALACCOUNT_PROVIDERS = {
    'openid': {
        'SERVERS': [
            dict(id='authentik',
                 name='authentik',
                 openid_url='*The provider's "OpenID Configuration Issuer"'),
        ]
    }
}
``

**Comment by Akruidenberg** [comment]
Maybe a noob question, but how to use this with docker compose? Tandoor is using a `SOCIAL_PROVIDERS` env.

**Comment by BeryJu** [comment]
Good question, there's no standard way to represent config like that as environment variables. Maybe the software has a specific solution for it?

**Comment by Akruidenberg** [comment]
From the Tandoor Docs:

_Depending on your authentication provider you might need to configure it. This needs to be done trough the settings system. To make the system flexible (allow multiple providers) and to not require another file to be mounted into the container the configuration ins done trough a single environment variable. The downside of this approach is that the configuration needs to be put into a single line as environment files loaded by docker compose don't support multiple lines for a single variable._

I will open question to ask the developer @vabene1111

**Comment by vabene1111** [comment]
so first of all thanks to @BeryJu for the help already provided. 

@Akruidenberg its exactly as the docs says, you basically take the configuration that beryJu provided above, move everythjing to a single line and put it into the environment variable. The hosted version of tandoor does just that with 10 different providers and it works without any problems. 

It is not super elegant but it keeps everything flexible, alternatives would be to read a file that would need to be mounted or put the settings inside some kind of database but the folks from django-allauth did not do that for a reason i suppose.

this (or similar) is what you need to do, there is also an example in the docs using nextcloud as the auth provider https://docs.tandoor.dev/features/authentication/#allauth
```
SOCIALACCOUNT_PROVIDERS={  'openid': {   'SERVERS': [ dict(id='authentik',  name='authentik', openid_url='*The provider's "OpenID Configuration Issuer"'), ]}}
```

**Comment by Akruidenberg** [comment]
> so first of all thanks to @BeryJu for the help already provided.
> 
> @Akruidenberg its exactly as the docs says, you basically take the configuration that beryJu provided above, move everythjing to a single line and put it into the environment variable. The hosted version of tandoor does just that with 10 different providers and it works without any problems.
> 
> It is not super elegant but it keeps everything flexible, alternatives would be to read a file that would need to be mounted or put the settings inside some kind of database but the folks from django-allauth did not do that for a reason i suppose.
> 
> this (or similar) is what you need to do, there is also an example in the docs using nextcloud as the auth provider https://docs.tandoor.dev/features/authentication/#allauth
> 
> ```
> SOCIALACCOUNT_PROVIDERS={  'openid': {   'SERVERS': [ dict(id='authentik',  name='authentik', openid_url='*The provider's "OpenID Configuration Issuer"'), ]}}
> ```

Thanks for your help @vabene1111. 
However, its not working because i´m using `:` after the env, not `=`. How to correct this?

**Comment by vabene1111** [comment]
why are you not using `=` ? i dont have much experience with other setups so you might need to try around with a few different formats

**Comment by Akruidenberg** [comment]
> why are you not using `=` ? i dont have much experience with other setups so you might need to try around with a few different formats

tested with separate env file. Container is now created correctly However, it wont start. Authentik has provider and application created. Website is changed in Tandoor admin interface.

Here are the logs:
```

  File "/opt/recipes/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__,
    mod = importlib.import_module(self.SETTINGS_MODULE),
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module,
    return _bootstrap._gcd_import(name[level:], package, level),
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import,
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load,
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked,
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked,
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module,
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed,
  File "/opt/recipes/recipes/settings.py", line 125, in <module>,
    SOCIALACCOUNT_PROVIDERS = ast.literal_eval(,
  File "/usr/local/lib/python3.9/ast.py", line 105, in literal_eval,
    return _convert(node_or_string),
  File "/usr/local/lib/python3.9/ast.py", line 94, in _convert,
    return dict(zip(map(_convert, node.keys),,
  File "/usr/local/lib/python3.9/ast.py", line 94, in _convert,
    return dict(zip(map(_convert, node.keys),,
  File "/usr/local/lib/python3.9/ast.py", line 85, in _convert,
    return list(map(_convert, node.elts)),
  File "/usr/local/lib/python3.9/ast.py", line 104, in _convert,
    return _convert_signed_num(node),
  File "/usr/local/lib/python3.9/ast.py", line 78, in _convert_signed_num,
    return _convert_num(node),
  File "/usr/local/lib/python3.9/ast.py", line 69, in _convert_num,
    _raise_malformed_node(node),
  File "/usr/local/lib/python3.9/ast.py", line 66, in _raise_malformed_node,
    raise ValueError(f'malformed node or string: {node!r}'),
ValueError: malformed node or string: <ast.Call object at 0x7febec1a9a60>,
Done,
[2021-07-31 10:09:23 +0000] [1] [INFO] Starting gunicorn 20.1.0,
[2021-07-31 10:09:23 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1),
[2021-07-31 10:09:23 +0000] [1] [INFO] Using worker: sync,
[2021-07-31 10:09:23 +0000] [12] [INFO] Booting worker with pid: 12,
[2021-07-31 10:09:23 +0000] [12] [ERROR] Exception in worker process,
Traceback (most recent call last):,
  File "/opt/recipes/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker,
    worker.init_process(),
  File "/opt/recipes/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process,
    self.load_wsgi(),
  File "/opt/recipes/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi,
    self.wsgi = self.app.wsgi(),
  File "/opt/recipes/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi,
    self.callable = self.load(),
  File "/opt/recipes/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load,
    return self.load_wsgiapp(),
  File "/opt/recipes/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp,
    return util.import_app(self.app_uri),
  File "/opt/recipes/venv/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app,
    mod = importlib.import_module(module),
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module,
    return _bootstrap._gcd_import(name[level:], package, level),
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import,
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load,
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked,
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked,
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module,
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed,
  File "/opt/recipes/recipes/wsgi.py", line 16, in <module>,
    application = get_wsgi_application(),
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application,
    django.setup(set_prefix=False),
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/__init__.py", line 19, in setup,
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING),
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__,
    self._setup(name),
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup,
    self._wrapped = Settings(settings_module),
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__,
    mod = importlib.import_module(self.SETTINGS_MODULE),
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module,
    return _bootstrap._gcd_import(name[level:], package, level),
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import,
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load,
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked,
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked,
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module,
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed,
  File "/opt/recipes/recipes/settings.py", line 125, in <module>,
    SOCIALACCOUNT_PROVIDERS = ast.literal_eval(,
  File "/usr/local/lib/python3.9/ast.py", line 105, in literal_eval,
    return _convert(node_or_string),
  File "/usr/local/lib/python3.9/ast.py", line 94, in _convert,
    return dict(zip(map(_convert, node.keys),,
  File "/usr/local/lib/python3.9/ast.py", line 94, in _convert,
    return dict(zip(map(_convert, node.keys),,
  File "/usr/local/lib/python3.9/ast.py", line 85, in _convert,
    return list(map(_convert, node.elts)),
  File "/usr/local/lib/python3.9/ast.py", line 104, in _convert,
    return _convert_signed_num(node),
  File "/usr/local/lib/python3.9/ast.py", line 78, in _convert_signed_num,
    return _convert_num(node),
  File "/usr/local/lib/python3.9/ast.py", line 69, in _convert_num,
    _raise_malformed_node(node),
  File "/usr/local/lib/python3.9/ast.py", line 66, in _raise_malformed_node,
    raise ValueError(f'malformed node or string: {node!r}'),
ValueError: malformed node or string: <ast.Call object at 0x7f1af7bc5be0>,
[2021-07-31 10:09:23 +0000] [12] [INFO] Worker exiting (pid: 12),
[2021-07-31 10:09:23 +0000] [1] [INFO] Shutting down: Master,
[2021-07-31 10:09:23 +0000] [1] [INFO] Reason: Worker failed to boot.
```

@BeryJu @vabene1111, can you provide some help?

**Comment by vabene1111** [comment]
this issue looks to me like it is happening in tandoor and that it fails to parse your environement variable. I would try to not write the dict using the dict function `SOCIALACCOUNT_PROVIDERS={ 'openid': { 'SERVERS': [ {'id':'authentik', 'name':'authentik', 'openid_url':'https://authentik.example.com/application/o/tandoor/"'}, ]}}`

if that does not work please open a new issue over on the tandoor repo as i am pretty sure that the nice people of this repository here are not responsible for whatever is broken in this setup of yours.

**Comment by Akruidenberg** [comment]
Will do
