### ISSUE TITLE
outpost error: DB column authentik_providers_ldap_ldapprovider.search_group_id does not exist

### ISSUE THREAD

**Issue by AlexVeeBee** [goauthentik/authentik#11860]
**Describe the bug**
The DB schema became out of date a while back without the outposts being touched for a while

**To Reproduce**
This only happens when the DB schema is out of date

**Expected behavior**
Automatically update the outpost

**Screenshots**
![floorp_pGccYMZrFe](https://github.com/user-attachments/assets/0684a1eb-72c4-4d81-b713-c9311cbccf9a)
![floorp_Cxsb00LEC5](https://github.com/user-attachments/assets/c4b3c90b-da0a-4b6b-aa2b-e16c45ba594c)
![floorp_R5lEVSQ2wi](https://github.com/user-attachments/assets/26f2ad41-9157-4695-b471-a4fced2a8e71)
![floorp_vrQYdzjNe7](https://github.com/user-attachments/assets/2e8d40ba-f90e-4b6e-b0bb-705218311774)

**Logs**
```
Task outpost_token_ensurer encountered an error: Traceback (most recent call last):
  File "/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/sentry_sdk/integrations/celery.py", line 306, in _inner
    reraise(*exc_info)
  File "/ak-root/venv/lib/python3.12/site-packages/sentry_sdk/_compat.py", line 127, in reraise
    raise value
  File "/ak-root/venv/lib/python3.12/site-packages/sentry_sdk/integrations/celery.py", line 301, in _inner
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/outposts/tasks.py", line 174, in outpost_token_ensurer
    outpost.build_user_permissions(outpost.user)
  File "/authentik/outposts/models.py", line 302, in build_user_permissions
    for model_or_perm in self.get_required_objects():
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/outposts/models.py", line 406, in get_required_objects
    for provider in Provider.objects.filter(outpost=self).select_related().select_subclasses():
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/model_utils/managers.py", line 20, in __iter__
    for obj in iter:
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/ak-root/venv/lib/python3.12/site-packages/sentry_sdk/integrations/django/__init__.py", line 641, in execute
    result = real_execute(self, sql, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
django.db.utils.ProgrammingError: column authentik_providers_ldap_ldapprovider.search_group_id does not exist
LINE 1: ...authentik_providers_ldap_ldapprovider"."base_dn", "authentik...
                                                             ^
```
DB:
`2024-10-30 16:10:18.687 UTC [822] ERROR:  column authentik_providers_ldap_ldapprovider.search_group_id does not exist at character 387`

**Version and Deployment (please complete the following information):**

-   Traefik 
-   authentik version: 2024.8.4
-   Deployment: Docker Compose

**Additional context**
error log from: outpost_token_ensurer

**Comment by AlexVeeBee** [comment]
bump

**Comment by AlexVeeBee** [comment]
found issue: Outdated worked version
> Change the compose file to match the version of the server version or use the latest tag
