### ISSUE TITLE
Authentik database error after upgrade

### ISSUE THREAD

**Issue by metril** [goauthentik/authentik#11874]
**Describe the bug**
After upgrading authentik to 2024.10, there is a database error.

```
django.db.utils.OperationalError: index row size 4256 exceeds btree version 4 maximum 2704 for index "authentik_p_token_4bc870_idx"
DETAIL:  Index row references tuple (14,10) in relation "authentik_providers_oauth2_accesstoken".
```

**To Reproduce**

1. At some point, you should have been running postgres12 and have upgrade to postgres16 due to authentik requirement changes.
2. Upgrade to any authentik version after 2024.8.3

**Expected behavior**
Authentik should be working after upgrading to the latest version

**Logs**
```
django.db.utils.OperationalError: index row size 4256 exceeds btree version 4 maximum 2704 for index "authentik_p_token_4bc870_idx"
DETAIL:  Index row references tuple (14,10) in relation "authentik_providers_oauth2_accesstoken".
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.
{"error":"authentik starting","event":"failed to proxy to backend","level":"warning","logger":"authentik.router","timestamp":"2024-10-31T04:06:03Z"}
{"error":"exit status 1","event":"gunicorn process died, restarting","level":"warning","logger":"authentik.router","timestamp":"2024-10-31T04:06:04Z"}
{"error":"exit status 1","event":"gunicorn failed to start, restarting","level":"error","logger":"authentik.router","timestamp":"2024-1
**Version and Deployment (please complete the following information):**
```

-   authentik version: [e.g. 2024.10]
-   Deployment: [docker-compose]

**Comment by metril** [comment]
I tried doing a migration manually and of course, it fails. See below.

```
standard:public] === Starting migration
[standard:public] Operations to perform:
[standard:public]   Apply all migrations: auth, authentik_blueprints, authentik_brands, authentik_core, authentik_crypto, authentik_enterprise, authentik_events, authentik_flows, authentik_outposts, authentik_policies, authentik_policies_dummy, authentik_policies_event_matcher, authentik_policies_expiry, authentik_policies_expression, authentik_policies_geoip, authentik_policies_password, authentik_policies_reputation, authentik_providers_google_workspace, authentik_providers_ldap, authentik_providers_microsoft_entra, authentik_providers_oauth2, authentik_providers_proxy, authentik_providers_rac, authentik_providers_radius, authentik_providers_saml, authentik_providers_scim, authentik_rbac, authentik_sources_kerberos, authentik_sources_ldap, authentik_sources_oauth, authentik_sources_plex, authentik_sources_saml, authentik_sources_scim, authentik_stages_authenticator_duo, authentik_stages_authenticator_endpoint_gdtc, authentik_stages_authenticator_sms, authentik_stages_authenticator_static, authentik_stages_authenticator_totp, authentik_stages_authenticator_validate, authentik_stages_authenticator_webauthn, authentik_stages_captcha, authentik_stages_consent, authentik_stages_deny, authentik_stages_dummy, authentik_stages_email, authentik_stages_identification, authentik_stages_invitation, authentik_stages_password, authentik_stages_prompt, authentik_stages_source, authentik_stages_user_delete, authentik_stages_user_login, authentik_stages_user_logout, authentik_stages_user_write, authentik_tenants, contenttypes, guardian, sessions
[standard:public] Running migrations:
[standard:public]   Applying authentik_providers_oauth2.0019_accesstoken_authentik_p_token_4bc870_idx_and_more...
Traceback (most recent call last):
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 103, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute
    raise ex.with_traceback(None)
psycopg.errors.ProgramLimitExceeded: index row size 4256 exceeds btree version 4 maximum 2704 for index "authentik_p_token_4bc870_idx"
DETAIL:  Index row references tuple (14,10) in relation "authentik_providers_oauth2_accesstoken".
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.
```

**Comment by metril** [comment]
Seems like the database issues might be limited to 2024.10. The 2024.8.4 version seems to work fine, but you need to make sure you are upgrading and not downgrading.

**Comment by User-26** [comment]
Same issue. Stopped working after updating to 2024.10:
`django.db.utils.OperationalError: index row size 3088 exceeds btree version 4 maximum 2704 for index "authentik_p_token_4bc870_idx"`

**Comment by fruworg** [comment]
+1

**Comment by EHRETic** [comment]
Hi, there, 

My 5 cents with apparently the same issue (this will loop forever):

![image](https://github.com/user-attachments/assets/285a781e-2970-45b2-aae2-398adcb2f650)

It makes the same behavior coming from 2027.8.3 or 2024.8.4. 
Luckily, rolling back 2024.8.X is possible.

**Comment by martipoe** [comment]
Same issue with index row limit here after upgrading to 10.0:
```
postgresql-1  | 2024-11-04 11:52:49.945 UTC [45] STATEMENT:  CREATE INDEX "authentik_p_token_4bc870_idx" ON "authentik_providers_oauth2_accesstoken" ("token")
worker-1      | {"domain_url": null, "event": "releasing database lock", "level": "info", "logger": "lifecycle.migrate", "pid": 6, "schema_name": "public", "timestamp": "2024-11-04T11:52:49.951248"}
worker-1      | Traceback (most recent call last):
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 103, in _execute
worker-1      |     return self.cursor.execute(sql)
worker-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django_prometheus/db/common.py", line 69, in execute
worker-1      |     return super().execute(*args, **kwargs)
worker-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute
worker-1      |     raise ex.with_traceback(None)
worker-1      | psycopg.errors.ProgramLimitExceeded: index row requires 233144 bytes, maximum size is 8191
worker-1      | 
worker-1      | The above exception was the direct cause of the following exception:
worker-1      | 
worker-1      | Traceback (most recent call last):
worker-1      |   File "<frozen runpy>", line 198, in _run_module_as_main
worker-1      |   File "<frozen runpy>", line 88, in _run_code
worker-1      |   File "/manage.py", line 43, in <module>
worker-1      |     run_migrations()
worker-1      |   File "/lifecycle/migrate.py", line 114, in run_migrations
worker-1      |     execute_from_command_line(["", "migrate_schemas"])
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
worker-1      |     utility.execute()
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
worker-1      |     self.fetch_command(subcommand).run_from_argv(self.argv)
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
worker-1      |     self.execute(*args, **cmd_options)
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
worker-1      |     output = self.handle(*args, **options)
worker-1      |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django_tenants/management/commands/migrate_schemas.py", line 63, in handle
worker-1      |     executor.run_migrations(tenants=[self.PUBLIC_SCHEMA_NAME])
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django_tenants/migration_executors/standard.py", line 11, in run_migrations
worker-1      |     run_migrations(self.args, self.options, self.codename, self.PUBLIC_SCHEMA_NAME)
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django_tenants/migration_executors/base.py", line 59, in run_migrations
worker-1      |     migrate_command_class(stdout=stdout, stderr=stderr).execute(*args, **options)
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
worker-1      |     output = self.handle(*args, **options)
worker-1      |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/base.py", line 107, in wrapper
worker-1      |     res = handle_func(*args, **kwargs)
worker-1      |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/commands/migrate.py", line 356, in handle
worker-1      |     post_migrate_state = executor.migrate(
worker-1      |                          ^^^^^^^^^^^^^^^^^
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django/db/migrations/executor.py", line 135, in migrate
worker-1      |     state = self._migrate_all_forwards(
worker-1      |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
worker-1      |     state = self.apply_migration(
worker-1      |             ^^^^^^^^^^^^^^^^^^^^^
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
worker-1      |     state = migration.apply(state, schema_editor)
worker-1      |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django/db/migrations/migration.py", line 132, in apply
worker-1      |     operation.database_forwards(
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django/db/migrations/operations/models.py", line 894, in database_forwards
worker-1      |     schema_editor.add_index(model, self.index)
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django/db/backends/postgresql/schema.py", line 325, in add_index
worker-1      |     self.execute(
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django/db/backends/postgresql/schema.py", line 45, in execute
worker-1      |     return super().execute(sql, params)
worker-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django/db/backends/base/schema.py", line 202, in execute
worker-1      |     cursor.execute(sql, params)
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/sentry_sdk/utils.py", line 1788, in runner
worker-1      |     return sentry_patched_function(*args, **kwargs)
worker-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/sentry_sdk/integrations/django/__init__.py", line 653, in execute
worker-1      |     result = real_execute(self, sql, params)
worker-1      |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
worker-1      |     return self._execute_with_wrappers(
worker-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
worker-1      |     return executor(sql, params, many, context)
worker-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
worker-1      |     with self.db.wrap_database_errors:
worker-1      |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
worker-1      |     raise dj_exc_value.with_traceback(traceback) from exc_value
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 103, in _execute
worker-1      |     return self.cursor.execute(sql)
worker-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/django_prometheus/db/common.py", line 69, in execute
worker-1      |     return super().execute(*args, **kwargs)
worker-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1      |   File "/ak-root/venv/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute
worker-1      |     raise ex.with_traceback(None)
worker-1      | django.db.utils.OperationalError: index row requires 233144 bytes, maximum size is 8191
worker-1      | Sentry is attempting to send 1 pending events
worker-1      | Waiting up to 2 seconds
worker-1      | Press Ctrl-C to quit
```
