### ISSUE TITLE
GET /api/v3/authenticators/all/

### ISSUE THREAD

**Issue by justsomemate** [goauthentik/authentik#11882]
**Describe the bug**
Unable to edit MFA devices

**To Reproduce**
1. Have existing WebAuthn devices configured (device_type_id column is NULL)
2. Log into authentik
3. Go to Settings > MFA Devices
4. See error "Failed to fetch objects."

**Expected behavior**
Be able to edit MFA devices

**Screenshots**
![image](https://github.com/user-attachments/assets/e5eaa1cc-c14a-4fec-8e6b-2ea73f900f17)

**Logs**
<details>
    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
  File "/ak-root/venv/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/ak-root/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/ak-root/venv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/core/api/devices.py", line 59, in list
    return Response(DeviceSerializer(devices, many=True).data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 687, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "/authentik/core/api/devices.py", line 43, in get_extra_description
    return instance.device_type.description
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
builtins.AttributeError: 'NoneType' object has no attribute 'description'
```
</details>

**Version and Deployment (please complete the following information):**
- authentik version: 2024.10.0
- Deployment: docker-compose

**Additional context**
All of the WebAuthn devices would have been registered on much earlier versions of authentik.
Only two entries in the authentik_stages_authenticator_webauthn_webauthndevice table have a value for device_type_id.
Of those, one has a last_updated and last_used value on 2024-10-21. The other has a last_updated on 2024-09-11 (but no last_used value).
There are entries with a last_used of today.
All of the entries show a created value of 0001-01-01 00:00:00+00.

I registered devices on a test instance of authentik after it was upgraded to 2024.10.0, and they correctly have a value for device_type_id

**Comment by MrBE4R** [comment]
Got the same problem. But, my TOTP Authenticator miraculously updated itself after authenticating on an app behind a proxy provider (which is broken on 2024.10.0 as per another issue) and is now visible.

I still got the error on another instance tho.

**Comment by jcheger** [comment]
Same here. Rollbacked to 2024.8.4, and it's working again.

Here is the error:
```
{
  "action": "system_exception",
  "auth_via": "session",
  "client_ip": "82.197.179.160",
  "context": {
    "geo": {
      "city": "Dübendorf",
      "continent": "EU",
      "country": "CH",
      "lat": 47.3975,
      "long": 8.6209
    },
    "http_request": {
      "args": {
        "user": "13"
      },
      "method": "GET",
      "path": "/api/v3/authenticators/admin/all/",
      "request_id": "9b11209060db4561a1e1ba7508d1fc3d",
      "user_agent": "Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0"
    },
    "message": "Traceback (most recent call last):
  File \"/ak-root/venv/lib/python3.12/site-packages/asgiref/sync.py\", line 518, in thread_handler
    raise exc_info[1]
  File \"/ak-root/venv/lib/python3.12/site-packages/django/core/handlers/base.py\", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File \"/ak-root/venv/lib/python3.12/site-packages/asgiref/sync.py\", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/ak-root/venv/lib/python3.12/site-packages/asgiref/current_thread_executor.py\", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/ak-root/venv/lib/python3.12/site-packages/asgiref/sync.py\", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File \"/ak-root/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py\", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/ak-root/venv/lib/python3.12/site-packages/rest_framework/viewsets.py\", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/ak-root/venv/lib/python3.12/site-packages/rest_framework/views.py\", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/ak-root/venv/lib/python3.12/site-packages/rest_framework/views.py\", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File \"/ak-root/venv/lib/python3.12/site-packages/rest_framework/views.py\", line 480, in raise_uncaught_exception
    raise exc
  File \"/ak-root/venv/lib/python3.12/site-packages/rest_framework/views.py\", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/authentik/rbac/decorators.py\", line 39, in wrapper
    return func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/authentik/core/api/devices.py\", line 93, in list
    return Response(DeviceSerializer(self.get_devices(**kwargs), many=True).data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/ak-root/venv/lib/python3.12/site-packages/rest_framework/serializers.py\", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File \"/ak-root/venv/lib/python3.12/site-packages/rest_framework/serializers.py\", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/ak-root/venv/lib/python3.12/site-packages/rest_framework/serializers.py\", line 687, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/ak-root/venv/lib/python3.12/site-packages/rest_framework/serializers.py\", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/ak-root/venv/lib/python3.12/site-packages/rest_framework/fields.py\", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File \"/authentik/core/api/devices.py\", line 43, in get_extra_description
    return instance.device_type.description
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
builtins.AttributeError: 'NoneType' object has no attribute 'description'"
  },
  "domain_url": "auth.some.where",
  "event": "Created Event",
  "host": "auth.some.where",
  "level": "info",
  "logger": "authentik.events.models",
  "pid": 94691,
  "request_id": "9b11209060db4561a1e1ba7508d1fc3d",
  "schema_name": "public",
  "timestamp": "2024-11-04T09:19:11.579300",
  "user": {
    "email": "admin@localhost.localdomain",
    "pk": 1,
    "username": "akadmin"
  }
}
```
