### ISSUE TITLE
`ak make_blueprint_schema` command is broken/crashes

### ISSUE THREAD

**Issue by solidDoWant** [goauthentik/authentik#12188]
**Describe the bug**
When running `ak make_blueprint_schema` from a worker instance, it crashes because the container image is missing the `drf_jsonschema_serializer` module.

**To Reproduce**
1. Deploy authentik
2. Run `ak make_blueprint_schema` inside a worker instance.

**Expected behavior**
The command should not crash.

**Screenshots**
N/A

**Logs**
```console
$ ak make_blueprint_schema
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1732573766.9796324, "file": "/authentik/lib/default.yml"}
... (omitted)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/manage.py", line 52, in <module>
    execute_from_command_line(sys.argv)
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 275, in fetch_command
    klass = load_command_class(app_name, subcommand)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 48, in load_command_class
    module = import_module("%s.management.commands.%s" % (app_name, name))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/authentik/blueprints/management/commands/make_blueprint_schema.py", line 8, in <module>
    from drf_jsonschema_serializer.convert import converter, field_to_converter
ModuleNotFoundError: No module named 'drf_jsonschema_serializer'
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.10.2
-   Deployment: Helm

**Additional context**
N/A

**Comment by BeryJu** [comment]
`make_blueprint_schema` is not a command intended to be ran in the final image, it's used during development and release to update the blueprint schema. You can find the blueprint schema in the container under `/blueprints/schema.json`
