### ISSUE TITLE
Proxy outpost fills up TMPDIR with sessions

### ISSUE THREAD

**Issue by zbig-t** [goauthentik/authentik#12230]
**Describe the bug**
Every few days my self-hosted Authentik instance crashes which correlates to full `/dev/shm` filesystem inside the container.

**To Reproduce**
Deploy Authentik on Kubernetes cluster using Helm chart as per documentation.

**Logs**
Excerpt from `authentik-server` pod's log:
```
{"event": "Starting gunicorn 23.0.0", "level": "info", "logger": "gunicorn.error", "timestamp": 1732875579.247224}
Traceback (most recent call last):
File "/ak-root/venv/bin/gunicorn", line 8, in <module>
sys.exit(run())
^^^^^
File "/ak-root/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 66, in run
WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()
File "/ak-root/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 235, in run
super().run()
File "/ak-root/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 71, in run
Arbiter(self).run()
File "/ak-root/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 197, in run
self.start()
File "/ak-root/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 136, in start
self.pidfile.create(self.pid)
File "/ak-root/venv/lib/python3.12/site-packages/gunicorn/pidfile.py", line 36, in create
os.write(fd, ("%s\n" % self.pid).encode('utf-8'))
OSError: [Errno 28] No space left on device
Sentry is attempting to send 1 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit
```
Output from `df`:
```
authentik@authentik-server-55d65ffb7c-8k6fj:/$ df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         118G   22G   96G  19% /
tmpfs            64M     0   64M   0% /dev
/dev/sda1       118G   22G   96G  19% /etc/hosts
shm              64M   64M     0 100% /dev/shm
tmpfs           7.8G   12K  7.8G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs           3.9G     0  3.9G   0% /proc/acpi
tmpfs           3.9G     0  3.9G   0% /proc/scsi
tmpfs           3.9G     0  3.9G   0% /sys/firmware
```

**Version and Deployment (please complete the following information):**

-   authentik version: since few months-old ones up to and including 2024.10.2
-   Deployment: Helm on k3s

**Comment by zbig-t** [comment]
Bump; here we go again, like a clockwork.
Pod `authentik-sserver-id`:
- 8 days uptime
- single CPU core fully loaded
- gunicorn exceptions scrolling through stdout
- over 9400 0-sized `tmp*` files in `/dev/shm`

To be honest, I'm quite surprised I seem to be the only one experiencing this. No funny business here, just deployed with Helm as per instructions.

**Comment by Atinlay** [comment]
You're not the only one, I'm experiencing the same thing for my worker pod:

`$ df -h
Filesystem                     Size  Used Avail Use% Mounted on
overlay                         89G  9.2G   75G  11% /
tmpfs                           64M     0   64M   0% /dev
tmpfs                          3.8G     0  3.8G   0% /sys/fs/cgroup
/dev/mapper/vgpaas-kubernetes  9.8G   49M  9.3G   1% /etc/hosts
/dev/mapper/vgpaas-dockersys    89G  9.2G   75G  11% /etc/hostname
shm                             64M   63M  1.1M  99% /dev/shm
tmpfs                          6.4G   12K  6.4G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                          3.8G     0  3.8G   0% /proc/acpi
tmpfs                          3.8G     0  3.8G   0% /proc/scsi
tmpfs                          3.8G     0  3.8G   0% /sys/firmware`

**Comment by aaronriedel** [comment]
I have the same issue since the latest version. Has anyone found a solition?

**Comment by cybermcm** [comment]
same issue with my simple installation and my proxy node, /dev/shm is full

**Comment by cybermcm** [comment]
some update from my side: I think my problem is that my shm volume gets filled with session files from my monitoring. I'm currently monitoring some of my services which redirect to the Authenik proxy. Due to the check interval of 1 min the session files grow fast in numbers.
This was never a problem until now, something has changed. Due to "auto update" (watchtower) I can't pinpoint the exact version at the moment which causes this behavior.

**Comment by aaronriedel** [comment]
from the changelog of version 2025.4:
```
Sessions are now stored in the database
Previously, sessions were stored by default in the cache. Now, they are stored in the database. This allows for numerous other performance improvements. On high traffic instances, requests to old instances after the upgrade has started will fail to authenticate.
```

**Comment by paradizelost** [comment]
I'm on 2025.6.3 and i'm still having this happen. /dev/shm in the container is filling with session_* files and running out of space. after destroying and rebuilding the proxy outpost container things work fine for a while and rinse repeat.
There was so much there i couldn't run an rm on it because there was too many files.

**Comment by aaronriedel** [comment]
> I'm on 2025.6.3 and i'm still having this happen. /dev/shm in the container is filling with session_* files and running out of space. after destroying and rebuilding the proxy outpost container things work fine for a while and rinse repeat. There was so much there i couldn't run an rm on it because there was too many files.

I also observe the same issue. I have played around with max session duration, but it did not help.

**Comment by rissson** [comment]
Could you actually show the files in there? Nothing interacting with sessions should be written to the filesystem.

**Comment by paradizelost** [comment]
I mean, its just a bunch of session_randomstuff files, 3651 have been created since i posted my message 7 hours ago

<img width="1698" height="686" alt="Image" src="https://github.com/user-attachments/assets/8cedfbd0-43bd-44b0-ae5f-f0750855c4e7" />

**Comment by rissson** [comment]
Ah right, the proxy outpost indeed uses the filesystem to store its sessions

**Comment by paradizelost** [comment]
short term workaround, i set "default-shm-size":"512M" in /etc/docker/daemon.json to buy more time before the issue rears its ugly head, but the core issue is still a problem. I had to do this because Authentik is what is creating the outpost via the docker socket, so i can't manually set it during container creation.

**Comment by bestrocker221** [comment]
Having same issue here, preventing outpost to work. (helm 2025.6.2)
Folder full of sessions files

**Comment by Tom3201** [comment]
Hi.
I'm also running into this issue, so I took a closer look. It seems that the package used for the file system sessions (`github.com/gorilla/sessions`) doesn't include any built-in session cleanup. I suspect that this is why expired session files are not automatically deleted.

**Comment by kazoob** [comment]
I am affected by the same issue. My outpost's shm folder fills up within 5 days.

**Comment by Tom3201** [comment]
The problem should have been resolved or at least reduced since 2025.8.0. Is anyone still experiencing errors, or can the issue be closed?

**Comment by cybermcm** [comment]
@Tom3201: I am on 2025.8.1 and still see session files, but it seems that they get deleted from time to time (it seems 1 time per hour). So working for my setup, thanks

**Comment by rissson** [comment]
Fixed in #15798. Thanks @Tom3201 for the fix :tada:
