### ISSUE TITLE
Authentik not starting after setting new env vars

### ISSUE THREAD

**Issue by sebiweise** [goauthentik/authentik#12250]
**Describe the bug**
Authentik not starting after setting new env vars for the SMTP/email configuration.

**To Reproduce**

1. Install authentik via docker compose
2. Chaneg env vars
3. See error

**Expected behavior**
Authentik should start as usual.

**Screenshots**
![{F5A0DC25-5328-4EF1-96F5-B018A41426C1}](https://github.com/user-attachments/assets/92f08133-8da3-49ee-a3ed-09841e346cbb)

**Logs**
```
ERR error=exit status 1 event=gunicorn failed to start, restarting logger=authentik.router timestamp=2024-12-03T10:30:10+01:00
DBG event=Loaded config logger=authentik.lib.config timestamp=1733218211.2034595 file=/authentik/lib/default.yml
Failed to read config file: ./lifecycle/gunicorn.conf.py
Traceback (most recent call last):
  File "/ak-root/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 110, in get_config_from_filename
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/lifecycle/gunicorn.conf.py", line 15, in <module>
    from authentik.lib.config import CONFIG
  File "/authentik/lib/config.py", line 316, in <module>
    CONFIG = ConfigLoader()
            ^^^^^^^^^^^^^^
  File "/authentik/lib/config.py", line 123, in __init__
    self.update_from_env()
  File "/authentik/lib/config.py", line 245, in update_from_env
    set_path_in_dict(outer, relative_key, attr_value)
  File "/authentik/lib/utils/dict.py", line 24, in set_path_in_dict
    root[path_parts[-1]] = value
    ~~~~^^^^^^^^^^^^^^^^
TypeError: 'Attr' object does not support item assignment
warning error=exit status 1 event=gunicorn process died, restarting logger=authentik.router timestamp=2024-12-03T10:30:11+01:00
ERR error=exit status 1 event=gunicorn failed to start, restarting logger=authentik.router timestamp=2024-12-03T10:30:11+01:00
warning error=authentik starting event=failed to proxy to backend logger=authentik.router timestamp=2024-12-03T10:30:11+01:00
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.10.4
-   Deployment: docker-compose

**Additional context**

**Comment by sebiweise** [comment]
`docker compose run --rm server dump_config` and `docker compose run --rm worker dump_config` is showing the correct output.

**Comment by sebiweise** [comment]
Removing the env var `AUTHENTIK_ERROR_REPORTING` and `AUTHENTIK_ERROR_REPORTING__ENABLED` from my compose and .env file fixed the issue.
