### ISSUE TITLE
All users have insufficient access using ldaps

### ISSUE THREAD

**Issue by RagingFlames** [goauthentik/authentik#12447]
**Describe the bug**
Any user I create including akadmin get the following error:
`ldap_bind: Insufficient access (50)`
when I try and connect to ldap. I have give the user full access to the application and provider
![image](https://github.com/user-attachments/assets/2ff028b9-fd8c-41cf-82bf-c69e48eee212)
![image](https://github.com/user-attachments/assets/c4077288-36bb-40e5-95b6-9ff1fec00278)
This was working in the past, as long as 20 days ago (12/2/2024) but now does not work.

**To Reproduce**

1. Interact with authentik using ldap

**Expected behavior**
Users with permissions are able to query ldap

**Logs**
Jellyfin logs
```
[06:39:43] [WRN] [17] Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin: User Manager could not find an user with such ldapUid, this may not be fatal
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin.Authenticate(String username, String password)
[06:39:43] [WRN] [17] Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin: User Manager could not find an user with such ldapUsername, this may not be fatal
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin.Authenticate(String username, String password)
[06:39:45] [ERR] [17] Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin: Failed to Connect or Bind to server as user cn=testuser,ou=users,dc=mclemo,dc=re
LdapException: Insufficient Access Rights (50) Insufficient Access Rights
LdapException: Matched DN:
[06:39:45] [INF] [17] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for testuser has been denied (IP: 192.168.1.1).
[06:39:45] [ERR] [17] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: Invalid username or password entered. URL POST /Users/authenticatebyname.
[06:41:11] [WRN] [26] Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin: Ldap Test Failed to Connect or Bind to server
LdapException: Insufficient Access Rights (50) Insufficient Access Rights
LdapException: Matched DN:
[06:47:22] [ERR] [22] Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin: Failed to Connect or Bind to server as user cn=akadmin,ou=users,dc=mclemo,dc=re
LdapException: Insufficient Access Rights (50) Insufficient Access Rights
LdapException: Matched DN:
[06:47:22] [INF] [22] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for akadmin has been denied (IP: 192.168.1.1).
[06:47:22] [ERR] [22] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: Invalid username or password entered. URL POST /Users/authenticatebyname.
```

Logs from ldap outpost container
```
{"event":"initialised direct binder","level":"info","logger":"authentik.outpost.ldap.binder.direct","timestamp":"2024-12-22T06:54:08Z"}
{"event":"Update providers","level":"info","logger":"authentik.outpost.ldap","timestamp":"2024-12-22T06:54:08Z"}
{"bindDN":"cn=akadmin,ou=users,dc=mclemo,dc=re","client":"172.17.0.1","event":"Access denied for user","level":"info","requestId":"b6baea95-9575-415a-ba0b-b863bcae00a4","timestamp":"2024-12-22T06:55:21Z"}
{"bindDN":"cn=akadmin,ou=users,dc=mclemo,dc=re","client":"172.17.0.1","event":"Bind request","level":"info","requestId":"b6baea95-9575-415a-ba0b-b863bcae00a4","timestamp":"2024-12-22T06:55:21Z","took-ms":1822}
```

ldapsearch
```
tyler@jellyfin:~$ ldapsearch -x -H ldaps://ldap.mclemo.re -D "cn=akadmin,ou=users,dc=mclemo,dc=re" -w "<MY_PASSWORD_HERE>" -b "" -s base "(objectclass=*)"
ldap_bind: Insufficient access (50)
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.10.4
-   Deployment: docker-compose

**Comment by RagingFlames** [comment]
Updated to 2024.12.1 and this is still an issue.

**Comment by seternate** [comment]
Have the same issue. LDAP worked when first configuring it like stated in the documentation and today (maybe earlier) LDAP stopped working for the ldapsearch user.

authentik version: 2024.10.4

**Comment by benedikt-bartscher** [comment]
I can confirm this is still an issue with latest authentik 2024.12.2

**Comment by 1moere1** [comment]
someone already found a solution to this?

**Comment by RagingFlames** [comment]
Still no fix that I am aware of.

**Comment by skel205** [comment]
I am having this issue in 2024.12.3

**Comment by skel205** [comment]
Restarted my whole vm instance and ran docker-compose up -d again its showing now Connect (Success); Bind (Success); Base Search (Found 13 Entities)

**Comment by tsallou** [comment]
full reboot of my VM also fixed the issue

**Comment by tylerhunt** [comment]
Rebooting did not fix the issue for me.

**Comment by RagingFlames** [comment]
Reset up everything according to the guide again on 2025-02.1, still not working.

**Comment by clbx** [comment]
I’m also having this issue 2025.2.1

**Comment by studyfranco** [comment]
Unfortunately I have the same issue in 2025.2.1...

**Comment by royaltongue** [comment]
Seeing the same problem here

**Comment by GitHanter** [comment]
> Seeing the same problem here
> 
> EDIT: Rebooting fixedf the issue for me thankfully

@royaltongue What service(s) you restarted, cause I'm facing the same issue, I restarted snipe-IT, I still can't login using my user credentials created in Authentik (Those users are successfully synced to snipe-IT)

![Image](https://github.com/user-attachments/assets/100411d7-33a9-432d-aea1-b962e35854a7)

**Comment by RagingFlames** [comment]
I finally got it working, I went to 2025-4 but before updating I deleted all my volumes so it was a completely fresh start. I don't know if there was a problem with the version I originally tried, or if there was some configuration I did that kept slipping thru, but that fixed the problem.
