### ISSUE TITLE
No module found named daphne

### ISSUE THREAD

**Issue by WoutAndAbout** [goauthentik/authentik#12505]
**Describe the bug**
No module found named daphne for pyhton. 
In the venv need to be added a module named daphne.

**To Reproduce**

setup a Authentik instance with debug mode on.

**Expected behavior**
to have the module installed already in the image before deploying it.

**Logs**
```
DBG event=Loaded config logger=authentik.lib.config timestamp=1735316005.8990903 file=/authentik/lib/default.yml
DBG event=Loaded environment variables logger=authentik.lib.config timestamp=1735316005.8994493 count=8
INF event=Starting authentik bootstrap logger=authentik.lib.config timestamp=1735316006.505558
INF event=PostgreSQL connection successful logger=authentik.lib.config timestamp=1735316006.519966
INF event=Redis Connection successful logger=authentik.lib.config timestamp=1735316006.5209436
INF event=Finished authentik bootstrap logger=authentik.lib.config timestamp=1735316006.5210192
warning event=Failed to parse config as int logger=authentik.lib.config timestamp=1735316008.460312 path=postgresql.conn_max_age exc=int() argument must be a string, a bytes-like bject or a real number, not 'type'

INF event=Booting authentik logger=authentik.lib.config timestamp=1735316008.4609842 version=2024.12.1
INF event=Enabled authentik enterprise logger=authentik.lib.config timestamp=1735316008.4641995
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1735316008.4652684 path=authentik.enterprise.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1735316008.4668064 path=authentik.sources.plex.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1735316008.467597 path=authentik.events.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1735316008.4683173 path=authentik.crypto.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1735316008.4695334 path=authentik.enterprise.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1735316008.4705794 path=authentik.sources.kerberos.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1735316008.4722502 path=authentik.providers.scim.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1735316008.4742522 path=authentik.outposts.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1735316008.4763956 path=authentik.sources.ldap.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1735316008.4769795 path=authentik.enterprise.providers.microsoft_entra.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1735316008.478651 path=authentik.stages.authenticator_webauthn.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1735316008.4799423 path=authentik.blueprints.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1735316008.480512 path=authentik.admin.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1735316008.4810727 path=authentik.enterprise.providers.google_workspace.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1735316008.4828928 path=authentik.sources.oauth.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1735316008.4837859 path=authentik.stages.authenticator_totp.settings
Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code

  File "/manage.py", line 52, in <module>

    execute_from_command_line(sys.argv)

  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()

  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()

  File "/ak-root/venv/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)

  File "/ak-root/venv/lib/python3.12/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)

                 ^^^^^^^^^^^^^^^^^^^^^^^

  File "/ak-root/venv/lib/python3.12/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)

  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import 
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'daphne
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.12.1
-   Deployment: docker compose portainer (i had this issue also with normal docker compose)

**Comment by scheibling** [comment]
This was addressed by Jens in another issue (#3093). Debugging is only for development and requires additional packages which are not included in the image likely to keep the size reasonable

If you just want debug logging, set the AUTHENTIK_LOG_LEVEL env variable to trace. Otherwise, build your own image from the repo and remove the --only=dev flag from the poetry command halfway through the Dockerfile

**Comment by BeryJu** [comment]
As mentioned above, `AUTHENTIK_DEBUG` should only be set for debugging and there are other steps to install the dependencies for that, so this error is "intended"
