### ISSUE TITLE
restore of 2021.7.3 backup fails for docker image above 2021.7.3

### ISSUE THREAD

**Issue by trzl47** [goauthentik/authentik#1349]
**Describe the bug**
I have a working docker-compose based setup for tag 2021.7.3 that I can bring down and restore perfectly fine.
If I attempt to restore a backup on any of the 2021.8.x tagged images, i receive an error traceback
```sh
ERROR:  constraint "authentik_sources_ldap_ldapsource_sync_users_password_key" of relation "authentik_sources_ldap_ldapsource" does not exist
```

it seems like an LDAP property mapping missing between versions and that prevents the backup from working?

**To Reproduce**
1. Have all containers down
2. Update `server` and `worker` services in docker-compose file to tag 2021.8.x
3. exec
```sh
    docker-compose up --build -d
```
4. (once all containers have finished startup) 
exec
```sh
    docker-compose run --rm worker restore -i <backup file>
```

**Expected behavior**
based on previous exp, the restore executes successfully with no output

**Screenshots**

**Logs**
traceback output:
```sh
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/manage.py", line 45, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/dbbackup/management/commands/dbrestore.py", line 53, in handle
    self._restore_backup()
  File "/usr/local/lib/python3.9/site-packages/dbbackup/management/commands/dbrestore.py", line 94, in _restore_backup
    self.connector.restore_dump(input_file)
  File "/usr/local/lib/python3.9/site-packages/dbbackup/db/base.py", line 98, in restore_dump
    result = self._restore_dump(dump)
  File "/usr/local/lib/python3.9/site-packages/dbbackup/db/postgresql.py", line 63, in _restore_dump
    stdout, stderr = self.run_command(cmd, stdin=dump, env=self.restore_env)
  File "/usr/local/lib/python3.9/site-packages/dbbackup/db/base.py", line 157, in run_command
    raise exceptions.CommandConnectorError(
dbbackup.db.exceptions.CommandConnectorError: Error running:  psql --dbname=postgresql://authentik:<obfuscated postgresql-key>@postgresql:5432/authentik-postgresql --set ON_ERROR_STOP=on --single-transaction authentik-postgresql 
ERROR:  constraint "authentik_sources_ldap_ldapsource_sync_users_password_key" of relation "authentik_sources_ldap_ldapsource" does not exist

ERROR: 1
```

**Version and Deployment (please complete the following information):**
 - authentik version: version/2021.8.x [e.g. 0.10.0-stable]
 - Deployment: docker-compose [e.g. docker-compose, helm]

**Additional context**
Happy to provide any needed additional info!

**Comment by BeryJu** [comment]
So the database dump file includes all the drop statements at the beginning, but those may obviously change when restoring on a different version. An easy workaround is to just drop the database manually before restoring, and I'll look into integrating that.

**Comment by BeryJu** [comment]
Never mind, it fails with a clean database too as PostgreSQL still tries to drop the old indicies, and django-dbbackup is setting `ON_ERROR_STOP=on`

**Comment by shizunge** [comment]
Hi BeryJu
I am new to authentik, I have questions related.
1. Do we save every settings in the postgresql database? If so that means we can just backup and restore the database directly. 
2. Is there a migration process when we start the authentik server and worker? i.e. if we start a stack with 2021.7, shutdown authentik server and worker, but keep the database running, then start a new authentik server and worker 2021.8, trying to connect to the existing database. Would the server and worker automatically upgrade the database scheme from 2021.7 to 2021.8? (I know that downgrade is not possbile)
Thanks

**Comment by ovizii** [comment]
I'm not sure if this is the same problem, if not please let me know and I'll open a different thread. 

running authentik  2021.10.1 via docker-compose and every day I see: backup status as failed.

![image](https://user-images.githubusercontent.com/837902/139852298-ae723747-c7b3-45b1-b1a3-da0d799f1218.png)

if I click the links next to backup status I see:
![image](https://user-images.githubusercontent.com/837902/139852370-119e18a9-fdbc-49d2-97c8-d79affd4eaf6.png)


these are the details:
```
Traceback (most recent call last):
File "/authentik/core/tasks.py", line 82, in backup_database
management.call_command("dbbackup", quiet=True, stdout=out)
File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 181, in call_command
return command.execute(*args, **defaults)
File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
output = self.handle(*args, **options)
File "/usr/local/lib/python3.9/site-packages/dbbackup/utils.py", line 114, in wrapper
func(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/dbbackup/management/commands/dbbackup.py", line 66, in handle
self._save_new_backup(database)
File "/usr/local/lib/python3.9/site-packages/dbbackup/management/commands/dbbackup.py", line 93, in _save_new_backup
self.write_to_storage(outputfile, filename)
File "/usr/local/lib/python3.9/site-packages/dbbackup/management/commands/_base.py", line 82, in write_to_storage
self.storage.write_file(file, path)
File "/usr/local/lib/python3.9/site-packages/dbbackup/storage.py", line 82, in write_file
self.storage.save(name=filename, content=filehandle)
File "/usr/local/lib/python3.9/site-packages/django/core/files/storage.py", line 54, in save
return self._save(name, content)
File "/usr/local/lib/python3.9/site-packages/storages/backends/s3boto3.py", line 458, in _save
obj = self.bucket.Object(name)
File "/usr/local/lib/python3.9/site-packages/storages/backends/s3boto3.py", line 385, in bucket
self._bucket = self.connection.Bucket(self.bucket_name)
File "/usr/local/lib/python3.9/site-packages/storages/backends/s3boto3.py", line 352, in connection
self._connections.connection = session.resource(
File "/usr/local/lib/python3.9/site-packages/boto3/session.py", line 396, in resource
client = self.client(
File "/usr/local/lib/python3.9/site-packages/boto3/session.py", line 270, in client
return self._session.create_client(
File "/usr/local/lib/python3.9/site-packages/botocore/session.py", line 841, in create_client
client = client_creator.create_client(
File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 88, in create_client
client_args = self._get_client_args(
File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 357, in _get_client_args
return args_creator.get_client_args(
File "/usr/local/lib/python3.9/site-packages/botocore/args.py", line 99, in get_client_args
endpoint = endpoint_creator.create_endpoint(
File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 286, in create_endpoint
raise ValueError("Invalid endpoint: %s" % endpoint_url)
Invalid endpoint:
```

**Comment by BeryJu** [comment]
Hi @ovizii, this is a different bug in 2021.10.1, already fixed in master but not released yet.
