### ISSUE TITLE
Browsing to /admin/users page results in internal server error on RC3

### ISSUE THREAD

**Issue by samip5** [goauthentik/authentik#1909]
**Describe the bug**
Browsing to https://authentik.company/if/admin/#/identity/users results in an API request failed message, with internal server error visible in authentik container logs.

**To Reproduce**
1. Log-in to Authentik with admin user
2. Go to https://authentik.company/if/admin/#/identity/users
3. See error

**Expected behavior**
Expected it to list users, which it currently does not due to an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/1703002/145674250-025a41c0-ce1c-43ba-97e5-5f02a7522559.png)

**Logs**
<details>
    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/usr/local/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/pagination.py", line 204, in paginate_queryset
    self.page = paginator.page(page_number)
  File "/usr/local/lib/python3.10/site-packages/django/core/paginator.py", line 76, in page
    number = self.validate_number(number)
  File "/usr/local/lib/python3.10/site-packages/django/core/paginator.py", line 54, in validate_number
    if number > self.num_pages:
  File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/site-packages/django/core/paginator.py", line 103, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/site-packages/django/core/paginator.py", line 97, in count
    return c()
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 416, in count
    return self.query.get_count(using=self.db)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 516, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 501, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1189, in execute_sql
    sql, params = self.as_sql()
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 547, in as_sql
    where, w_params = self.compile(self.where) if self.where is not None else ('', [])
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 463, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/where.py", line 81, in as_sql
    sql, params = compiler.compile(child)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 463, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/lookups.py", line 543, in as_sql
    raise ValueError(
The QuerySet value for an isnull lookup must be True or False.
```
</details>

Container log snippet:
```
{"event": "Internal Server Error: /api/v3/core/users/", "exc_info": ["<class 'ValueError'>", "ValueError('The QuerySet value for an isnull lookup must be True or False.')", "<traceback object at 0x7efeb48464c0>"], "level": "error", "logger": "django.request", "timestamp": 1639220589.3142145}
```

**Version and Deployment:**
 - authentik version: 2021.12.1-rc3
 - Deployment: Docker with Ansible

**Additional context**
It worked fine in RC1-RC2.

**Comment by BeryJu** [comment]
fixed by 340a9bc8ee7ff65cb869fe59ec91609692b710ae
