### ISSUE TITLE
Add Key via Webauthn not possible

### ISSUE THREAD

**Issue by joshua-schnabel** [goauthentik/authentik#1936]
Thank you for the quick implementation of my proposed [change](https://github.com/goauthentik/authentik/issues/1921). However, it seems that the change has broken something.

**Describe the bug**
It is not possible to use a Yubikey as a second factor via webauthn.

**To Reproduce**
1. Go to User Settings
2. Click on MFA Devices
3. Click on Enroll -> Security key authenticator

**Expected behavior**
Here the operating system popup should appear prompting to add the second factor. 

**Screenshots**
![grafik](https://user-images.githubusercontent.com/5574446/146089833-5a737b61-5a52-44e6-aba0-521d54fd3601.png)

**Logs**
```
{"event":"/static/dist/empty-state.css","host":"login.1js.de","level":"info","logger":"authentik.router","method":"GET","remote":"2003:e5:b712:4d00:b98f:15d0:fdef:1a3f","timestamp":"2021-12-14T19:53:33Z","took":392978}
{"event":"/static/dist/authentik.css","host":"login.1js.de","level":"info","logger":"authentik.router","method":"GET","remote":"2003:e5:b712:4d00:b98f:15d0:fdef:1a3f","timestamp":"2021-12-14T19:53:33Z","took":505572}
{"event":"/static/dist/spinner.css","host":"login.1js.de","level":"info","logger":"authentik.router","method":"GET","remote":"2003:e5:b712:4d00:b98f:15d0:fdef:1a3f","timestamp":"2021-12-14T19:53:33Z","took":6194471}
{"event":"/static/dist/poly.js","host":"login.1js.de","level":"info","logger":"authentik.router","method":"GET","remote":"2003:e5:b712:4d00:b98f:15d0:fdef:1a3f","timestamp":"2021-12-14T19:53:33Z","took":7133669}
{"event":"/static/dist/page.css","host":"login.1js.de","level":"info","logger":"authentik.router","method":"GET","remote":"2003:e5:b712:4d00:b98f:15d0:fdef:1a3f","timestamp":"2021-12-14T19:53:33Z","took":814389}
{"event":"/static/dist/patternfly-base.css","host":"login.1js.de","level":"info","logger":"authentik.router","method":"GET","remote":"2003:e5:b712:4d00:b98f:15d0:fdef:1a3f","timestamp":"2021-12-14T19:53:33Z","took":2947330}
{"event":"/static/dist/flow/FlowInterface.js","host":"login.1js.de","level":"info","logger":"authentik.router","method":"GET","remote":"2003:e5:b712:4d00:b98f:15d0:fdef:1a3f","timestamp":"2021-12-14T19:53:33Z","took":16547569}
{"event":"/static/dist/assets/fonts/RedHatText/RedHatText-Regular.woff2","host":"login.1js.de","level":"info","logger":"authentik.router","method":"GET","remote":"2003:e5:b712:4d00:b98f:15d0:fdef:1a3f","timestamp":"2021-12-14T19:53:35Z","took":199360}
{"event":"/static/dist/assets/icons/icon.png","host":"login.1js.de","level":"info","logger":"authentik.router","method":"GET","remote":"2003:e5:b712:4d00:b98f:15d0:fdef:1a3f","timestamp":"2021-12-14T19:53:37Z","took":165085}
{"event":"/static/dist/flow/locale-en-798772ef.js","host":"login.1js.de","level":"info","logger":"authentik.router","method":"GET","remote":"2003:e5:b712:4d00:b98f:15d0:fdef:1a3f","timestamp":"2021-12-14T19:53:40Z","took":2219304}
{"event":"/static/dist/flow/locale-fr_FR-df471a43.js","host":"login.1js.de","level":"info","logger":"authentik.router","method":"GET","remote":"2003:e5:b712:4d00:b98f:15d0:fdef:1a3f","timestamp":"2021-12-14T19:53:40Z","took":2962599}
{"event":"/static/dist/flow/locale-pseudo-LOCALE-7c6de990.js","host":"login.1js.de","level":"info","logger":"authentik.router","method":"GET","remote":"2003:e5:b712:4d00:b98f:15d0:fdef:1a3f","timestamp":"2021-12-14T19:53:40Z","took":10029120}
{"event":"/static/dist/flow/api-6e055e14.js","host":"login.1js.de","level":"info","logger":"authentik.router","method":"GET","remote":"2003:e5:b712:4d00:b98f:15d0:fdef:1a3f","timestamp":"2021-12-14T19:53:40Z","took":5418113}
{"event":"/static/dist/flow/vendor-79b059de.js","host":"login.1js.de","level":"info","logger":"authentik.router","method":"GET","remote":"2003:e5:b712:4d00:b98f:15d0:fdef:1a3f","timestamp":"2021-12-14T19:53:40Z","took":33004104}
{"event": "/-/health/live/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 21, "remote": "127.0.0.1", "request_id": "104b65b1483949cea5dbf17117ff9133", "runtime": 13, "scheme": "http", "status": 204, "timestamp": "2021-12-14T19:53:41.713525", "user": "", "user_agent": "goauthentik.io go proxy healthcheck"}
{"event": "f(exec): Continuing existing plan", "flow_slug": "default-authenticator-webauthn-setup", "host": "login.1js.de", "level": "debug", "logger": "authentik.flows.views.executor", "pid": 21, "request_id": "4e2f31622a7c4e9fa3368ba251ec63c9", "timestamp": "2021-12-14T19:53:46.497364"}
{"current_stage": "<AuthenticateWebAuthnStage: WebAuthn Authenticator Setup Stage default-authenticator-webauthn-setup>", "event": "f(exec): Current stage", "flow_slug": "default-authenticator-webauthn-setup", "host": "login.1js.de", "level": "debug", "logger": "authentik.flows.views.executor", "pid": 21, "request_id": "4e2f31622a7c4e9fa3368ba251ec63c9", "timestamp": "2021-12-14T19:53:46.498437"}
{"event":"/static/dist/assets/fonts/RedHatDisplay/RedHatDisplay-Medium.woff2","host":"login.1js.de","level":"info","logger":"authentik.router","method":"GET","remote":"2003:e5:b712:4d00:b98f:15d0:fdef:1a3f","timestamp":"2021-12-14T19:53:46Z","took":1933310}
{"event": "f(exec): Passing GET", "flow_slug": "default-authenticator-webauthn-setup", "host": "login.1js.de", "level": "debug", "logger": "authentik.flows.views.executor", "pid": 21, "request_id": "4e2f31622a7c4e9fa3368ba251ec63c9", "stage": "<AuthenticateWebAuthnStage: WebAuthn Authenticator Setup Stage default-authenticator-webauthn-setup>", "timestamp": "2021-12-14T19:53:46.499104", "view_class": "authentik.stages.authenticator_webauthn.stage.AuthenticatorWebAuthnStageView"}
{"event": "TypeError(\"a bytes-like object is required, not 'str'\")", "flow_slug": "default-authenticator-webauthn-setup", "host": "login.1js.de", "level": "warning", "logger": "authentik.flows.views.executor", "pid": 21, "request_id": "4e2f31622a7c4e9fa3368ba251ec63c9", "timestamp": "2021-12-14T19:53:46.513591"}
{"event": "/api/v3/root/config/", "host": "login.1js.de", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 21, "remote": "2003:e5:b712:4d00:b98f:15d0:fdef:1a3f", "request_id": "76c00043ceac4628ab00f6180184bd3f", "runtime": 68, "scheme": "https", "status": 200, "timestamp": "2021-12-14T19:53:46.524397", "user": "akadmin", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"}
{"event": "/api/v3/core/tenants/current/", "host": "login.1js.de", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 21, "remote": "2003:e5:b712:4d00:b98f:15d0:fdef:1a3f", "request_id": "c5a7c4ad209e4784a4a94ec5ba6c458b", "runtime": 93, "scheme": "https", "status": 200, "timestamp": "2021-12-14T19:53:46.553390", "user": "akadmin", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"}
{"event":"/static/dist/assets/images/flow_background.jpg","host":"login.1js.de","level":"info","logger":"authentik.router","method":"GET","remote":"2003:e5:b712:4d00:b98f:15d0:fdef:1a3f","timestamp":"2021-12-14T19:53:46Z","took":59706775}
{"action": "system_exception", "client_ip": "2003:e5:b712:4d00:b98f:15d0:fdef:1a3f", "context": {"http_request": {"args": {"query": "next=%2Fif%2Fuser%2F%23%2Fsettings%3Bpage-mfa"}, "method": "GET", "path": "/api/v3/flows/executor/default-authenticator-webauthn-setup/"}, "message": "Traceback (most recent call last):\n  File \"/authentik/flows/views/executor.py\", line 284, in get\n    stage_response = self.current_stage_view.get(request, *args, **kwargs)\n  File \"/authentik/stages/authenticator_webauthn/stage.py\", line 114, in get\n    return super().get(request, *args, **kwargs)\n  File \"/authentik/flows/stage.py\", line 67, in get\n    challenge = self._get_challenge(*args, **kwargs)\n  File \"/authentik/flows/stage.py\", line 120, in _get_challenge\n    challenge = self.get_challenge(*args, **kwargs)\n  File \"/authentik/stages/authenticator_webauthn/stage.py\", line 105, in get_challenge\n    \"registration\": loads(options_to_json(registration_options)),\n  File \"/usr/local/lib/python3.10/site-packages/webauthn/helpers/options_to_json.py\", line 48, in options_to_json\n    return json.dumps(converter.unstructure(options))\n  File \"/usr/local/lib/python3.10/site-packages/cattr/converters.py\", line 197, in unstructure\n    return self._unstructure_func.dispatch(\n  File \"<cattrs generated unstructure webauthn.helpers.structs.PublicKeyCredentialCreationOptions>\", line 4, in unstructure_PublicKeyCredentialCreationOptions\n    'user': unstructure_user(instance.user),\n  File \"<cattrs generated unstructure webauthn.helpers.structs.PublicKeyCredentialUserEntity>\", line 3, in unstructure_PublicKeyCredentialUserEntity\n    'id': unstructure_id(instance.id),\n  File \"/usr/local/lib/python3.10/site-packages/webauthn/helpers/bytes_to_base64url.py\", line 8, in bytes_to_base64url\n    return urlsafe_b64encode(val).decode(\"utf-8\").replace(\"=\", \"\")\n  File \"/usr/local/lib/python3.10/base64.py\", line 118, in urlsafe_b64encode\n    return b64encode(s).translate(_urlsafe_encode_translation)\n  File \"/usr/local/lib/python3.10/base64.py\", line 58, in b64encode\n    encoded = binascii.b2a_base64(s, newline=False)\na bytes-like object is required, not 'str'"}, "event": "Created Event", "host": "login.1js.de", "level": "debug", "logger": "authentik.events", "pid": 21, "request_id": "4e2f31622a7c4e9fa3368ba251ec63c9", "timestamp": "2021-12-14T19:53:46.737532", "user": {"email": "a****@j****.de", "pk": 1, "username": "akadmin"}}
{"event": "Task published", "host": "login.1js.de", "level": "info", "logger": "authentik.root.celery", "pid": 21, "request_id": "4e2f31622a7c4e9fa3368ba251ec63c9", "task_id": "9b264aa7-7c67-4f44-a2b9-40d7b0cc6c82", "task_name": "authentik.events.tasks.event_notification_handler", "timestamp": "2021-12-14T19:53:46.747252"}
{"event": "/api/v3/flows/executor/default-authenticator-webauthn-setup/?query=next%3D%252Fif%252Fuser%252F%2523%252Fsettings%253Bpage-mfa", "host": "login.1js.de", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 21, "remote": "2003:e5:b712:4d00:b98f:15d0:fdef:1a3f", "request_id": "4e2f31622a7c4e9fa3368ba251ec63c9", "runtime": 315, "scheme": "https", "status": 200, "timestamp": "2021-12-14T19:53:46.773001", "user": "akadmin", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"}
{"event":"/static/dist/assets/icons/icon_left_brand.svg","host":"login.1js.de","level":"info","logger":"authentik.router","method":"GET","remote":"2003:e5:b712:4d00:b98f:15d0:fdef:1a3f","timestamp":"2021-12-14T19:53:52Z","took":490384}
{"event":"/static/dist/assets/icons/icon.png","host":"login.1js.de","level":"info","logger":"authentik.router","method":"GET","remote":"2003:e5:b712:4d00:b98f:15d0:fdef:1a3f","timestamp":"2021-12-14T19:53:52Z","took":942715}
```

**Version and Deployment (please complete the following information):**
 - authentik version: dev-server:gh-next
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
Cheers for the report, could you post the full stacktrace for this? It can be found in the event log

**Comment by joshua-schnabel** [comment]
The only thing I found that looks like stacktrace I already posted above. Here is the line: 

```
{"action": "system_exception", "client_ip": "2003:e5:b712:4d00:b98f:15d0:fdef:1a3f", "context": {"http_request": {"args": {"query": "next=%2Fif%2Fuser%2F%23%2Fsettings%3Bpage-mfa"}, "method": "GET", "path": "/api/v3/flows/executor/default-authenticator-webauthn-setup/"}, "message": "Traceback (most recent call last):
  File \"/authentik/flows/views/executor.py\", line 284, in get
    stage_response = self.current_stage_view.get(request, *args, **kwargs)
  File \"/authentik/stages/authenticator_webauthn/stage.py\", line 114, in get
    return super().get(request, *args, **kwargs)
  File \"/authentik/flows/stage.py\", line 67, in get
    challenge = self._get_challenge(*args, **kwargs)
  File \"/authentik/flows/stage.py\", line 120, in _get_challenge
    challenge = self.get_challenge(*args, **kwargs)
  File \"/authentik/stages/authenticator_webauthn/stage.py\", line 105, in get_challenge
    \"registration\": loads(options_to_json(registration_options)),
  File \"/usr/local/lib/python3.10/site-packages/webauthn/helpers/options_to_json.py\", line 48, in options_to_json
    return json.dumps(converter.unstructure(options))
  File \"/usr/local/lib/python3.10/site-packages/cattr/converters.py\", line 197, in unstructure
    return self._unstructure_func.dispatch(
  File \"<cattrs generated unstructure webauthn.helpers.structs.PublicKeyCredentialCreationOptions>\", line 4, in unstructure_PublicKeyCredentialCreationOptions
    'user': unstructure_user(instance.user),
  File \"<cattrs generated unstructure webauthn.helpers.structs.PublicKeyCredentialUserEntity>\", line 3, in unstructure_PublicKeyCredentialUserEntity
    'id': unstructure_id(instance.id),
  File \"/usr/local/lib/python3.10/site-packages/webauthn/helpers/bytes_to_base64url.py\", line 8, in bytes_to_base64url
    return urlsafe_b64encode(val).decode(\"utf-8\").replace(\"=\", \"\")
  File \"/usr/local/lib/python3.10/base64.py\", line 118, in urlsafe_b64encode
    return b64encode(s).translate(_urlsafe_encode_translation)
  File \"/usr/local/lib/python3.10/base64.py\", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
a bytes-like object is required, not 'str'"}, "event": "Created Event", "host": "login.1js.de", "level": "debug", "logger": "authentik.events", "pid": 21, "request_id": "4e2f31622a7c4e9fa3368ba251ec63c9", "timestamp": "2021-12-14T19:53:46.737532", "user": {"email": "a****@j****.de", "pk": 1, "username": "akadmin"}}
```

These are the logs I got from the "server" part of the application via "docker logs". The worker had nothing special in the log data. If these are the wrong logs, where can I find the ones you need?

**Comment by joshua-schnabel** [comment]
The moment I sent the top post, I realized what you were asking for. Here again the stacktrace from the event log. 
```
Traceback (most recent call last):
  File "/authentik/flows/views/executor.py", line 284, in get
    stage_response = self.current_stage_view.get(request, *args, **kwargs)
  File "/authentik/stages/authenticator_webauthn/stage.py", line 114, in get
    return super().get(request, *args, **kwargs)
  File "/authentik/flows/stage.py", line 67, in get
    challenge = self._get_challenge(*args, **kwargs)
  File "/authentik/flows/stage.py", line 120, in _get_challenge
    challenge = self.get_challenge(*args, **kwargs)
  File "/authentik/stages/authenticator_webauthn/stage.py", line 105, in get_challenge
    "registration": loads(options_to_json(registration_options)),
  File "/usr/local/lib/python3.10/site-packages/webauthn/helpers/options_to_json.py", line 48, in options_to_json
    return json.dumps(converter.unstructure(options))
  File "/usr/local/lib/python3.10/site-packages/cattr/converters.py", line 197, in unstructure
    return self._unstructure_func.dispatch(
  File "<cattrs generated unstructure webauthn.helpers.structs.PublicKeyCredentialCreationOptions>", line 4, in unstructure_PublicKeyCredentialCreationOptions
    'user': unstructure_user(instance.user),
  File "<cattrs generated unstructure webauthn.helpers.structs.PublicKeyCredentialUserEntity>", line 3, in unstructure_PublicKeyCredentialUserEntity
    'id': unstructure_id(instance.id),
  File "/usr/local/lib/python3.10/site-packages/webauthn/helpers/bytes_to_base64url.py", line 8, in bytes_to_base64url
    return urlsafe_b64encode(val).decode("utf-8").replace("=", "")
  File "/usr/local/lib/python3.10/base64.py", line 118, in urlsafe_b64encode
    return b64encode(s).translate(_urlsafe_encode_translation)
  File "/usr/local/lib/python3.10/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
a bytes-like object is required, not 'str'
```
