### ISSUE TITLE
Authentik 2021.12.5 server crashes (docker-compose)

### ISSUE THREAD

**Issue by sdimovv** [goauthentik/authentik#2099]
First of all just want to say - AWESOME WORK! I love this project.

**Describe the bug**
Upon starting the server crashes

**To Reproduce**
1. Get the latest `docker-compose.yml` from the `master` branch
2. Create an `.env` file
```
PG_PASS=...
AUTHENTIK_SECRET_KEY=...
AUTHENTIK_ERROR_REPORTING__ENABLED=true
AK_ADMIN_PASS=...
# AUTHENTIK_TAG=2021.12.4
```
3. Invoke `docker-compose up`

**Expected behavior**
Normal startup. 
Problem does not exist when using version `2021.12.04` (tested by uncommenting `AUTHENTIK_TAG=2021.12.4` in the `.env` file after a `docker-compose down && docker system prune --all -f && docker volume rm -f $(docker volume ls)` )

**Screenshots**
N/A

**Logs**
```
server_1       | {"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1642469372.2547066, "file": "/authentik/lib/default.yml"}
server_1       | {"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1642469372.25498, "count": 7}
server_1       | {"event": "Bootstrap completed", "level": "info", "logger": "bootstrap"}
server_1       | {"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1642469372.4363596, "file": "/authentik/lib/default.yml"}
server_1       | {"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1642469372.436614, "count": 7}
server_1       | 2022-01-18 01:29.32 [info     ] applying django migrations
server_1       | 2022-01-18 01:29.32 [info     ] waiting to acquire database lock
server_1       | 2022-01-18 01:29.33 [debug    ] sending event to sentry        exc=AttributeError("'int' object has no attribute 'encode'") source_logger=None
server_1       | Traceback (most recent call last):
server_1       |   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
server_1       |     return _run_code(code, main_globals, None,
server_1       |   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
server_1       |     exec(code, run_globals)
server_1       |   File "/lifecycle/migrate.py", line 91, in <module>
server_1       |     execute_from_command_line(["", "migrate"])
server_1       |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
server_1       |     utility.execute()
server_1       |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 369, in execute
server_1       |     settings.INSTALLED_APPS
server_1       |   File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 84, in __getattr__
server_1       |     self._setup(name)
server_1       |   File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 71, in _setup
server_1       |     self._wrapped = Settings(settings_module)
server_1       |   File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 179, in __init__
server_1       |     mod = importlib.import_module(self.SETTINGS_MODULE)
server_1       |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
server_1       |     return _bootstrap._gcd_import(name[level:], package, level)
server_1       |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
server_1       |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
server_1       |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
server_1       |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
server_1       |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
server_1       |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
server_1       |   File "/authentik/root/settings.py", line 428, in <module>
server_1       |     set_tag("authentik.uuid", sha512(SECRET_KEY.encode("ascii")).hexdigest()[:16])
server_1       | AttributeError: 'int' object has no attribute 'encode'
authentik_server_1 exited with code 1
````

**Version and Deployment (please complete the following information):**
 - authentik version:2021.12.5
 - Deployment: docker-compose

**Additional context**
N/A

**Comment by vmsman** [comment]
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.server.ports contains an invalid type, it should be a number, or an object

**Comment by BeryJu** [comment]
@sdimovv the error is caused by the secret_key you're using being purely numerical, or at least it is being parsed by python as such. This will be fixed, but as a workaround you can can (and should) use a secret key with alpha-numerics and symbols.

@vmsman Your issue is unrelated, please open a separate issue

**Comment by sdimovv** [comment]
> @sdimovv the error is caused by the secret_key you're using being purely numerical, or at least it is being parsed by python as such. This will be fixed, but as a workaround you can can (and should) use a secret key with alpha-numerics and symbols.
> 
> @vmsman Your issue is unrelated, please open a separate issue

Oh, interesting. Yes, I wanted to test it on my machine and could not be bothered to generate a secure password, so I used '123'. Thanks for solving this.
