### ISSUE TITLE
Text read only prompt causes JSON serialization exception if placeholder value doesn't already exist in context

### ISSUE THREAD

**Issue by sevmonster** [goauthentik/authentik#2572]
**Describe the bug**
Read only text prompts with a placeholder value cause an exception when saving the flow if there is not already a value in the plan/prompt context. The error appears to be invisible to the user and non-fatal in normal flows but blocks submission in the user settings flow and breaks the inspector with a 500 error.

**To Reproduce**
1. Set up any flow with a read only text prompt with a placeholder (expression or not)
2. Try to submit the flow

**Screenshots**
![Screenshot_20220322-233011_Kiwi_Browser](https://user-images.githubusercontent.com/16788697/159624968-7813eace-6c00-44b8-9e5f-52409e100b91.png)
![Screenshot_20220322-233016_Kiwi_Browser](https://user-images.githubusercontent.com/16788697/159624990-593b935a-9071-4190-a8ee-c764f4235887.png)

**Logs**
<details>
    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 451, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 284, in _get_response_async
    response = await sync_to_async(
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/usr/local/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.10/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/usr/local/lib/python3.10/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
Object of type type is not JSON serializable
```
</details>

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.3.3 dev-server gh-master
 - Deployment: docker-compose

**Additional context**
<details><summary>Test flow</summary><pre>{"version": 1, "entries": [{"identifiers": {"pk": "d8a7768b-f251-43ff-baf2-948c70d4df80", "slug": "test"}, "model": "authentik_flows.flow", "attrs": {"name": "test-bug", "title": "test", "designation": "stage_configuration", "cache_count": 1, "policy_engine_mode": "any", "compatibility_mode": false}}, {"identifiers": {"pk": "8ead8ee8-64a0-499b-b243-cddcdc77a64c"}, "model": "authentik_stages_prompt.prompt", "attrs": {"field_key": "test-prompt", "label": "test", "type": "text_read_only", "required": false, "placeholder": "return 'hello'", "order": 0, "sub_text": "", "placeholder_expression": true}}, {"identifiers": {"pk": "7079cf8a-3065-464f-a8a2-37088e87bf0d", "name": "deny-if"}, "model": "authentik_stages_deny.denystage", "attrs": {"meta_model_name": "authentik_stages_deny.denystage"}}, {"identifiers": {"pk": "fb9eb380-74b5-487d-858f-012498d10244", "name": "test"}, "model": "authentik_stages_prompt.promptstage", "attrs": {"meta_model_name": "authentik_stages_prompt.promptstage", "fields": ["8ead8ee8-64a0-499b-b243-cddcdc77a64c"], "validation_policies": []}}, {"identifiers": {"pk": "71bba914-7135-44d2-9359-3ce1db0b056e", "target": "d8a7768b-f251-43ff-baf2-948c70d4df80", "stage": "fb9eb380-74b5-487d-858f-012498d10244", "order": 0}, "model": "authentik_flows.flowstagebinding", "attrs": {"evaluate_on_plan": true, "re_evaluate_policies": false, "policy_engine_mode": "any", "invalid_response_action": "retry"}}, {"identifiers": {"pk": "9bf60ebc-4aba-4a07-b737-f5a67b4cc960", "target": "d8a7768b-f251-43ff-baf2-948c70d4df80", "stage": "7079cf8a-3065-464f-a8a2-37088e87bf0d", "order": 1}, "model": "authentik_flows.flowstagebinding", "attrs": {"evaluate_on_plan": true, "re_evaluate_policies": false, "policy_engine_mode": "any", "invalid_response_action": "retry"}}]}<pre>
</details>

**Comment by sevmonster** [comment]
ed: Can't replicate in user settings with test flow, but this happens for my production flow:
![Screenshot_20220322-234844_Kiwi_Browser](https://user-images.githubusercontent.com/16788697/159626239-cdf8a836-85e5-44f1-b1cd-b49964385b51.png)

**Comment by sevmonster** [comment]
> I wasn't able to reproduce the error with the flow you uploaded

At all? That's interesting. I have seen it occur on Chromium  browsers (Kiwi and Ungoogled Chromium latest builds) if that helps.

>(thanks for the detailed report with stacktrace and flow btw)

👍

>what does the placeholder in your production flow look like?

It is a username field with this expression placeholder:
```python3
try:
  return request.user.username
except:
  return ''
```
It's necessary so that the prompt stage validation has the username in the prompt context; I could use `user` in the update settings flow, but use the same stage in my enroll flow where `user` doesn't exist yet.

Changing it to a text prompt allows it to go through fine, where I get the error if it is read only.

![Screenshot_20220323-101430_Kiwi_Browser_1](https://user-images.githubusercontent.com/16788697/159735151-d5be4694-1d48-4133-a674-9b7841d90d0f.png)
![Screenshot_20220323-101332_Kiwi_Browser](https://user-images.githubusercontent.com/16788697/159735153-c91c2031-d6d3-48e1-8a48-25113c820aae.png)

[user-settings.akflow](https://github.com/goauthentik/authentik/files/8334275/user-settings.akflow.txt)

**Comment by sevmonster** [comment]
I pulled the latest master and with the same code am now getting the below. I believe the error is happening with `prompt_data['email']` being the `empty` object instead of a string. Based on your commit I don't think that should be happening though? `username` being what it is is also curious.

### Event info

#### Binding
|||
|---|---|
|UID|5e5a9a59132f4ef085b47c89e9705fad|
|Name|Binding - #None to Policy prompt-user-settings-post|
|App|authentik_policies|
|Model Name|policybinding|

#### Request
##### Object:
|||
|---|---|
UID|8e4bd37d6de24c9b9b7edfbca457f32b
Name|PolicyBindingModel object (8e4bd37d-6de2-4c9b-9b7e-dfbca457f32b)
App|authentik_policies
Model Name|policybindingmodel

##### Context:
```json
{
    "name": "sev",
    "email": "sev@example.com",
    "username": "rest_framework.fields.empty",
    "component": "ak-stage-prompt",
    "attributes": {
        "sn": "sev",
        "settings": {
            "locale": ""
        },
        "givenName": "",
        "verification-email": "test@example.com"
    },
    "prompt_data": {
        "name": "sev",
        "email": "sev@example.com",
        "username": "rest_framework.fields.empty",
        "component": "ak-stage-prompt",
        "attributes": {
            "sn": "sev",
            "settings": {
                "locale": ""
            },
            "givenName": "",
            "verification-email": "test@example.com"
        }
    }
}
```
#### Exception
```
Traceback (most recent call last):
  File "prompt-user-settings-post", line 26, in <module>
  File "prompt-user-settings-post", line 21, in handler
type object 'empty' has no attribute 'lower'
```

#### Context
```json
{
    "binding": {
        "pk": "5e5a9a59132f4ef085b47c89e9705fad",
        "app": "authentik_policies",
        "name": "Binding - #None to Policy prompt-user-settings-post",
        "model_name": "policybinding"
    },
    "message": "Traceback (most recent call last):\n  File \"prompt-user-settings-post\", line 26, in <module>\n  File \"prompt-user-settings-post\", line 21, in handler\ntype object 'empty' has no attribute 'lower'",
    "request": {
        "obj": {
            "pk": "8e4bd37d6de24c9b9b7edfbca457f32b",
            "app": "authentik_policies",
            "name": "PolicyBindingModel object (8e4bd37d-6de2-4c9b-9b7e-dfbca457f32b)",
            "model_name": "policybindingmodel"
        },
        "user": {
            "pk": 4,
            "email": "sev@example.com",
            "username": "sev"
        },
        "debug": false,
        "context": {
            "name": "sev",
            "email": "sev@example.com",
            "username": "rest_framework.fields.empty",
            "component": "ak-stage-prompt",
            "attributes": {
                "sn": "sev",
                "settings": {
                    "locale": ""
                },
                "givenName": "",
                "verification-email": "test@example.com"
            },
            "prompt_data": {
                "name": "sev",
                "email": "sev@example.com",
                "username": "rest_framework.fields.empty",
                "component": "ak-stage-prompt",
                "attributes": {
                    "sn": "sev",
                    "settings": {
                        "locale": ""
                    },
                    "givenName": "",
                    "verification-email": "test@example.com"
                }
            }
        },
        "http_request": null
    },
    "policy_uuid": "df58ab66c46c48998486bc1b1a7e4bed",
    "http_request": {
        "args": {
            "query": ""
        },
        "path": "/api/v3/flows/executor/user-settings/",
        "method": "POST"
    }
}
```

#### User
```json
{
    "pk": 4,
    "email": "sev@example.com",
    "username": "sev"
}
```
