### ISSUE TITLE
Startup database check fails with IPv6

### ISSUE THREAD

**Issue by btrepp** [goauthentik/authentik#2623]
I'm not 100% sure why this is yet, but the server is crashing as below.

```
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1648637914.0871172, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1648637914.0892565, "count": 49}
{"event": "Starting authentik bootstrap", "level": "info", "logger": "__main__", "timestamp": 1648637914.0903296}
{"event": "PostgreSQL connection successful", "level": "info", "logger": "__main__", "timestamp": 1648637914.1039495}
{"event": "Redis Connection successful", "level": "info", "logger": "__main__", "timestamp": 1648637914.1044345}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/lifecycle/wait_for_db.py", line 66, in <module>
    redis = Redis.from_url(REDIS_URL)
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 852, in from_url
    connection_pool = ConnectionPool.from_url(url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 1258, in from_url
    url_options = parse_url(url)
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 1152, in parse_url
    url = urlparse(url)
  File "/usr/local/lib/python3.10/urllib/parse.py", line 393, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "/usr/local/lib/python3.10/urllib/parse.py", line 484, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
```

values.yaml
```
envFrom:
        - secretRef:
            name: authentik-secrets
        postgresql:
          enabled: true
          image: 
            repository: postgres
            tag: 11.15
          persistence:
            existingClaim: "pvc-authentik-postgres"
          existingSecret: "authentik-postgres"
        redis:
          enabled: true

          image:
            repository: redis
            tag: 6.2.6

          master:
            persistence:
              existingClaim: "pvc-authentik-redis"
          existingSecret: "authentik-redis"
```

I'm using existign claims and secrets to be a bit more declarative, and have had to override some images to make it work on arm, but those are for the data layer.

This might not be an issue with the helm chart, could be upstream from authentik itself, though I imagine it's run on ipv6 networks somewhere, so could be a helm specific template generation failing

**Comment by BeryJu** [comment]
Moved this to the main repo as that error would happen with any ipv6-based setup

**Comment by btrepp** [comment]
Might be similar to this

https://github.com/puckel/docker-airflow/issues/411.

I did use a password generator, so it had a large amount of special characters. Root cause might be some of them not being allowed in redis/or breaking the shell

**Comment by BeryJu** [comment]
in this case its my fault (https://github.com/goauthentik/authentik/blob/master/lifecycle/wait_for_db.py#L59), for not using the python URL package to create the correct URL
