### ISSUE TITLE
Automatic proxy outpost deployment restart loop

### ISSUE THREAD

**Issue by thechubbypanda** [goauthentik/authentik#2650]
**Describe the bug**
I'm having Authentik automatically create a proxy outpost through a docker integration.  
The outpost gets created quite nicely with all the labels etc, the main server can even read healthchecks from it.  
The issue is that the outpost is in a continually restarting state, spitting out the logs below

**To Reproduce**

1. Start with an otherwise working authentik setup with the original embedded outpost
2. Create a proxy provider, forward auth single app
3. Add the local docker outpost integration
4. Create an outpost using that integration such that it connects correctly to the server and add the provider from before, my config is as follows:

```
docker_labels:
  traefik.http.routers.ak-outpost-traefik-router.entrypoints: https
authentik_host: http://authentik:9000
docker_network: traefik
docker_map_ports: false
authentik_host_browser: https://authentik.example.com
object_naming_template: ak-outpost-traefik
authentik_host_insecure: true
```

5. `watch docker ps`: Observe the issue (hopefully)

**Expected behavior**
Outpost spins up and stays up with no errors

**Logs**
```
{"event":"not enabling debug server, set `AUTHENTIK_DEBUG` to `true` to enable it.","level":"info","logger":"authentik.go_debugger","timestamp":"2022-04-03T10:21:30Z"}
{"event":"Fetched outpost configuration","level":"debug","logger":"authentik.outpost.ak-api-controller","name":"Traefik","timestamp":"2022-04-03T10:21:31Z"}
{"event":"Fetched global configuration","level":"debug","logger":"authentik.outpost.ak-api-controller","timestamp":"2022-04-03T10:21:31Z"}
{"event":"HA Reload offset","level":"debug","logger":"authentik.outpost.ak-api-controller","offset":"5s","timestamp":"2022-04-03T10:21:31Z"}
{"event":"Successfully connected websocket","level":"debug","logger":"authentik.outpost.ak-ws","outpost":"c8cc004f-54be-4653-97e6-365f2cc97875","timestamp":"2022-04-03T10:21:31Z"}
{"event":"Enabled USR1 hook to reload","level":"debug","logger":"authentik.outpost.ak-api-controller","timestamp":"2022-04-03T10:21:31Z"}
{"dir":"/tmp","event":"using filesystem session backend","level":"debug","logger":"authentik.outpost.proxyv2.application","name":"Traefik","timestamp":"2022-04-03T10:21:31Z"}
{"event":"Swapped maps","level":"debug","logger":"authentik.outpost.proxyv2","timestamp":"2022-04-03T10:21:31Z"}
{"event":"Starting WS Handler...","level":"debug","logger":"authentik.outpost.ak-api-controller","timestamp":"2022-04-03T10:21:31Z"}
{"event":"Starting Interval updater...","level":"debug","logger":"authentik.outpost.ak-api-controller","timestamp":"2022-04-03T10:21:31Z"}
{"event":"Starting Metrics server","level":"info","listen":"0.0.0.0:9300","logger":"authentik.outpost.metrics","timestamp":"2022-04-03T10:21:31Z"}
{"event":"Starting WS Health notifier...","level":"debug","logger":"authentik.outpost.ak-api-controller","timestamp":"2022-04-03T10:21:31Z"}
{"event":"Starting periodical timer...","level":"debug","logger":"authentik.outpost.ak-api-controller","timestamp":"2022-04-03T10:21:31Z"}
{"event":"Running interval update","level":"debug","logger":"authentik.outpost.ak-api-controller","loop":"interval-updater","timestamp":"2022-04-03T10:21:31Z"}
{"event":"Starting HTTP server","level":"info","listen":"0.0.0.0:9000","logger":"authentik.outpost.proxyv2","timestamp":"2022-04-03T10:21:31Z"}
{"event":"Starting HTTPS server","level":"info","listen":"0.0.0.0:9443","logger":"authentik.outpost.proxyv2","timestamp":"2022-04-03T10:21:31Z"}
{"event":"Fetched outpost configuration","level":"debug","logger":"authentik.outpost.ak-api-controller","name":"Traefik","timestamp":"2022-04-03T10:21:31Z"}
panic: interface conversion: interface {} is nil, not string

goroutine 14 [running]:
goauthentik.io/internal/outpost/ak.doGlobalSetup({{0xc0002af050, 0x24}, {0xc00044f830, 0x7}, {0xc00044f837, 0x5}, {0xc00044f840, 0x1, 0x4}, {0xc000296d80, ...}, ...}, ...)
	/go/src/goauthentik.io/internal/outpost/ak/global.go:20 +0x906
goauthentik.io/internal/outpost/ak.(*APIController).OnRefresh(0xc0000001e0)
	/go/src/goauthentik.io/internal/outpost/ak/api.go:160 +0x468
goauthentik.io/internal/outpost/ak.(*APIController).startIntervalUpdater(0xc0000001e0)
	/go/src/goauthentik.io/internal/outpost/ak/api_ws.go:199 +0x185
goauthentik.io/internal/outpost/ak.(*APIController).StartBackgorundTasks.func3()
	/go/src/goauthentik.io/internal/outpost/ak/api.go:186 +0x65
created by goauthentik.io/internal/outpost/ak.(*APIController).StartBackgorundTasks
	/go/src/goauthentik.io/internal/outpost/ak/api.go:184 +0x385
```

**Version and Deployment (please complete the following information):**
 - authentik version: latest
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
so this happens because in your config, a bunch of the default fields are missing, which is not usually handled

**Comment by thechubbypanda** [comment]
Oh, thank you. I assumed that they would just be defaulted out
