### ISSUE TITLE
[OAuth2] Fail to sign JWT with ECC signing key

### ISSUE THREAD

**Issue by haatveit** [goauthentik/authentik#2703]
**Describe the bug**
authentik fails to sign JWT with an imported `ELLIPTICCURVE` signing key set in the provider.

**To Reproduce**
1. Create OAuth2/OpenID provider
2. Set signing key to an imported `ELLIPTICCURVE` (ECDSA curve P-384) certificate
3. Attempt to log in to service (`POST /application/o/token/`)
4. Fail to issue token
5. See event log entry for "General system exception" with stack trace from the Python `jwt` package.

**Expected behavior**
Successful token issuing.

**Logs**
<details>
    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 451, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/usr/local/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/authentik/providers/oauth2/views/token.py", line 234, in dispatch
    response = super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/authentik/providers/oauth2/views/token.py", line 260, in post
    return TokenResponse(self.create_code_response())
  File "/authentik/providers/oauth2/views/token.py", line 276, in create_code_response
    refresh_token = self.params.authorization_code.provider.create_refresh_token(
  File "/authentik/providers/oauth2/models.py", line 234, in create_refresh_token
    token.access_token = token.create_access_token(user, request)
  File "/authentik/providers/oauth2/models.py", line 429, in create_access_token
    return self.provider.encode(token)
  File "/authentik/providers/oauth2/models.py", line 294, in encode
    return encode(payload, key, algorithm=alg, headers=headers)
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jwt.py", line 63, in encode
    return api_jws.encode(json_payload, key, algorithm, headers, json_encoder)
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jws.py", line 123, in encode
    raise NotImplementedError("Algorithm not supported") from e
Algorithm not supported
```
</details>

**Version and Deployment (please complete the following information):**
- authentik version: 2022.3.3
- Deployment: docker-compose

**Comment by BeryJu** [comment]
I think the issue is that I defined elliptic curve as `EC256` when it should be `ES256`?

**Comment by haatveit** [comment]
Quickly reading over the [`get_default_algorithms()` function in `pyjwt.algorithms`](https://github.com/jpadilla/pyjwt/blob/3d4d82248f1120c87f1f4e0e8793eaa1d54843a6/jwt/algorithms.py#L73), this does indeed seem to be the case.
