### ISSUE TITLE
Module Silk not found error on Docker

### ISSUE THREAD

**Issue by wdiazux** [goauthentik/authentik#2929]
**Describe the bug**
After I set the variable AUTHENTIK_DEBUG=true I am getting the error that the module 'silk' is not found and after that, it stops working, I was using the variable on a previous version 2022.4.2 where it was working but if I remove the variable everything works.
 
**To Reproduce**
1. Set variable AUTHENTIK_DEBUG=true

**Logs**
```{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1653284108.4838274, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1653284108.484402, "count": 13}
{"event": "Starting authentik bootstrap", "level": "info", "logger": "__main__", "timestamp": 1653284108.4845908}
{"event": "PostgreSQL connection failed, retrying... (connection to server at \"authentik_db\" (192.168.16.4), port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\n)", "level": "info", "logger": "__main__", "timestamp": 1653284109.4868288}
{"event": "PostgreSQL connection successful", "level": "info", "logger": "__main__", "timestamp": 1653284109.4869802}
{"event": "PostgreSQL connection failed, retrying... (connection to server at \"authentik_db\" (192.168.16.4), port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\n)", "level": "info", "logger": "__main__", "timestamp": 1653284110.4889107}
{"event": "PostgreSQL connection successful", "level": "info", "logger": "__main__", "timestamp": 1653284110.4890122}
{"event": "PostgreSQL connection successful", "level": "info", "logger": "__main__", "timestamp": 1653284110.4937873}
{"event": "Redis Connection successful", "level": "info", "logger": "__main__", "timestamp": 1653284110.501211}
{"event": "Finished authentik bootstrap", "level": "info", "logger": "__main__", "timestamp": 1653284110.5012772}
{"event": "Bootstrap completed", "level": "info", "logger": "bootstrap"}
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1653284110.8490922, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1653284110.8497179, "count": 13}
2022-05-22 23:35.10 [info     ] applying django migrations
2022-05-22 23:35.10 [info     ] waiting to acquire database lock
{"event": "Booting authentik", "level": "info", "logger": "authentik.root.settings", "timestamp": 1653284112.0353887, "version": "2022.5.2"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/lifecycle/migrate.py", line 91, in <module>
    execute_from_command_line(["", "migrate"])
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.10/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'silk'
```

**Version and Deployment:**
 - authentik version: 2022.5.2
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
Hi, this is a new development dependency to help with debugging and optimising database queries and such. However, `AUTHENTIK_DEBUG` should only be set for actual development environments, it has certain performance and security implications

**Comment by wdiazux** [comment]
Thanks for your response, I was using it because I installed Authentik recently and was getting errors by some settings that I used wrongly and I saw in the logs the variable AUTHENTIK_DEBUG so I thought it was going to be useful to know if the error was coming from the code or from my settings.
