### ISSUE TITLE
Enable debug in docker container breaks runtime

### ISSUE THREAD

**Issue by poelzi** [goauthentik/authentik#3093]
**Describe the bug**
Setting env `AUTHENTIK_DEBUG=true` breaks docker container.

**To Reproduce**
1. set `AUTHENTIK_DEBUG=true`

**Expected behavior**
Server starts and creates more debug output, log files etc.

**Logs**
```
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1655243673.8789532, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1655243673.8818767, "count": 10}
{"event": "Starting authentik bootstrap", "level": "info", "logger": "__main__", "timestamp": 1655243673.8829067}
{"event": "PostgreSQL connection successful", "level": "info", "logger": "__main__", "timestamp": 1655243673.8895185}
{"event": "Redis Connection successful", "level": "info", "logger": "__main__", "timestamp": 1655243673.8984425}
{"event": "Finished authentik bootstrap", "level": "info", "logger": "__main__", "timestamp": 1655243673.8994262}
{"event": "Bootstrap completed", "level": "info", "logger": "bootstrap"}
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1655243674.530764, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1655243674.5352845, "count": 10}
2022-06-14 21:54.34 [info     ] applying django migrations
2022-06-14 21:54.34 [info     ] waiting to acquire database lock
2022-06-14 21:54.37 [info     ] Error reporting is enabled     env=customer
{"event": "Booting authentik", "level": "info", "logger": "authentik.root.settings", "timestamp": 1655243677.8291898, "version": "2022.6.2"}
2022-06-14T21:54:38.832556 [debug    ] sending event to sentry        [authentik.lib.sentry] exc=ModuleNotFoundError("No module named 'silk'") pid=8 source_logger=None
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/lifecycle/migrate.py", line 91, in <module>
    execute_from_command_line(["", "migrate"])
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.10/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'silk'
```

**Version and Deployment (please complete the following information):**
 - authentik version: 22.6.2
 - Deployment: docker

**Comment by BeryJu** [comment]
The documentation should probably make this a bit clearer, but `AUTHENTIK_DEBUG` is only used for development, to get more logs use `AUTHENTIK_LOG_LEVEL=trace` (see https://goauthentik.io/docs/installation/configuration#authentik_log_level)

When using AUTHENTIK_DEBUG in a container, it is required to also install the dev-dependencies by running `pip install --no-cache-dir -r /requirements-dev.txt` (or using `ak test` to run tests)
