### ISSUE TITLE
Error when accepting consent while expired consent is not deleted yet

### ISSUE THREAD

**Issue by kaigoh** [goauthentik/authentik#3233]
**Describe the bug**
I noticed that I suddenly could no longer access apps that rely on Authentik for authentication using OAuth2. Instead of redirecting to the application as expected, I just got a vague "something went wrong" message.

I found no errors in the Authentik logs in Docker, but did notice (by chance) a SQL error in my Postgresql container:

> ERROR:  duplicate key value violates unique constraint "authentik_stages_consent_user_id_application_id_p_e44c6458_uniq"
> DETAIL:  Key (user_id, application_id, permissions)=(4, d6ae6665-2bb0-4418-b1c8-93e2586a5a4b, ) already exists.
> STATEMENT:  INSERT INTO "authentik_stages_consent_userconsent" ("expires", "expiring", "user_id", "application_id", "permissions") VALUES ('2022-09-29T12:24:38.680840+00:00'::timestamptz, true, 4, 'd6ae6665-2bb0-4418-b1c8-93e2586a5a4b'::uuid, '') RETURNING "authentik_stages_consent_userconsent"."id"

To allow access to the affected applications again, I had to delete the consent entries in the user interface.

**To Reproduce**
Unknown, as I am unsure what caused the issue in the first place.

**Expected behavior**
Login to flow as per usual.

**Screenshots**
N/A

**Logs**
N/A

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.7.1
 - Deployment: docker-compose

**Additional context**
N/A

**Comment by nightred** [comment]
I confirm this issue with `2022.7.2`
Here is the log from a health check ping.

```
Context
{
    "message": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/asgiref/sync.py\", line 472, in thread_handler\n    raise exc_info[1]\n  File \"/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py\", line 284, in _get_response_async\n    response = await sync_to_async(\n  File \"/usr/local/lib/python3.10/site-packages/asgiref/sync.py\", line 435, in __call__\n    ret = await asyncio.wait_for(future, timeout=None)\n  File \"/usr/local/lib/python3.10/asyncio/tasks.py\", line 408, in wait_for\n    return await fut\n  File \"/usr/local/lib/python3.10/site-packages/asgiref/current_thread_executor.py\", line 22, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/asgiref/sync.py\", line 476, in thread_handler\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/django/template/response.py\", line 114, in render\n    self.content = self.rendered_content\n  File \"/usr/local/lib/python3.10/site-packages/django/template/response.py\", line 92, in rendered_content\n    return template.render(context, self._request)\n  File \"/usr/local/lib/python3.10/site-packages/django/template/backends/django.py\", line 62, in render\n    return self.template.render(context)\n  File \"/usr/local/lib/python3.10/site-packages/django/template/base.py\", line 175, in render\n    return self._render(context)\n  File \"/usr/local/lib/python3.10/site-packages/django/template/base.py\", line 167, in _render\n    return self.nodelist.render(context)\n  File \"/usr/local/lib/python3.10/site-packages/django/template/base.py\", line 1000, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n  File \"/usr/local/lib/python3.10/site-packages/django/template/base.py\", line 1000, in <listcomp>\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n  File \"/usr/local/lib/python3.10/site-packages/django/template/base.py\", line 958, in render_annotated\n    return self.render(context)\n  File \"/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py\", line 157, in render\n    return compiled_parent._render(context)\n  File \"/usr/local/lib/python3.10/site-packages/django/template/base.py\", line 167, in _render\n    return self.nodelist.render(context)\n  File \"/usr/local/lib/python3.10/site-packages/django/template/base.py\", line 1000, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n  File \"/usr/local/lib/python3.10/site-packages/django/template/base.py\", line 1000, in <listcomp>\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n  File \"/usr/local/lib/python3.10/site-packages/django/template/base.py\", line 958, in render_annotated\n    return self.render(context)\n  File \"/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py\", line 63, in render\n    result = block.nodelist.render(context)\n  File \"/usr/local/lib/python3.10/site-packages/django/template/base.py\", line 1000, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n  File \"/usr/local/lib/python3.10/site-packages/django/template/base.py\", line 1000, in <listcomp>\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n  File \"/usr/local/lib/python3.10/site-packages/django/template/base.py\", line 958, in render_annotated\n    return self.render(context)\n  File \"/usr/local/lib/python3.10/site-packages/django/template/base.py\", line 1059, in render\n    output = self.filter_expression.resolve(context)\n  File \"/usr/local/lib/python3.10/site-packages/django/template/base.py\", line 712, in resolve\n    obj = self.var.resolve(context)\n  File \"/usr/local/lib/python3.10/site-packages/django/template/base.py\", line 842, in resolve\n    value = self._resolve_lookup(context)\n  File \"/usr/local/lib/python3.10/site-packages/django/template/base.py\", line 885, in _resolve_lookup\n    current = getattr(current, bit)\n  File \"/authentik/tenants/models.py\", line 71, in default_locale\n    return self.attributes.get(\"settings\", {}).get(\"locale\", \"\")\nbuiltins.AttributeError: 'str' object has no attribute 'get'",
    "http_request": {
        "args": {
            "next": "/"
        },
        "path": "/if/flow/default-authentication-flow/",
        "method": "GET"
    }
}
User
{
    "pk": 2,
    "email": "",
    "username": "AnonymousUser"
}
```

**Comment by BeryJu** [comment]
@kaigoh that error is caused when an existing consent has expired but the scheduled task has not deleted it yet, and as such it's trying to create a new consent but failing because of the database constraint

@nightred Your error is not related, make sure that in the tenant's attributes, `settings` is a dict and not a string

**Comment by nightred** [comment]
Rolling back one version fixed the issue for me, i did make the assumption that it was related.

**Comment by ScuttleSE** [comment]
Running 2022.7.3 wherein I though this was fixed, but encountered the same issue

```
Traceback (most recent call last):
  File "/authentik/flows/views/executor.py", line 337, in post
    stage_response = self.current_stage_view.post(request, *args, **kwargs)
  File "/authentik/flows/stage.py", line 121, in post
    return self.challenge_valid(challenge)
  File "/authentik/stages/consent/stage.py", line 120, in challenge_valid
    UserConsent.objects.create(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 514, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 857, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1000, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1041, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django_prometheus/db/common.py", line 71, in execute
    return super().execute(*args, **kwargs)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "authentik_stages_consent_user_id_application_id_p_e44c6458_uniq"
DETAIL:  Key (user_id, application_id, permissions)=(7, 88fb533d-072d-4497-929c-4efce73acc6a, ) already exists.
```

**Comment by BeryJu** [comment]
@ScuttleSE can you try https://github.com/goauthentik/authentik/pkgs/container/dev-server/32948267?tag=gh-next, this should be fixed on that image

**Comment by ScuttleSE** [comment]
I have redeployed the server with this image. It's not something that happends everyday though...

**Comment by ScuttleSE** [comment]
Uh, yeah...I have to go back on that...after installing that image, auth was completely broken. Got to the conscent page, but clicking "Continue" did nothing.

So back to 2022.7.3...
