### ISSUE TITLE
`silk_request relationship does not exist` error at first launch

### ISSUE THREAD

**Issue by azmeuk** [goauthentik/authentik#3320]
**Describe the bug**
Following [this documentation](https://goauthentik.io/developer-docs/setup/full-dev-environment), the `make run` step loops over raising a `silk_request relationship does not exist` exception.

**To Reproduce**
1. git clone https://github.com/goauthentik/authentik.git
2. cd authentik
3. poetry shell
4. poetry install
5. vi local.env.yml
6. make migrate
7. make web-build
8. make run

**Expected behavior**
I expected no exception.

**Logs**

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/azmeuk/.cache/pypoetry/virtualenvs/authentik-KRwG3g24-py3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/azmeuk/.cache/pypoetry/virtualenvs/authentik-KRwG3g24-py3.10/lib/python3.10/site-packages/silk/middleware.py", line 70, in __call__
    self.process_request(request)
  File "/home/azmeuk/.cache/pypoetry/virtualenvs/authentik-KRwG3g24-py3.10/lib/python3.10/site-packages/silk/middleware.py", line 120, in process_request
    request_model = RequestModelFactory(request).construct_request_model()
  File "/home/azmeuk/.cache/pypoetry/virtualenvs/authentik-KRwG3g24-py3.10/lib/python3.10/site-packages/silk/model_factory.py", line 252, in construct_request_model
    request_model = models.Request.objects.create(
  File "/home/azmeuk/.cache/pypoetry/virtualenvs/authentik-KRwG3g24-py3.10/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/azmeuk/.cache/pypoetry/virtualenvs/authentik-KRwG3g24-py3.10/lib/python3.10/site-packages/django/db/models/query.py", line 514, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/azmeuk/.cache/pypoetry/virtualenvs/authentik-KRwG3g24-py3.10/lib/python3.10/site-packages/silk/models.py", line 190, in save
    super().save(*args, **kwargs)
  File "/home/azmeuk/.cache/pypoetry/virtualenvs/authentik-KRwG3g24-py3.10/lib/python3.10/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/home/azmeuk/.cache/pypoetry/virtualenvs/authentik-KRwG3g24-py3.10/lib/python3.10/site-packages/django/db/models/base.py", line 857, in save_base
    updated = self._save_table(
  File "/home/azmeuk/.cache/pypoetry/virtualenvs/authentik-KRwG3g24-py3.10/lib/python3.10/site-packages/django/db/models/base.py", line 1000, in _save_table
    results = self._do_insert(
  File "/home/azmeuk/.cache/pypoetry/virtualenvs/authentik-KRwG3g24-py3.10/lib/python3.10/site-packages/django/db/models/base.py", line 1041, in _do_insert
    return manager._insert(
  File "/home/azmeuk/.cache/pypoetry/virtualenvs/authentik-KRwG3g24-py3.10/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/azmeuk/.cache/pypoetry/virtualenvs/authentik-KRwG3g24-py3.10/lib/python3.10/site-packages/django/db/models/query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/azmeuk/.cache/pypoetry/virtualenvs/authentik-KRwG3g24-py3.10/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "/home/azmeuk/.cache/pypoetry/virtualenvs/authentik-KRwG3g24-py3.10/lib/python3.10/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/home/azmeuk/.cache/pypoetry/virtualenvs/authentik-KRwG3g24-py3.10/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/azmeuk/.cache/pypoetry/virtualenvs/authentik-KRwG3g24-py3.10/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/azmeuk/.cache/pypoetry/virtualenvs/authentik-KRwG3g24-py3.10/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/azmeuk/.cache/pypoetry/virtualenvs/authentik-KRwG3g24-py3.10/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/azmeuk/.cache/pypoetry/virtualenvs/authentik-KRwG3g24-py3.10/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/azmeuk/.cache/pypoetry/virtualenvs/authentik-KRwG3g24-py3.10/lib/python3.10/site-packages/django_prometheus/db/common.py", line 71, in execute
    return super().execute(*args, **kwargs)
django.db.utils.ProgrammingError: ERREUR:  la relation « silk_request » n'existe pas
LINE 1: INSERT INTO "silk_request" ("id", "path", "query_params", "r...
```

**Version and Deployment (please complete the following information):**
 - authentik version: 282ebeb

**Comment by azmeuk** [comment]
Re-launching `make migrate` solved this.
