### ISSUE TITLE
Error "duplicate key value violates unique constraint" after OIDC login

### ISSUE THREAD

**Issue by evgnblkn** [goauthentik/authentik#3436]
**Describe the bug**
The error occurs when trying to login again to an application. 
**To Reproduce**
1. Open the application URL
2. Authorize through OIDC
3. Specify login and password
4. Confirm consent to receive email and profile information
5. See error "Whoops! Something went wrong! Please try again later."

**Expected behavior**
After authorization and obtaining consent, the application should open without error.

**Logs**
<details>
    <summary>Stacktrace from authentik POST /api/v3/flows/executor/default-provider-authorization-explicit-consent/</summary>

```
POST /api/v3/flows/executor/default-provider-authorization-explicit-consent/

Traceback (most recent call last):
  File "/authentik/flows/views/executor.py", line 337, in post
    stage_response = self.current_stage_view.post(request, *args, **kwargs)
  File "/authentik/flows/stage.py", line 121, in post
    return self.challenge_valid(challenge)
  File "/authentik/stages/consent/stage.py", line 137, in challenge_valid
    consent.save()
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 857, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1000, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1041, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django_prometheus/db/common.py", line 71, in execute
    return super().execute(*args, **kwargs)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "authentik_stages_consent_user_id_application_id_p_e44c6458_uniq"
DETAIL:  Key (user_id, application_id, permissions)=(24, 7223a3b7-57de-4146-ac62-70e7a981e0f7, email profile) already exists.

```
</details>
<details>
    <summary>Logs from postgres</summary>

```
ERROR:  duplicate key value violates unique constraint "authentik_stages_consent_user_id_application_id_p_e44c6458_uniq"
DETAIL:  Key (user_id, application_id, permissions)=(24, 7223a3b7-57de-4146-ac62-70e7a981e0f7, email profile) already exists.
STATEMENT:  INSERT INTO "authentik_stages_consent_userconsent" ("expires", "expiring", "user_id", "application_id", "permissions") VALUES ('2022-08-17T13:22:21.424779+00:00'::timestamptz, true, 24, '7223a3b7-57de-4146-ac62-70e7a981e0f7'::uuid, 'email profile') RETURNING "authentik_stages_consent_userconsent"."id"

```
</details>

**Version and Deployment (please complete the following information):**
- authentik version: 2022.7.3
- Deployment: docker-compose

**Additional context**
Authentik was upgraded via docker pull from 2022.4.1.
For testing, I installed authentik from the latest tag. There is no error, successfully authorizes.

**Comment by evgnblkn** [comment]
After some time, it may take 10-15 minutes to successfully authorize in the application without an error. But if you repeat it right away, it's an error again.

**Comment by evgnblkn** [comment]
Updated to 2022.8.1. There is no error. I'm closing the issue. Always update to the latest release! Authentic is cool! Thank you!

**Comment by masterwishx** [comment]
have same issue
