### ISSUE TITLE
Manual certificate import failing: "Valid PEM but no BEGIN CERTIFICATE/END CERTIFICATE delimiters." on valid certificates

### ISSUE THREAD

**Issue by Aterfax** [goauthentik/authentik#3713]
**Describe the bug**
Authentik is failing to import valid certificates manually (and probably automatically too) with errors about missing delimiters which are present.

**To Reproduce**
1. Setup the latest docker-compose version of Authentik.
2. Pass through certbot generated letsencrypt certs via bind mounts (e.g.  `/etc/letsencrypt/live/domain.com/fullchain.pem:/certs/domain.com/fullchain.pem`
3. `docker exec -it authentik-worker-1  bash`
4. Attempt a manual import as per https://goauthentik.io/docs/core/certificates#manual-imports

**Expected behavior**
Certificate/s should import correctly.

**Logs**

```
root@auth:~# docker exec -it authentik-worker-1  bash
root@835190a99116:/# head -n 1 /certs/domain.com/fullchain.pem                                                                                    
-----BEGIN CERTIFICATE-----
root@835190a99116:/# tail -n 1 /certs/domain.com/fullchain.pem                                                                                    
-----END CERTIFICATE-----
root@835190a99116:/# ak import_certificate --certificate /certs/DOMAIN.com/fullchain.pem  --private-key /certs/DOMAIN.com/privkey.pem --name test
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1664645059.8276238, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1664645059.8284364, "count": 18}
{"event": "Booting authentik", "level": "info", "logger": "authentik.lib.config", "timestamp": 1664645061.5176857, "version": "2022.9.0"}
{"event": "Loaded GeoIP database", "last_write": 1664639833.1606064, "level": "info", "logger": "authentik.events.geo", "pid": 246, "timestamp": "2022-10-01T17:24:22.263451"}
{"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 246, "task_id": "be759a1e-6c12-4482-bf52-9085f791f806", "task_name": "authentik.blueprints.v1.tasks.blueprints_discover", "timestamp": "2022-10-01T17:24:23.447505"}
{"event": "Failed to load certificate", "exc": "ValueError('Valid PEM but no BEGIN CERTIFICATE/END CERTIFICATE delimiters. Are you sure this is a certificate?')", "level": "warning", "logger": "authentik.crypto.api", "pid": 246, "timestamp": "2022-10-01T17:24:24.993300"}
Traceback (most recent call last):
  File "/authentik/crypto/api.py", line 85, in validate_certificate_data
    str(load_pem_x509_certificate(value.encode("utf-8"), default_backend()))
  File "/usr/local/lib/python3.10/site-packages/cryptography/x509/base.py", line 514, in load_pem_x509_certificate
    return rust_x509.load_pem_x509_certificate(data)
ValueError: Valid PEM but no BEGIN CERTIFICATE/END CERTIFICATE delimiters. Are you sure this is a certificate?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/authentik/crypto/management/commands/import_certificate.py", line 41, in handle
    serializer.validate_certificate_data(keypair.key_data)
  File "/authentik/crypto/api.py", line 88, in validate_certificate_data
    raise ValidationError("Unable to load certificate.")
rest_framework.exceptions.ValidationError: [ErrorDetail(string='Unable to load certificate.', code='invalid')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/manage.py", line 38, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "/authentik/crypto/management/commands/import_certificate.py", line 43, in handle
    self.stderr.write(exc)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 167, in write
    if ending and not msg.endswith(ending):
AttributeError: 'ValidationError' object has no attribute 'endswith'
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

**Version and Deployment (please complete the following information):**
 - authentik version: [2022.9.0] Latest as per https://goauthentik.io/docker-compose.yml
 - Deployment: [docker-compose]

**Other notes:**
I doubt that passing through the certs in this manner is causing the issue. `domain.com` appears where I have censored my domain name. Might be something hinky with the Python parsing library?

The same error occurs when attempting to import `cert.pem` so it's not the multiple certs in `fullchain.pem` causing an issue.

Given that the certificates are not being imported automatically I am assuming the same issue is affecting automatic import?

**Comment by Aterfax** [comment]
It appears the automatic discovery has had no issues importing so this is only an issue for manual certificate import.

**Comment by Aterfax** [comment]
Super speedy, much appreciated!

**Comment by RegisPerdreau** [comment]
Hi,

Sorry to disagree but :
Same constation with version 2023.2, still the same problem.
And i dont see any automatic discovery regarding /certs directory.

I feel stuck

Regards,

Régis

**Comment by BeryJu** [comment]
Please post the error you're getting and the certificate if possible, I can't reproduce the error on the latest version
