### ISSUE TITLE
ak createsuperuser: AttributeError: can't set attribute 'is_staff'

### ISSUE THREAD

**Issue by chris13524** [goauthentik/authentik#3888]
**Describe the bug**
`AttributeError: can't set attribute 'is_staff'` when trying to `createsuperuser` using the `ak` CLI tool.

**To Reproduce**
1. Run `ak createsuperuser` command
2. Set user, empty (or set) email, and set a password
3. See error

**Logs**

```
 % kubectl exec -it deploy/authentik-server -- ak createsuperuser
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1666892953.9755948, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1666892953.976146, "count": 24}
{"event": "Booting authentik", "level": "info", "logger": "authentik.lib.config", "timestamp": 1666892954.4915245, "version": "2022.10.0"}
{"event": "Failed to load GeoIP database", "exc": "FileNotFoundError(2, 'No such file or directory')", "level": "warning", "logger": "authentik.events.geo", "pid": 165, "timestamp": "2022-10-27T17:49:14.742311"}
{"app_name": "authentik.admin", "event": "Starting reconciler", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_admin_signals", "pid": 165, "timestamp": "2022-10-27T17:49:14.945801"}
{"app_name": "authentik.admin", "event": "Successfully reconciled", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_admin_signals", "pid": 165, "timestamp": "2022-10-27T17:49:14.975622"}
{"app_name": "authentik.crypto", "event": "Starting reconciler", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_crypto_tasks", "pid": 165, "timestamp": "2022-10-27T17:49:14.975891"}
{"app_name": "authentik.crypto", "event": "Successfully reconciled", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_crypto_tasks", "pid": 165, "timestamp": "2022-10-27T17:49:14.981416"}
{"app_name": "authentik.crypto", "event": "Starting reconciler", "level": "debug", "logger": "authentik.blueprints.apps", "name": "managed_jwt_cert", "pid": 165, "timestamp": "2022-10-27T17:49:14.981561"}
{"app_name": "authentik.crypto", "event": "Successfully reconciled", "level": "debug", "logger": "authentik.blueprints.apps", "name": "managed_jwt_cert", "pid": 165, "timestamp": "2022-10-27T17:49:14.988891"}
{"app_name": "authentik.crypto", "event": "Starting reconciler", "level": "debug", "logger": "authentik.blueprints.apps", "name": "self_signed", "pid": 165, "timestamp": "2022-10-27T17:49:14.989025"}
{"app_name": "authentik.crypto", "event": "Successfully reconciled", "level": "debug", "logger": "authentik.blueprints.apps", "name": "self_signed", "pid": 165, "timestamp": "2022-10-27T17:49:14.992728"}
{"app_name": "authentik.events", "event": "Starting reconciler", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_events_signals", "pid": 165, "timestamp": "2022-10-27T17:49:14.992995"}
{"app_name": "authentik.events", "event": "Successfully reconciled", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_events_signals", "pid": 165, "timestamp": "2022-10-27T17:49:15.006227"}
{"app_name": "authentik.flows", "event": "Starting reconciler", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_flows_signals", "pid": 165, "timestamp": "2022-10-27T17:49:15.006473"}
{"app_name": "authentik.flows", "event": "Successfully reconciled", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_flows_signals", "pid": 165, "timestamp": "2022-10-27T17:49:15.007286"}
{"app_name": "authentik.flows", "event": "Starting reconciler", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_stages", "pid": 165, "timestamp": "2022-10-27T17:49:15.007419"}
{"app_name": "authentik.flows", "event": "Successfully reconciled", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_stages", "pid": 165, "timestamp": "2022-10-27T17:49:15.036054"}
{"app_name": "authentik.outposts", "event": "Starting reconciler", "level": "debug", "logger": "authentik.blueprints.apps", "name": "embedded_outpost", "pid": 165, "timestamp": "2022-10-27T17:49:15.036288"}
{"app_name": "authentik.outposts", "event": "Successfully reconciled", "level": "debug", "logger": "authentik.blueprints.apps", "name": "embedded_outpost", "pid": 165, "timestamp": "2022-10-27T17:49:15.049337"}
{"app_name": "authentik.outposts", "event": "Starting reconciler", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_outposts_signals", "pid": 165, "timestamp": "2022-10-27T17:49:15.049488"}
{"app_name": "authentik.outposts", "event": "Successfully reconciled", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_outposts_signals", "pid": 165, "timestamp": "2022-10-27T17:49:15.068753"}
{"app_name": "authentik.policies.reputation", "event": "Starting reconciler", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_policies_reputation_signals", "pid": 165, "timestamp": "2022-10-27T17:49:15.068925"}
{"app_name": "authentik.policies.reputation", "event": "Successfully reconciled", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_policies_reputation_signals", "pid": 165, "timestamp": "2022-10-27T17:49:15.070242"}
{"app_name": "authentik.policies.reputation", "event": "Starting reconciler", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_policies_reputation_tasks", "pid": 165, "timestamp": "2022-10-27T17:49:15.070381"}
{"app_name": "authentik.policies.reputation", "event": "Successfully reconciled", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_policies_reputation_tasks", "pid": 165, "timestamp": "2022-10-27T17:49:15.070516"}
{"app_name": "authentik.policies", "event": "Starting reconciler", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_policies_signals", "pid": 165, "timestamp": "2022-10-27T17:49:15.070692"}
{"app_name": "authentik.policies", "event": "Successfully reconciled", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_policies_signals", "pid": 165, "timestamp": "2022-10-27T17:49:15.071640"}
{"app_name": "authentik.sources.ldap", "event": "Starting reconciler", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_sources_ldap_signals", "pid": 165, "timestamp": "2022-10-27T17:49:15.071933"}
{"app_name": "authentik.sources.ldap", "event": "Successfully reconciled", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_sources_ldap_signals", "pid": 165, "timestamp": "2022-10-27T17:49:15.080595"}
{"app_name": "authentik.sources.oauth", "event": "Starting reconciler", "level": "debug", "logger": "authentik.blueprints.apps", "name": "sources_loaded", "pid": 165, "timestamp": "2022-10-27T17:49:15.080795"}
{"app_name": "authentik.sources.oauth", "event": "Successfully reconciled", "level": "debug", "logger": "authentik.blueprints.apps", "name": "sources_loaded", "pid": 165, "timestamp": "2022-10-27T17:49:15.086819"}
{"app_name": "authentik.sources.saml", "event": "Starting reconciler", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_sources_saml_signals", "pid": 165, "timestamp": "2022-10-27T17:49:15.087051"}
{"app_name": "authentik.sources.saml", "event": "Successfully reconciled", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_sources_saml_signals", "pid": 165, "timestamp": "2022-10-27T17:49:15.087600"}
{"app_name": "authentik.stages.authenticator_duo", "event": "Starting reconciler", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_tasks", "pid": 165, "timestamp": "2022-10-27T17:49:15.087802"}
{"app_name": "authentik.stages.authenticator_duo", "event": "Successfully reconciled", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_tasks", "pid": 165, "timestamp": "2022-10-27T17:49:15.088485"}
{"app_name": "authentik.stages.authenticator_static", "event": "Starting reconciler", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_stages_authenticator_static_signals", "pid": 165, "timestamp": "2022-10-27T17:49:15.088678"}
{"app_name": "authentik.stages.authenticator_static", "event": "Successfully reconciled", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_stages_authenticator_static_signals", "pid": 165, "timestamp": "2022-10-27T17:49:15.089165"}
{"app_name": "authentik.stages.email", "event": "Starting reconciler", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_stages_emails_tasks", "pid": 165, "timestamp": "2022-10-27T17:49:15.089351"}
{"app_name": "authentik.stages.email", "event": "Successfully reconciled", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_stages_emails_tasks", "pid": 165, "timestamp": "2022-10-27T17:49:15.089494"}
{"app_name": "authentik.blueprints", "event": "Starting reconciler", "level": "debug", "logger": "authentik.blueprints.apps", "name": "blueprints_discover", "pid": 165, "timestamp": "2022-10-27T17:49:15.089667"}
{"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 165, "task_id": "e95da8e0-fd55-410a-8d40-567731948733", "task_name": "authentik.blueprints.v1.tasks.blueprints_discover", "timestamp": "2022-10-27T17:49:15.111131"}
{"app_name": "authentik.blueprints", "event": "Successfully reconciled", "level": "debug", "logger": "authentik.blueprints.apps", "name": "blueprints_discover", "pid": 165, "timestamp": "2022-10-27T17:49:15.111629"}
{"app_name": "authentik.blueprints", "event": "Starting reconciler", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_blueprints_v1_tasks", "pid": 165, "timestamp": "2022-10-27T17:49:15.111769"}
{"app_name": "authentik.blueprints", "event": "Successfully reconciled", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_blueprints_v1_tasks", "pid": 165, "timestamp": "2022-10-27T17:49:15.111921"}
{"app_name": "authentik.core", "event": "Starting reconciler", "level": "debug", "logger": "authentik.blueprints.apps", "name": "debug_worker_hook", "pid": 165, "timestamp": "2022-10-27T17:49:15.220298"}
{"app_name": "authentik.core", "event": "Successfully reconciled", "level": "debug", "logger": "authentik.blueprints.apps", "name": "debug_worker_hook", "pid": 165, "timestamp": "2022-10-27T17:49:15.220447"}
{"app_name": "authentik.core", "event": "Starting reconciler", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_core_signals", "pid": 165, "timestamp": "2022-10-27T17:49:15.220532"}
{"app_name": "authentik.core", "event": "Successfully reconciled", "level": "debug", "logger": "authentik.blueprints.apps", "name": "load_core_signals", "pid": 165, "timestamp": "2022-10-27T17:49:15.220641"}
{"app_name": "authentik.core", "event": "Starting reconciler", "level": "debug", "logger": "authentik.blueprints.apps", "name": "source_inbuilt", "pid": 165, "timestamp": "2022-10-27T17:49:15.220726"}
{"app_name": "authentik.core", "event": "Successfully reconciled", "level": "debug", "logger": "authentik.blueprints.apps", "name": "source_inbuilt", "pid": 165, "timestamp": "2022-10-27T17:49:15.232732"}
{"app_mountpoint": "api/", "app_name": "authentik.api", "event": "Mounted URLs", "level": "debug", "logger": "authentik.root.urls", "namespace": "authentik_api", "pid": 165, "timestamp": "2022-10-27T17:49:15.553375"}
{"app_mountpoint": "flows/", "app_name": "authentik.flows", "event": "Mounted URLs", "level": "debug", "logger": "authentik.root.urls", "namespace": "authentik_flows", "pid": 165, "timestamp": "2022-10-27T17:49:15.553988"}
{"app_mountpoint": "", "app_name": "authentik.providers.oauth2", "event": "Mounted URLs", "level": "debug", "logger": "authentik.root.urls", "namespace": "authentik_providers_oauth2_root", "pid": 165, "timestamp": "2022-10-27T17:49:15.565823"}
{"app_mountpoint": "application/o/", "app_name": "authentik.providers.oauth2", "event": "Mounted URLs", "level": "debug", "logger": "authentik.root.urls", "namespace": "authentik_providers_oauth2", "pid": 165, "timestamp": "2022-10-27T17:49:15.569611"}
{"app_mountpoint": "application/saml/", "app_name": "authentik.providers.saml", "event": "Mounted URLs", "level": "debug", "logger": "authentik.root.urls", "namespace": "authentik_providers_saml", "pid": 165, "timestamp": "2022-10-27T17:49:15.576108"}
{"app_mountpoint": "recovery/", "app_name": "authentik.recovery", "event": "Mounted URLs", "level": "debug", "logger": "authentik.root.urls", "namespace": "authentik_recovery", "pid": 165, "timestamp": "2022-10-27T17:49:15.576827"}
{"app_mountpoint": "source/oauth/", "app_name": "authentik.sources.oauth", "event": "Mounted URLs", "level": "debug", "logger": "authentik.root.urls", "namespace": "authentik_sources_oauth", "pid": 165, "timestamp": "2022-10-27T17:49:15.577807"}
{"app_mountpoint": "source/saml/", "app_name": "authentik.sources.saml", "event": "Mounted URLs", "level": "debug", "logger": "authentik.root.urls", "namespace": "authentik_sources_saml", "pid": 165, "timestamp": "2022-10-27T17:49:15.582419"}
{"app_mountpoint": "", "app_name": "authentik.core", "event": "Mounted URLs", "level": "debug", "logger": "authentik.root.urls", "namespace": "authentik_core", "pid": 165, "timestamp": "2022-10-27T17:49:15.585623"}
Username: user
Email address: 
Password: 
Password (again): 
{"event": "sending event to sentry", "exc": "AttributeError(\"can't set attribute 'is_staff'\")", "level": "debug", "logger": "authentik.lib.sentry", "pid": 165, "source_logger": null, "timestamp": "2022-10-27T17:49:23.827716"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/manage.py", line 38, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 88, in execute
    return super().execute(*args, **options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 233, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/models.py", line 172, in create_superuser
    return self._create_user(username, email, password, **extra_fields)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/models.py", line 153, in _create_user
    user = self.model(username=username, email=email, **extra_fields)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 554, in __init__
    _setattr(self, prop, value)
AttributeError: can't set attribute 'is_staff'
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
command terminated with exit code 1
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.10.0, CLI version 4.1.2
 - Deployment: Helm

**Comment by BeryJu** [comment]
`createsuperuser` is not intended to be used, you can either use https://goauthentik.io/docs/installation/automated-install, https://goauthentik.io/docs/troubleshooting/login, or create a user with blueprints

**Comment by chris13524** [comment]
In my case I deactivated the single akadmin user, so I am unable to use `create_recovery_key` and I believe automated install does not work either. So I will need to use blueprints. Is there an example user blueprint or is there a schema that defines all of the models?
