### ISSUE TITLE
Using arbitrary UID/GID does not work

### ISSUE THREAD

**Issue by jocelynthode** [goauthentik/authentik#4098]
**Describe the bug**
When running the container with an arbitrary UID/GID (e.g.: 100000) Gunicorn crashed repeatedly. This is problematic on my end as uid 1000 used for the authentik user in the container corresponds to my user on the host.

For security purposes I'd like to use an arbitrary UID not assigned on my host to run authentik.

**To Reproduce**
1. Run the container with an arbitrary UID/GID (e.g. 100000)
2. Gunicorn crashed

**Expected behavior**
The image should work with any arbitrary UID/GID.

**Logs**
```
nov 27 12:54:14 servetek authentik-server[222596]: {"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1669550054.3338413, "count": 8}
nov 27 12:54:14 servetek authentik-server[222596]: 1669550054.6837564 [info     ] Starting gunicorn 20.1.0       [gunicorn.error] 
nov 27 12:54:14 servetek authentik-server[222596]: 1669550054.6846466 [info     ] Listening at: http://127.0.0.1:8000 (161) [gunicorn.error] 
nov 27 12:54:14 servetek authentik-server[222596]: 1669550054.6849332 [info     ] Using worker: lifecycle.worker.DjangoUvicornWorker [gunicorn.error] 
nov 27 12:54:14 servetek authentik-server[222596]: 1669550054.685367 [info     ] Unhandled exception in main loop [gunicorn.error] 
nov 27 12:54:14 servetek authentik-server[222596]: Traceback (most recent call last):
nov 27 12:54:14 servetek authentik-server[222596]:   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 202, in run
nov 27 12:54:14 servetek authentik-server[222596]:     self.manage_workers()
nov 27 12:54:14 servetek authentik-server[222596]:   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 551, in manage_workers
nov 27 12:54:14 servetek authentik-server[222596]:     self.spawn_workers()
nov 27 12:54:14 servetek authentik-server[222596]:   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 622, in spawn_workers
nov 27 12:54:14 servetek authentik-server[222596]:     self.spawn_worker()
nov 27 12:54:14 servetek authentik-server[222596]:   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 569, in spawn_worker
nov 27 12:54:14 servetek authentik-server[222596]:     worker = self.worker_class(self.worker_age, self.pid, self.LISTENERS,
nov 27 12:54:14 servetek authentik-server[222596]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nov 27 12:54:14 servetek authentik-server[222596]:   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 23, in __init__
nov 27 12:54:14 servetek authentik-server[222596]:     super(UvicornWorker, self).__init__(*args, **kwargs)
nov 27 12:54:14 servetek authentik-server[222596]:   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 64, in __init__
nov 27 12:54:14 servetek authentik-server[222596]:     self.tmp = WorkerTmp(cfg)
nov 27 12:54:14 servetek authentik-server[222596]:                ^^^^^^^^^^^^^^
nov 27 12:54:14 servetek authentik-server[222596]:   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/workertmp.py", line 29, in __init__
nov 27 12:54:14 servetek authentik-server[222596]:     util.chown(name, cfg.uid, cfg.gid)
nov 27 12:54:14 servetek authentik-server[222596]:   File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 153, in chown
nov 27 12:54:14 servetek authentik-server[222596]:     os.chown(path, uid, gid)
nov 27 12:54:14 servetek authentik-server[222596]: PermissionError: [Errno 1] Operation not permitted: '/dev/shm/authentik_worker_tmp/wgunicorn-rb3rrgmc'
nov 27 12:54:14 servetek authentik-server[222596]: {"error":"exit status 255","event":"gunicorn process died, restarting","level":"warning","logger":"authentik.router","timestamp":"2022-11-27T11:54:14Z"}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.11.1
 - Deployment: docker-compose

**Comment by jocelynthode** [comment]
Might be related to https://github.com/goauthentik/authentik/issues/3236 although I do not think having the ability to drop priv to another user is necessary for me.

**Comment by jocelynthode** [comment]
@BeryJu thanks for the fix. Do you know in which release can I expect this fix?
