### ISSUE TITLE
Authentik Helm Deployment CrashLoopBackOff

### ISSUE THREAD

**Issue by pr0ton11** [goauthentik/authentik#4208]
**Describe the bug**
Deployed Authentik with Helm. I have both external Postgres and Redis instances running in the same namespace as Authentik.
Unfortunately both server and worker fail with the same errors.
The CrashLoopBackOff error is explained by the Logs.

**To Reproduce**
1. Create manifest for Helm:
```
authentik:
    secret_key: "redacted"
    error_reporting:
        enabled: false
    postgresql:
        host: "postgres.world.svc.cluster.int"
        name: "authentik"
        user: "authentik"
        password: "redacted"
    redis:
        host: "rfr-redis-auth.world.svc.cluster.int"
        password: "redacted"
    geoip:
        accountId: "redacted"
        editionIds: "GeoLite2-City"
        enabled: true
        image: "maxmindinc/geoipupdate:latest"
        licenseKey: "redacted"
        updateInterval: 24
    image:
        tag: "2022.11.3"

ingress:
    enabled: true
    ingressClassName: "redacted"
    hosts:
        - host: redacted.redacted.com
          paths:
            - path: "/"
              pathType: Prefix

postgresql:
    enabled: false
redis:
    enabled: false
```
2. Run helm upgrade -n world --install authentik authentik/authentik -f values.yaml

**Expected behavior**
Authentik gets deployed and is available

**Logs**
```
# kubectl -n world logs authentik-server-76f5bd5648-h8gcn
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1670939686.7187352, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1670939686.7205944, "count": 38}
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/lifecycle/wait_for_db.py", line 12, in <module>
    from authentik.lib.config import CONFIG
  File "/authentik/lib/config.py", line 191, in <module>
    CONFIG = ConfigLoader()
             ^^^^^^^^^^^^^^
  File "/authentik/lib/config.py", line 63, in __init__
    self.update_from_env()
  File "/authentik/lib/config.py", line 148, in update_from_env
    self.update(self.__config, outer)
  File "/authentik/lib/config.py", line 81, in update
    root[key] = self.update(root.get(key, {}), value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/lib/config.py", line 85, in update
    root[key] = value
    ~~~~^^^^^
TypeError: 'str' object does not support item assignment
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.11.3
 - Deployment: helm

**Additional context**

**Comment by BeryJu** [comment]
The GeoIP settings are not meant to be under the `authentik` key, but rather one level higher, see https://artifacthub.io/packages/helm/goauthentik/authentik?modal=values&path=geoip
