### ISSUE TITLE
Forward Auth Proxy invalid memory address panic on versions 2022.12.1 and up

### ISSUE THREAD

**Issue by adaexec** [goauthentik/authentik#4369]
**Describe the bug**
After updating from 2022.12.0 to 2022.12.1 (or 2022.12.2) all of my forward auth proxy providers panic on every request

**To Reproduce**
1. Setup a Proxy Provider with the type Forward Auth (Single Application) on version 2022.12.0
2. Upgrade to 2022.12.1 or 2022.12.2
3. Try to access the Website behind the auth

**Expected behavior**
The request should be correctly proxied without panicking

**Logs**
***Version 2022.12.1***
```
AuthentikServer  | 2023/01/05 14:28:55 http: panic serving 172.20.0.10:44236: runtime error: invalid memory address or nil pointer dereference
AuthentikServer  | goroutine 274 [running]:
AuthentikServer  | net/http.(*conn).serve.func1()
AuthentikServer  |      /usr/local/go/src/net/http/server.go:1850 +0xbf
AuthentikServer  | panic({0xfef140, 0x1a0e9e0})
AuthentikServer  |      /usr/local/go/src/runtime/panic.go:890 +0x262
AuthentikServer  | goauthentik.io/internal/web/tenant_tls.(*Watcher).GetCertificate(0xc000276080, 0xc0000f6dd0?)
AuthentikServer  |      /work/internal/web/tenant_tls/tenant_tls.go:80 +0x63
AuthentikServer  | goauthentik.io/internal/web.(*WebServer).GetCertificate.func1(0xc0000f6dd0?)
AuthentikServer  |      /work/internal/web/tls.go:29 +0x79
AuthentikServer  | crypto/tls.(*Config).getCertificate(0xc000190180, 0xc0000f6dd0)
AuthentikServer  |      /usr/local/go/src/crypto/tls/common.go:1069 +0x42
AuthentikServer  | crypto/tls.(*serverHandshakeState).processClientHello(0xc0005957c8)
AuthentikServer  |      /usr/local/go/src/crypto/tls/handshake_server.go:228 +0x7c7
AuthentikServer  | crypto/tls.(*serverHandshakeState).handshake(0xc0005957c8)
AuthentikServer  |      /usr/local/go/src/crypto/tls/handshake_server.go:68 +0x2a
AuthentikServer  | crypto/tls.(*Conn).serverHandshake(0xc000301500, {0x12b7bb0, 0xc000653e40})
AuthentikServer  |      /usr/local/go/src/crypto/tls/handshake_server.go:62 +0x12d
AuthentikServer  | crypto/tls.(*Conn).handshakeContext(0xc000301500, {0x12b7c58, 0xc0001bea20})
AuthentikServer  |      /usr/local/go/src/crypto/tls/conn.go:1462 +0x32f
AuthentikServer  | crypto/tls.(*Conn).HandshakeContext(...)
AuthentikServer  |      /usr/local/go/src/crypto/tls/conn.go:1405
AuthentikServer  | net/http.(*conn).serve(0xc000228be0, {0x12b7c58, 0xc00065fec0})
AuthentikServer  |      /usr/local/go/src/net/http/server.go:1873 +0xdd3
AuthentikServer  | created by net/http.(*Server).Serve
AuthentikServer  |      /usr/local/go/src/net/http/server.go:3102 +0x4db
```

***Version 2022.12.2***
```
AuthentikServer  | 2023/01/05 14:30:15 http: panic serving 172.20.0.10:47024: runtime error: invalid memory address or nil pointer dereference
AuthentikServer  | goroutine 220 [running]:
AuthentikServer  | net/http.(*conn).serve.func1()
AuthentikServer  |      /usr/local/go/src/net/http/server.go:1850 +0xbf
AuthentikServer  | panic({0xfef240, 0x1a0f9e0})
AuthentikServer  |      /usr/local/go/src/runtime/panic.go:890 +0x262
AuthentikServer  | goauthentik.io/internal/web/tenant_tls.(*Watcher).GetCertificate(0xc00059c080, 0xc0000afd40?)
AuthentikServer  |      /work/internal/web/tenant_tls/tenant_tls.go:80 +0x63
AuthentikServer  | goauthentik.io/internal/web.(*WebServer).GetCertificate.func1(0xc0000afd40?)
AuthentikServer  |      /work/internal/web/tls.go:29 +0x79
AuthentikServer  | crypto/tls.(*Config).getCertificate(0xc0001b0600, 0xc0000afd40)
AuthentikServer  |      /usr/local/go/src/crypto/tls/common.go:1069 +0x42
AuthentikServer  | crypto/tls.(*serverHandshakeState).processClientHello(0xc0005757c8)
AuthentikServer  |      /usr/local/go/src/crypto/tls/handshake_server.go:228 +0x7c7
AuthentikServer  | crypto/tls.(*serverHandshakeState).handshake(0xc0005757c8)
AuthentikServer  |      /usr/local/go/src/crypto/tls/handshake_server.go:68 +0x2a
AuthentikServer  | crypto/tls.(*Conn).serverHandshake(0xc000270a80, {0x12b7df0, 0xc00067a500})
AuthentikServer  |      /usr/local/go/src/crypto/tls/handshake_server.go:62 +0x12d
AuthentikServer  | crypto/tls.(*Conn).handshakeContext(0xc000270a80, {0x12b7e98, 0xc000495860})
AuthentikServer  |      /usr/local/go/src/crypto/tls/conn.go:1462 +0x32f
AuthentikServer  | crypto/tls.(*Conn).HandshakeContext(...)
AuthentikServer  |      /usr/local/go/src/crypto/tls/conn.go:1405
AuthentikServer  | net/http.(*conn).serve(0xc000689040, {0x12b7e98, 0xc00028b740})
AuthentikServer  |      /usr/local/go/src/net/http/server.go:1873 +0xdd3
AuthentikServer  | created by net/http.(*Server).Serve
AuthentikServer  |      /usr/local/go/src/net/http/server.go:3102 +0x4db
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.12.1 and 2022.12.2
 - Deployment: docker-compose

**Additional context**
I use Authentik with a forward auth middleware in traefik 2.9.6
172.20.0.10 is the IP of my traefik container

**Comment by BeryJu** [comment]
So apparently on https://github.com/goauthentik/authentik/commit/06f67c738c13b3ad53076359c8fa92893e4ba325#diff-b42c1e113bdfa847fbb669d8a5f234121bd89a793cedae2983308b0a363ac069L67 calling `.IsSet()` can return true even when the value is nil, so this fixes it to check the actual value

As a workaround you can select any certificate in your tenant, which should stop this error from happening

**Comment by adaexec** [comment]
That works, thank you
