### ISSUE TITLE
Task send_mail encountered an error

### ISSUE THREAD

**Issue by simonszu** [goauthentik/authentik#4506]
**Describe the bug**
I have set up email password recovery, based on [this tutorial](https://www.youtube.com/watch?v=NKJkYz0BIlA)
For that, i have set up email connection via docker-compose following [this article](https://goauthentik.io/docs/installation/docker-compose#email-configuration-optional-but-recommended) 
Sending a test email following [this article](https://goauthentik.io/docs/troubleshooting/emails) is working well. 

Doing a test of the actual recovery step causes a System task exception. 

```
Task send_mail encountered an error: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/autoretry.py", line 54, in run
    ret = task.retry(exc=exc, **retry_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/task.py", line 717, in retry
    raise_with_context(exc)
  File "/usr/local/lib/python3.11/site-packages/celery/app/autoretry.py", line 34, in run
    return task._orig_run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/email/tasks.py", line 103, in send_mail
    raise exc
  File "/authentik/stages/email/tasks.py", line 73, in send_mail
    backend.open()
  File "/usr/local/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 80, in open
    self.connection = self.connection_class(
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
builtins.OSError: [Errno 99] Cannot assign requested address
```

**To Reproduce**
1. Log out
2. Click on "Forgot username or password"
3. Enter your username
4. Nothing happens
5. Log in
6. See error in Event list

**Expected behavior**
A password recovery email is sent out

**Screenshots**

**Logs**
```
{"auth_via": "unauthenticated", "event": "Task published", "host": "authentik.simonszu.de", "level": "info", "logger": "authentik.root.celery", "pid": 23, "request_id": "990fcf6936294582921a013fd2af0ede", "task_id": "abdeaf93-e0b7-4d37-a378-ffb799df5ec8", "task_name": "authentik.events.tasks.event_notification_handler", "timestamp": "2023-01-24T07:51:00.772054"}
{"auth_via": "unauthenticated", "event": "/application/o/token/", "host": "authentik.simonszu.de", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 23, "remote": "94.114.14.52", "request_id": "990fcf6936294582921a013fd2af0ede", "runtime": 121, "scheme": "https", "status": 200, "timestamp": "2023-01-24T07:51:00.816686", "user": "", "user_agent": "goauthentik.io/outpost/2023.1.2 (provider=Prometheus Naugol)"}
{"auth_via": "unauthenticated", "event": "/-/health/live/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 24, "remote": "127.0.0.1", "request_id": "a2b1afda8997484988701359d6a69a27", "runtime": 21, "scheme": "http", "status": 204, "timestamp": "2023-01-24T07:51:04.294991", "user": "", "user_agent": "goauthentik.io/proxy/healthcheck"}
{"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "localhost:9000", "level": "info", "logger": "authentik.asgi", "method": "HEAD", "pid": 23, "remote": "127.0.0.1", "request_id": "db0ccdc3944945938ef1b2ffb0e21fc7", "runtime": 14, "scheme": "http", "status": 204, "timestamp": "2023-01-24T07:51:21.626994", "user": "", "user_agent": "goauthentik.io lifecycle Healthcheck"}
{"auth_via": "unauthenticated", "event": "/-/health/live/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 23, "remote": "127.0.0.1", "request_id": "98a152dc673e42bda258074e887f90e9", "runtime": 16, "scheme": "http", "status": 204, "timestamp": "2023-01-24T07:51:34.288081", "user": "", "user_agent": "goauthentik.io/proxy/healthcheck"}
{"auth_via": "unauthenticated", "event": "/if/flow/recovery/?next=%2F", "host": "authentik.simonszu.de", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 23, "remote": "94.114.14.52", "request_id": "94d07236817c4883b1aa20cdbaa70587", "runtime": 35, "scheme": "https", "status": 200, "timestamp": "2023-01-24T07:51:48.578360", "user": "", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"}
{"auth_via": "unauthenticated", "event": "f(exec): Found existing plan for other flow, deleting plan", "flow_slug": "recovery", "host": "authentik.simonszu.de", "level": "warning", "logger": "authentik.flows.views.executor", "other_flow": "94c94641a2cb471db85a90990221b014", "pid": 23, "request_id": "ac0d70c5c8274815a98465e1d44cc611", "timestamp": "2023-01-24T07:51:48.840472"}
{"auth_via": "unauthenticated", "event": "/api/v3/flows/executor/recovery/?query=next%3D%252F", "host": "authentik.simonszu.de", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 23, "remote": "94.114.14.52", "request_id": "ac0d70c5c8274815a98465e1d44cc611", "runtime": 67, "scheme": "https", "status": 200, "timestamp": "2023-01-24T07:51:48.889056", "user": "", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"}
{"auth_via": "unauthenticated", "event": "/api/v3/flows/executor/recovery/?query=next%3D%252F", "host": "authentik.simonszu.de", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 23, "remote": "94.114.14.52", "request_id": "3c3d2a178cb14c0f96412004b635c8ed", "runtime": 32, "scheme": "https", "status": 302, "timestamp": "2023-01-24T07:51:51.725570", "user": "", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"}
{"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "localhost:9000", "level": "info", "logger": "authentik.asgi", "method": "HEAD", "pid": 23, "remote": "127.0.0.1", "request_id": "42b3b626ee904389b8519303a6ae3672", "runtime": 16, "scheme": "http", "status": 204, "timestamp": "2023-01-24T07:51:51.756284", "user": "", "user_agent": "goauthentik.io lifecycle Healthcheck"}
{"auth_via": "unauthenticated", "event": "Task published", "host": "authentik.simonszu.de", "level": "info", "logger": "authentik.root.celery", "pid": 24, "request_id": "a6a361ec510e4ecea8ed38b436d19c9f", "task_id": "dc9576a3-c8e0-494f-9ccf-f991d8d0270a", "task_name": "authentik.stages.email.tasks.send_mail", "timestamp": "2023-01-24T07:51:51.818397"}
{"auth_via": "unauthenticated", "event": "/api/v3/flows/executor/recovery/?query=next%3D%252F", "host": "authentik.simonszu.de", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 24, "remote": "94.114.14.52", "request_id": "a6a361ec510e4ecea8ed38b436d19c9f", "runtime": 78, "scheme": "https", "status": 200, "timestamp": "2023-01-24T07:51:51.830386", "user": "", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"}
{"auth_via": "unauthenticated", "event": "/-/health/live/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 24, "remote": "127.0.0.1", "request_id": "486d6295e6f94033b5ceef29b8d7905b", "runtime": 16, "scheme": "http", "status": 204, "timestamp": "2023-01-24T07:52:04.287649", "user": "", "user_agent": "goauthentik.io/proxy/healthcheck"}
{"event":"updating tenant certificates","level":"info","logger":"authentik.router.tenant_tls","timestamp":"2023-01-24T07:52:04Z"}
{"auth_via": "secret_key", "event": "/api/v3/core/tenants/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 24, "remote": "127.0.0.1", "request_id": "ee5389f187984ab881587bf7ed001159", "runtime": 50, "scheme": "http", "status": 200, "timestamp": "2023-01-24T07:52:04.947253", "user": "ak-outpost-68ff9004e4c94388a78d9038bd6f1ac3", "user_agent": "goauthentik.io/outpost/2023.1.2"}
{"action": "login", "auth_via": "unauthenticated", "client_ip": "94.114.14.52", "context": {"PLAN_CONTEXT_APPLICATION": {"app": "authentik_core", "model_name": "application", "name": "Prometheus Naugol", "pk": "e33a7de084b14a34a5f10a27678fd7f4"}, "PLAN_CONTEXT_METHOD": "token", "PLAN_CONTEXT_METHOD_ARGS": {"identifier": "prometheus-scraper-password"}, "geo": {"city": "Dortmund", "continent": "EU", "country": "DE", "lat": 51.5208, "long": 7.4442}, "http_request": {"args": {}, "method": "POST", "path": "/application/o/token/"}}, "event": "Created Event", "host": "authentik.simonszu.de", "level": "info", "logger": "authentik.events.models", "pid": 24, "request_id": "466fccaa62d34f159dff717805346453", "timestamp": "2023-01-24T07:52:15.763774", "user": {"email": "", "pk": 8, "username": "prometheus-scraper"}}
```
**Version and Deployment (please complete the following information):**
 - authentik version: 2023.1.2 - but happened with 2022.12.2 as well. 
 - Deployment: docker-compose

**Additional context**

**Comment by sevenwalls2081** [comment]
@simonszu I'm having the same issue however I can't even get the test email to work.  If you don't mind sharing your configuration for the email portion (of course omitting identifiable info) I'd like to see if maybe I've set mine up incorrectly.  I've followed all of the same tutorial's you have but at the very least you can get the test email to work.  FYI, I'm attempting to use an external SMTP server for this.

**Comment by simonszu** [comment]
Yeah, similar solution for me. I did not use the docker compose to download, but wrote an ansible playbook to deploy authentik and some remote outposts, and i did not set up the email envs for the worker, but only on the server, and tested the email on the master, not being aware that the workers are responsible to sent them out.
