### ISSUE TITLE
Webhook notification transports that do not receive a response trigger: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by rhaex** [goauthentik/authentik#4589]
**Describe the bug**
Notification transports that fail to be delivered do not give proper feedback.

**To Reproduce**
1. Create a Webhook Property mapping called `user-mapping-create`
As expression use:
```
return {
	"user_email":notification.event.context["email"],
	"user_name":notification.event.context["name"],
	"user_username":notification.event.context["username"],
	"created":notification.event.context["created"]
}
```
2. Create an Event matcher policy called `user-trigger-create`, bind it to the `User Write` action, leave ClientIP and App empty.
3. Create a notification transport called `user-transport-create` of type Webhook. Set send once to true and use the webhook mapping that was created before. For endpoint use some localhost endpoint that does not exist or respond.
4. Create a notification rule called `user-rule-create` and use the transport created before, and bind the created event matcher policy to it.
5. Create a new user

**Expected behavior**
Because the transport endpoint is not responding or incorrect, you would expect a proper error message to be shown.
Instead it seems that it always assumes to receive a response with a text, because in this case it cannot connect and therefor there will be no response, null object does not contain a text value which triggers this technical error message.

**Logs**
<details>
    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/autoretry.py", line 34, in run
    return task._orig_run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/events/tasks.py", line 126, in notification_transport
    transport.send(notification)
  File "/authentik/events/models.py", line 324, in send
    return self.send_webhook(notification)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/events/models.py", line 365, in send_webhook
    raise NotificationTransportError(exc.response.text) from exc
                                     ^^^^^^^^^^^^^^^^^
builtins.AttributeError: 'NoneType' object has no attribute 'text'
```
</details>

**Version and Deployment (please complete the following information):**
- authentik version: 2023.1.2
- Deployment: custom k8s deployment

**Comment by rhaex** [comment]
After some more debugging it turns out that the webhook endpoint used does not respond properly because of incorrect configuration, so the webhook functionality is not broken as it seemed before.

I updated the original ticket, and the priority is also much lower. It would still be a helpful improvement to provide a proper error message in these cases instead of this generic NoneType error so thats why the ticket is not closed.

**Comment by rhaex** [comment]
After some more debugging it turns out that the webhook endpoint used does not respond properly because of incorrect configuration, so the webhook functionality is not broken as it seemed before.

I updated the original ticket, and the priority is also much lower. It would still be a helpful improvement to provide a proper error message in these cases instead of this generic NoneType error so thats why the ticket is not closed.
