### ISSUE TITLE
authentik server crashing with "Exception in ASGI application"

### ISSUE THREAD

**Issue by fischer-felix** [goauthentik/authentik#4646]
**Describe the bug**
After running for about 48h, my Authentik server crashes with the message `Exception in ASGI application`. Restarting it works flawlessly, however the issue always appears again sooner or later.

**To Reproduce**
1. Deploy authentik usgin the official guide and compose file
2. Wait for ~2 days
3. See that authentik-server container will have crashed

**Expected behavior**
Container does not crash.

**Logs**
```
Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/websockets/wsproto_impl.py", line 208, in run_asgi
    result = await self.app(self.scope, self.receive, self.send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
    raise exc from None
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/asgi.py", line 139, in _run_asgi3
    return await self._run_app(scope, lambda: self.app(scope, receive, send))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/asgi.py", line 188, in _run_app
    raise exc from None
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/asgi.py", line 183, in _run_app
    return await callback()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/channels/routing.py", line 62, in __call__
    return await application(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/root/asgi.py", line 54, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/channels/routing.py", line 116, in __call__
    return await application(
           ^^^^^^^^^^^^^^^^^^
  File "/authentik/lib/sentry.py", line 48, in __call__
    return await self.inner(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/channels/consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "/usr/local/lib/python3.11/site-packages/channels/utils.py", line 57, in await_many_dispatch
    await task
redis.exceptions.ConnectionError: Connection closed by server.
{"error":"websocket: close 1006 (abnormal closure): unexpected EOF","event":"ws read error","level":"warning","logger":"authentik.outpost.ak-api-controller","loop":"ws-handler","timestamp":"2023-02-08T05:26:26Z"}
1675833986.872803 [info     ] Handling signal: term          [gunicorn.error] 
{"event":"shutting down webserver","level":"info","logger":"authentik.root","timestamp":"2023-02-08T05:26:26Z"}
{"event":"shutting down gunicorn","level":"info","logger":"authentik.root","timestamp":"2023-02-08T05:26:26Z"}
{"event":"stopping gunicorn","level":"warning","logger":"authentik.router.unicorn","method":"sigterm","timestamp":"2023-02-08T05:26:26Z"}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.12.2
 - Deployment: docker-compose

**Additional context**
I am using watchtower to keep my containers up to date, however its logs don't show anything unusual around that time and it should run every day, not every two days.

**Comment by BeryJu** [comment]
Looks like watchtower is updating redis, cause the authentik connection to break and authentik to restart. With the default docker compose the server and worker containers will just restart, so there shouldn't be any actual impact from that

**Comment by fischer-felix** [comment]
Just an update on this: updating to 2023.4.0 fixed the issue for me, haven't had any issues so far (1 week uptime).
