### ISSUE TITLE
Trying to create a token from a blueprint results in `builtins.KeyError: 'request'`

### ISSUE THREAD

**Issue by traverseda** [goauthentik/authentik#4716]
**Describe the bug**

Trying to create a token from a blueprint results in `builtins.KeyError: 'request'`.

**To Reproduce**

Run the following blueprint

 ```
- attrs:
    attributes: {}
    name: ldapsearch
  conditions: []
  id: ldapsearch-group
  identifiers:
    name: ldapsearch
  model: authentik_core.group
  state: present

- attrs:
    attributes:
      goauthentik.io/user/service-account: true
      goauthentik.io/user/token-expires: false
    is_active: true
    name: ldapservice
    path: goauthentik.io/service-accounts
    username: ldapservice
    groups:
      - !KeyOf ldapsearch-group
    
  conditions: []
  id: ldapservice-user
  identifiers:
    name: ldapservice
  model: authentik_core.user
  state: present


- attrs:
    identifier: service-account-ldapservice-password
    intent: app_password
    key: test_password_please_ignore
    user: !KeyOf ldapservice-user
  conditions: []
  id: null
  identifiers:
    identifier: service-account-ldapservice-password
  model: authentik_core.token
  state: present
```

**Logs**
<details>
    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/django/views.py", line 85, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/api/decorators.py", line 31, in wrapper
    return func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/blueprints/api.py", line 125, in apply
    apply_blueprint.delay(str(blueprint.pk)).get()
  File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 224, in get
    return self.backend.wait_for_pending(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/backends/asynchronous.py", line 223, in wait_for_pending
    return result.maybe_throw(callback=callback, propagate=propagate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 336, in maybe_throw
    self.throw(value, self._to_remote_traceback(tb))
  File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 329, in throw
    self.on_ready.throw(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 234, in throw
    reraise(type(exc), exc, tb)
  File "/usr/local/lib/python3.11/site-packages/vine/utils.py", line 30, in reraise
    raise value
builtins.KeyError: 'request'
```
</details>

**Version and Deployment (please complete the following information):**
- authentik version: 2023.2.2
- Deployment: docker compose

**Comment by traverseda** [comment]
Amazing, thanks!
