### ISSUE TITLE
Unable to authenticate using Discord Social Login

### ISSUE THREAD

**Issue by miovo** [goauthentik/authentik#4817]
**Describe the bug**
I added and configured the Discord Social Login to use to allow people to login with Discord without me having to create an account manually. 

When clicking on the discord login button from the login page for the first time, it create the user and drops the user at the dashboard however upon logging into using the discord button, it drops the user back at the login screen with no error.

**To Reproduce**
1. After configuring the Discord social login config, attempt to login for the first time
2. Logout and attempt to login back in using Discord

**Expected behavior**
Authenticate without issue

**Screenshots**

**Logs**
<details>
    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 207, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 202, in _inner
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/core/tasks.py", line 46, in clean_expired_models
    value = cache.get(cache_key)
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_redis/cache.py", line 91, in get
    value = self._get(key, default, version, client)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_redis/cache.py", line 31, in _decorator
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_redis/cache.py", line 98, in _get
    return self.client.get(key, default=default, version=version, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_redis/client/default.py", line 265, in get
    return self.decode(value)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_redis/client/default.py", line 448, in decode
    value = self._serializer.loads(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_redis/serializers/pickle.py", line 32, in loads
    return pickle.loads(value)
           ^^^^^^^^^^^^^^^^^^^
builtins.ModuleNotFoundError: No module named 'authentik.providers.saml.processors.authn_request_parser'
```
</details>

**Version and Deployment (please complete the following information):**
- authentik version: 2023.2.2
- Deployment: docker-compose

**Additional context**

EDIT: This also appears to happen with any of the Social Login options.

**Comment by slimshizn** [comment]
I suggest you go to the authentik discord and search discord login. You have a better chance of finding answers there.
