### ISSUE TITLE
ldap version 2023.3.0 fails to start

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [goauthentik/authentik#4929]
**Describe the bug**
ldap version 2023.3.0 fails to start. Stuck in a boot loop.

**To Reproduce**
1. Create an ldap outpost
2. See error in docker logs

**Expected behavior**
Ldap container starts.

**Logs**
```
DBG undefined | event=Loaded config from environment timestamp=2023-03-13T19:16:14Z 
timestamp="2023-03-13T19:16:14Z" level=info event="Starting Debug server" listen="0.0.0.0:9900" logger=authentik.go_debugger
timestamp="2023-03-13T19:16:15Z" level=panic event="Failed to run server" error="500 Internal Server Error"
timestamp="2023-03-13T19:16:15Z" level=info event="finished shutdown" logger=authentik.outpost.ak-api-controller
panic: (*logrus.Entry) 0xc0002140e0

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc000214070, 0x0, {0xc00003a0d8, 0x14})
	/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:260 +0x4d6
github.com/sirupsen/logrus.(*Entry).Log(0xc000214070, 0x0, {0xc000623e50?, 0xfc7060?, 0xc0002d20c0?})
	/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:304 +0x4f
github.com/sirupsen/logrus.(*Entry).Panic(...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:342
main.main()
	/go/src/goauthentik.io/cmd/ldap/main.go:73 +0x585
DBG undefined | event=Loaded config from environment timestamp=2023-03-13T19:16:16Z 
timestamp="2023-03-13T19:16:16Z" level=info event="Starting Debug server" listen="0.0.0.0:9900" logger=authentik.go_debugger
timestamp="2023-03-13T19:16:16Z" level=panic event="Failed to run server" error="500 Internal Server Error"
timestamp="2023-03-13T19:16:16Z" level=info event="finished shutdown" logger=authentik.outpost.ak-api-controller
panic: (*logrus.Entry) 0xc0001a8230

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc0001a8150, 0x0, {0xc00003a1c8, 0x14})
	/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:260 +0x4d6
github.com/sirupsen/logrus.(*Entry).Log(0xc0001a8150, 0x0, {0xc0005abe50?, 0xfc7060?, 0xc000132200?})
	/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:304 +0x4f
github.com/sirupsen/logrus.(*Entry).Panic(...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:342
main.main()
	/go/src/goauthentik.io/cmd/ldap/main.go:73 +0x585
DBG undefined | event=Loaded config from environment timestamp=2023-03-13T19:16:17Z 
timestamp="2023-03-13T19:16:17Z" level=info event="Starting Debug server" listen="0.0.0.0:9900" logger=authentik.go_debugger
timestamp="2023-03-13T19:16:18Z" level=panic event="Failed to run server" error="500 Internal Server Error"
timestamp="2023-03-13T19:16:18Z" level=info event="finished shutdown" logger=authentik.outpost.ak-api-controller
panic: (*logrus.Entry) 0xc0000ec3f0

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc0000ec380, 0x0, {0xc00003aa38, 0x14})
	/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:260 +0x4d6
github.com/sirupsen/logrus.(*Entry).Log(0xc0000ec380, 0x0, {0xc00056fe50?, 0xfc7060?, 0xc0004320c0?})
	/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:304 +0x4f
github.com/sirupsen/logrus.(*Entry).Panic(...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:342
main.main()
	/go/src/goauthentik.io/cmd/ldap/main.go:73 +0x585
DBG undefined | event=Loaded config from environment timestamp=2023-03-13T19:16:19Z 
timestamp="2023-03-13T19:16:19Z" level=info event="Starting Debug server" listen="0.0.0.0:9900" logger=authentik.go_debugger
timestamp="2023-03-13T19:16:19Z" level=panic event="Failed to run server" error="500 Internal Server Error"
timestamp="2023-03-13T19:16:19Z" level=info event="finished shutdown" logger=authentik.outpost.ak-api-controller
panic: (*logrus.Entry) 0xc00055a930

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc00055a8c0, 0x0, {0xc00003a618, 0x14})
	/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:260 +0x4d6
github.com/sirupsen/logrus.(*Entry).Log(0xc00055a8c0, 0x0, {0xc000509e50?, 0xfc7060?, 0xc0001324c0?})
	/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:304 +0x4f
github.com/sirupsen/logrus.(*Entry).Panic(...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:342
main.main()
	/go/src/goauthentik.io/cmd/ldap/main.go:73 +0x585
DBG undefined | event=Loaded config from environment timestamp=2023-03-13T19:16:20Z 
timestamp="2023-03-13T19:16:20Z" level=info event="Starting Debug server" listen="0.0.0.0:9900" logger=authentik.go_debugger
timestamp="2023-03-13T19:16:21Z" level=panic event="Failed to run server" error="500 Internal Server Error"
timestamp="2023-03-13T19:16:21Z" level=info event="finished shutdown" logger=authentik.outpost.ak-api-controller
panic: (*logrus.Entry) 0xc0001d2310

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc0001d22a0, 0x0, {0xc0003d8000, 0x14})
	/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:260 +0x4d6
github.com/sirupsen/logrus.(*Entry).Log(0xc0001d22a0, 0x0, {0xc000743e50?, 0xfc7060?, 0xc000300080?})
	/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:304 +0x4f
github.com/sirupsen/logrus.(*Entry).Panic(...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:342
main.main()
	/go/src/goauthentik.io/cmd/ldap/main.go:73 +0x585


```

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.3.0
 - Deployment: docker

**Additional context**

**Comment by BeryJu** [comment]
Check that your authentik server is updated correctly, this is not an issue in the LDAP outpost but rather looks like an issue caused by missing migrations

**Comment by Cookie-Monster-Coder** [comment]
I just restored a backup from this morning (version 2023.2.3) and used ```docker compose pull``` and ```docker compose up -d``` and still the same error. Also created a fresh setup of authentik and same issue.

**Comment by BeryJu** [comment]
Can you post the logs of the authentik server and worker container

**Comment by Cookie-Monster-Coder** [comment]
This is a brand new setup:
[authtest-server-1_logs.txt](https://github.com/goauthentik/authentik/files/10962238/authtest-server-1_logs.txt)
[authtest-worker-1_logs.txt](https://github.com/goauthentik/authentik/files/10962239/authtest-worker-1_logs.txt)

**Comment by BeryJu** [comment]
The issue is caused by the LDAP provider not having a bind flow selected. This should've been required by the API but that's not the case.

**Comment by davidus05** [comment]
Still a problem in 2023.3.1, can't bring authentik up. 

Container status always goes from **Up Less than a second (health: starting)** to **Restarting (1) Less than a second ago**

Can you also reproduce that an upgrade from 2022.2.3 to 2023.3.1 does not work as intended?
