### ISSUE TITLE
Adding internal blueprint through console creates blueprint with no metadata

### ISSUE THREAD

**Issue by jarrettprosser** [goauthentik/authentik#5036]
**Describe the bug**
I'm trying to add a simple blueprint via the console. I give the blueprint instance a name, select "Internal", and paste the blueprint content into the textfield. I press 

**To Reproduce**
1. Go to "Customisation > Blueprints"
2. Click on "Create"
3. Add a name for the blueprint
4. Select "Internal" 
5. Paste the blueprint content: 
```
version: 1
metadata:
  name: Test Blueprint
entries:
- model: authentik_events.notificationtransport
  id: test-email-transport
  attrs:
    mode: email
  identifiers:
    name: test-email-transport
```
<img width="1151" alt="Screenshot 2023-03-22 at 11 30 59 am" src="https://user-images.githubusercontent.com/63215649/226772209-82ef9ea0-d351-4de6-8222-4ed53abc967c.png">

6. Press "Create", observe the "Successfully created instance" banner.
7. Select ">" to load the next page of the table and see the new blueprint.
8. The table loads indefinitely. 
<img width="1086" alt="Screenshot 2023-03-22 at 11 31 24 am" src="https://user-images.githubusercontent.com/63215649/226772253-5656d651-e3fc-44aa-a370-73e820e54b4f.png">
There is an error in the console. 

```
BlueprintListPage.ts:129 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.hasOwn (<anonymous>)
    at n.value (BlueprintListPage.ts:129:20)
    at Table.ts:380:28
    at Array.map (<anonymous>)
    at n.value (Table.ts:292:22)
    at n.value (Table.ts:279:25)
    at n.value (Table.ts:502:78)
    at n.value (TablePage.ts:84:59)
    at n.update (lit-element.js:6:304)
    at n.performUpdate (reactive-element.js:6:4849)
    at n.scheduleUpdate (reactive-element.js:6:4496)
    at n._$Ej (reactive-element.js:6:4404)
```
In the database, the record has no metadata. 

<img width="1837" alt="Screenshot 2023-03-22 at 11 33 24 am" src="https://user-images.githubusercontent.com/63215649/226772276-218a2a33-6561-456b-8367-85383d34777c.png">

Removing the record from the database, or adding metadata with a name and empty labels, corrects the loading behaviour: 

<img width="1861" alt="Screenshot 2023-03-22 at 11 34 57 am" src="https://user-images.githubusercontent.com/63215649/226772303-bf9adca1-e9cc-4ab4-9f53-407729df1c47.png">

<img width="1092" alt="Screenshot 2023-03-22 at 11 34 40 am" src="https://user-images.githubusercontent.com/63215649/226772290-e2dee054-0e71-45e5-9d4f-465a73082b77.png">

Running the blueprint creates the expected resource: 

<img width="1090" alt="Screenshot 2023-03-22 at 11 37 37 am" src="https://user-images.githubusercontent.com/63215649/226772414-12141f6a-2f8d-437a-a297-5a289ffae121.png">

**Expected behavior**
Adding an internal blueprint will not cause the console to fail to load the page. 

**Screenshots**
Embedded above in context. 

**Logs**
```
{"auth_via": "session", "event": "Task published", "host": "authentik.bench01.future-grid.com", "level": "info", "logger": "authentik.root.celery", "pid": 19020, "request_id": "87b004ca6543404ab36e7a72d921a4b1", "task_id": "e951bc74-2f23-49f8-91dd-ba0651ddb707", "task_name": "authentik.blueprints.v1.tasks.apply_blueprint", "timestamp": "2023-03-22T00:36:58.734710"}
{"auth_via": "session", "event": "/api/v3/managed/blueprints/213c3e0b-e2c8-4357-a59c-12a7d1e0d255/apply/", "host": "authentik.bench01.future-grid.com", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 19020, "remote": "10.3.1.34", "request_id": "87b004ca6543404ab36e7a72d921a4b1", "runtime": 52, "scheme": "https", "status": 200, "timestamp": "2023-03-22T00:36:58.767302", "user": "akadmin", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"}
{"auth_via": "session", "event": "/api/v3/root/config/", "host": "authentik.bench01.future-grid.com", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19020, "remote": "10.3.1.34", "request_id": "06f119d7a60f45baa6a6299d9b08a6ca", "runtime": 14, "scheme": "https", "status": 200, "timestamp": "2023-03-22T00:36:58.830907", "user": "akadmin", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"}
{"auth_via": "session", "event": "/api/v3/core/tenants/current/", "host": "authentik.bench01.future-grid.com", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19020, "remote": "10.3.1.34", "request_id": "adb26d0b0ec148ac87b6705ec369b53b", "runtime": 14, "scheme": "https", "status": 200, "timestamp": "2023-03-22T00:36:58.832409", "user": "akadmin", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"}
{"auth_via": "session", "event": "/api/v3/managed/blueprints/?ordering=name&page=2&page_size=20&search=", "host": "authentik.bench01.future-grid.com", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 18230, "remote": "10.3.1.34", "request_id": "0ba9cf9a4fb14ba7b3452ae098af5fd1", "runtime": 15, "scheme": "https", "status": 200, "timestamp": "2023-03-22T00:36:58.832812", "user": "akadmin", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"}
{"auth_via": "session", "event": "/api/v3/managed/blueprints/213c3e0b-e2c8-4357-a59c-12a7d1e0d255/", "host": "authentik.bench01.future-grid.com", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19020, "remote": "10.3.1.34", "request_id": "f45fa8dcfb8b4838b79e9c78918f1781", "runtime": 15, "scheme": "https", "status": 200, "timestamp": "2023-03-22T00:37:05.136808", "user": "akadmin", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.3.1
 - Deployment: Helm

**Comment by BeryJu** [comment]
thanks for the very detailed issue report @jarrettprosser

**Comment by macmoritz** [comment]
Quickfix via `ak shell`:
```
>>> bp = BlueprintInstance.objects.get(name="your-blueprint-name")
>>> bp.metadata = {"name": "your-blueprint-name", "labels": {}}
>>> bp.save()
```

**Comment by macmoritz** [comment]
#5295 fixes this
