### ISSUE TITLE
BluePrintListPage.ts crashed and stuck loading

### ISSUE THREAD

**Issue by macmoritz** [goauthentik/authentik#5112]
**Describe the bug**
I created a Blueprint and something went wrong. Now it is stuck loading as seen in the screenshot. JS error below.

**To Reproduce**
IDK by now, just created a blueprint

**Screenshots**
![image](https://user-images.githubusercontent.com/49832924/228349501-93de6397-7c8e-4a07-8601-c4170b227544.png)

**Logs**
BlueprintListPage.ts:129 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.hasOwn (<anonymous>)
    at n.value (BlueprintListPage.ts:129:20)
    at Table.ts:380:28
    at Array.map (<anonymous>)
    at n.value (Table.ts:292:22)
    at n.value (Table.ts:279:25)
    at n.value (Table.ts:502:78)
    at n.value (TablePage.ts:84:59)
    at n.update (lit-element.js:6:304)
    at n.performUpdate (reactive-element.js:6:4849)
    at n.scheduleUpdate (reactive-element.js:6:4496)
    at n._$Ej (reactive-element.js:6:4404)

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.3.1
 - Deployment: helm

**Comment by BeryJu** [comment]
See https://github.com/goauthentik/authentik/issues/5036, the error happens due to missing metadata, you can add an empty metadata block via the API or the blueprint file

**Comment by macmoritz** [comment]
Deleted them via ak shell. Model is BlueprintInstance

**Comment by benedikt-bartscher** [comment]
Same issue persists on Authentik 2023.4.1
