### ISSUE TITLE
Authentik Server Container Down

### ISSUE THREAD

**Issue by julianq** [goauthentik/authentik#5439]
Cannot access Authentik at all, even on local network with local IP.

Container logs show the following:

```
2023-05-01 14:09:31 [info     ] applying django migrations
2023-05-01 14:09:31 [info     ] waiting to acquire database lock
DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.126205 DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.126205 path=authentik.admin.settings
DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.1278417 DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.1278417 path=authentik.crypto.settings
DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.129099 DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.129099 path=authentik.events.settings
DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.1315231 DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.1315231 path=authentik.outposts.settings
DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.1374028 DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.1374028 path=authentik.policies.reputation.settings
DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.1428263 DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.1428263 path=authentik.providers.scim.settings
DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.1451895 DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.1451895 path=authentik.sources.ldap.settings
DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.1470203 DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.1470203 path=authentik.sources.plex.settings
DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.1498363 DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.1498363 path=authentik.stages.authenticator_static.settings
DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.1506383 DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.1506383 path=authentik.stages.authenticator_totp.settings
DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.1515846 DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.1515846 path=authentik.stages.authenticator_validate.settings
DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.1605437 DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.1605437 path=authentik.blueprints.settings
INF INF INF INF INF INF INF INF event=Booting authentik INF INF INF INF INF INF INF INF event=Booting authentik logger=authentik.lib.config INF INF INF INF INF INF INF INF event=Booting authentik INF INF INF INF INF INF INF INF event=Booting authentik logger=authentik.lib.config timestamp=1682950172.1606798 INF INF INF INF INF INF INF INF event=Booting authentik INF INF INF INF INF INF INF INF event=Booting authentik logger=authentik.lib.config INF INF INF INF INF INF INF INF event=Booting authentik INF INF INF INF INF INF INF INF event=Booting authentik logger=authentik.lib.config timestamp=1682950172.1606798 version=2023.4.1
INF INF INF INF INF INF INF INF event=Enabled authentik enterprise INF INF INF INF INF INF INF INF event=Enabled authentik enterprise logger=authentik.lib.config INF INF INF INF INF INF INF INF event=Enabled authentik enterprise INF INF INF INF INF INF INF INF event=Enabled authentik enterprise logger=authentik.lib.config timestamp=1682950172.1618795
DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.1621847 DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings DBG DBG DBG DBG DBG DBG DBG DBG event=Loaded app settings logger=authentik.lib.config timestamp=1682950172.1621847 path=authentik.enterprise.settings
INF INF INF INF INF INF INF INF event=Loaded GeoIP database INF INF INF INF INF INF INF INF event=Loaded GeoIP database last_write=1682873719 INF INF INF INF INF INF INF INF event=Loaded GeoIP database INF INF INF INF INF INF INF INF event=Loaded GeoIP database last_write=1682873719 logger=authentik.events.geo INF INF INF INF INF INF INF INF event=Loaded GeoIP database INF INF INF INF INF INF INF INF event=Loaded GeoIP database last_write=1682873719 INF INF INF INF INF INF INF INF event=Loaded GeoIP database INF INF INF INF INF INF INF INF event=Loaded GeoIP database last_write=1682873719 logger=authentik.events.geo pid=9 INF INF INF INF INF INF INF INF event=Loaded GeoIP database INF INF INF INF INF INF INF INF event=Loaded GeoIP database last_write=1682873719 INF INF INF INF INF INF INF INF event=Loaded GeoIP database INF INF INF INF INF INF INF INF event=Loaded GeoIP database last_write=1682873719 logger=authentik.events.geo INF INF INF INF INF INF INF INF event=Loaded GeoIP database INF INF INF INF INF INF INF INF event=Loaded GeoIP database last_write=1682873719 INF INF INF INF INF INF INF INF event=Loaded GeoIP database INF INF INF INF INF INF INF INF event=Loaded GeoIP database last_write=1682873719 logger=authentik.events.geo pid=9 timestamp=2023-05-01T14:09:32.513519
INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery pid=9 INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery pid=9 task_id=93b10e7b-6ff3-4cbe-a854-0e76d484334b INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery pid=9 INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery pid=9 task_id=93b10e7b-6ff3-4cbe-a854-0e76d484334b task_name=authentik.blueprints.v1.tasks.blueprints_discovery INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery pid=9 INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery pid=9 task_id=93b10e7b-6ff3-4cbe-a854-0e76d484334b INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery pid=9 INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery pid=9 task_id=93b10e7b-6ff3-4cbe-a854-0e76d484334b task_name=authentik.blueprints.v1.tasks.blueprints_discovery timestamp=2023-05-01T14:09:33.036700
INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery pid=9 INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery pid=9 task_id=d801a525-1729-49da-934a-f0854f3a9061 INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery pid=9 INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery pid=9 task_id=d801a525-1729-49da-934a-f0854f3a9061 task_name=authentik.blueprints.v1.tasks.clear_failed_blueprints INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery pid=9 INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery pid=9 task_id=d801a525-1729-49da-934a-f0854f3a9061 INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery pid=9 INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery INF INF INF INF INF INF INF INF event=Task published INF INF INF INF INF INF INF INF event=Task published logger=authentik.root.celery pid=9 task_id=d801a525-1729-49da-934a-f0854f3a9061 task_name=authentik.blueprints.v1.tasks.clear_failed_blueprints timestamp=2023-05-01T14:09:33.037949
Operations to perform:
  Apply all migrations: auth, authentik_blueprints, authentik_core, authentik_crypto, authentik_events, authentik_flows, authentik_outposts, authentik_policies, authentik_policies_dummy, authentik_policies_event_matcher, authentik_policies_expiry, authentik_policies_expression, authentik_policies_password, authentik_policies_reputation, authentik_providers_ldap, authentik_providers_oauth2, authentik_providers_proxy, authentik_providers_radius, authentik_providers_saml, authentik_providers_scim, authentik_sources_ldap, authentik_sources_oauth, authentik_sources_plex, authentik_sources_saml, authentik_stages_authenticator_duo, authentik_stages_authenticator_sms, authentik_stages_authenticator_static, authentik_stages_authenticator_totp, authentik_stages_authenticator_validate, authentik_stages_authenticator_webauthn, authentik_stages_captcha, authentik_stages_consent, authentik_stages_deny, authentik_stages_dummy, authentik_stages_email, authentik_stages_identification, authentik_stages_invitation, authentik_stages_password, authentik_stages_prompt, authentik_stages_user_delete, authentik_stages_user_login, authentik_stages_user_logout, authentik_stages_user_write, authentik_tenants, contenttypes, guardian, otp_static, otp_totp, sessions
Running migrations:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_prometheus/db/common.py", line 71, in execute
    return super().execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UniqueViolation: could not create unique index "authentik_crypto_certificatekeypair_name_719603a4_uniq"
DETAIL:  Key (name)=(authentik Self-signed Certificate_2) is duplicated.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/lifecycle/migrate.py", line 95, in <module>
    execute_from_command_line(["", "migrate"])
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/migration.py", line 130, in apply
    operation.database_forwards(
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/operations/fields.py", line 235, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 788, in alter_field
    self._alter_field(
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/postgresql/schema.py", line 245, in _alter_field
    super()._alter_field(
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 1045, in _alter_field
    self.execute(self._create_unique_sql(model, [new_field]))
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 199, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/django/__init__.py", line 582, in execute
    return real_execute(self, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_prometheus/db/common.py", line 71, in execute
    return super().execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: could not create unique index "authentik_crypto_certificatekeypair_name_719603a4_uniq"
DETAIL:  Key (name)=(authentik Self-signed Certificate_2) is duplicated.
  Applying authentik_crypto.0004_alter_certificatekeypair_name...
```

Issue started overnight, have not changed any settings.

**Comment by julianq** [comment]
Fixed by rolling back fro dev to 2023.4.1

**Comment by rmundel** [comment]
Same here when using the release 2023.5.0

**Comment by kapsikkum** [comment]
Roll back to 2023.4.1 then delete any duplicate certificates (make sure you don't use them), that's what fixed it for me

**Comment by rmundel** [comment]
@kapsikkum indeed that was the issue. Thanks!

**Comment by BeryJu** [comment]
duplicate of #5650, which has a workaround included
