### ISSUE TITLE
Post-update errors due to upstream PostgreSQL error

### ISSUE THREAD

**Issue by Chifilly** [goauthentik/authentik#5590]
**Describe the bug**
After updating, I can no longer authenticate, because attempting to gives the `Something went wrong! Please try again later.` error.

**To Reproduce**
For me, just be on the latest version and try and use it. I don't know of the cause.

**Expected behavior**
I can access the login page and/or authenticate.

**Logs**
The errors I could find on the server are;
```
OperationalError('could not load library "/usr/local/lib/postgresql/llvmjit.so": Error relocating /usr/local/lib/postgresql/llvmjit.so: LLVMBuildGEP: symbol not found
```
and
```
Traceback (most recent call last):
  File "/authentik/flows/views/executor.py", line 298, in get
    stage_response = self.current_stage_view.get(request, *args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/flows/stage.py", line 93, in get
    challenge = self._get_challenge(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/flows/stage.py", line 163, in _get_challenge
    challenge = self.get_challenge(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/identification/stage.py", line 231, in get_challenge
    for source in sources:
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 394, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/model_utils/managers.py", line 20, in __iter__
    for obj in iter:
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
	              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/django/__init__.py", line 582, in execute
    return real_execute(self, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_prometheus/db/common.py", line 71, in execute
    return super().execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: could not load library "/usr/local/lib/postgresql/llvmjit.so": Error relocating /usr/local/lib/postgresql/llvmjit.so: LLVMBuildGEP: symbol not found
```

I also noticed that the `Flows` page threw the same or similar error to the logs and wouldn't load anything in the table, but after clearing cookies to see if that fixed it, I can no longer access the dashboard.

Also, all my authentication goes through `/if/flow/default-authentication-flow` if that makes a difference, so all my redirects to the login page will go to that path.

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.4.1
-   Deployment: docker-compose

**Comment by scolastico** [comment]
Same problem here please fix asap.

**Comment by tanpro260196** [comment]
Found the problem it's a postgresql issue, please downgrade to 12-alpine3.17 for a temporary workaround.

**Comment by rzumbado** [comment]
> Found the problem it's a postgresql issue, please downgrade to `12-alpine3.17` for a temporary workaround. Postgresql issue: [docker-library/postgres#1076](https://github.com/docker-library/postgres/issues/1076)

I can confirm this worked. Thanks for the quick workaround, I was in full panic mode this morning.

**Comment by gtronset** [comment]
Hopefully they'll have this resolved soon, a Dev literally just posted they're working on a fix: https://github.com/docker-library/postgres/issues/1076#issuecomment-1546087911

**Comment by tanpro260196** [comment]
Postgresql docker team fixed the issue, everyone can safely update now.

**Comment by Chifilly** [comment]
Can confirm it has been fixed. I switched back to `12-alpine` from `12-alpine3.17` and it still works
