### ISSUE TITLE
FLOWS WONT EXECUTE / GET /api/v3/flows/executor/ldap-auth-flow/

### ISSUE THREAD

**Issue by Mafyuh** [goauthentik/authentik#5593]
**Describe the bug**
Flows will not load in admin interface nor are any flows actually executing, thus cannot login besides recovery.

**Expected behavior**
Flows load and execute

**Logs**
<details>
    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
  File "/authentik/flows/views/executor.py", line 296, in get
    stage_response = self.current_stage_view.get(request, *args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/flows/stage.py", line 93, in get
    challenge = self._get_challenge(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/flows/stage.py", line 163, in _get_challenge
    challenge = self.get_challenge(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/identification/stage.py", line 231, in get_challenge
    for source in sources:
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 394, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/model_utils/managers.py", line 20, in __iter__
    for obj in iter:
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_prometheus/db/common.py", line 71, in execute
    return super().execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: could not load library "/usr/local/lib/postgresql/llvmjit.so": Error relocating /usr/local/lib/postgresql/llvmjit.so: LLVMBuildGEP: symbol not found

```
</details>

**Version and Deployment (please complete the following information):**
- authentik version: 2023.3.1
- Deployment: docker-compose

**Additional context**
Was working fine for months, added custom backgrounds and logo's yesterday and now this, no flows executing at all, i have already ran permission fix commands on my dir's where photos are. It may be something wrong with my ldap-auth-flow as that is what the GET request but i dont see how i can delete it as i cant view any of the flows. Have cleared cache in admin interface multiple times, multiple reboots. Was working fine for about 24hrs after i uploaded the png's and randomly just stopped and everything else besides flows is working fine

**Comment by hr87** [comment]
This seems to be a problem with the postgresql image. I had the same error running the postgresql:12-alpine (which is 12-alpine:3.18) image. It was updated a day ago. Trying with postgresql:12-alpine3.16, everything works. Same for postgresql:12-alpine3.17. It seems postgresql pushed a bad image.
