### ISSUE TITLE
Unable to upgrade to 2023.5.0

### ISSUE THREAD

**Issue by Changer90** [goauthentik/authentik#5649]
Hi everyone,

i currently have migration issues when I try to update from 2023.4.1 to 2023.5.0. This is the error log, i receive, when i try to upgrade:

`INF event=Finished authentik bootstrap logger=authentik.lib.config timestamp=1684301384.6618218
DBG event=Loaded config logger=authentik.lib.config timestamp=1684301384.9929287 file=/authentik/lib/default.yml
DBG event=Loaded environment variables logger=authentik.lib.config timestamp=1684301384.9934382 count=12
2023-05-17 05:29:45 [info     ] applying django migrations
2023-05-17 05:29:45 [info     ] waiting to acquire database lock
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1684301386.001737 path=authentik.admin.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1684301386.0037503 path=authentik.crypto.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1684301386.0049472 path=authentik.events.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1684301386.007375 path=authentik.outposts.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1684301386.01083 path=authentik.policies.reputation.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1684301386.014554 path=authentik.providers.scim.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1684301386.0165284 path=authentik.sources.ldap.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1684301386.0181084 path=authentik.sources.plex.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1684301386.020204 path=authentik.stages.authenticator_static.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1684301386.0209324 path=authentik.stages.authenticator_totp.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1684301386.0216553 path=authentik.stages.authenticator_validate.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1684301386.0294037 path=authentik.blueprints.settings
INF event=Booting authentik logger=authentik.lib.config timestamp=1684301386.029626 version=2023.5.0
INF event=Enabled authentik enterprise logger=authentik.lib.config timestamp=1684301386.031502
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1684301386.0318606 path=authentik.enterprise.settings
INF event=Loaded GeoIP database last_write=1684239713 logger=authentik.events.geo pid=9 timestamp=2023-05-17T05:29:46.806577
INF event=Task published logger=authentik.root.celery pid=9 task_id=57aa80c5-4d1f-489f-955d-0919375b8045 task_name=authentik.blueprints.v1.tasks.blueprints_discovery timestamp=2023-05-17T05:29:47.748913
INF event=Task published logger=authentik.root.celery pid=9 task_id=530b67f8-e87e-430c-91ee-6e53596731ac task_name=authentik.blueprints.v1.tasks.clear_failed_blueprints timestamp=2023-05-17T05:29:47.751216
Operations to perform:
  Apply all migrations: auth, authentik_blueprints, authentik_core, authentik_crypto, authentik_events, authentik_flows, authentik_outposts, authentik_policies, authentik_policies_dummy, authentik_policies_event_matcher, authentik_policies_expiry, authentik_policies_expression, authentik_policies_password, authentik_policies_reputation, authentik_providers_ldap, authentik_providers_oauth2, authentik_providers_proxy, authentik_providers_radius, authentik_providers_saml, authentik_providers_scim, authentik_sources_ldap, authentik_sources_oauth, authentik_sources_plex, authentik_sources_saml, authentik_stages_authenticator_duo, authentik_stages_authenticator_sms, authentik_stages_authenticator_static, authentik_stages_authenticator_totp, authentik_stages_authenticator_validate, authentik_stages_authenticator_webauthn, authentik_stages_captcha, authentik_stages_consent, authentik_stages_deny, authentik_stages_dummy, authentik_stages_email, authentik_stages_identification, authentik_stages_invitation, authentik_stages_password, authentik_stages_prompt, authentik_stages_user_delete, authentik_stages_user_login, authentik_stages_user_logout, authentik_stages_user_write, authentik_tenants, contenttypes, guardian, otp_static, otp_totp, sessions
Running migrations:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UniqueViolation: could not create unique index "authentik_crypto_certificatekeypair_name_719603a4_uniq"
DETAIL:  Key (name)=(authentik Self-signed Certificate_2) is duplicated.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/lifecycle/migrate.py", line 95, in <module>
    execute_from_command_line(["", "migrate"])
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/migration.py", line 130, in apply
    operation.database_forwards(
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/operations/fields.py", line 235, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 788, in alter_field
    self._alter_field(
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/postgresql/schema.py", line 245, in _alter_field
    super()._alter_field(
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 1045, in _alter_field
    self.execute(self._create_unique_sql(model, [new_field]))
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 199, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: could not create unique index "authentik_crypto_certificatekeypair_name_719603a4_uniq"
DETAIL:  Key (name)=(authentik Self-signed Certificate_2) is duplicated.
  Applying authentik_crypto.0004_alter_certificatekeypair_name..`

do you have any ideas, what i can do to fix this issue?

Thank you all and best regards
Changer

**Comment by Changer90** [comment]
I was able to fix this issue.
For some reason I had 3 authentik Self-Signed Certificates. I renamed two of them and was then able to upgrade
