### ISSUE TITLE
Issue with authentik after domain change

### ISSUE THREAD

**Issue by buzzard10** [goauthentik/authentik#5795]
**Describe the bug**
I'm using authentik and I've decided to change domain in docker-compose. Unfortunately, after recreating docker container i can't log in to Authentik. I have error `Something went wrong! Please try again later.`

**Logs**
```warning auth_via=unauthenticated event=OperationalError('could not load library "/usr/local/lib/postgresql/llvmjit.so": Error relocating /usr/local/lib/postgresql/llvmjit.so: LLVMBuildGEP: symbol not found\n') flow_slug=default-authentication-flow host=auth.XXXXXXXXXXXXX logger=authentik.flows.views.executor pid=22 request_id=XXXXXXXXXXXXX timestamp=2023-05-29T08:28:52.425816

({"action": "system_exception", "auth_via": "unauthenticated", "client_ip": "XXXXXXXXXXXXX", "context": {"geo": {XXXXXXXXXXXXX}, "http_request": {"args": {"next": "/"}, "method": "GET", "path": "/api/v3/flows/executor/default-authentication-flow/"}, "message": "Traceback (most recent call last):\n  File \"/authentik/flows/views/executor.py\", line 298, in get\n    stage_response = self.current_stage_view.get(request, *args, **kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/authentik/flows/stage.py\", line 93, in get\n    challenge = self._get_challenge(*args, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/authentik/flows/stage.py\", line 163, in _get_challenge\n    challenge = self.get_challenge(*args, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/authentik/stages/identification/stage.py\", line 231, in get_challenge\n    for source in sources:\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/query.py\", line 394, in __iter__\n    self._fetch_all()\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/query.py\", line 1867, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/model_utils/managers.py\", line 20, in __iter__\n    for obj in iter:\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/query.py\", line 87, in __iter__\n    results = compiler.execute_sql(\n              ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py\", line 1398, in execute_sql\n    cursor.execute(sql, params)\n  File \"/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py\", line 67, in execute\n    return self._execute_with_wrappers(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py\", line 80, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py\", line 84, in _execute\n    with self.db.wrap_database_errors:\n  File \"/usr/local/lib/python3.11/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py\", line 89, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django_prometheus/db/common.py\", line 69, in execute\n    return super().execute(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: could not load library \"/usr/local/lib/postgresql/llvmjit.so\": Error relocating /usr/local/lib/postgresql/llvmjit.so: LLVMBuildGEP: symbol not found\n"}, "event": "Created Event", "host": "auth.dubascompany.com", "level": "info", "logger": "authentik.events.models", "pid": 22, "request_id": "XXXXXXXXXXXXX", "timestamp": "2023-05-29T08:28:52.438479", "user": {"email": "", "pk": 2, "username": "AnonymousUser"}}
INF auth_via=unauthenticated event=Task published host=auth.XXXXXXXXXXXXX logger=authentik.root.celery pid=22 request_id=XXXXXXXXXXXXX task_id=XXXXXXXXXXXXX task_name=authentik.events.tasks.event_notification_handler timestamp=2023-05-29T08:28:52.469954
INF auth_via=unauthenticated event=/api/v3/flows/executor/default-authentication-flow/?query=next%3D%252F host=auth.XXXXXXXXXXXXX logger=authentik.asgi method=GET pid=22 remote=XXXXXXXXXXXXX request_id=XXXXXXXXXXXXX runtime=191 scheme=https status=200 timestamp=2023-05-29T08:28:52.483272 user= user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36```

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. 2023.5.2]
-   Deployment: docker-compose

**Comment by BeryJu** [comment]
```
Traceback (most recent call last):
  File "/authentik/flows/views/executor.py", line 298, in get
    stage_response = self.current_stage_view.get(request, *args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/flows/stage.py", line 93, in get
    challenge = self._get_challenge(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/flows/stage.py", line 163, in _get_challenge
    challenge = self.get_challenge(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/identification/stage.py", line 231, in get_challenge
    for source in sources:
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 394, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/model_utils/managers.py", line 20, in __iter__
    for obj in iter:
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: could not load library "/usr/local/lib/postgresql/llvmjit.so": Error relocating /usr/local/lib/postgresql/llvmjit.so: LLVMBuildGEP: symbol not found
```

looks like https://github.com/docker-library/postgres/issues/1080, you might need to pull a new postgres image
