### ISSUE TITLE
Property mapping exception when accessing /.well-known/openid-configuration

### ISSUE THREAD

**Issue by uumas** [goauthentik/authentik#6149]
**Describe the bug**
Accessing `/.well-known/openid-configuration` of an application (`/application/o/<app>/.well-known/openid-configuration`) seems to cause property mapping to be evaluated with an anonymous user context. groups is not defined in that context so it fails with `builtins.NameError: name 'groups' is not defined`.

**To Reproduce**

1. Create an application with openid connect provider
2. Make a request to `/application/o/<app>/.well-known/openid-configuration`
3. Get an error in event log

**Logs**

Exception
```
Traceback (most recent call last):
  File "authentik default OAuth Mapping: OpenID 'profile'", line 13, in <module>
  File "authentik default OAuth Mapping: OpenID 'profile'", line 11, in handler
builtins.NameError: name 'groups' is not defined
```

Expression
```
return {
    # Because authentik only saves the user's full name, and has no concept of first and last names,
    # the full name is used as given name.
    # You can override this behaviour in custom mappings, i.e. `request.user.name.split(" ")`
    "name": request.user.name,
    "given_name": request.user.name,
    "preferred_username": request.user.username,
    "nickname": request.user.username,
    # groups is not part of the official userinfo schema, but is a quasi-standard
    "groups": groups,
}
```

Context
```
{
    "geo": {
        ...
    },
    "message": "Traceback (most recent call last):\n  File \"authentik default OAuth Mapping: OpenID 'profile'\", line 13, in <module>\n  File \"authentik default OAuth Mapping: OpenID 'profile'\", line 11, in handler\nbuiltins.NameError: name 'groups' is not defined",
    "expression": "return {\n    # Because authentik only saves the user's full name, and has no concept of first and last names,\n    # the full name is used as given name.\n    # You can override this behaviour in custom mappings, i.e. `request.user.name.split(\" \")`\n    \"name\": request.user.name,\n    \"given_name\": request.user.name,\n    \"preferred_username\": request.user.username,\n    \"nickname\": request.user.username,\n    # groups is not part of the official userinfo schema, but is a quasi-standard\n    \"groups\": groups,\n}",
    "http_request": {
        "args": {},
        "path": "/application/o/nextcloud/.well-known/openid-configuration",
        "method": "GET"
    }
}
User
{
    "pk": 2,
    "email": "",
    "username": "AnonymousUser"
}
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.5.4
-   Deployment: docker

**Comment by BeryJu** [comment]
The default scope mapping has a different expression for groups: https://github.com/goauthentik/authentik/blob/main/blueprints/system/providers-oauth2.yaml#L46

**Comment by uumas** [comment]
Oh, I must have changed that when testing something and failed to return it to default. Sorry.
