### ISSUE TITLE
SMTP stopped working after helm upgrade

### ISSUE THREAD

**Issue by shmanubhav** [goauthentik/authentik#6196]
**Describe the bug**
After upgrading to the 2023.5.5 and 2023.6.0 helm chart, I've started to get a bunch of system exceptions in the logs (batches of ~100 events at the same time) regarding smtp server disconnecting unexpectedly.
```
SMTPServerDisconnected: Connection unexpectedly closed
```
Email was working just fine previously. I still receive emails occasionally from the same pods, but they are ~100 emails that probably got queued up way earlier. Downgrading to a different version did not help. Same error persists. Do not want to do a clean install right now, to avoid losing the current configuration, hence I reused the same volumes.

**To Reproduce**
run the following command inside the pod
```
env | grep EMAIL
AUTHENTIK_EMAIL__TIMEOUT=30
AUTHENTIK_EMAIL__FROM=<email_id>
AUTHENTIK_EMAIL__HOST=smtp.gmail.com
AUTHENTIK_EMAIL__USE_TLS=true
AUTHENTIK_EMAIL__USE_SSL=false
AUTHENTIK_EMAIL__PASSWORD=<password>
AUTHENTIK_EMAIL__USERNAME=<email-id>
AUTHENTIK_EMAIL__PORT=587
ak test_email <email_id>
```
Error:
```
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1688881601.5901184, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1688881601.591136, "count": 49}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1688881602.2661345, "path": "authentik.admin.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1688881602.267452, "path": "authentik.crypto.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1688881602.2683656, "path": "authentik.events.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1688881602.269962, "path": "authentik.outposts.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1688881602.272181, "path": "authentik.policies.reputation.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1688881602.2744005, "path": "authentik.providers.scim.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1688881602.275912, "path": "authentik.sources.ldap.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1688881602.2772348, "path": "authentik.sources.plex.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1688881602.2787557, "path": "authentik.stages.authenticator_static.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1688881602.279413, "path": "authentik.stages.authenticator_totp.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1688881602.2799098, "path": "authentik.stages.authenticator_validate.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1688881602.2858598, "path": "authentik.blueprints.settings"}
{"event": "Booting authentik", "level": "info", "logger": "authentik.lib.config", "timestamp": 1688881602.286006, "version": "2023.5.3"}
{"event": "Enabled authentik enterprise", "level": "info", "logger": "authentik.lib.config", "timestamp": 1688881602.2872107}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1688881602.2875025, "path": "authentik.enterprise.settings"}
{"event": "Loaded GeoIP database", "last_write": 1685644396.0, "level": "info", "logger": "authentik.events.geo", "pid": 49, "timestamp": "2023-07-09T05:46:42.859910"}
{"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 49, "task_id": "71eb0e63-882a-4db9-bdb2-31a64de091a6", "task_name": "authentik.blueprints.v1.tasks.blueprints_discovery", "timestamp": "2023-07-09T05:46:43.697838"}
{"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 49, "task_id": "ee0910cf-9222-4f17-9839-b440c138be5f", "task_name": "authentik.blueprints.v1.tasks.clear_failed_blueprints", "timestamp": "2023-07-09T05:46:43.699704"}
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/email/management/commands/test_email.py", line 36, in handle
    send_mail(message.__dict__, stage.pk)
  File "/usr/local/lib/python3.11/site-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/task.py", line 392, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/autoretry.py", line 54, in run
    ret = task.retry(exc=exc, **retry_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/task.py", line 701, in retry
    raise_with_context(exc or Retry('Task can be retried', None))
  File "/usr/local/lib/python3.11/site-packages/celery/app/autoretry.py", line 34, in run
    return task._orig_run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/email/tasks.py", line 103, in send_mail
    raise exc
  File "/authentik/stages/email/tasks.py", line 73, in send_mail
    backend.open()
  File "/usr/local/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 91, in open
    self.connection.login(self.username, self.password)
  File "/usr/local/lib/python3.11/smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "/usr/local/lib/python3.11/smtplib.py", line 642, in auth
    (code, resp) = self.docmd("AUTH", mechanism + " " + response)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/smtplib.py", line 432, in docmd
    return self.getreply()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/smtplib.py", line 405, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed
```

**Expected behavior**
Expecting a test email to be sent out to the given email id.

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. 2023.6.0]
-   Deployment: helm k8s

**Comment by MegaShinySnivy** [comment]
Can confirm, sent myself about 2k emails before I was able to get it stopped.

**Comment by masterwishx** [comment]
also have this error in console of docker in Portainer in Oracle cloud.
befor has error timeout , but after increased timeout to "30" from "10"
have this error ...
 command in console :   ak test_email myemail.gmail.com

**Comment by masterwishx** [comment]
![image](https://github.com/goauthentik/authentik/assets/28630321/5eb68d85-1a8b-4ea8-b673-b33e8bc1a29b)

![image](https://github.com/goauthentik/authentik/assets/28630321/b75f6913-6e5d-41c9-a5f4-a38a3936b820)

![image](https://github.com/goauthentik/authentik/assets/28630321/f7904407-d9f3-411b-983a-b363d8624b96)

**Comment by wwebb** [comment]
> Can confirm, sent myself about 2k emails before I was able to get it stopped.

I can also confirm that I sent about 10k emails to two different addresses (both mine) before I noticed and stopped the worker and server containers. This was after upgrading from 2023.5.X to 2023.6.0.

**Comment by MegaShinySnivy** [comment]
Wait, yours was on an upgrade? Mine was only after a downgrade from 6 to 5.

**Comment by wwebb** [comment]
> Wait, yours was on an upgrade? Mine was only after a downgrade from 6 to 5.

Yes, it was after upgrading to 2023.6. I started the containers back up and the emails immediately resumed. I went into the notification email transport settings and changed it to local notification only. The emails stopped, but I'm now getting in-browser alerts at 7-10/sec. Postgres is consuming 2 full cores updating the db with all the notifications. Also the process running the command `python -m manage_worker` is consuming 50% of another core.

When I look at the worker container logs, I think I see what the issue is, a database table version issue. My postgres database must have updated to a newer version. 

```
INF event=Task started logger=authentik.root.celery pid=9578 task_id=da7cc477-dfd9-4030-8401-25d4d3fc4e34 task_name=notification_transport timestamp=2023-07-10T23:58:08.301554
WARNING:  database "authentik" has a collation version mismatch
DETAIL:  The database was created using collation version 2.31, but the operating system provides version 2.36.
HINT:  Rebuild all objects in this database that use the default collation and run ALTER DATABASE authentik REFRESH COLLATION VERSION, or build PostgreSQL with the right library version.
INF event=Task finished logger=authentik.root.celery pid=9578 state=SUCCESS task_id=da7cc477-dfd9-4030-8401-25d4d3fc4e34 task_name=notification_transport timestamp=2023-07-10T23:58:08.323289
```

When I run the command `ALTER DATABASE authentik REFRESH COLLATION VERSION` as mentioned in the authentik log below, the database errors go away.

```
NOTICE:  changing version from 2.31 to 2.36
ALTER DATABASE

Query returned successfully in 91 msec.
```
However it is still generating events. I'm unable to figure out yet what is generating the events. 

```
INF event=Task started logger=authentik.root.celery pid=21893 task_id=ee3c71f6-0e99-4e93-a1e5-f072b426cb1e task_name=notification_transport timestamp=2023-07-11T00:29:29.441269
INF event=Task finished logger=authentik.root.celery pid=21893 state=SUCCESS task_id=ee3c71f6-0e99-4e93-a1e5-f072b426cb1e task_name=notification_transport timestamp=2023-07-11T00:29:29.460516
INF event=Task started logger=authentik.root.celery pid=21896 task_id=fa9350b2-f206-44f4-8fb8-5d10f6d222cb task_name=notification_transport timestamp=2023-07-11T00:29:30.162387
INF event=Task finished logger=authentik.root.celery pid=21896 state=SUCCESS task_id=fa9350b2-f206-44f4-8fb8-5d10f6d222cb task_name=notification_transport timestamp=2023-07-11T00:29:30.185697
INF event=Task started logger=authentik.root.celery pid=21897 task_id=06944a36-0549-4498-8024-5e60282f3179 task_name=notification_transport timestamp=2023-07-11T00:29:30.202474
INF event=Task finished logger=authentik.root.celery pid=21897 state=SUCCESS task_id=06944a36-0549-4498-8024-5e60282f3179 task_name=notification_transport timestamp=2023-07-11T00:29:30.223249
```

![image](https://github.com/goauthentik/authentik/assets/7040666/3be56d97-2aa0-408f-a50e-3a5bec1a4de2)

**Comment by shmanubhav** [comment]
Upgraded to `2023.6.1` with explicit server and worker image tags which resolved the issue and `ak test_email` works as expected now so closing the issue.
```
  image:
    repository: ghcr.io/goauthentik/server
    tag: '2023.6.1'
```

**Comment by masterwishx** [comment]
> Upgraded to `2023.6.1` with explicit server and worker image tags which resolved the issue and `ak test_email` works as expected now so closing the issue.

strange , i still have this issue

**Comment by masterwishx** [comment]
Still having this issue in latest version
