### ISSUE TITLE
SCIM Sync Issue

### ISSUE THREAD

**Issue by antt1995** [goauthentik/authentik#6335]
**Describe the bug**
Want to Sync Users and Groups to AWS IAM,
All Groups Sync no Issues
I have only 2 Users and they Dont Sync

**To Reproduce**

Setup AWS IAM Sync as per [AWS Integrations](https://goauthentik.io/integrations/services/aws/)
 Wait for the SCIM Sync

**Expected behavior**
Syncing Users and Groups to AWS IAM

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/3181038/8c470265-acd3-4631-9df2-1bb2a76b2f26)

**Logs**
Docker Logs
``
2023-07-22T22:21:32.366892018Z warning | event=Soft time limit (600s) exceeded for authentik.providers.scim.tasks.scim_sync[23e898fb-220a-4971-b474-6e76cb822262] logger=celery.worker.request timestamp=1690064492.3663187 

2023-07-22T22:21:32.595749430Z INF | action=system_task_exception client_ip=null context={"message":"Task scim_sync encountered an error: Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/celery/app/trace.py\", line 477, in trace_task\n    R = retval = fun(*args, **kwargs)\n                 ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py\", line 275, in _inner\n    reraise(*exc_info)\n  File \"/usr/local/lib/python3.11/site-packages/sentry_sdk/_compat.py\", line 60, in reraise\n    raise value\n  File \"/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py\", line 270, in _inner\n    return f(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/celery/app/trace.py\", line 760, in __protected_call__\n    return self.run(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/authentik/providers/scim/tasks.py\", line 60, in scim_sync\n    for msg in scim_sync_users.delay(page, provider_pk).get():\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/celery/result.py\", line 247, in get\n    return self.backend.wait_for_pending(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/celery/backends/asynchronous.py\", line 221, in wait_for_pending\n    for _ in self._wait_for_pending(result, **kwargs):\n  File \"/usr/local/lib/python3.11/site-packages/celery/backends/asynchronous.py\", line 287, in _wait_for_pending\n    for _ in self.drain_events_until(\n  File \"/usr/local/lib/python3.11/site-packages/celery/backends/asynchronous.py\", line 54, in drain_events_until\n    yield self.wait_for(p, wait, timeout=interval)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/celery/backends/asynchronous.py\", line 63, in wait_for\n    wait(timeout=timeout)\n  File \"/usr/local/lib/python3.11/site-packages/celery/backends/redis.py\", line 161, in drain_events\n    message = self._pubsub.get_message(timeout=timeout)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/redis/client.py\", line 1690, in get_message\n    response = self.parse_response(block=(timeout is None), timeout=timeout)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/redis/client.py\", line 1542, in parse_response\n    response = self._execute(conn, try_read)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/redis/client.py\", line 1518, in _execute\n    return conn.retry.call_with_retry(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/redis/retry.py\", line 46, in call_with_retry\n    return do()\n           ^^^^\n  File \"/usr/local/lib/python3.11/site-packages/redis/client.py\", line 1519, in <lambda>\n    lambda: command(*args, **kwargs),\n            ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/redis/client.py\", line 1536, in try_read\n    if not conn.can_read(timeout=timeout):\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/redis/connection.py\", line 869, in can_read\n    return self._parser.can_read(timeout)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/redis/connection.py\", line 344, in can_read\n    return self._buffer and self._buffer.can_read(timeout)\n                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/redis/connection.py\", line 242, in can_read\n    return bool(self.unread_bytes()) or self._read_from_socket(\n                                        ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/redis/connection.py\", line 212, in _read_from_socket\n    data = self._sock.recv(socket_read_size)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/billiard/pool.py\", line 228, in soft_timeout_sighandler\n    raise SoftTimeLimitExceeded()\nbilliard.exceptions.SoftTimeLimitExceeded: SoftTimeLimitExceeded()"} event=Created Event logger=authentik.events.models pid=116819 task_id=task-23e898fb220a4971b4746e76cb822262 timestamp=2023-07-22T22:21:32.595397 user={} 

2023-07-22T22:21:32.598860286Z INF | event=Task published logger=authentik.root.celery pid=116819 task_id=a00971ef-ee58-433b-bd4a-eabb052de02c task_name=authentik.events.tasks.event_notification_handler timestamp=2023-07-22T22:21:32.598699 

2023-07-22T22:21:32.599207046Z warning | event=Task failure exc=SoftTimeLimitExceeded() logger=authentik.root.celery pid=116819 task_id=task-23e898fb220a4971b4746e76cb822262 timestamp=2023-07-22T22:21:32.599064 

2023-07-22T22:21:32.599466783Z ERR | event=Task authentik.providers.scim.tasks.scim_sync[23e898fb-220a-4971-b474-6e76cb822262] raised unexpected: SoftTimeLimitExceeded() exc_info=["<class 'billiard.exceptions.SoftTimeLimitExceeded'>","SoftTimeLimitExceeded()","<billiard.einfo.Traceback object at 0x7f05868ded50>"] logger=celery.app.trace timestamp=1690064492.599314 
``
Authentik Logs
``Exception

Task scim_sync encountered an error: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 275, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/_compat.py", line 60, in reraise
    raise value
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 270, in _inner
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/providers/scim/tasks.py", line 60, in scim_sync
    for msg in scim_sync_users.delay(page, provider_pk).get():
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/result.py", line 247, in get
    return self.backend.wait_for_pending(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/backends/asynchronous.py", line 221, in wait_for_pending
    for _ in self._wait_for_pending(result, **kwargs):
  File "/usr/local/lib/python3.11/site-packages/celery/backends/asynchronous.py", line 287, in _wait_for_pending
    for _ in self.drain_events_until(
  File "/usr/local/lib/python3.11/site-packages/celery/backends/asynchronous.py", line 54, in drain_events_until
    yield self.wait_for(p, wait, timeout=interval)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/backends/asynchronous.py", line 63, in wait_for
    wait(timeout=timeout)
  File "/usr/local/lib/python3.11/site-packages/celery/backends/redis.py", line 161, in drain_events
    message = self._pubsub.get_message(timeout=timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1690, in get_message
    response = self.parse_response(block=(timeout is None), timeout=timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1542, in parse_response
    response = self._execute(conn, try_read)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1518, in _execute
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1519, in <lambda>
    lambda: command(*args, **kwargs),
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1536, in try_read
    if not conn.can_read(timeout=timeout):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 869, in can_read
    return self._parser.can_read(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 344, in can_read
    return self._buffer and self._buffer.can_read(timeout)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 242, in can_read
    return bool(self.unread_bytes()) or self._read_from_socket(
                                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 212, in _read_from_socket
    data = self._sock.recv(socket_read_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 228, in soft_timeout_sighandler
    raise SoftTimeLimitExceeded()
billiard.exceptions.SoftTimeLimitExceeded: SoftTimeLimitExceeded()

``

**Version and Deployment (please complete the following information):**

-   authentik version: [2023.6.1]
-   Deployment: [docker-compose]

**Additional context**

**Comment by antt1995** [comment]
Okay,
After trying for 2 days and then Opening this issue, I have Partially now resolved this,

1. I didn't have a Surname, so AWS said no to all my users. - Maybe update docs to reflect this AWS Requirement (See Below)

2. SCIM Cert didn't upload to AWS, so I had issues upon getting SCIM to Sync.

3. I am still getting the "SoftTimeLimitExceeded()" error, but it seems to have synced
** 1 **
![image](https://github.com/goauthentik/authentik/assets/3181038/8a291238-c865-4aba-8180-9a9a8bef34ba)
https://docs.aws.amazon.com/singlesignon/latest/userguide/provision-automatically.html

**Comment by antt1995** [comment]
Okay,
After 24 Hours it seems to have started working without the error
