### ISSUE TITLE
Debug ldap sync

### ISSUE THREAD

**Issue by boesr** [goauthentik/authentik#6595]
**Describe your question/**
Is there a possibility to debug the ldap sync any further? I already tried `docker compose run --rm worker ldap_sync <slug>`, but that only show that the tasks are started. Is there a way to have a deeper look into the tasks? A progress bar or something like that would be nice to have. The API (api/v3/sources/ldap/(slug)/debug/) just throws an error (500 internal server error - console shows `Unexpteced end of JSON input`).

The sync process only creates ~2000 users max (sometimes 10xx, somtimes 17xx), but my ad contains around 90 000 entries. 

There actually was an error (probably too many requests)?

**Relevant infos**
/

**Screenshots**
<img width="1094" alt="image" src="https://github.com/goauthentik/authentik/assets/88541074/c6c346d0-6157-4c1e-b7b9-4d333de2ef6b">

**Logs**

```text
Traceback (most recent call last): File "/authentik/sources/ldap/tasks.py", line 86, in ldap_sync sync_inst: BaseLDAPSynchronizer = sync(source) ^^^^^^^^^^^^ File "/authentik/sources/ldap/sync/base.py", line 30, in __init__ self._connection = source.connection() ^^^^^^^^^^^^^^^^^^^ File "/authentik/sources/ldap/models.py", line 174, in connection connection.start_tls(read_server_info=False) File "/usr/local/lib/python3.11/site-packages/ldap3/core/connection.py", line 1314, in start_tls if self.server.tls.start_tls(self) and self.strategy.sync: # for asynchronous connections _start_tls is run by the strategy ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/ldap3/core/tls.py", line 259, in start_tls result = connection.extended('1.3.6.1.4.1.1466.20037') ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/ldap3/core/connection.py", line 1275, in extended response = self.post_send_single_response(self.send('extendedReq', request, controls)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/ldap3/strategy/sync.py", line 160, in post_send_single_response responses, result = self.get_response(message_id) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/ldap3/strategy/base.py", line 403, in get_response raise LDAPOperationResult(result=result['result'], description=result['description'], dn=result['dn'], message=result['message'], response_type=result['type']) ldap3.core.exceptions.LDAPOperationsErrorResult: LDAPOperationsErrorResult - 1 - operationsError - None - 00000000: LdapErr: DSID-0C09150D, comment: Unable to start TLS due to an outstanding request or multi-stage bind, data 0, v4f7c - extendedResp - None
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.6.1
-   Deployment: docker-compose

**Additional context**
/

**Comment by boesr** [comment]
This one can be closed since the sync is fixed in 2023.8.3
