### ISSUE TITLE
FreeIPA LDAP sync broken in 2023.8.*

### ISSUE THREAD

**Issue by Hitman247m** [goauthentik/authentik#6692]
**Describe the bug**
After upgrading Authentik to `2023.8.0` (and `2023.8.1`), the LDAP sync with FreeIPA seems to be broken. The `ldap_sync:freeipa:groups` tasks complete without issues, but the `ldap_sync:freeipa:users` task fails:

```
ldap_sync:freeipa:users:cd24b105-15d6-4d2b-85bc-29492f0f86a8

Task finished with errors
["“['TRUE']” value must be either True or False."]
```

**To Reproduce**

1. Go to 'if/admin/#/core/sources'
2. Click on the FreeIPA LDAP source
3. Click "Run Sync Again"

**Expected behavior**
It is expected that the sync completes without errors

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/9056525/864efc40-83e7-4fc4-9a0a-01cce4ba9a23)

**Logs**
Error log from `if/admin/#/events/log` --> `System task exception: authentik.events.monitored_tasks`:

```
Task ldap_sync encountered an error: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 275, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/_compat.py", line 60, in reraise
    raise value
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 270, in _inner
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/sources/ldap/tasks.py", line 97, in ldap_sync
    count = sync_inst.sync(page)
            ^^^^^^^^^^^^^^^^^^^^
  File "/authentik/sources/ldap/sync/users.py", line 73, in sync
    FreeIPA(self._source).sync(attributes, ak_user, created)
  File "/authentik/sources/ldap/sync/vendor/freeipa.py", line 23, in sync
    self.check_nsaccountlock(attributes, user)
  File "/authentik/sources/ldap/sync/vendor/freeipa.py", line 51, in check_nsaccountlock
    user.save()
  File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/base_user.py", line 76, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 990, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1054, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1231, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1984, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1947, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 954, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 947, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 1122, in get_prep_value
    return self.to_python(value)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 1112, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ["“['TRUE']” value must be either True or False."]
```

**Version and Deployment (please complete the following information):**

-   authentik version: `2023.8.0`, `2023.8.1`
-   Deployment: `docker-compose`

**Additional context**
N/A

**Comment by BeryJu** [comment]
caused by #6270

**Comment by Aterfax** [comment]
Also confirming I see this on my setup.
