### ISSUE TITLE
System Task Error: ldap_sync() missing 1 required positional argument: 'page_cache_key'

### ISSUE THREAD

**Issue by a-gerhard** [goauthentik/authentik#6698]
**Describe the bug**
System Task ldap_sync throws an error

**To Reproduce**
This started showing up at some point.

**Expected behavior**
The background task doesn't fail with what seems to be a programming error, or if the error is known it tells me how to fix it.

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/986924/5f8fa499-5443-4b3e-9d7d-3ff56bd459eb)

**Logs**
Found in System Events (authentik.root.celery and authentik.events.monitored_tasks):
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
builtins.TypeError: ldap_sync() missing 1 required positional argument: 'page_cache_key'
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.8.1
-   Deployment: docker-compose

**Comment by a-gerhard** [comment]
I think that this was due to leftover tasks in the queue after upgrading to the new sync task structure.
