### ISSUE TITLE
Email settings keep configured even without having them, causing error.

### ISSUE THREAD

**Issue by EricFROL** [goauthentik/authentik#6762]
Hello. I'm using Authentik with docker compose.
I wanted to try to use google SMTP as email server. It did not work, so I removed all environments values I set.
And Authentik keeps returning me that error, flooding the notifications.

![image](https://github.com/goauthentik/authentik/assets/42719382/4e002316-0dff-475a-8e90-23e9b7688ef2)

Error:
```
Task notification_transport encountered an error: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/autoretry.py", line 54, in run
    ret = task.retry(exc=exc, **retry_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/task.py", line 717, in retry
    raise_with_context(exc)
  File "/usr/local/lib/python3.11/site-packages/celery/app/autoretry.py", line 34, in run
    return task._orig_run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/events/tasks.py", line 129, in notification_transport
    raise exc
  File "/authentik/events/tasks.py", line 125, in notification_transport
    transport.send(notification)
  File "/authentik/events/models.py", line 331, in send
    return self.send_email(notification)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/events/models.py", line 472, in send_email
    raise NotificationTransportError(exc) from exc
authentik.events.models.NotificationTransportError: (530, b'5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError y21-20020a05600c365500b003fed7fa6c00sm16722769wmq.7 - gsmtp', 'xxxx@xxxx.xxxx')
```

My actual env, on both worker and server:
```
      AUTHENTIK_REDIS__HOST: x
      AUTHENTIK_POSTGRESQL__HOST: x
      AUTHENTIK_POSTGRESQL__PORT: x
      AUTHENTIK_POSTGRESQL__USER: x
      AUTHENTIK_POSTGRESQL__NAME: x
      AUTHENTIK_POSTGRESQL__PASSWORD: x
      AUTHENTIK_SECRET_KEY: x

```

**Comment by EricFROL** [comment]
Any update? I still getting this

**Comment by BeryJu** [comment]
As a temporary workaround you can remove the email notification transport in the Admin interface in Events -> Notification Transports

**Comment by EricFROL** [comment]
I've already removed that, and still notifying me

**Comment by EricFROL** [comment]
Still with this.

**Comment by EricFROL** [comment]
Still with this.

**Comment by EricFROL** [comment]
Solved itself... odd...
