### ISSUE TITLE
SSL: WRONG_VERSION_NUMBER when using email stage, but test mail works

### ISSUE THREAD

**Issue by danieldietzler** [goauthentik/authentik#6914]
**Describe the bug**
I am using SMTP over SSL and my configuration seems to work, because the test email gets through.
However, when using the email stage for mail validation, the task fails with the described SSL exception.

**To Reproduce**

1. Events -> Notification Transport
2. Click on Test icon for the default-email-transport => Mail arrives, everything works
3. Add an Email Stage to a flow with the "Account Confirmation" Template
4. When this flow gets executed, everything works and the "mail got send" window appears, but the mail never arrives and the logs show the described error.
5. Clicking on send again yields the same error

**Expected behavior**
A validation mail to arrive in my inbox.

**Logs**
```
Task send_mail encountered an error: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/autoretry.py", line 60, in run
    ret = task.retry(exc=exc, **retry_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/task.py", line 736, in retry
    raise_with_context(exc)
  File "/usr/local/lib/python3.11/site-packages/celery/app/autoretry.py", line 38, in run
    return task._orig_run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/email/tasks.py", line 103, in send_mail
    raise exc
  File "/authentik/stages/email/tasks.py", line 73, in send_mail
    backend.open()
  File "/usr/local/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 85, in open
    self.connection = self.connection_class(
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/smtplib.py", line 1050, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout,
  File "/usr/local/lib/python3.11/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/smtplib.py", line 1057, in _get_socket
    new_socket = self.context.wrap_socket(new_socket,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 1108, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1006)
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.8.3
-   Deployment: docker-compose

**Additional context**
Env variables:
```
AUTHENTIK_EMAIL__HOST=***
AUTHENTIK_EMAIL__PORT=465
AUTHENTIK_EMAIL__USERNAME=***
AUTHENTIK_EMAIL__PASSWORD=***
AUTHENTIK_EMAIL__USE_SSL=true
AUTHENTIK_EMAIL__TIMEOUT=10
AUTHENTIK_EMAIL__FROM=Authentik <***>
```
Any help would be much appreciated! Apologies if this is just a configuration error, however it would be great if anyone could help me resolve it. :)

**Comment by danieldietzler** [comment]
It appears that disabling `Use global settings` and providing the exact same settings seems to work. So maybe an issue with reading the default settings?
