### ISSUE TITLE
One user unable to log in with LDAP outposts

### ISSUE THREAD

**Issue by foux** [goauthentik/authentik#7213]
**Describe the bug**
Most of my apps uses proxy, SAML or Oauth providers, but for two of them I need an LDAP outpost.

It works for most of my users, but one of them systematically receive an error when trying to login with LDAP. Here is for example the logs on Jellyfin when he tries to login : 

```
[11:26:43] [ERR] [128] Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin: Failed to Connect or Bind to server as user cn=my_user,ou=users,dc=jellyfin,dc=payet,dc=io
LdapException: Invalid Credentials (49) Invalid Credentials
LdapException: Matched DN:
[11:26:43] [ERR] [128] Jellyfin.Server.Implementations.Users.UserManager: Error authenticating with provider LDAP-Authentication
MediaBrowser.Controller.Authentication.AuthenticationException: Error completing LDAP login. Invalid username or password.
   at Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin.ConnectToLdap(String userDn, String userPassword)
   at Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin.Authenticate(String username, String password)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[11:26:43] [INF] [128] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for my_user has been denied (IP: my_ip).
[11:26:43] [ERR] [128] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: Invalid username or password entered. URL POST /Users/authenticatebyname.
```

I don't see anything in Authentik logs, and am not even sure where to look.

The user is of course able to login with SAML, OAuth or Proxy providers with the same credentials

**Expected behavior**
User should be able to login

**Logs**
Logs of the LDAP outpost : 
```
{"bindDN":"cn=ldap_bind,ou=users,dc=jellyfin,dc=payet,dc=io","event":"authenticated from session","level":"info","logger":"authentik.outpost.ldap.binder.session","timestamp":"2023-10-18T09:26:43Z"}
{"bindDN":"cn=ldap_bind,ou=users,dc=jellyfin,dc=payet,dc=io","client":"192.168.10.1","event":"Bind request","level":"info","requestId":"75637b71-10f3-4084-ad78-a62e24b86a2d","timestamp":"2023-10-18T09:26:43Z","took-ms":0}
{"attributes":["cn"],"baseDN":"ou=users,DC=jellyfin,DC=payet,DC=io","bindDN":"cn=ldap_bind,ou=users,dc=jellyfin,dc=payet,dc=io","client":"192.168.10.1","event":"Search request","filter":"(&(memberOf=cn=mediausers,ou=groups,DC=jellyfin,DC=payet,DC=io)(|(uid=my_user)(cn=my_user)(mail=my_user)(displayName=my_user)))","level":"info","requestId":"27f50e04-85b2-4839-9950-903008b5166a","scope":"Whole Subtree","timestamp":"2023-10-18T09:26:43Z","took-ms":0}
{"bindDN":"cn=my_user,ou=users,dc=jellyfin,dc=payet,dc=io","event":"authenticated from session","level":"info","logger":"authentik.outpost.ldap.binder.session","timestamp":"2023-10-18T09:26:43Z"}
{"bindDN":"cn=my_user,ou=users,dc=jellyfin,dc=payet,dc=io","client":"192.168.10.1","event":"Bind request","level":"info","requestId":"3744d473-19a9-41e1-bf0b-4dd6c9a3d4f1","timestamp":"2023-10-18T09:26:43Z","took-ms":0}
{"event":"Fingerprint hasn't changed, not fetching cert","level":"info","logger":"authentik.outpost.cryptostore","timestamp":"2023-10-18T09:26:58Z","uuid":"d1ddf53b-fcee-40ad-a732-a4f907ac866e"}
{"event":"Fingerprint hasn't changed, not fetching cert","level":"info","logger":"authentik.outpost.cryptostore","timestamp":"2023-10-18T09:26:58Z","uuid":"d1ddf53b-fcee-40ad-a732-a4f907ac866e"}
{"event":"Update providers","level":"info","logger":"authentik.outpost.ldap","timestamp":"2023-10-18T09:26:58Z"}
```

**Version and Deployment (please complete the following information):**

-   authentik version: [2023.8.3](https://goauthentik.io/docs/releases/2023.8)
-   Deployment: docker-compose

Any pointers on where to look to debug this issue?

Thanks a lot

**Comment by foux** [comment]
As additional informations, login in with an App Password works.
And the user has no MFA WebAuthn nor TOTP, be used to in the past.

Thanks

**Comment by PythonCoderAS** [comment]
Have you tried restarting the LDAP outpost?

**Comment by foux** [comment]
Indeed, just restarting the LDAP outpost did the trick, silly me....
Thanks @PythonCoderAS !

**Comment by PythonCoderAS** [comment]
For some reason when new users are created (at least via social sign ins) the LDAP outpost does not like that

**Comment by BeryJu** [comment]
By default the LDAP provider uses cached binding and searching to improve speed, see https://goauthentik.io/docs/providers/ldap/#bind-modes and https://goauthentik.io/docs/providers/ldap/#search-modes

**Comment by foux** [comment]
> By default the LDAP provider uses cached binding and searching to improve speed, see https://goauthentik.io/docs/providers/ldap/#bind-modes and https://goauthentik.io/docs/providers/ldap/#search-modes

I know that, but even after switching to direct queries (no cache), I still had the issue. Only after restarting the outpost the issue vanished.
