### ISSUE TITLE
Local Docker connection perpetually 'Unhealthy' 

### ISSUE THREAD

**Issue by iTim314** [goauthentik/authentik#7279]
**Describe the bug**
On the Outpost Integrations page, the delivered "Local Docker connection" integration is in an unhealthy state no matter what I do. I'm not yet sure what the impact of this issue is, but am hesitant to continue any additional setup in Authentik. 

This extends to any Output Integration of type "Docker Service-Connection". I tried creating a test outpost and it, too, is showing unhealthy. 

**To Reproduce**
I am honestly unsure how exactly to reproduce this bug, given that I can't find any possible solution. I think (but am unsure) that it has been unhealthy since I first ran docker-compose. 

**Expected behavior**
Docker Service Connections should be healthy.

**Screenshots**
<img width="1194" alt="Screenshot 2023-10-24 at 9 50 21 AM" src="https://github.com/goauthentik/authentik/assets/57271008/96521ba6-4a13-4ca6-afc9-ccc69b47ceb6">

**Logs**
There is an event log that gives a clue to a possible problem:

```
Task outpost_connection_discovery encountered an error: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 275, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/_compat.py", line 99, in reraise
    raise value
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 270, in _inner
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/outposts/tasks.py", line 290, in outpost_connection_discovery
    DockerServiceConnection.objects.create(
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 876, in save_base
    parent_inserted = self._save_parents(cls, using, update_fields)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 918, in _save_parents
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/django/__init__.py", line 616, in execute
    return real_execute(self, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "authentik_outposts_outpostserviceconnection_name_ec30b5ea_uniq"
DETAIL:  Key (name)=(Local Docker connection) already exists.
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.8.3
-   Deployment: docker-compose

**Additional context**
I tried adding `user: root` to the docker-compose.yml file for both the `server` and `worker` but that didn't make a difference.

If you make any change to any one outpost integration, then all outpost integrations show as healthy with 24.0.5 and a green check mark. But as soon as you reload the page, they're all unhealthy again.

**Comment by Mailstorm-ctrl** [comment]
I don't believe you can have two docker outpost (that's what you're error says). But either way this bug exist with just a single outpost. The worker container also shows no errors. Anytime you do anything that involves sending data to or from they all show as a SUCCESS in the console.

**Comment by iTim314** [comment]
> I don't believe you can have two docker outpost (that's what you're error says). 

It actually said that before I created that test integration. 

> But either way this bug exist with just a single outpost. The worker container also shows no errors. Anytime you do anything that involves sending data to or from they all show as a SUCCESS in the console.

That's what I (think) I'm seeing. The docker integration is seemingly working despite it being in an unhealthy status. I created an LDAP outpost, and it shows as a new docker container without my adding it to my `docker-compose.yml` file.

**Comment by BeryJu** [comment]
The error above is because the discovery doesn't check for the existing connection correctly if its not set to local, but you can very much have multiple docker connection.

To see what is causing the unhealthy status, check the System tasks page, there should be a task for outpost health

**Comment by iTim314** [comment]
I found `outpost_service_connection_monitor`. It shows a Successful status, both last run and when run manually. Inside the task:

```
Duration: 0.02 seconds
Messages: Successfully updated 1 connections.
```

The local docker connection still shows Unhealthy.

**Comment by iTim314** [comment]
Small update: I launched a completely vanilla instance of Authentik, and out of the box the Docker connection outpost is in Unhealthy status.

**Comment by Mailstorm-ctrl** [comment]
> Small update: I launched a completely vanilla instance of Authentik, and out of the box the Docker connection outpost is in Unhealthy status.

> To see what is causing the unhealthy status, check the System tasks page, there should be a task for outpost health

Mine was missing mail information. However it would be nice that if no mail information was provided it would just ignore it/pass it.

**Comment by iTim314** [comment]
> > Small update: I launched a completely vanilla instance of Authentik, and out of the box the Docker connection outpost is in Unhealthy status.
> 
> > To see what is causing the unhealthy status, check the System tasks page, there should be a task for outpost health
> 
> Mine was missing mail information. However it would be nice that if no mail information was provided it would just ignore it/pass it.

What mail information did you provide and where?

**Comment by radiantwave** [comment]
same issue on fresh install of 2023.10.6

**Comment by wociscz** [comment]
When I click "refresh" - it is healthy and shows 25.0.0 version. When I go to any other menu and then back to integrations - then again "unhealthy" - with refresh button click healthy again...
Should unhealthy status be the cause that when I add a new tenant with new valid certificate the new tenant (under it's hostname and with the certificate) is not working unless I restart the whole authentik docker-compose?
