### ISSUE TITLE
Authentik does not start after upgrading to 2023.10.1

### ISSUE THREAD

**Issue by Ksdmg** [goauthentik/authentik#7343]
**Describe the bug**
Authentik does not start after upgrading to 2023.10.1

As far as I can tell this is caused by an migrations issue. Because I do not follow best practices, I do not know what exact verison I was coming from, but I did the last Update around April this year.

This is the Postgres log:
```
PostgreSQL Database directory appears to contain a database; Skipping initialization

2023-10-27 11:37:00.141 UTC [1] LOG:  starting PostgreSQL 12.16 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
2023-10-27 11:37:00.144 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-10-27 11:37:00.144 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-10-27 11:37:00.144 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-10-27 11:37:00.164 UTC [22] LOG:  database system was shut down at 2023-10-27 10:23:40 UTC
2023-10-27 11:37:00.171 UTC [1] LOG:  database system is ready to accept connections
2023-10-27 11:37:13.852 UTC [33] ERROR:  column "throttling_failure_count" of relation "authentik_stages_authenticator_static_staticdevice" already exists
2023-10-27 11:37:13.852 UTC [33] STATEMENT:  ALTER TABLE "authentik_stages_authenticator_static_staticdevice" ADD COLUMN "throttling_failure_count" integer DEFAULT 0 NOT NULL CHECK ("throttling_failure_count" >= 0)
2023-10-27 11:37:22.168 UTC [36] ERROR:  column "throttling_failure_count" of relation "authentik_stages_authenticator_static_staticdevice" already exists
2023-10-27 11:37:22.168 UTC [36] STATEMENT:  ALTER TABLE "authentik_stages_authenticator_static_staticdevice" ADD COLUMN "throttling_failure_count" integer DEFAULT 0 NOT NULL CHECK ("throttling_failure_count" >= 0)
2023-10-27 11:37:30.301 UTC [38] ERROR:  column "throttling_failure_count" of relation "authentik_stages_authenticator_static_staticdevice" already exists
2023-10-27 11:37:30.301 UTC [38] STATEMENT:  ALTER TABLE "authentik_stages_authenticator_static_staticdevice" ADD COLUMN "throttling_failure_count" integer DEFAULT 0 NOT NULL CHECK ("throttling_failure_count" >= 0)
2023-10-27 11:37:38.292 UTC [47] ERROR:  column "throttling_failure_count" of relation "authentik_stages_authenticator_static_staticdevice" already exists
2023-10-27 11:37:38.292 UTC [47] STATEMENT:  ALTER TABLE "authentik_stages_authenticator_static_staticdevice" ADD COLUMN "throttling_failure_count" integer DEFAULT 0 NOT NULL CHECK ("throttling_failure_count" >= 0)
2023-10-27 11:37:50.128 UTC [52] ERROR:  column "throttling_failure_count" of relation "authentik_stages_authenticator_static_staticdevice" already exists
2023-10-27 11:37:50.128 UTC [52] STATEMENT:  ALTER TABLE "authentik_stages_authenticator_static_staticdevice" ADD COLUMN "throttling_failure_count" integer DEFAULT 0 NOT NULL CHECK ("throttling_failure_count" >= 0)
2023-10-27 11:37:58.059 UTC [53] ERROR:  column "throttling_failure_count" of relation "authentik_stages_authenticator_static_staticdevice" already exists
2023-10-27 11:37:58.059 UTC [53] STATEMENT:  ALTER TABLE "authentik_stages_authenticator_static_staticdevice" ADD COLUMN "throttling_failure_count" integer DEFAULT 0 NOT NULL CHECK ("throttling_failure_count" >= 0)
2023-10-27 11:38:09.508 UTC [66] ERROR:  column "throttling_failure_count" of relation "authentik_stages_authenticator_static_staticdevice" already exists
2023-10-27 11:38:09.508 UTC [66] STATEMENT:  ALTER TABLE "authentik_stages_authenticator_static_staticdevice" ADD COLUMN "throttling_failure_count" integer DEFAULT 0 NOT NULL CHECK ("throttling_failure_count" >= 0)
2023-10-27 11:38:17.465 UTC [67] ERROR:  column "throttling_failure_count" of relation "authentik_stages_authenticator_static_staticdevice" already exists
2023-10-27 11:38:17.465 UTC [67] STATEMENT:  ALTER TABLE "authentik_stages_authenticator_static_staticdevice" ADD COLUMN "throttling_failure_count" integer DEFAULT 0 NOT NULL CHECK ("throttling_failure_count" >= 0)
```

This is Authentik Server:

```
{"app_name": "authentik.stages.authenticator", "event": "Could not import app's URLs", "exc": "ModuleNotFoundError(\"No module named 'authentik.stages.authenticator.urls'\")", "level": "warning", "logger": "authentik.api.v3.urls", "pid": 9, "timestamp": "2023-10-27T11:44:31.000209"}
Traceback (most recent call last):
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.DuplicateColumn: column "throttling_failure_count" of relation "authentik_stages_authenticator_static_staticdevice" already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/lifecycle/migrate.py", line 112, in <module>
    execute_from_command_line(["", "migrate"])
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/migrations/operations/fields.py", line 108, in database_forwards
    schema_editor.add_field(
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 712, in add_field
    self.execute(sql, params)
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/postgresql/schema.py", line 48, in execute
    return super().execute(sql, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 201, in execute
    cursor.execute(sql, params)
  File "/ak-root/venv/lib/python3.11/site-packages/sentry_sdk/integrations/django/__init__.py", line 628, in execute
    return real_execute(self, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
django.db.utils.ProgrammingError: column "throttling_failure_count" of relation "authentik_stages_authenticator_static_staticdevice" already exists
Sentry is attempting to send 1 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit

```

**Comment by BeryJu** [comment]
see #7326

**Comment by Ksdmg** [comment]
Thanks for the fast response @BeryJu , but the solutions didn't work for me. I did the following:

1. Enter Container PostgreSQL and execute command `alter table authentik_stages_authenticator_static_authenticatorstaticstage add column token_length INTEGER default 12;` as stated in the linked ticket
2. Enter container authentik_server and execute `ak migrate authentik_stages_authenticator_static 0009_throttling --fake` as stated in the linked ticket

Result is still:

```
2023-10-27 12:18:56.694 UTC [224] ERROR:  column "throttling_failure_count" of relation "authentik_stages_authenticator_static_staticdevice" already exists
2023-10-27 12:18:56.694 UTC [224] STATEMENT:  ALTER TABLE "authentik_stages_authenticator_static_staticdevice" ADD COLUMN "throttling_failure_count" integer DEFAULT 0 NOT NULL CHECK ("throttling_failure_count" >= 0)
```

**Comment by BeryJu** [comment]
after running `ak migrate authentik_stages_authenticator_static 0009_throttling --fake`, restart the containers

**Comment by Ksdmg** [comment]
@BeryJu I did restart.

```
<removed>@<removed>:/home/authentik$ docker exec -it c9c76aa48370 bash
authentik@c9c76aa48370:/$ ak migrate authentik_stages_authenticator_static 0009_throttling --fake
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1698408762.9470613, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1698408762.9476047, "count": 16}
<removed>@<removed>:/home/authentik$ docker-compose restart
Restarting authentik_worker_1     ... done
Restarting authentik_server_1     ... done
Restarting authentik_redis_1      ... done
Restarting authentik_postgresql_1 ... done
```

**Comment by nz2o** [comment]
I'm having the same issue. I have no choice but to rip Authentik out and go with some other solution.
