### ISSUE TITLE
Database Error: 

### ISSUE THREAD

**Issue by djarbz** [goauthentik/authentik#7376]
**Describe the bug**
Worker container unable to start due to failed DB Migrations.

**To Reproduce**
Podman Quadlet Conatinerfile

```ini
[Unit]
Description=Authentik Authentication Worker
Documentation=https://github.com/brokenscripts/authentik_traefik
RequiresMountsFor=%t/containers

## Dependancy Options

Requires=authentik_postgres.service
After=authentik_postgres.service

Requires=authentik_redis.service
After=authentik_redis.service

Wants=authentik_geoip.service
After=authentik_geoip.service

[Container]
ContainerName=%N
Image=ghcr.io/goauthentik/server:2023.8
Exec=worker

PodmanArgs=--log-driver=journald


Environment=AUTHENTIK_REDIS__HOST=10.0.2.2
Environment=AUTHENTIK_POSTGRESQL__HOST=10.0.2.2
Environment=AUTHENTIK_POSTGRESQL__NAME=authentik
Environment=AUTHENTIK_POSTGRESQL__USER=authentik
Environment=AUTHENTIK_POSTGRESQL__PASSWORD=${AUTHENTIK_POSTGRES_PASSWORD}
Environment=AUTHENTIK_ERROR_REPORTING__ENABLED="false"
Environment=AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
Environment=AUTHENTIK_COOKIE_DOMAIN=<REDACTED>
Environment=AUTHENTIK_AUTHENTIK__GEOIP=/geoip/GeoLite2-City.mmdb

Network=slirp4netns:allow_host_loopback=true

Volume=%E/authentik/media:/media:rw,z
Volume=%E/authentik/templates:/templates:rw,z
Volume=%E/authentik/geoip:/geoip:rw,z


Label="io.containers.autoupdate=registry"

NoNewPrivileges=true
DropCapability=All


[Service]
Restart=on-failure
# Restart Delay
RestartSec=30
# Restart Delay Increment
#RestartSteps=30
# Max Restart Delay
#RestartMaxDelaySec=300
# Allowed time for the service to start.
TimeoutStartSec=90
# Allowed time for the service to stop.
TimeoutStopSec=90

ExecStartPre=mkdir -p %E/authentik/media
ExecStartPre=mkdir -p %E/authentik/templates
ExecStartPre=mkdir -p %E/authentik/geoip

## The worker container can be monitored by running /lifecycle/ak healthcheck in the worker container. This will ping the worker and ensure it can communicate with redis as required.
ExecStartPost=/usr/bin/timeout 30 bash -c 'until podman exec %N /lifecycle/ak healthcheck; do sleep 1; done'

[Install]
WantedBy=default.target
```

**Logs**
```
Operations to perform:
Oct 29 21:30:40 oracle authentik_worker[75880]:   Apply all migrations: auth, authentik_blueprints, authentik_core, authentik_crypto, authentik_enterprise, authentik_events, authentik_flows, authentik_outposts,>
Oct 29 21:30:40 oracle authentik_worker[75880]: Running migrations:
Oct 29 21:30:40 oracle authentik_worker[75880]: Traceback (most recent call last):
Oct 29 21:30:40 oracle authentik_worker[75880]:   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
Oct 29 21:30:40 oracle authentik_worker[75880]:     return self.cursor.execute(sql)
Oct 29 21:30:40 oracle authentik_worker[75880]:            ^^^^^^^^^^^^^^^^^^^^^^^^
Oct 29 21:30:40 oracle authentik_worker[75880]:   File "/usr/local/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
Oct 29 21:30:40 oracle authentik_worker[75880]:     return super().execute(*args, **kwargs)
Oct 29 21:30:40 oracle authentik_worker[75880]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 29 21:30:40 oracle authentik_worker[75880]:   File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
Oct 29 21:30:40 oracle authentik_worker[75880]:     raise ex.with_traceback(None)
Oct 29 21:30:40 oracle authentik_worker[75880]: psycopg.errors.DuplicateTable: relation "otp_static_staticdevice_user_id_7f9cff2b" already exists
Oct 29 21:30:40 oracle authentik_worker[75880]:
Oct 29 21:30:40 oracle authentik_worker[75880]: The above exception was the direct cause of the following exception:
Oct 29 21:30:40 oracle authentik_worker[75880]:
Oct 29 21:30:40 oracle authentik_worker[75880]: Traceback (most recent call last):
Oct 29 21:30:40 oracle authentik_worker[75880]:   File "<frozen runpy>", line 198, in _run_module_as_main
Oct 29 21:30:40 oracle authentik_worker[75880]:   File "<frozen runpy>", line 88, in _run_code
Oct 29 21:30:40 oracle authentik_worker[75880]:   File "/lifecycle/migrate.py", line 95, in <module>
Oct 29 21:30:40 oracle authentik_worker[75880]:     execute_from_command_line(["", "migrate"])
Oct 29 21:30:40 oracle authentik_worker[75880]:   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
Oct 29 21:30:40 oracle authentik_worker[75880]:     utility.execute()
Oct 29 21:30:40 oracle authentik_worker[75880]:   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
Oct 29 21:30:40 oracle authentik_worker[75880]:     self.fetch_command(subcommand).run_from_argv(self.argv)
Oct 29 21:30:40 oracle authentik_worker[75880]:   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
Oct 29 21:30:40 oracle authentik_worker[75880]:     self.execute(*args, **cmd_options)
Oct 29 21:30:40 oracle authentik_worker[75880]:   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
Oct 29 21:30:40 oracle authentik_worker[75880]:     output = self.handle(*args, **options)
Oct 29 21:30:40 oracle authentik_worker[75880]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 29 21:30:40 oracle authentik_worker[75880]:   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
Oct 29 21:30:40 oracle authentik_worker[75880]:     res = handle_func(*args, **kwargs)
Oct 29 21:30:40 oracle authentik_worker[75880]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 29 21:30:40 oracle authentik_worker[75880]:   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 356, in handle
Oct 29 21:30:40 oracle authentik_worker[75880]:     post_migrate_state = executor.migrate(
Oct 29 21:30:40 oracle authentik_worker[75880]:                          ^^^^^^^^^^^^^^^^^
Oct 29 21:30:40 oracle authentik_worker[75880]:   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
Oct 29 21:30:40 oracle authentik_worker[75880]:     state = self._migrate_all_forwards(
Oct 29 21:30:40 oracle authentik_worker[75880]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 29 21:30:40 oracle authentik_worker[75880]:   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
Oct 29 21:30:40 oracle authentik_worker[75880]:     state = self.apply_migration(
Oct 29 21:30:40 oracle authentik_worker[75880]:             ^^^^^^^^^^^^^^^^^^^^^
Oct 29 21:30:40 oracle authentik_worker[75880]:   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 249, in apply_migration
Oct 29 21:30:40 oracle authentik_worker[75880]:     with self.connection.schema_editor(
Oct 29 21:30:40 oracle authentik_worker[75880]:   File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 166, in __exit__
Oct 29 21:30:40 oracle authentik_worker[75880]:     self.execute(sql)
Oct 29 21:30:40 oracle authentik_worker[75880]:   File "/usr/local/lib/python3.11/site-packages/django/db/backends/postgresql/schema.py", line 48, in execute
Oct 29 21:30:40 oracle authentik_worker[75880]:     return super().execute(sql, None)
Oct 29 21:30:40 oracle authentik_worker[75880]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 29 21:30:40 oracle authentik_worker[75880]:   File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 201, in execute
Oct 29 21:30:40 oracle authentik_worker[75880]:     cursor.execute(sql, params)
Oct 29 21:30:40 oracle authentik_worker[75880]:   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
Oct 29 21:30:40 oracle authentik_worker[75880]:     return self._execute_with_wrappers(
Oct 29 21:30:40 oracle authentik_worker[75880]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 29 21:30:40 oracle authentik_worker[75880]:   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
Oct 29 21:30:40 oracle authentik_worker[75880]:     return executor(sql, params, many, context)
Oct 29 21:30:40 oracle authentik_worker[75880]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 29 21:30:40 oracle authentik_worker[75880]:   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
Oct 29 21:30:40 oracle authentik_worker[75880]:     with self.db.wrap_database_errors:
Oct 29 21:30:40 oracle authentik_worker[75880]:   File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
Oct 29 21:30:40 oracle authentik_worker[75880]:     raise dj_exc_value.with_traceback(traceback) from exc_value
Oct 29 21:30:40 oracle authentik_worker[75880]:   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
Oct 29 21:30:40 oracle authentik_worker[75880]:     return self.cursor.execute(sql)
Oct 29 21:30:40 oracle authentik_worker[75880]:            ^^^^^^^^^^^^^^^^^^^^^^^^
Oct 29 21:30:40 oracle authentik_worker[75880]:   File "/usr/local/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
Oct 29 21:30:40 oracle authentik_worker[75880]:     return super().execute(*args, **kwargs)
Oct 29 21:30:40 oracle authentik_worker[75880]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 29 21:30:40 oracle authentik_worker[75880]:   File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
Oct 29 21:30:40 oracle authentik_worker[75880]:     raise ex.with_traceback(None)
Oct 29 21:30:40 oracle authentik_worker[75880]: django.db.utils.ProgrammingError: relation "otp_static_staticdevice_user_id_7f9cff2b" already exists
```
**Version and Deployment (please complete the following information):**

-   authentik version: 2023.8
-   Deployment: Podman Quadlet

**Additional context**
I think this may be in relation to https://github.com/goauthentik/authentik/issues/7326
I did have the container set to auto-update using the latest tag, read that I may need to try upgrading to 2023.8 first.
Also read that I should try some manual DB Migrations, which look like they had applied.

**Comment by stiivo** [comment]
+1 same here :(

**Comment by djarbz** [comment]
I did that, but I am still getting the ` django.db.utils.ProgrammingError: relation "otp_static_staticdevice_user_id_7f9cff2b" already exists` error.

**Comment by djarbz** [comment]
I was able to get the worker running with the below.

```
/usr/bin/podman run --rm --network=slirp4netns:allow_host_loopback=true --env AUTHENTIK_POSTGRESQL__HOST=10.0.2.2 --env AUTHENTIK_POSTGRESQL__NAME=authentik --env AUTHENTIK_POSTGRESQL__PASSWORD=5c5e309880694b9ab47d66ca32466f3f --env AUTHENTIK_POSTGRESQL__USER=authentik --env AUTHENTIK_REDIS__HOST=10.0.2.2 --env AUTHENTIK_SECRET_KEY=d70eca0f37046bb98b78905d7ec470d0 --entrypoint bash -it ghcr.io/goauthentik/server:latest


ak migrate authentik_stages_authenticator_totp 0009_auto_20190420_0723 --fake
```

But now the server portion is just crashing, doesn't seem to give a reason why.
```
Job for authentik_server.service failed because the control process exited with error code.
See "systemctl --user status authentik_server.service" and "journalctl --user -xeu authentik_server.service" for details.
Oct 30 20:39:14 oracle authentik_server[23259]: {"auth_via": "secret_key", "event": "/api/v3/core/tenants/", "host": "0.0.0.0:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 17, "remote": "127.0.0.1", "request_id": "10c07e53a76d4dd2a509bc21dfe6e97a", "runtime": 33, "scheme": "http", "status": 200, "timestamp": "2023-10-31T01:39:14.102696", "user": "ak-outpost-fd6d77f86fb2495fa4d98a3beeb0c386", "user_agent": "goauthentik.io/outpost/2023.10.2"}
Oct 30 20:39:14 oracle authentik_server[23259]: {"auth_via": "secret_key", "event": "/api/v3/outposts/instances/", "host": "0.0.0.0:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 17, "remote": "127.0.0.1", "request_id": "93ea16865b9c4b8e8a849f8f93f3c7c6", "runtime": 72, "scheme": "http", "status": 200, "timestamp": "2023-10-31T01:39:14.567016", "user": "ak-outpost-fd6d77f86fb2495fa4d98a3beeb0c386", "user_agent": "goauthentik.io/outpost/2023.10.2"}
Oct 30 20:39:14 oracle authentik_server[23259]: {"event":"Starting authentik outpost","hash":"tagged","level":"info","logger":"authentik.outpost","timestamp":"2023-10-31T01:39:14Z","version":"2023.10.2"}
Oct 30 20:39:14 oracle authentik_server[23259]: {"auth_via": "secret_key", "event": "/api/v3/outposts/proxy/", "host": "0.0.0.0:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 17, "remote": "127.0.0.1", "request_id": "761ad805d40041f187249eb2feccae2d", "runtime": 237, "scheme": "http", "status": 200, "timestamp": "2023-10-31T01:39:14.807989", "user": "ak-outpost-fd6d77f86fb2495fa4d98a3beeb0c386", "user_agent": "goauthentik.io/outpost/2023.10.2"}
Oct 30 20:39:14 oracle authentik_server[23259]: {"event":"updating tenant certificates","level":"info","logger":"authentik.router.tenant_tls","timestamp":"2023-10-31T01:39:14Z"}
Oct 30 20:39:14 oracle authentik_server[23259]: {"auth_via": "secret_key", "event": "/api/v3/core/tenants/", "host": "0.0.0.0:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 17, "remote": "127.0.0.1", "request_id": "555e74edbf324c11903a006ab1127e87", "runtime": 31, "scheme": "http", "status": 200, "timestamp": "2023-10-31T01:39:14.857213", "user": "ak-outpost-fd6d77f86fb2495fa4d98a3beeb0c386", "user_agent": "goauthentik.io/outpost/2023.10.2"}
Oct 30 20:39:28 oracle authentik_server[23259]: {"event":"shutting down webserver","level":"info","logger":"authentik.root","timestamp":"2023-10-31T01:39:28Z"}
Oct 30 20:39:28 oracle authentik_server[23259]: {"event": "Handling signal: term", "level": "info", "logger": "gunicorn.error", "timestamp": 1698716368.1313643}
```

**Comment by einst6** [comment]
Got the same error - but the problem was that in compose file I only changed the Image version of the server, not the worker image version (was still 2023.8.2)
