### ISSUE TITLE
missing config option to define schema (since Postgres 15 schema public is not available by default and Django migrations fail)

### ISSUE THREAD

**Issue by Girgitt** [goauthentik/authentik#7481]
**Describe your question/**
Is it possible to configure specific schema to be used by Authentik user connecting to Postgres? 

**Relevant infos**
Default Django behavior results in worker not being able to start due to failed migrations as access to "public" schema is by default denied since Postgres 15. Specific requirements are described in details here: https://gist.github.com/axelbdt/74898d80ceee51b69a16b575345e8457 
It would be also helpful to include a reference to Django documentation or similar summary on how to properly create database and user for Authentik - existing documentation is missing this part.

The issue is more Django-related but Authentik documentation (https://goauthentik.io/developer-docs/setup/full-dev-environment#requirements) states "PostgreSQL (any recent version will do)" which is not the case - a clean deployment of Authentik will fail to start leaving the worker in an initialization loop due to failed migrations. 

**Logs**
```
[worker] | 2023-11-07 15:16:49 [info     ] Migration needs to be applied  migration=install_id.py 
Traceback (most recent call last): 
  File "/lifecycle/migrate.py", line 98, in <module> 
    migration.run() 
  File "/lifecycle/system_migrations/install_id.py", line 41, in run 
    return self.upgrade(migrate=False) 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "/lifecycle/system_migrations/install_id.py", line 22, in upgrade 
    self.cur.execute(SQL_STATEMENT) 
  File "/ak-root/venv/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute 
    raise ex.with_traceback(None) 
psycopg.errors.InsufficientPrivilege: permission denied for schema public 
LINE 2: CREATE TABLE IF NOT EXISTS authentik_install_id ( 
                                   ^ 
  
During handling of the above exception, another exception occurred: 
  
Traceback (most recent call last): 
  File "<frozen runpy>", line 198, in _run_module_as_main 
  File "<frozen runpy>", line 88, in _run_code 
  File "/lifecycle/migrate.py", line 114, in <module> 
    release_lock(curr) 
  File "/lifecycle/migrate.py", line 67, in release_lock 
    cursor.execute("SELECT pg_advisory_unlock(%s)", (ADV_LOCK_UID,)) 
  File "/ak-root/venv/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute 
    raise ex.with_traceback(None) 
psycopg.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block 
exit code: 1 
```

**Version and Deployment (please complete the following information):**
-   authentik version: 2023.10.2 
-   Deployment: podman-compose v4.4 on Rocky 9.2 amd64

**Additional context**
Workaround for this issue is to grant superuser permissions to authentik user but for obvious reasons such approach may not work for everyone.

**Comment by Girgitt** [comment]
I was able to resolve the issue without superuser permissions for authentik user. 

Here is how the database and user should be created in Postgres 15:

```
-- Create the database
CREATE DATABASE authentik_test; 

-- Create user 
CREATE USER authentik_test_user WITH ENCRYPTED PASSWORD '<password matching .env or docker-compose>'; 

-- Connect to database 
\connect authentik_test; 

-- Assign permissions to public schema for user
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO authentik_test_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO authentik_test_user; 
GRANT CREATE ON SCHEMA public TO authentik_test_user; 

-- Set some settings as recommended by the Django documentation 
ALTER ROLE authentik_test_user SET client_encoding TO 'utf8'; 
ALTER ROLE authentik_test_user SET default_transaction_isolation TO 'read committed'; 
ALTER ROLE authentik_test_user SET timezone TO 'UTC'; 
```

The missing part in my original approach was:
```
GRANT CREATE ON SCHEMA public TO authentik_test_user; 
```

I am closing this issue because in fact no change in Authentik is needed. However documentation could be improved to address requirements by the newer Postgres versions.
