### ISSUE TITLE
null values in token

### ISSUE THREAD

**Issue by adepto-io** [goauthentik/authentik#785]
**Describe the bug**
The ID token contains the [exp](https://tools.ietf.org/html/rfc7519#section-4.1.4) claim even though it's set to null. This results in an JSONException because it expects a long.
```kotlin
    AuthorizationException: {"type":0,"code":8,"errorDescription":"Unable to parse ID Token"}
        at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:691)
        at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:564)
        at android.os.AsyncTask.finish(AsyncTask.java:771)
        at android.os.AsyncTask.access$900(AsyncTask.java:199)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: org.json.JSONException: Value null at exp of type org.json.JSONObject$1 cannot be converted to long
        at org.json.JSON.typeMismatch(JSON.java:101)
        at org.json.JSONObject.getLong(JSONObject.java:528)
        at net.openid.appauth.IdToken.from(IdToken.java:99)
        at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:688)
        at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:564) 
        at android.os.AsyncTask.finish(AsyncTask.java:771) 
        at android.os.AsyncTask.access$900(AsyncTask.java:199) 
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7660) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

**To Reproduce**
1. Authenticate with Authentik
2. Parse the retrieved ID token
3. See JSONException

**Expected behavior**
The [exp](https://tools.ietf.org/html/rfc7519#section-4.1.4) claim is not [mandatory](https://tools.ietf.org/html/rfc7519#section-4.1). Wouldn't it be better if null values are not included in tokens?

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.4.4
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
Hmmm, that definitely shouldn't happen, the `exp` value should always be set.

The ID Tokens are generated here: https://github.com/goauthentik/authentik/blob/master/authentik/providers/oauth2/models.py#L488

The only way it could be empty is from this fallback here https://github.com/goauthentik/authentik/blob/master/authentik/providers/oauth2/models.py#L422

**Comment by BeryJu** [comment]
@adepto-io Could you post the settings of your provider and also client configuration (most importantly which oauth flow)

**Comment by adepto-io** [comment]
I'm using an **OAuth2/OpenID** provider using the **default-provider-authorization-explicit-consent** flow. Client type is set to **public** and the redirect URI is **com.example.app://oauth2redirect**. JWT algorithm is set to **RS256** using the Authentik **self-signed certificate**.

**Comment by BeryJu** [comment]
Which kind of Response Type are you requesting? Could you post the full authorization URL with parameters too if possible?

**Comment by adepto-io** [comment]
This is the logging from the start of the authentication process up until the crash on my Android device. The response type is **code**.

```json
{
    "event": "/application/o/example/.well-known/openid-configuration",
    "host": "172.16.81.72",
    "level": "info",
    "logger": "authentik.asgi",
    "method": "GET",
    "pid": 39,
    "request_id": "2319a7c98c8d4f1da62d0249dbcc06fe",
    "runtime": 1306,
    "scheme": "http",
    "size": 0.062,
    "status": 200,
    "timestamp": "2021-04-27T08:38:09.349196"
}
{
    "event": "/application/o/authorize/?redirect_uri=com.example.app%3A%2F%2Foauth2redirect&client_id=04d6f630d8899bc63798f3be2d8be4aea3d87c24&response_type=code&state=YiQeapnL2RhAB3Y5dTWnpQ&nonce=FCipOV5yfxb3WbEXDmfj1A&code_challenge=iBQp7XQcv32RktSyGOJizx25GAO8sfa4k991vOBbeEg&code_challenge_method=S256",
    "host": "172.16.81.72",
    "level": "info",
    "logger": "authentik.asgi",
    "method": "GET",
    "pid": 39,
    "request_id": "4aa4ea14365748fbaf690bc0bfe1aa3b",
    "runtime": 0,
    "scheme": "http",
    "size": 0.067,
    "status": 302,
    "timestamp": "2021-04-27T08:38:10.786019"
}
{
    "event": "/api/v2beta/root/config/",
    "host": "172.16.81.72",
    "level": "info",
    "logger": "authentik.asgi",
    "method": "GET",
    "pid": 39,
    "request_id": "02aa204875e44013a15d50da30d4a8ea",
    "runtime": 345,
    "scheme": "http",
    "size": 0.044,
    "status": 200,
    "timestamp": "2021-04-27T08:38:11.215828"
}
{
    "event": "/api/v2beta/flows/executor/default-provider-authorization-explicit-consent/?query=redirect_uri%3Dcom.example.app%253A%252F%252Foauth2redirect%26client_id%3D04d6f630d8899bc63798f3be2d8be4aea3d87c24%26response_type%3Dcode%26state%3DYiQeapnL2RhAB3Y5dTWnpQ%26nonce%3DFCipOV5yfxb3WbEXDmfj1A%26code_challenge%3DiBQp7XQcv32RktSyGOJizx25GAO8sfa4k991vOBbeEg%26code_challenge_method%3DS256",
    "host": "172.16.81.72",
    "level": "info",
    "logger": "authentik.asgi",
    "method": "GET",
    "pid": 37,
    "request_id": "0055743ebbb64953919df6d898284416",
    "runtime": 384,
    "scheme": "http",
    "size": 0.049,
    "status": 200,
    "timestamp": "2021-04-27T08:38:11.223980"
}
```

**Comment by BeryJu** [comment]
So, a couple of things I noticed from that.

- There are no scopes being requested, which means authentik identifies it as a generic OAuth request, not OpenID. Seeing as you're using an OpenID Library, please add at least `openid`, maybe `openid profile email` as a scope param.
- It looks like no request to the `/token/` endpoint is made, so I wonder where it gets the id_token from in the first place.
- I don't have full test coverage for the PKCE part, I'll add that

**Comment by adepto-io** [comment]
OK, so this was actually a bug on my end :grimacing: My scopes we're set but not used....Sorry to have wasted your time!

**Comment by BeryJu** [comment]
:D no worries, the exp still shouldn't be empty, I'll add some more tests for this and PKCE.
