### ISSUE TITLE
Authentik consuming huge number of database connections

### ISSUE THREAD

**Issue by PythonCoderAS** [goauthentik/authentik#7965]
**Describe the bug**
The server will consume way too many database connections, eventually filling up all of the connections.

**To Reproduce**
Unknown reproduction, but I did only see this happen after upgrading to 2023.10.5.

**Expected behavior**
Not so many DB connections

**Screenshots**
<img width="1573" alt="Screenshot 2023-12-21 at 1 36 28 PM" src="https://github.com/goauthentik/authentik/assets/13932583/214bfe7b-fd6f-47f6-9d11-476b1fa4ac60">

**Logs**
Logfile produced was 120 MB so unable to attach

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. 2021.8.5] 2023.10.5
-   Deployment: [e.g. docker-compose, helm] docker-compose

**Additional context**
Once the process saturated the DB connection pool every task started failing as it ran out of connection slots. However, it was able to somehow log these in the authentik log on the admin panel:

```
ask clean_expired_models encountered an error: Traceback (most recent call last):
  File "/ak-root/venv/lib/python3.11/site-packages/celery/app/trace.py", line 494, in trace_task
    I, R, state, retval = on_error(task_request, exc)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/celery/app/trace.py", line 399, in on_error
    R = I.handle_error_state(
        ^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/celery/app/trace.py", line 178, in handle_error_state
    return {
           ^
  File "/ak-root/venv/lib/python3.11/site-packages/celery/app/trace.py", line 236, in handle_failure
    task.on_failure(exc, req.id, req.args, req.kwargs, einfo)
  File "/authentik/events/monitored_tasks.py", line 191, in on_failure
    ).save()
      ^^^^^^
  File "/authentik/events/models.py", line 272, in save
    super().save(*args, **kwargs)
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1820, in execute_sql
    with self.connection.cursor() as cursor:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/base/base.py", line 330, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/base/base.py", line 306, in _cursor
    self.ensure_connection()
  File "/ak-root/venv/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/base/base.py", line 288, in ensure_connection
    with self.wrap_database_errors:
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
    self.connect()
  File "/ak-root/venv/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/base/base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django_prometheus/db/backends/postgresql/base.py", line 9, in get_new_connection
    conn = super().get_new_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django_prometheus/db/common.py", line 45, in get_new_connection
    return super().get_new_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/psycopg/connection.py", line 738, in connect
    raise ex.with_traceback(None)
django.db.utils.OperationalError: connection failed: FATAL:  sorry, too many clients already
```

**Comment by BeryJu** [comment]
![image](https://github.com/goauthentik/authentik/assets/1932513/77c72ea4-9ce3-4e89-abb0-f20a09e24908)
I can actually confirm this my own instance, we had a similar issue to this previously, and this started on the 19th december so I'm trying to find which beta build from that time could've caused this

**Comment by BeryJu** [comment]
https://github.com/goauthentik/authentik/pull/6677 was the PR reverted last time

**Comment by BeryJu** [comment]
none of the settings reverted in the above PR changed their defaults when we upgraded to django 5.0

**Comment by PythonCoderAS** [comment]
I wonder if there's something in conjunction with the worker, because the worker was consuming an insane amount of CPU time so I turned it off for now.

**Comment by BeryJu** [comment]
There's https://github.com/goauthentik/authentik/issues/7025 and https://github.com/goauthentik/authentik/pull/7762 for the worker CPU usage that might fix that

**Comment by j007bond007** [comment]
This just occurred for me as well after updating to 2023.10.5. I need to restart the postgres database server every 1-2 hours to fix it. Is there a proper workaround for now?

**Comment by PythonCoderAS** [comment]
> This just occurred for me as well after updating to 2023.10.5. I need to restart the postgres database server every 1-2 hours to fix it. Is there a proper workaround for now?

I tried restarting the worker and the server containers and that has kind of helped.

**Comment by joachimtingvold** [comment]
Was there anything done regarding this? I just encountered the same issue running 2024.4.2. If nothing was done, maybe remove the stale/wontfix-tags, @BeryJu?

**Comment by Sampath8797** [comment]
We too encounter the same issue in 2023.10.6, the error which we get in the backend application is. `Unable to get current user profile { error: 'failed to connect to authentik backend: EOF'` also the DB connection limit has reached its maximum
