### ISSUE TITLE
Confirmation email not sent to user

### ISSUE THREAD

**Issue by GD-Dal** [goauthentik/authentik#8071]
**Describe the bug**
I try to create a flow that allows users to sign up.
That works, but they never get an email.

The event log creates System task exception like this:

`Exception

Task send_mail encountered an error: Traceback (most recent call last):
  File "/ak-root/venv/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 280, in _inner
    reraise(*exc_info)
  File "/ak-root/venv/lib/python3.11/site-packages/sentry_sdk/_compat.py", line 115, in reraise
    raise value
  File "/ak-root/venv/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 275, in _inner
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/celery/app/autoretry.py", line 60, in run
    ret = task.retry(exc=exc, **retry_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/celery/app/task.py", line 736, in retry
    raise_with_context(exc)
  File "/ak-root/venv/lib/python3.11/site-packages/celery/app/autoretry.py", line 38, in run
    return task._orig_run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/email/tasks.py", line 108, in send_mail
    raise exc
  File "/authentik/stages/email/tasks.py", line 74, in send_mail
    backend.open()
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 85, in open
    self.connection = self.connection_class(
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/sentry_sdk/integrations/socket.py", line 66, in create_connection
    return real_create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
builtins.ConnectionRefusedError: [Errno 111] Connection refused

`

**To Reproduce**
Easily reproduced by creating a new user

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.5
-   Deployment: Unraid Docker

**Additional context**
Sending a test email using ha test_email works fine

**Comment by whitephoenix117** [comment]
Looks the same as

#8049

**Comment by GD-Dal** [comment]
Can confirm, still not working

**Comment by rissson** [comment]
It seems that authentik does not connect to your email server and gets a "connection refused". Check your email settings: https://docs.goauthentik.io/docs/troubleshooting/emails

**Comment by GD-Dal** [comment]
ak test_email <email address> -S email-account-confirmation
and
ak test_email <email address>

Work perfectly fine, and I'm receiving the test emails
