### ISSUE TITLE
Command `ak test_email` is timing out

### ISSUE THREAD

**Issue by iTim314** [goauthentik/authentik#8108]
**Describe the bug**
I am trying to setup Authentik to use AWS SES. I have followed Amazon's instructions to use SES with SMTP. However, when I try to send a test mail with `ak test_mail` in the docker container, the process is timing out. I tried increasing the timeout to larger and larger times to no avail. 

**To Reproduce**

My environment config (with redaction):
```
AUTHENTIK_EMAIL__HOST=email-smtp.us-east-1.amazonaws.com
AUTHENTIK_EMAIL__PORT=465
AUTHENTIK_EMAIL__USERNAME=AWS_ACCESS_KEY_ID
AUTHENTIK_EMAIL__PASSWORD=AWS_ACCESS_KEY_TOKEN
AUTHENTIK_EMAIL__USE_TLS=TRUE
AUTHENTIK_EMAIL__USE_SSL=FALSE
AUTHENTIK_EMAIL__TIMEOUT=30
AUTHENTIK_EMAIL__FROM=no-reply@my.verfieid.domain
```

I entered the worker container:
`docker exec -it auth-worker /bin/bash`

I ran this command from the container:
` ak test_email myemail@my.verfieid.domain` (email redacted, but this is a valid email address)

**Expected behavior**
I am expecting the `ak test_email` command to work.

**Logs**
```
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1704824986.8564484, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1704824986.8567996, "count": 15}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1704824989.2560484, "path": "authentik.admin.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1704824989.2567086, "path": "authentik.crypto.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1704824989.2571602, "path": "authentik.events.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1704824989.25819, "path": "authentik.outposts.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1704824989.2595632, "path": "authentik.policies.reputation.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1704824989.2610388, "path": "authentik.providers.scim.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1704824989.2619529, "path": "authentik.sources.ldap.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1704824989.2623925, "path": "authentik.sources.oauth.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1704824989.2628217, "path": "authentik.sources.plex.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1704824989.2643476, "path": "authentik.stages.authenticator_totp.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1704824989.2675655, "path": "authentik.blueprints.settings"}
{"event": "Booting authentik", "level": "info", "logger": "authentik.lib.config", "timestamp": 1704824989.2676835, "version": "2023.10.5"}
{"event": "Enabled authentik enterprise", "level": "info", "logger": "authentik.lib.config", "timestamp": 1704824989.268594}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1704824989.268886, "path": "authentik.enterprise.settings"}
{"event": "Loaded GeoIP database", "last_write": 1703165606.0, "level": "info", "logger": "authentik.events.geo", "pid": 33, "timestamp": "2024-01-09T18:29:50.277635"}
{"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 33, "task_id": "6789e22295b84c98bbf0e1354d2afaba", "task_name": "authentik.blueprints.v1.tasks.blueprints_discovery", "timestamp": "2024-01-09T18:29:51.313897"}
{"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 33, "task_id": "fa1b499fd4994192be917bdc41ef8d98", "task_name": "authentik.blueprints.v1.tasks.clear_failed_blueprints", "timestamp": "2024-01-09T18:29:51.315143"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/smtplib.py", line 398, in getreply
    line = self.file.readline(_MAXLINE + 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/email/management/commands/test_email.py", line 36, in handle
    send_mail(message.__dict__, stage.pk)
  File "/ak-root/venv/lib/python3.11/site-packages/celery/local.py", line 182, in __call__
    return self._get_current_object()(*a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/celery/app/task.py", line 411, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/celery/app/autoretry.py", line 60, in run
    ret = task.retry(exc=exc, **retry_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/celery/app/task.py", line 720, in retry
    raise_with_context(exc or Retry('Task can be retried', None))
  File "/ak-root/venv/lib/python3.11/site-packages/celery/app/autoretry.py", line 38, in run
    return task._orig_run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/email/tasks.py", line 108, in send_mail
    raise exc
  File "/authentik/stages/email/tasks.py", line 74, in send_mail
    backend.open()
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 85, in open
    self.connection = self.connection_class(
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/smtplib.py", line 343, in connect
    (code, msg) = self.getreply()
                  ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/smtplib.py", line 401, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed: "
smtplib.SMTPServerDisconnected: Connection unexpectedly closed: timed out
Sentry is attempting to send 1 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.5
-   Deployment: docker-compose

**Additional context**

- The email+domain I'm sending from has been verified in AWS. 
- I followed AWS's SMTP instructions here: https://docs.aws.amazon.com/ses/latest/dg/send-email-smtp.html
- It may not be related, but since I first setup Authentik my `docker-connection` outpost integration has been in an unhealthy state. See #7279

**Comment by XA21X** [comment]
I think USE_TLS confusingly means StartTLS (for port 587), which is not supported on port 465. 😂

I'm using the K8s helm chart with MXroute as the email provider. Switching to USE_SSL fixed it for me. :)

```
AUTHENTIK_EMAIL__USE_TLS=FALSE
AUTHENTIK_EMAIL__USE_SSL=TRUE
```

**Comment by iTim314** [comment]
> I think USE_TLS confusingly means StartTLS (for port 587), which is not supported on port 465. 😂
> 
> I'm using the K8s helm chart with MXroute as the email provider. Switching to USE_SSL fixed it for me. :)
> 
> ```
> AUTHENTIK_EMAIL__USE_TLS=FALSE
> AUTHENTIK_EMAIL__USE_SSL=TRUE
> ```
> 
> EDIT: Alternatively, [switching to port 587 should work with USE_TLS](https://docs.aws.amazon.com/ses/latest/dg/smtp-connect.html#smtp-connect-starttls).

Hot dog! That worked. So to use TLS, you have to set TLS to false. Right.

**Comment by rissson** [comment]
> So to use TLS, you have to set TLS to false. Right.

Yeah email terminology is very bad and not consistent between anything. Use SSL usually means using the SSL/TLS protocol directly, where use TLS usually means use STARTTLS.
