### ISSUE TITLE
GET /api/v3/admin/workers/

### ISSUE THREAD

**Issue by Arragon5xpwm** [goauthentik/authentik#8329]
**Describe the bug**

**To Reproduce**
1. Add ForwardAuth for traefik for <domain>
2. Add Application and bind user
3. Update embedded Outpost
4. goto <domain>
5. Get message: ```{
	"Message": "no app for hostname",
	"Host": "<domain>",
	"Detail": "Check the outpost settings and make sure '<domain>' is included."
}```

**Expected behavior**
Redirect to Authentik login or show application

**Logs**
<details>
    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
  File "/ak-root/venv/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/ak-root/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/ak-root/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/admin/api/workers.py", line 21, in get
    count = len(CELERY_APP.control.ping(timeout=0.5))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/celery/app/control.py", line 563, in ping
    return self.broadcast(
           ^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/celery/app/control.py", line 776, in broadcast
    return self.mailbox(conn)._broadcast(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/kombu/pidbox.py", line 346, in _broadcast
    return self._collect(reply_ticket, limit=limit,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/kombu/pidbox.py", line 388, in _collect
    self.connection.drain_events(timeout=timeout)
  File "/ak-root/venv/lib/python3.11/site-packages/kombu/connection.py", line 341, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/kombu/transport/virtual/base.py", line 997, in drain_events
    get(self._deliver, timeout=timeout)
  File "/ak-root/venv/lib/python3.11/site-packages/kombu/transport/redis.py", line 588, in get
    ret = self.handle_event(fileno, event)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/kombu/transport/redis.py", line 570, in handle_event
    return self.on_readable(fileno), self
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/kombu/transport/redis.py", line 566, in on_readable
    chan.handlers[type]()
  File "/ak-root/venv/lib/python3.11/site-packages/kombu/transport/redis.py", line 971, in _brpop_read
    self.connection._deliver(loads(bytes_to_str(item)), dest)
  File "/ak-root/venv/lib/python3.11/site-packages/kombu/transport/virtual/base.py", line 1017, in _deliver
    callback(message)
  File "/ak-root/venv/lib/python3.11/site-packages/kombu/transport/virtual/base.py", line 639, in _callback
    return callback(message)
           ^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/kombu/messaging.py", line 650, in _receive_callback
    decoded = None if on_m else message.decode()
                                ^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/kombu/message.py", line 201, in decode
    self._decoded_cache = self._decode()
                          ^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/kombu/message.py", line 205, in _decode
    return loads(self.body, self.content_type,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/kombu/serialization.py", line 255, in loads
    raise self._for_untrusted_content(content_type, 'untrusted')
kombu.exceptions.ContentDisallowed: Refusing to deserialize untrusted content of type pickle (application/x-python-serialize)
```
</details>

**Version and Deployment (please complete the following information):**
- authentik version: 2023.10.6
- Deployment: [e.g. docker-compose, helm]

**Additional context**
Currently authentik-worker is crashing as described in Authentik discord https://discord.com/channels/809154715984199690/1194434892784738315/1194434892784738315

**Comment by Arragon5xpwm** [comment]
Error from Authentik Worker:
```{"event": "/ak-root/venv/lib/python3.11/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine\nwhether broker connection retries are made during startup in Celery 6.0 and above.\nIf you wish to retain the existing behavior for retrying connections on startup,\nyou should set broker_connection_retry_on_startup to True.\n  warnings.warn(\n", "level": "warning", "logger": "py.warnings", "timestamp": 1706771879.4028625}
{"event": "/ak-root/venv/lib/python3.11/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine\nwhether broker connection retries are made during startup in Celery 6.0 and above.\nIf you wish to retain the existing behavior for retrying connections on startup,\nyou should set broker_connection_retry_on_startup to True.\n  warnings.warn(\n", "level": "warning", "logger": "py.warnings", "timestamp": 1706771879.4081633}
{"event": "Unrecoverable error: ContentDisallowed('Refusing to deserialize untrusted content of type pickle (application/x-python-serialize)')", "exception": [{"exc_type": "ContentDisallowed", "exc_value": "Refusing to deserialize untrusted content of type pickle (application/x-python-serialize)", "frames": [{"filename": "/ak-root/venv/lib/python3.11/site-packages/celery/worker/worker.py", "line": "", "lineno": 202, "locals": {"exc": "\"ContentDisallowed('Refusing to deserialize untrusted content of type pickle (app\"+30", "self": "<Worker: celery@97cb475ddd10 (running)>"}, "name": "start"}, {"filename": "/ak-root/venv/lib/python3.11/site-packages/celery/bootsteps.py", "line": "", "lineno": 116, "locals": {"i": "5", "parent": "<Worker: celery@97cb475ddd10 (running)>", "self": "<celery.worker.worker.WorkController.Blueprint object at 0x154832e06890>", "step": "<step: Consumer>"}, "name": "start"}, {"filename": "/ak-root/venv/lib/python3.11/site-packages/celery/bootsteps.py", "line": "", "lineno": 365, "locals": {"parent": "<Worker: celery@97cb475ddd10 (running)>", "self": "<step: Consumer>"}, "name": "start"}, {"filename": "/ak-root/venv/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", "line": "", "lineno": 340, "locals": {"blueprint": "<celery.worker.consumer.consumer.Consumer.Blueprint object at 0x154832e07490>", "recoverable_errors": "\"(<class 'amqp.exceptions.ConnectionError'>, <class 'kombu.exceptions.Inconsisten\"+200", "self": "<Consumer: celery@97cb475ddd10 (running)>"}, "name": "start"}, {"filename": "/ak-root/venv/lib/python3.11/site-packages/celery/bootsteps.py", "line": "", "lineno": 116, "locals": {"i": "2", "parent": "<Consumer: celery@97cb475ddd10 (running)>", "self": "<celery.worker.consumer.consumer.Consumer.Blueprint object at 0x154832e07490>", "step": "<step: Mingle>"}, "name": "start"}, {"filename": "/ak-root/venv/lib/python3.11/site-packages/celery/worker/consumer/mingle.py", "line": "", "lineno": 37, "locals": {"c": "<Consumer: celery@97cb475ddd10 (running)>", "self": "<step: Mingle>"}, "name": "start"}, {"filename": "/ak-root/venv/lib/python3.11/site-packages/celery/worker/consumer/mingle.py", "line": "", "lineno": 41, "locals": {"c": "<Consumer: celery@97cb475ddd10 (running)>", "self": "<step: Mingle>"}, "name": "sync"}, {"filename": "/ak-root/venv/lib/python3.11/site-packages/celery/worker/consumer/mingle.py", "line": "", "lineno": 54, "locals": {"c": "<Consumer: celery@97cb475ddd10 (running)>", "inspect": "<celery.app.control.Inspect object at 0x154832e984d0>", "our_revoked": "<LimitedSet(0): maxlen=50000, expires=10800.0, minlen=0>", "self": "<step: Mingle>"}, "name": "send_hello"}, {"filename": "/ak-root/venv/lib/python3.11/site-packages/celery/app/control.py", "line": "", "lineno": 389, "locals": {"from_node": "celery@97cb475ddd10", "revoked": "{}", "self": "<celery.app.control.Inspect object at 0x154832e984d0>"}, "name": "hello"}, {"filename": "/ak-root/venv/lib/python3.11/site-packages/celery/app/control.py", "line": "", "lineno": 106, "locals": {"command": "hello", "kwargs": "{'from_node': 'celery@97cb475ddd10', 'revoked': {}}", "self": "<celery.app.control.Inspect object at 0x154832e984d0>"}, "name": "_request"}, {"filename": "/ak-root/venv/lib/python3.11/site-packages/celery/app/control.py", "line": "", "lineno": 776, "locals": {"arguments": "{'from_node': 'celery@97cb475ddd10', 'revoked': {}}", "callback": "None", "channel": "None", "command": "hello", "conn": "<Connection: redis://:**@host.docker.internal:6379/0 at 0x154832eb1cd0>", "connection": "<Connection: redis://:**@host.docker.internal:6379/0 at 0x154832eb1cd0>", "destination": "None", "extra_kwargs": "{}", "limit": "None", "matcher": "None", "pattern": "None", "reply": "True", "self": "<celery.app.control.Control object at 0x154832d893d0>", "timeout": "1.0"}, "name": "broadcast"}, {"filename": "/ak-root/venv/lib/python3.11/site-packages/kombu/pidbox.py", "line": "", "lineno": 346, "locals": {"arguments": "{'from_node': 'celery@97cb475ddd10', 'revoked': {}}", "callback": "None", "chan": "<kombu.transport.redis.Channel object at 0x15483eed54d0>", "channel": "None", "command": "hello", "destination": "None", "limit": "None", "matcher": "None", "pattern": "None", "reply": "True", "reply_ticket": "7f76b82c-e7ee-439f-8ead-e4e6ec0b482f", "self": "<kombu.pidbox.Mailbox object at 0x154832da6c50>", "serializer": "json", "timeout": "1.0"}, "name": "_broadcast"}, {"filename": "/ak-root/venv/lib/python3.11/site-packages/kombu/pidbox.py", "line": "", "lineno": 388, "locals": {"accept": "('json',)", "adjust_clock": "<bound method LamportClock.adjust of <LamportClock: 1>>", "callback": "None", "chan": "<kombu.transport.redis.Channel object at 0x15483eed54d0>", "channel": "<kombu.transport.redis.Channel object at 0x15483eed54d0>", "consumer": "'<Consumer: [<Queue 133f5360-70d2-3123-b14b-5f7b53cddfed.reply.celery.pidbox -> <'+112", "i": "0", "limit": "None", "on_message": "<function Mailbox._collect.<locals>.on_message at 0x1548336d8a40>", "queue": "'<unbound Queue 133f5360-70d2-3123-b14b-5f7b53cddfed.reply.celery.pidbox -> <unbo'+82", "responses": "[]", "self": "<kombu.pidbox.Mailbox object at 0x154832da6c50>", "ticket": "7f76b82c-e7ee-439f-8ead-e4e6ec0b482f", "timeout": "1.0", "unclaimed": "defaultdict(<class 'collections.deque'>, {})"}, "name": "_collect"}, {"filename": "/ak-root/venv/lib/python3.11/site-packages/kombu/connection.py", "line": "", "lineno": 341, "locals": {"kwargs": "{'timeout': 1.0}", "self": "<Connection: redis://:**@host.docker.internal:6379/0 at 0x154832eb1cd0>"}, "name": "drain_events"}, {"filename": "/ak-root/venv/lib/python3.11/site-packages/kombu/transport/virtual/base.py", "line": "", "lineno": 997, "locals": {"connection": "<kombu.transport.redis.Transport object at 0x15483eed5310>", "get": "'<bound method MultiChannelPoller.get of <kombu.transport.redis.MultiChannelPolle'+28", "polling_interval": "None", "self": "<kombu.transport.redis.Transport object at 0x15483eed5310>", "time_start": "416221.608847213", "timeout": "1.0"}, "name": "drain_events"}, {"filename": "/ak-root/venv/lib/python3.11/site-packages/kombu/transport/redis.py", "line": "", "lineno": 588, "locals": {"callback": "'<bound method Transport._deliver of <kombu.transport.redis.Transport object at 0'+15", "channel": "<kombu.transport.redis.Channel object at 0x15483eed54d0>", "event": "1", "events": "[(26, 1)]", "fileno": "26", "self": "<kombu.transport.redis.MultiChannelPoller object at 0x15483eed5490>", "timeout": "1.0"}, "name": "get"}, {"filename": "/ak-root/venv/lib/python3.11/site-packages/kombu/transport/redis.py", "line": "", "lineno": 570, "locals": {"event": "1", "fileno": "26", "self": "<kombu.transport.redis.MultiChannelPoller object at 0x15483eed5490>"}, "name": "handle_event"}, {"filename": "/ak-root/venv/lib/python3.11/site-packages/kombu/transport/redis.py", "line": "", "lineno": 566, "locals": {"chan": "<kombu.transport.redis.Channel object at 0x15483eed54d0>", "fileno": "26", "self": "<kombu.transport.redis.MultiChannelPoller object at 0x15483eed5490>", "type": "BRPOP"}, "name": "on_readable"}, {"filename": "/ak-root/venv/lib/python3.11/site-packages/kombu/transport/redis.py", "line": "", "lineno": 971, "locals": {"dest": "133f5360-70d2-3123-b14b-5f7b53cddfed.reply.celery.pidbox", "dest__item": "'(b\\'133f5360-70d2-3123-b14b-5f7b53cddfed.reply.celery.pidbox\\', b\\'{\"body\": \"gASVNw'+484", "item": "'b\\'{\"body\": \"gASVNwAAAAAAAAB9lIwTY2VsZXJ5QGQ4MjM5YmU0NDQ3OZR9lCiMB3Jldm9rZWSUfZSM'+421", "options": "{}", "self": "<kombu.transport.redis.Channel object at 0x15483eed54d0>"}, "name": "_brpop_read"}, {"filename": "/ak-root/venv/lib/python3.11/site-packages/kombu/transport/virtual/base.py", "line": "", "lineno": 1017, "locals": {"callback": "<function Channel.basic_consume.<locals>._callback at 0x1548336d8860>", "message": "\"{'body': 'gASVNwAAAAAAAAB9lIwTY2VsZXJ5QGQ4MjM5YmU0NDQ3OZR9lCiMB3Jldm9rZWSUfZSMBW\"+418", "queue": "133f5360-70d2-3123-b14b-5f7b53cddfed.reply.celery.pidbox", "self": "<kombu.transport.redis.Transport object at 0x15483eed5310>"}, "name": "_deliver"}, {"filename": "/ak-root/venv/lib/python3.11/site-packages/kombu/transport/virtual/base.py", "line": "", "lineno": 639, "locals": {"callback": "'<bound method Consumer._receive_callback of <Consumer: [<Queue 133f5360-70d2-312'+157", "message": "\"<Message object at 0x154832ca5d90 with details {'state': 'RECEIVED', 'content_ty\"+241", "no_ack": "True", "raw_message": "\"{'body': 'gASVNwAAAAAAAAB9lIwTY2VsZXJ5QGQ4MjM5YmU0NDQ3OZR9lCiMB3Jldm9rZWSUfZSMBW\"+418", "self": "<kombu.transport.redis.Channel object at 0x15483eed54d0>"}, "name": "_callback"}, {"filename": "/ak-root/venv/lib/python3.11/site-packages/kombu/messaging.py", "line": "", "lineno": 650, "locals": {"accept": "{'application/json'}", "channel": "<kombu.transport.redis.Channel object at 0x15483eed54d0>", "decoded": "None", "m2p": "'<bound method Channel.message_to_python of <kombu.transport.redis.Channel object'+20", "message": "\"<Message object at 0x154832ca5d90 with details {'state': 'RECEIVED', 'content_ty\"+241", "on_m": "None", "self": "'<Consumer: [<Queue 133f5360-70d2-3123-b14b-5f7b53cddfed.reply.celery.pidbox -> <'+112"}, "name": "_receive_callback"}, {"filename": "/ak-root/venv/lib/python3.11/site-packages/kombu/message.py", "line": "", "lineno": 201, "locals": {"self": "\"<Message object at 0x154832ca5d90 with details {'state': 'RECEIVED', 'content_ty\"+241"}, "name": "decode"}, {"filename": "/ak-root/venv/lib/python3.11/site-packages/kombu/message.py", "line": "", "lineno": 205, "locals": {"self": "\"<Message object at 0x154832ca5d90 with details {'state': 'RECEIVED', 'content_ty\"+241"}, "name": "_decode"}, {"filename": "/ak-root/venv/lib/python3.11/site-packages/kombu/serialization.py", "line": "", "lineno": 255, "locals": {"_trusted_content": "frozenset({'application/data', 'application/text'})", "accept": "{'application/json'}", "content_encoding": "binary", "content_type": "application/x-python-serialize", "data": "\"b'\\\\x80\\\\x04\\\\x957\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00}\\\\x94\\\\x8c\\\\x13celery@d8239be44479\\\\x94}\"+67", "force": "False", "self": "<kombu.serialization.SerializerRegistry object at 0x1548412be790>"}, "name": "loads"}], "is_cause": false, "syntax_error": null}], "level": "critical", "logger": "celery.worker", "timestamp": 1706771879.4225428}
{"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 12, "task_id": "cadbd5d011544e36b8257fd85f792e08", "task_name": "authentik.outposts.tasks.outpost_service_connection_monitor", "timestamp": "2024-02-01T07:18:00.006566"}
Sentry is attempting to send 1 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit```
