### ISSUE TITLE
Authentik-server container unable to start after upgrade to 2023.10.7

### ISSUE THREAD

**Issue by aheath70** [goauthentik/authentik#8366]
**Describe the bug**
Post upgrade to 2023.10.7, container never becomes healthy, website is unavailable and CPU usage on machine is very high.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x108943f]
goroutine 54 [running]:
goauthentik.io/internal/outpost/proxyv2.(*ProxyServer).Refresh(0xc0000c3130)
	/go/src/goauthentik.io/internal/outpost/proxyv2/refresh.go:38 +0x59f
goauthentik.io/internal/outpost/ak.(*APIController).OnRefresh(0xc0000f0a80)
	/go/src/goauthentik.io/internal/outpost/ak/api.go:180 +0x314
goauthentik.io/internal/outpost/ak.(*APIController).startIntervalUpdater(0xc0000f0a80)
	/go/src/goauthentik.io/internal/outpost/ak/api_ws.go:191 +0x17b
goauthentik.io/internal/outpost/ak.(*APIController).StartBackgroundTasks.func3()
	/go/src/goauthentik.io/internal/outpost/ak/api.go:218 +0x5d
created by goauthentik.io/internal/outpost/ak.(*APIController).StartBackgroundTasks in goroutine 40
	/go/src/goauthentik.io/internal/outpost/ak/api.go:216 +0x38d

```

Downgrade back to 2023.10.6 has not restored functrionality. 

**To Reproduce**

1. Upgrade to 2023.10.7 authentik using prescribed method

**Expected behavior**
No fault

**Screenshots**
Not relevant

**Logs**
[_authentik-server_logs.txt](https://github.com/goauthentik/authentik/files/14096507/_authentik-server_logs.txt)
**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.7
-   Deployment: docker compose

**Additional context**
None

**Comment by gmpreussner** [comment]
My upgrade failed as well, albeit with different errors (see below). The `worker` and `server` containers are repeatedly attempting to restart and fail. My CPU usage is low.

I upgraded via:
```
$ curl -O https://goauthentik.io/docker-compose.yml
$ sudo docker compose up -d
$ sudo docker compose run --rm server migrate
```

```
server-1 exited with code 1
worker-1      | 2024-02-03T05:52:21.283945264Z {"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1706939541.2728472, "file": "/authentik/lib/default.yml"}
worker-1      | 2024-02-03T05:52:21.283972615Z {"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1706939541.277387, "count": 7}
worker-1      | 2024-02-03T05:52:21.283976265Z {"event": "Starting authentik bootstrap", "level": "info", "logger": "authentik.lib.config", "timestamp": 1706939541.277554}
worker-1      | 2024-02-03T05:52:21.291720864Z {"event": "PostgreSQL connection successful", "level": "info", "logger": "authentik.lib.config", "timestamp": 1706939541.2869651}
worker-1      | 2024-02-03T05:52:21.303692558Z {"event": "Redis Connection successful", "level": "info", "logger": "authentik.lib.config", "timestamp": 1706939541.3002732}
worker-1      | 2024-02-03T05:52:21.303703278Z {"event": "Finished authentik bootstrap", "level": "info", "logger": "authentik.lib.config", "timestamp": 1706939541.300333}
server-1      | 2024-02-03T05:52:21.521477406Z {"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1706939541.5213273, "file": "/authentik/lib/default.yml"}
server-1      | 2024-02-03T05:52:21.522320017Z {"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1706939541.5222516, "count": 7}
server-1      | 2024-02-03T05:52:21.522617551Z {"event": "Starting authentik bootstrap", "level": "info", "logger": "authentik.lib.config", "timestamp": 1706939541.522554}
server-1      | 2024-02-03T05:52:21.528923562Z {"event": "PostgreSQL connection successful", "level": "info", "logger": "authentik.lib.config", "timestamp": 1706939541.5288491}
server-1      | 2024-02-03T05:52:21.540250437Z {"event": "Redis Connection successful", "level": "info", "logger": "authentik.lib.config", "timestamp": 1706939541.5401797}
server-1      | 2024-02-03T05:52:21.540446989Z {"event": "Finished authentik bootstrap", "level": "info", "logger": "authentik.lib.config", "timestamp": 1706939541.5403636}
worker-1      | 2024-02-03T05:52:22.884569332Z {"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1706939542.875439, "file": "/authentik/lib/default.yml"}
worker-1      | 2024-02-03T05:52:22.884590982Z {"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1706939542.8800583, "count": 7}
server-1      | 2024-02-03T05:52:23.176159493Z {"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1706939543.1759994, "file": "/authentik/lib/default.yml"}
server-1      | 2024-02-03T05:52:23.179715418Z {"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1706939543.1767511, "count": 7}
worker-1      | 2024-02-03T05:52:23.227955349Z 2024-02-03 05:52:23 [info     ] waiting to acquire database lock
worker-1      | 2024-02-03T05:52:23.228589377Z 2024-02-03 05:52:23 [info     ] Migration needs to be applied  migration=otp_merge.py
postgresql-1  | 2024-02-03T05:52:23.229469349Z 2024-02-03 05:52:23.229 UTC [120] WARNING:  there is already a transaction in progress
postgresql-1  | 2024-02-03T05:52:23.230039396Z 2024-02-03 05:52:23.229 UTC [120] ERROR:  relation "authentik_stages_authenticator_static_staticdevice" already exists
postgresql-1  | 2024-02-03T05:52:23.230047166Z 2024-02-03 05:52:23.229 UTC [120] STATEMENT:
postgresql-1  | 2024-02-03T05:52:23.230049716Z  BEGIN TRANSACTION;
postgresql-1  | 2024-02-03T05:52:23.230051916Z  -- Update migrations (static)
postgresql-1  | 2024-02-03T05:52:23.230053946Z  UPDATE django_migrations SET app = 'authentik_stages_authenticator_static', name = '0008_initial' WHERE app = 'otp_static' AND name = '0001_initial';
postgresql-1  | 2024-02-03T05:52:23.230056076Z  UPDATE django_migrations SET app = 'authentik_stages_authenticator_static', name = '0009_throttling' WHERE app = 'otp_static' AND name = '0002_throttling';
postgresql-1  | 2024-02-03T05:52:23.230058046Z  -- Rename tables (static)
postgresql-1  | 2024-02-03T05:52:23.230059856Z  ALTER TABLE otp_static_staticdevice RENAME TO authentik_stages_authenticator_static_staticdevice;
postgresql-1  | 2024-02-03T05:52:23.230061696Z  ALTER TABLE otp_static_statictoken RENAME TO authentik_stages_authenticator_static_statictoken;
postgresql-1  | 2024-02-03T05:52:23.230063506Z  ALTER SEQUENCE otp_static_statictoken_id_seq RENAME TO authentik_stages_authenticator_static_statictoken_id_seq;
postgresql-1  | 2024-02-03T05:52:23.230065316Z  ALTER SEQUENCE otp_static_staticdevice_id_seq RENAME TO authentik_stages_authenticator_static_staticdevice_id_seq;
postgresql-1  | 2024-02-03T05:52:23.230067156Z  -- Update migrations (totp)
postgresql-1  | 2024-02-03T05:52:23.230075606Z  UPDATE django_migrations SET app = 'authentik_stages_authenticator_totp', name = '0008_initial' WHERE app = 'otp_totp' AND name = '0001_initial';
postgresql-1  | 2024-02-03T05:52:23.230077726Z  UPDATE django_migrations SET app = 'authentik_stages_authenticator_totp', name = '0009_auto_20190420_0723' WHERE app = 'otp_totp' AND name = '0002_auto_20190420_0723';
postgresql-1  | 2024-02-03T05:52:23.230079666Z  -- Rename tables (totp)
postgresql-1  | 2024-02-03T05:52:23.230081426Z  ALTER TABLE otp_totp_totpdevice RENAME TO authentik_stages_authenticator_totp_totpdevice;
postgresql-1  | 2024-02-03T05:52:23.230083256Z  ALTER SEQUENCE otp_totp_totpdevice_id_seq RENAME TO authentik_stages_authenticator_totp_totpdevice_id_seq;
postgresql-1  | 2024-02-03T05:52:23.230097816Z  COMMIT;
postgresql-1  | 2024-02-03T05:52:23.230099966Z
postgresql-1  | 2024-02-03T05:52:23.231930340Z 2024-02-03 05:52:23.231 UTC [120] ERROR:  current transaction is aborted, commands ignored until end of transaction block
postgresql-1  | 2024-02-03T05:52:23.231938830Z 2024-02-03 05:52:23.231 UTC [120] STATEMENT:  SELECT pg_advisory_unlock($1)
worker-1      | 2024-02-03T05:52:23.232343965Z Traceback (most recent call last):
worker-1      | 2024-02-03T05:52:23.232486326Z   File "/lifecycle/migrate.py", line 98, in <module>
worker-1      | 2024-02-03T05:52:23.232734099Z     migration.run()
worker-1      | 2024-02-03T05:52:23.232899533Z   File "/lifecycle/system_migrations/otp_merge.py", line 37, in run
worker-1      | 2024-02-03T05:52:23.233122235Z     self.cur.execute(SQL_STATEMENT)
worker-1      | 2024-02-03T05:52:23.233288237Z   File "/ak-root/venv/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
worker-1      | 2024-02-03T05:52:23.233622591Z     raise ex.with_traceback(None)
worker-1      | 2024-02-03T05:52:23.233881744Z psycopg.errors.DuplicateTable: relation "authentik_stages_authenticator_static_staticdevice" already exists
worker-1      | 2024-02-03T05:52:23.234005046Z
worker-1      | 2024-02-03T05:52:23.234140898Z During handling of the above exception, another exception occurred:
worker-1      | 2024-02-03T05:52:23.234280009Z
worker-1      | 2024-02-03T05:52:23.234408951Z Traceback (most recent call last):
worker-1      | 2024-02-03T05:52:23.234575373Z   File "<frozen runpy>", line 198, in _run_module_as_main
worker-1      | 2024-02-03T05:52:23.234859397Z   File "<frozen runpy>", line 88, in _run_code
worker-1      | 2024-02-03T05:52:23.235095920Z   File "/lifecycle/migrate.py", line 114, in <module>
worker-1      | 2024-02-03T05:52:23.235552286Z     release_lock(curr)
worker-1      | 2024-02-03T05:52:23.235854379Z   File "/lifecycle/migrate.py", line 67, in release_lock
worker-1      | 2024-02-03T05:52:23.236132553Z     cursor.execute("SELECT pg_advisory_unlock(%s)", (ADV_LOCK_UID,))
worker-1      | 2024-02-03T05:52:23.236317995Z   File "/ak-root/venv/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
worker-1      | 2024-02-03T05:52:23.236716920Z     raise ex.with_traceback(None)
worker-1      | 2024-02-03T05:52:23.237035775Z psycopg.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block
server-1      | 2024-02-03T05:52:23.435147724Z 2024-02-03 05:52:23 [info     ] waiting to acquire database lock
server-1      | 2024-02-03T05:52:23.435777402Z 2024-02-03 05:52:23 [info     ] Migration needs to be applied  migration=otp_merge.py
postgresql-1  | 2024-02-03T05:52:23.436707533Z 2024-02-03 05:52:23.436 UTC [128] WARNING:  there is already a transaction in progress
postgresql-1  | 2024-02-03T05:52:23.437256491Z 2024-02-03 05:52:23.437 UTC [128] ERROR:  relation "authentik_stages_authenticator_static_staticdevice" already exists
postgresql-1  | 2024-02-03T05:52:23.437264371Z 2024-02-03 05:52:23.437 UTC [128] STATEMENT:
postgresql-1  | 2024-02-03T05:52:23.437267041Z  BEGIN TRANSACTION;
postgresql-1  | 2024-02-03T05:52:23.437269411Z  -- Update migrations (static)
postgresql-1  | 2024-02-03T05:52:23.437271471Z  UPDATE django_migrations SET app = 'authentik_stages_authenticator_static', name = '0008_initial' WHERE app = 'otp_static' AND name = '0001_initial';
postgresql-1  | 2024-02-03T05:52:23.437273571Z  UPDATE django_migrations SET app = 'authentik_stages_authenticator_static', name = '0009_throttling' WHERE app = 'otp_static' AND name = '0002_throttling';
postgresql-1  | 2024-02-03T05:52:23.437275601Z  -- Rename tables (static)
postgresql-1  | 2024-02-03T05:52:23.437277411Z  ALTER TABLE otp_static_staticdevice RENAME TO authentik_stages_authenticator_static_staticdevice;
postgresql-1  | 2024-02-03T05:52:23.437279231Z  ALTER TABLE otp_static_statictoken RENAME TO authentik_stages_authenticator_static_statictoken;
postgresql-1  | 2024-02-03T05:52:23.437281161Z  ALTER SEQUENCE otp_static_statictoken_id_seq RENAME TO authentik_stages_authenticator_static_statictoken_id_seq;
postgresql-1  | 2024-02-03T05:52:23.437283041Z  ALTER SEQUENCE otp_static_staticdevice_id_seq RENAME TO authentik_stages_authenticator_static_staticdevice_id_seq;
postgresql-1  | 2024-02-03T05:52:23.437284951Z  -- Update migrations (totp)
postgresql-1  | 2024-02-03T05:52:23.437286701Z  UPDATE django_migrations SET app = 'authentik_stages_authenticator_totp', name = '0008_initial' WHERE app = 'otp_totp' AND name = '0001_initial';
postgresql-1  | 2024-02-03T05:52:23.437288591Z  UPDATE django_migrations SET app = 'authentik_stages_authenticator_totp', name = '0009_auto_20190420_0723' WHERE app = 'otp_totp' AND name = '0002_auto_20190420_0723';
postgresql-1  | 2024-02-03T05:52:23.437290501Z  -- Rename tables (totp)
postgresql-1  | 2024-02-03T05:52:23.437292321Z  ALTER TABLE otp_totp_totpdevice RENAME TO authentik_stages_authenticator_totp_totpdevice;
postgresql-1  | 2024-02-03T05:52:23.437299011Z  ALTER SEQUENCE otp_totp_totpdevice_id_seq RENAME TO authentik_stages_authenticator_totp_totpdevice_id_seq;
postgresql-1  | 2024-02-03T05:52:23.437301051Z  COMMIT;
postgresql-1  | 2024-02-03T05:52:23.437302881Z
postgresql-1  | 2024-02-03T05:52:23.439418878Z 2024-02-03 05:52:23.439 UTC [128] ERROR:  current transaction is aborted, commands ignored until end of transaction block
postgresql-1  | 2024-02-03T05:52:23.439428538Z 2024-02-03 05:52:23.439 UTC [128] STATEMENT:  SELECT pg_advisory_unlock($1)
server-1      | 2024-02-03T05:52:23.439845463Z Traceback (most recent call last):
server-1      | 2024-02-03T05:52:23.439980125Z   File "/lifecycle/migrate.py", line 98, in <module>
server-1      | 2024-02-03T05:52:23.440226898Z     migration.run()
server-1      | 2024-02-03T05:52:23.440388050Z   File "/lifecycle/system_migrations/otp_merge.py", line 37, in run
server-1      | 2024-02-03T05:52:23.440604342Z     self.cur.execute(SQL_STATEMENT)
server-1      | 2024-02-03T05:52:23.440766424Z   File "/ak-root/venv/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
server-1      | 2024-02-03T05:52:23.441075329Z     raise ex.with_traceback(None)
server-1      | 2024-02-03T05:52:23.441336902Z psycopg.errors.DuplicateTable: relation "authentik_stages_authenticator_static_staticdevice" already exists
server-1      | 2024-02-03T05:52:23.441465184Z
server-1      | 2024-02-03T05:52:23.441595706Z During handling of the above exception, another exception occurred:
server-1      | 2024-02-03T05:52:23.441722967Z
server-1      | 2024-02-03T05:52:23.441864949Z Traceback (most recent call last):
server-1      | 2024-02-03T05:52:23.441984920Z   File "<frozen runpy>", line 198, in _run_module_as_main
server-1      | 2024-02-03T05:52:23.442124352Z   File "<frozen runpy>", line 88, in _run_code
server-1      | 2024-02-03T05:52:23.442262594Z   File "/lifecycle/migrate.py", line 114, in <module>
server-1      | 2024-02-03T05:52:23.442569667Z     release_lock(curr)
server-1      | 2024-02-03T05:52:23.442739769Z   File "/lifecycle/migrate.py", line 67, in release_lock
server-1      | 2024-02-03T05:52:23.442985523Z     cursor.execute("SELECT pg_advisory_unlock(%s)", (ADV_LOCK_UID,))
server-1      | 2024-02-03T05:52:23.443164136Z   File "/ak-root/venv/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
server-1      | 2024-02-03T05:52:23.443502160Z     raise ex.with_traceback(None)
server-1      | 2024-02-03T05:52:23.443766643Z psycopg.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block
```

**Comment by roney492** [comment]
Hi @aheath70,
Your issue looks to be due to resource limations, kindly check if the container is contending for resources with other containers on the same host. High CPU or memory usage by other containers may affect the stability of your application and cause such as issue.

**Comment by roney492** [comment]
Hi @gmpreussner,

It appears that there migration issue causing the error (`DuplicateTable: relation "authentik_stages_authenticator_static_staticdevice" already exists`) which might be due to migration history inconsistencies.

If you've migrated back and forth between versions, unreverted changes from a newer version might conflict with those from an older version, leading to the error.
```
UPDATE django_migrations SET app = 'authentik_stages_authenticator_static', name = '0008_initial' WHERE app = 'otp_static' AND name = '0001_initial';
UPDATE django_migrations SET app = 'authentik_stages_authenticator_static', name = '0009_throttling' WHERE app = 'otp_static' AND name = '0002_throttling';
```
These statements should align the migration history with the correct versions and address the conflict.

**Comment by gmpreussner** [comment]
@roney492 I've had no migration history. Like I stated in my post, I installed a vanilla deployment of an earlier version a few weeks ago (I think late November or early December). The only change to that instance was that I ran the initial admin setup to add an email address and password for the admin. I have not made any changes to this instance, and it was never in use for anything.

I then attempted to upgrade that vanilla instance yesterday to 2023.10.7, which is where I got the errors.

I have since completely removed and reinstalled Authentik, which worked fine. Since I did not have any configuration/customization previously, there was no data loss.

**Comment by aheath70** [comment]
> Hi @aheath70, Your issue looks to be due to resource limations, kindly check if the container is contending for resources with other containers on the same host. High CPU or memory usage by other containers may affect the stability of your application and cause such as issue.

Thanks @roney492 

I am fairly confident that if it is caused by any resource contention it is within Authentik itself. With the Authentik container not running, CPU usage on the machine hover around 0.64%, memory is ~15% (600MB of 4GB) and swap is under 10%. When I start Authentik, CPU spikes up to around 95% and then fluctuates between approximately 75% and 90% and continues to do this until I stop the container, when the CPU drops back to < 1%. Memory uasge also goes up whilst it is running, but ony to abour 1.36GB.

**Comment by roney492** [comment]
> > Hi @aheath70, Your issue looks to be due to resource limations, kindly check if the container is contending for resources with other containers on the same host. High CPU or memory usage by other containers may affect the stability of your application and cause such as issue.
> 
> Thanks @roney492
> 
> I am fairly confident that if it is caused by any resource contention it is within Authentik itself. With the Authentik container not running, CPU usage on the machine hover around 0.64%, memory is ~15% (600MB of 4GB) and swap is under 10%. When I start Authentik, CPU spikes up to around 95% and then fluctuates between approximately 75% and 90% and continues to do this until I stop the container, when the CPU drops back to < 1%. Memory uasge also goes up whilst it is running, but ony to abour 1.36GB.

Hmm, 
Could you please share logs so we can narrow down the stage during which it utilizes so much CPU.

**Comment by aheath70** [comment]
Full Docker log of container startup attached.
[_authentik-server_logs (1).txt](https://github.com/goauthentik/authentik/files/14156139/_authentik-server_logs.1.txt)

**Comment by roney492** [comment]
Hi @aheath70,
Am unable to see nor replicate this issue from my side using any of my current deployments,
As a temporary fix for the dereferencing issue could you please add the below inside  ./authentik/internal/outpost/proxyv2/refresh.go
```
func (ps *ProxyServer) Refresh() error {
	// Ensure ps.akAPI is not nil before making the API call
	if ps.akAPI == nil {
		return fmt.Errorf("akAPI is nil")
	}
```
Then add the file using volume mounts in your docker-compose:
      - ./authentik/internal/outpost/proxyv2/refresh.go:/authentik/internal/outpost/proxyv2/refresh.go

**Comment by aheath70** [comment]
Done, and looks like a very similar results. Error in logs looks the same, high CPU until I stop the authentik server container.
[Uploading _authentik-server_logs (3).txt…]()
