### ISSUE TITLE
General system exception in logs (stacktrace)

### ISSUE THREAD

**Issue by curtishall** [goauthentik/authentik#8403]
<details>

Appears to be non-fatal, I did not see this error and only saw it in the logs.

    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
  File "/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py", line 569, in trace_task
    task_after_return(
  File "/authentik/events/system_tasks.py", line 69, in after_return
    DBSystemTask.objects.update_or_create(
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/query.py", line 984, in update_or_create
    obj, created = self.select_for_update().get_or_create(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/query.py", line 946, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.MultipleObjectsReturned(
authentik.events.models.MultipleObjectsReturned: get() returned more than one SystemTask -- it returned 2!
```
</details>

**Version and Deployment (please complete the following information):**
- authentik version: 2023.10.7
- Deployment: [docker-compose]

**Comment by Fymyte** [comment]
@curtishall I had the same issue but managed to fixed it.
maybe check #9253
