### ISSUE TITLE
Python error when running test_email

### ISSUE THREAD

**Issue by andymarden** [goauthentik/authentik#8465]
Trying to get email setup. Running `docker exec worker ak test_email email@address.com`.

(Note that the guidance page [here](https://goauthentik.io/docs/troubleshooting/emails) incorrectly says to run `docker compose exec worker ak test_email [...]`

Was getting a bug in 2023.10.05: 
```
No module named 'authentik.stages.authenticator.urls'
```
So upgraded to 2023.10.7 and that error has gone, but I get the following dump - is this a bug in the code?:
```
{"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 260, "task_id": "8b376bae0416469f8e8b4259bdbc2320", "task_name": "authentik.blu
eprints.v1.tasks.clear_failed_blueprints", "timestamp": "2024-02-09T07:59:53.074894"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/smtplib.py", line 398, in getreply
    line = self.file.readline(_MAXLINE + 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/email/management/commands/test_email.py", line 36, in handle
    send_mail(message.__dict__, stage.pk)
  File "/ak-root/venv/lib/python3.11/site-packages/celery/local.py", line 182, in __call__
    return self._get_current_object()(*a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/celery/app/task.py", line 411, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/celery/app/autoretry.py", line 60, in run
    ret = task.retry(exc=exc, **retry_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/celery/app/task.py", line 720, in retry
    raise_with_context(exc or Retry('Task can be retried', None))
  File "/ak-root/venv/lib/python3.11/site-packages/celery/app/autoretry.py", line 38, in run
    return task._orig_run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/email/tasks.py", line 108, in send_mail
    raise exc
  File "/authentik/stages/email/tasks.py", line 74, in send_mail
    backend.open()
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 85, in open
    self.connection = self.connection_class(
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/smtplib.py", line 343, in connect
    (code, msg) = self.getreply()
                  ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/smtplib.py", line 401, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed: "
smtplib.SMTPServerDisconnected: Connection unexpectedly closed: timed out
Sentry is attempting to send 1 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit
```

**Comment by rissson** [comment]
> TimeoutError: timed out

This probably means that the worker cannot connect to the configured SMTP server.

**Comment by andymarden** [comment]
Thanks - I will check that - not exactly a "handled error" is it? Even if that is the case it should handle it a lot better than that

**Comment by andymarden** [comment]
That was indeed it - I used port 465 instead of 587 - Authentik silently seems to fail when this is wrong and this test_email could be a little more explicit about the issue. Still - sorted now. Cheers.

**Comment by andymarden** [comment]
Closed? Maybe better error messages?

**Comment by rissson** [comment]
I mean, the error is pretty clear that the connection with the SMTP server isn't working

**Comment by andymarden** [comment]
Yes - let's just have every error unhandled cos it provide the most information. Really?

There should always be an application-level error eg "cannot connection to SMTP server" followed by the error stack.
