### ISSUE TITLE
Email recovery link not working

### ISSUE THREAD

**Issue by roney492** [goauthentik/authentik#8507]
1. Go to 'Directory -> Users'
2. Select any User
3. Click on Email recovery link,
4. Select any email recovery stage
5. Click Send

**Expected behavior**
Email should have gotten send

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/116948023/0b39b6c6-894d-484f-85cd-0618ea9b0829)

**Version and Deployment :**
-   authentik version: 2023.10.7
-   Deployment: docker-compose

**Comment by roney492** [comment]
Setting default Recovery Flow in Tenant Settings fixed the issue

**Comment by LucaTheHacker** [comment]
To have an easier solution for the future users:

1. Navigate to System > Brands (in Sidebar)
2. Edit "authentik-default" (Actions column) (or the brand you want to edit)
3. Open "Default flows" section
4. Set "Recovery flow" to your recovery flow (default: default-recovery-flow)
5. Save using "update".

**Comment by rickyelopez** [comment]
I am having the same problem on 2024.12.3 in Docker but unfortunately setting the "Recovery Flow" option did not help in my case. Running `ak test_email <address>` command yielded the following error, however, testing the `default-email-transport` from the `Notification Transports` page _does_ work...

<details>
  <summary>Error from running `ak test_email`</summary>

  ```python
  Traceback (most recent call last):
    File "<frozen runpy>", line 198, in _run_module_as_main
    File "<frozen runpy>", line 88, in _run_code
    File "/manage.py", line 52, in <module>
      execute_from_command_line(sys.argv)
    File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
      utility.execute()
    File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
      self.fetch_command(subcommand).run_from_argv(self.argv)
    File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
      self.execute(*args, **cmd_options)
    File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
      output = self.handle(*args, **options)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/authentik/tenants/management/__init__.py", line 38, in handle
      self.handle_per_tenant(*args, **options)
    File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/base.py", line 107, in wrapper
      res = handle_func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/authentik/stages/email/management/commands/test_email.py", line 38, in handle_per_tenant
      send_mail(message.__dict__, stage.pk)
    File "/ak-root/venv/lib/python3.12/site-packages/celery/local.py", line 182, in __call__
      return self._get_current_object()(*a, **kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/ak-root/venv/lib/python3.12/site-packages/celery/app/task.py", line 411, in __call__
      return self.run(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/ak-root/venv/lib/python3.12/site-packages/celery/app/autoretry.py", line 60, in run
      ret = task.retry(exc=exc, **retry_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/ak-root/venv/lib/python3.12/site-packages/celery/app/task.py", line 720, in retry
      raise_with_context(exc or Retry('Task can be retried', None))
    File "/ak-root/venv/lib/python3.12/site-packages/celery/app/autoretry.py", line 38, in run
      return task._orig_run(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/authentik/stages/email/tasks.py", line 105, in send_mail
      raise exc
    File "/authentik/stages/email/tasks.py", line 73, in send_mail
      backend.open()
    File "/ak-root/venv/lib/python3.12/site-packages/django/core/mail/backends/smtp.py", line 86, in open
      self.connection = self.connection_class(
                        ^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
      (code, msg) = self.connect(host, port)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
      self.sock = self._get_socket(host, port, self.timeout)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
      return socket.create_connection((host, port), timeout,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/ak-root/venv/lib/python3.12/site-packages/sentry_sdk/integrations/socket.py", line 65, in create_connection
      return real_create_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/socket.py", line 841, in create_connection
      for res in getaddrinfo(host, port, 0, SOCK_STREAM):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/ak-root/venv/lib/python3.12/site-packages/sentry_sdk/integrations/socket.py", line 90, in getaddrinfo
      return real_getaddrinfo(host, port, family, type, proto, flags)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/socket.py", line 976, in getaddrinfo
      for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
</details>



Any suggestions? Any other logs I can provide or tests I can run that might help?

**Comment by adegoodyer** [comment]
> To have an easier solution for the future users:
> 
> 1. Navigate to System > Brands (in Sidebar)
> 2. Edit "authentik-default" (Actions column) (or the brand you want to edit)
> 3. Open "Default flows" section
> 4. Set "Recovery flow" to your recovery flow (default: default-recovery-flow)
> 5. Save using "update".

Why this isn't enabled as the default I've no idea.

**Comment by kapuett** [comment]
> > To have an easier solution for the future users:
> > 
> > 1. Navigate to System > Brands (in Sidebar)
> > 2. Edit "authentik-default" (Actions column) (or the brand you want to edit)
> > 3. Open "Default flows" section
> > 4. Set "Recovery flow" to your recovery flow (default: default-recovery-flow)
> > 5. Save using "update".
> 
> Why this isn't enabled as the default I've no idea.

Also it should be in the docs that a default needs to be set. Took me an hour to figure this out/find this thread...

**Comment by dewi-tik** [comment]
> > > To have an easier solution for the future users:
> > > 
> > > 1. Navigate to System > Brands (in Sidebar)
> > > 2. Edit "authentik-default" (Actions column) (or the brand you want to edit)
> > > 3. Open "Default flows" section
> > > 4. Set "Recovery flow" to your recovery flow (default: default-recovery-flow)
> > > 5. Save using "update".
> > 
> > 
> > Why this isn't enabled as the default I've no idea.
> 
> Also it should be in the docs that a default needs to be set. Took me an hour to figure this out/find this thread...

It was mentioned in the docs but I've created a PR to make this clearer. We'll also investigate the possibility of adding the recovery flow as a default.
