### ISSUE TITLE
Weblate example broken

### ISSUE THREAD

**Issue by DenuxPlays** [goauthentik/authentik#8650]
I've tried to implement authentik in weblate using your [guide](https://goauthentik.io/integrations/services/weblate/).
Sadly it is broken.
I've done everything twice to ensure that I didn't mess anything up.
But with the newest version of weblate and authentik I get and Internal Server Errro back:
![image](https://github.com/goauthentik/authentik/assets/83671398/176ca81e-d297-46b7-955d-e47a754ef4aa)

This is the exeception from weblate:
```
weblate-1   | nginx stdout | 127.0.0.1 - - [22/Feb/2024:13:56:07 +0100] "GET /healthz/ HTTP/1.1" 200 12 "-" "curl/7.88.1"
weblate-1   | gunicorn stderr | [2024-02-22 13:56:17,909: WARNING/382] Handled exception: AuthMissingParameter: Missing needed parameter RelayState
weblate-1   | gunicorn stderr | [2024-02-22 13:56:17,984: ERROR/382] Internal Server Error: /accounts/complete/saml/
weblate-1   | gunicorn stderr | Traceback (most recent call last):
weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/django/utils/datastructures.py", line 84, in __getitem__
weblate-1   | gunicorn stderr |     list_ = super().__getitem__(key)
weblate-1   | gunicorn stderr |             ^^^^^^^^^^^^^^^^^^^^^^^^
weblate-1   | gunicorn stderr | KeyError: 'RelayState'
weblate-1   | gunicorn stderr | 
weblate-1   | gunicorn stderr | During handling of the above exception, another exception occurred:
weblate-1   | gunicorn stderr | 
weblate-1   | gunicorn stderr | Traceback (most recent call last):
weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/social_core/backends/saml.py", line 313, in auth_complete
weblate-1   | gunicorn stderr |     relay_state_str = self.strategy.request_data()["RelayState"]
weblate-1   | gunicorn stderr |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/django/utils/datastructures.py", line 86, in __getitem__
weblate-1   | gunicorn stderr |     raise MultiValueDictKeyError(key)
weblate-1   | gunicorn stderr | django.utils.datastructures.MultiValueDictKeyError: 'RelayState'
weblate-1   | gunicorn stderr | 
weblate-1   | gunicorn stderr | During handling of the above exception, another exception occurred:
weblate-1   | gunicorn stderr | 
weblate-1   | gunicorn stderr | Traceback (most recent call last):
weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
weblate-1   | gunicorn stderr |     response = get_response(request)
weblate-1   | gunicorn stderr |                ^^^^^^^^^^^^^^^^^^^^^
weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
weblate-1   | gunicorn stderr |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
weblate-1   | gunicorn stderr |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
weblate-1   | gunicorn stderr |     return view_func(*args, **kwargs)
weblate-1   | gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
weblate-1   | gunicorn stderr |     response = view_func(request, *args, **kwargs)
weblate-1   | gunicorn stderr |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/accounts/views.py", line 1287, in social_complete
weblate-1   | gunicorn stderr |     return complete(request, backend)
weblate-1   | gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
weblate-1   | gunicorn stderr |     response = view_func(request, *args, **kwargs)
weblate-1   | gunicorn stderr |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
weblate-1   | gunicorn stderr |     return view_func(*args, **kwargs)
weblate-1   | gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/social_django/utils.py", line 49, in wrapper
weblate-1   | gunicorn stderr |     return func(request, backend, *args, **kwargs)
weblate-1   | gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/social_django/views.py", line 31, in complete
weblate-1   | gunicorn stderr |     return do_complete(
weblate-1   | gunicorn stderr |            ^^^^^^^^^^^^
weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/social_core/actions.py", line 49, in do_complete
weblate-1   | gunicorn stderr |     user = backend.complete(user=user, redirect_name=redirect_name, *args, **kwargs)
weblate-1   | gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/social_core/backends/base.py", line 39, in complete
weblate-1   | gunicorn stderr |     return self.auth_complete(*args, **kwargs)
weblate-1   | gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/social_core/backends/saml.py", line 315, in auth_complete
weblate-1   | gunicorn stderr |     raise AuthMissingParameter(self, "RelayState")
weblate-1   | gunicorn stderr | social_core.exceptions.AuthMissingParameter: Missing needed parameter RelayState
weblate-1   | nginx stdout | 162.158.202.37 - - [22/Feb/2024:13:56:18 +0100] "POST /accounts/complete/saml/ HTTP/1.1" 500 10001 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0"
``

As I do not have any knowledge with SSO or SAML i am kinda helpless on what to do.

**Comment by rissson** [comment]
@ilijamt initially contributed this documentation in https://github.com/goauthentik/authentik/pull/2786. Maybe they'll have more insight into this.
