### ISSUE TITLE
Federate Authentik to LDAP from Authentik

### ISSUE THREAD

**Issue by los93sol** [goauthentik/authentik#9009]
I'm attempting to setup federation to LDAP provided by another instance of Authentik's LDAP outpost.  I can get the users to sync, but the groups will not sync.  I get errors like the following in the worker when it tries to sync groups.  Anyone configured it this way before?  

2024-03-22 23:04:38 {"event": "Task authentik.sources.ldap.tasks.ldap_sync_single[88751aaf-c285-4030-825e-1c81bd85371c] raised unexpected: LDAPAttributeError('invalid attribute type distinguishedName')", "exception": [{"exc_type": "LDAPAttributeError", "exc_value": "invalid attribute type distinguishedName", "frames": [{"filename": "/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py", "line": "", "lineno": 477, "locals": {}, "name": "trace_task"}, {"filename": "/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py", "line": "", "lineno": 760, "locals": {}, "name": "__protected_call__"}, {"filename": "/authentik/sources/ldap/tasks.py", "line": "", "lineno": 83, "locals": {}, "name": "ldap_sync_single"}, {"filename": "/authentik/sources/ldap/tasks.py", "line": "", "lineno": 97, "locals": {}, "name": "ldap_sync_paginator"}, {"filename": "/authentik/sources/ldap/sync/base.py", "line": "", "lineno": 112, "locals": {}, "name": "search_paginator"}, {"filename": "/ak-root/venv/lib/python3.12/site-packages/ldap3/core/connection.py", "line": "", "lineno": 836, "locals": {}, "name": "search"}], "is_cause": false, "syntax_error": null}], "level": "error", "logger": "celery.app.trace", "timestamp": 1711163078.3946087}

**Comment by pascal260303** [comment]
I'm currently trying the same thing but I can't even sync the users and get the same error.\
I tested it with the command: `docker compose run --rm worker ldap_sync authentik-ldap`\
And got the error:
```python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/manage.py", line 52, in <module>
    execute_from_command_line(sys.argv)
  File "/ak-root/.venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/ak-root/.venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/ak-root/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/ak-root/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/tenants/management/__init__.py", line 38, in handle
    self.handle_per_tenant(*args, **options)
  File "/authentik/sources/ldap/management/commands/ldap_sync.py", line 30, in handle_per_tenant
    + ldap_sync_paginator(source, MembershipLDAPSynchronizer)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/sources/ldap/tasks.py", line 90, in ldap_sync_paginator
    for page in sync_inst.get_objects():
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/sources/ldap/sync/base.py", line 100, in search_paginator
    self._connection.search(
  File "/ak-root/.venv/lib/python3.12/site-packages/ldap3/core/connection.py", line 836, in search
    raise LDAPAttributeError(self.last_error)
ldap3.core.exceptions.LDAPAttributeError: invalid attribute type distinguishedName
```

**Comment by pascal260303** [comment]
Ok when I disable group synchronizing I can at least sync the users, so I think I have the exact same issue as you.\
But I have no solution so far.

**Comment by SpiGAndromeda** [comment]
I am experiencing the same problem. I digged a bit into the code (not a python developer and not an LDAP expert).

This line might be the problem: https://github.com/goauthentik/authentik/blob/3dbecdbd3012e88fb41651758657fc19c9c1ecec/authentik/sources/ldap/sync/membership.py#L35

It fetches `distinguishedName` as an attribute from LDAP but it seems not every LDAP instance supports this. The one I want to use only supports `dn`. It doesnt seem to be configurable in Authentik though. So maybe the LDAP source could be changed to allow a different `distinguishedName`/`dn` can be used for member fetching.

The problem itself comes from the LDAP3 package. It checks the server schema if it contains the requested attribute. The package defines several excludes for the check but `distinguishedName` is not amongst them.
