### ISSUE TITLE
General system exception in logs (stacktrace)

### ISSUE THREAD

**Issue by Fymyte** [goauthentik/authentik#9253]
**Describe the bug**
General system exception appears in logs.

I am being spammed by `General system exception` line in logs.

I have seen the issue #8403 but there were not any comment on it.

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/34305318/8cb167e1-68f1-4f87-8326-8d382b376c49)

Further collapsed lines are identical to the first 2 detailed error messages.

In `System  Tasks`, I have multiple tasks with the same ids, so I suspect the error comes from here, though I don't have a clue on how this happend.

![image](https://github.com/goauthentik/authentik/assets/34305318/2c90e2bb-54fc-4b5d-9968-6f64eaf0658b)

**Logs**
<details>
    <summary>Stacktrace from authentik</summary>

```
Context
{
    "message": "Traceback (most recent call last):\nauthentik.events.models.MultipleObjectsReturned: get() returned more than one SystemTask -- it returned 2!"
}
User
{}
```

```
Traceback (most recent call last):
  File "/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py", line 569, in trace_task
    task_after_return(
  File "/authentik/events/system_tasks.py", line 81, in after_return
    DBSystemTask.objects.update_or_create(
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/query.py", line 986, in update_or_create
    obj, created = self.select_for_update().get_or_create(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/query.py", line 948, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/query.py", line 652, in get
    raise self.model.MultipleObjectsReturned(
authentik.events.models.MultipleObjectsReturned: get() returned more than one SystemTask -- it returned 2!
```

</details>

<details> <summary>Docker compose related logs</summary>

```
authentik-worker  | {"domain_url": null, "event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 584583, "schema_name": "public", "task_id": "8e14ea93845f426f96a5f52e54b5ec25", "task_name": "authentik.events.tasks.event_notification_handler", "timestamp": "2024-04-14T10:44:27.018867"}
authentik-worker  | {"event": "/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py:686: RuntimeWarning: Exception raised outside body: MultipleObjectsReturned('get() returned more than one SystemTask -- it returned 2!'):\nTraceback (most recent call last):\n  File \"/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py\", line 569, in trace_task\n    task_after_return(\n  File \"/authentik/events/system_tasks.py\", line 81, in after_return\n    DBSystemTask.objects.update_or_create(\n  File \"/ak-root/venv/lib/python3.12/site-packages/django/db/models/manager.py\", line 87, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/ak-root/venv/lib/python3.12/site-packages/django/db/models/query.py\", line 986, in update_or_create\n    obj, created = self.select_for_update().get_or_create(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/ak-root/venv/lib/python3.12/site-packages/django/db/models/query.py\", line 948, in get_or_create\n    return self.get(**kwargs), False\n           ^^^^^^^^^^^^^^^^^^\n  File \"/ak-root/venv/lib/python3.12/site-packages/django/db/models/query.py\", line 652, in get\n    raise self.model.MultipleObjectsReturned(\nauthentik.events.models.SystemTask.MultipleObjectsReturned: get() returned more than one SystemTask -- it returned 2!\n\n  warn(RuntimeWarning(\n", "level": "warning", "logger": "py.warnings", "timestamp": 1713091467.0211232}
authentik-worker  | {"domain_url": null, "event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 7, "schema_name": "public", "task_id": "08282bdd4dd8457ea0e14e2fc21fc626", "task_name": "authentik.events.tasks.event_notification_handler", "timestamp": "2024-04-14T10:44:27.055020"}
authentik-worker  | {"event": "Task handler raised error: MultipleObjectsReturned('get() returned more than one SystemTask -- it returned 3!')", "exception": [{"exc_type": "MultipleObjectsReturned", "exc_value": "get() returned more than one SystemTask -- it returned 3!", "frames": [{"filename": "/ak-root/venv/lib/python3.12/site-packages/billiard/pool.py", "line": "", "lineno": 361, "locals": {}, "name": "workloop"}, {"filename": "/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py", "line": "", "lineno": 675, "locals": {}, "name": "fast_trace_task"}, {"filename": "/ak-root/venv/lib/python3.12/site-packages/sentry_sdk/integrations/celery.py", "line": "", "lineno": 283, "locals": {}, "name": "_inner"}, {"filename": "/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py", "line": "", "lineno": 598, "locals": {}, "name": "trace_task"}, {"filename": "/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py", "line": "", "lineno": 399, "locals": {}, "name": "on_error"}, {"filename": "/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py", "line": "", "lineno": 178, "locals": {}, "name": "handle_error_state"}, {"filename": "/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py", "line": "", "lineno": 236, "locals": {}, "name": "handle_failure"}, {"filename": "/authentik/events/system_tasks.py", "line": "", "lineno": 106, "locals": {}, "name": "on_failure"}, {"filename": "/ak-root/venv/lib/python3.12/site-packages/django/db/models/manager.py", "line": "", "lineno": 87, "locals": {}, "name": "manager_method"}, {"filename": "/ak-root/venv/lib/python3.12/site-packages/django/db/models/query.py", "line": "", "lineno": 986, "locals": {}, "name": "update_or_create"}, {"filename": "/ak-root/venv/lib/python3.12/site-packages/django/db/models/query.py", "line": "", "lineno": 948, "locals": {}, "name": "get_or_create"}, {"filename": "/ak-root/venv/lib/python3.12/site-packages/django/db/models/query.py", "line": "", "lineno": 652, "locals": {}, "name": "get"}], "is_cause": false, "syntax_error": null}], "level": "error", "logger": "celery.worker.request", "timestamp": 1713091467.055731}
authentik-worker  | {"domain_url": null, "event": "Task failure", "exc": "MultipleObjectsReturned('get() returned more than one SystemTask -- it returned 2!')", "level": "warning", "logger": "authentik.root.celery", "pid": 7, "schema_name": "public", "timestamp": "2024-04-14T10:44:27.070741"}
authentik-worker  | {"action": "system_exception", "client_ip": null, "context": {"message": "Traceback (most recent call last):\nauthentik.events.models.MultipleObjectsReturned: get() returned more than one SystemTask -- it returned 2!"}, "domain_url": null, "event": "Created Event", "level": "info", "logger": "authentik.events.models", "pid": 7, "schema_name": "public", "timestamp": "2024-04-14T10:44:27.073710", "user": {}}
authentik-worker  | {"domain_url": null, "event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 7, "schema_name": "public", "task_id": "3f425390e7da4c5cbc75b1e2f976cc19", "task_name": "authentik.events.tasks.event_notification_handler", "timestamp": "2024-04-14T10:44:27.118727"}
authentik-worker  | {"event": "Task handler raised error: MultipleObjectsReturned('get() returned more than one SystemTask -- it returned 2!')", "exception": [{"exc_type": "MultipleObjectsReturned", "exc_value": "get() returned more than one SystemTask -- it returned 2!", "frames": [{"filename": "/ak-root/venv/lib/python3.12/site-packages/billiard/pool.py", "line": "", "lineno": 361, "locals": {}, "name": "workloop"}, {"filename": "/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py", "line": "", "lineno": 675, "locals": {}, "name": "fast_trace_task"}, {"filename": "/ak-root/venv/lib/python3.12/site-packages/sentry_sdk/integrations/celery.py", "line": "", "lineno": 283, "locals": {}, "name": "_inner"}, {"filename": "/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py", "line": "", "lineno": 598, "locals": {}, "name": "trace_task"}, {"filename": "/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py", "line": "", "lineno": 399, "locals": {}, "name": "on_error"}, {"filename": "/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py", "line": "", "lineno": 178, "locals": {}, "name": "handle_error_state"}, {"filename": "/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py", "line": "", "lineno": 236, "locals": {}, "name": "handle_failure"}, {"filename": "/authentik/events/system_tasks.py", "line": "", "lineno": 106, "locals": {}, "name": "on_failure"}, {"filename": "/ak-root/venv/lib/python3.12/site-packages/django/db/models/manager.py", "line": "", "lineno": 87, "locals": {}, "name": "manager_method"}, {"filename": "/ak-root/venv/lib/python3.12/site-packages/django/db/models/query.py", "line": "", "lineno": 986, "locals": {}, "name": "update_or_create"}, {"filename": "/ak-root/venv/lib/python3.12/site-packages/django/db/models/query.py", "line": "", "lineno": 948, "locals": {}, "name": "get_or_create"}, {"filename": "/ak-root/venv/lib/python3.12/site-packages/django/db/models/query.py", "line": "", "lineno": 652, "locals": {}, "name": "get"}], "is_cause": false, "syntax_error": null}], "level": "error", "logger": "celery.worker.request", "timestamp": 1713091467.1193306}
```

</details>

**Version and Deployment:**

- authentik version: 2024.2.2
-  Deployment: docker-compose

**Additional context**
Running with a pg db 16, not 12 as in the installation instructions in the doc. Don't know if this could introduce these kinds of errors.
I have created a dedicated `authentik` database and user, with all right to this database to the user

**Comment by Fymyte** [comment]
Maybe deleting the corresponding entries in the db would be enough but I don't know in which tables this is happening

**Comment by Fymyte** [comment]
Well, guess I figured. For anyone having this issue

Login to the db with your authentik user and database

 Check the output of
```sql
select * from authentik_events_systemtask
```
Output
```markdown
            expires            | expiring |                 uuid                 |                name                | uid |   status   |                             description                              |            messages            |          task_call_module           |           task_call_func           | task_call_args | task_call_kwargs |     duration      |       finish_timestamp        |        start_timestamp        
-------------------------------+----------+--------------------------------------+------------------------------------+-----+------------+----------------------------------------------------------------------+--------------------------------+-------------------------------------+------------------------------------+----------------+------------------+-------------------+-------------------------------+-------------------------------
 2024-03-24 16:12:57.429279+00 | f        | fef7904b-a5aa-4ef0-92a8-2e83fe1f2efa | update_latest_version              |     | unknown    | Update latest version info                                           | ["Task has not been run yet."] | authentik.admin.tasks               | update_latest_version              | []             | {}               |                 0 | 2024-03-24 15:42:57.429155+00 | 2024-03-24 15:42:57.429149+00
 2024-03-24 16:12:57.306+00    | f        | 64727bfe-3745-4fd3-8d12-85a90a8d1b8c | update_latest_version              |     | unknown    | Update latest version info                                           | ["Task has not been run yet."] | authentik.admin.tasks               | update_latest_version              | []             | {}               |                 0 | 2024-03-24 15:42:57.305871+00 | 2024-03-24 15:42:57.305864+00
 2024-03-24 16:12:57.454975+00 | f        | a47d0248-0061-483a-8697-5f1d473e7907 | certificate_discovery              |     | unknown    | Discover, import and update certificates from the filesystem         | ["Task has not been run yet."] | authentik.crypto.tasks              | certificate_discovery              | []             | {}               |     s_celery.scheduler", "timestamp": 1713005040.0054283}
            0 | 2024-03-24 15:42:57.454902+00 | 2024-03-24 15:42:57.454899+00
 2024-03-24 16:12:57.341966+00 | f        | 70b3bd61-ca1d-4f0c-a48a-db82c920bbe4 | certificate_discovery              |     | unknown    | Discover, import and update certificates from the filesystem         | ["Task has not been run yet."] | authentik.crypto.tasks              | certificate_discovery              | []             | {}               |                 0 | 2024-03-24 15:42:57.341848+00 | 2024-03-24 15:42:57.341842+00
 2024-03-24 16:12:58.39653+00  | f        | ec67add3-73f6-45b8-8e39-2f2a2994b278 | outpost_service_connection_monitor |     | unknown    | Regularly check the state of Outpost Service Connections             | ["Task has not been run yet."] | authentik.outposts.tasks            | outpost_service_connection_monitor | []             | {}               |                 0 | 2024-03-24 15:42:58.396431+00 | 2024-03-24 15:42:58.396425+00
 2024-03-24 16:12:58.416704+00 | f        | 7d09548d-9156-4aac-920a-687205fff321 | outpost_service_connection_monitor |     | unknown    | Regularly check the state of Outpost Service Connections             | ["Task has not been run yet."] | authentik.outposts.tasks            | outpost_service_connection_monitor | []             | {}               |                 0 | 2024-03-24 15:42:58.416605+00 | 2024-03-24 15:42:58.416602+00
 2024-03-24 16:12:58.396664+00 | f        | 686fa3c9-4dbc-4abe-8887-e9c7e29a2b79 | outpost_token_ensurer              |     | unknown    | Periodically ensure that all Outposts have valid Service Accounts   +| ["Task has not been run yet."] | authentik.outposts.tasks            | outpost_token_ensurer              | []             | {}               |                 0 | 2024-03-24 15:42:58.396617+00 | 2024-03-24 15:42:58.396614+00
                               |          |                                      |                                    |     |            |     and Tokens                                                       |                                |                                     |                                    |                |                  |                   |                               | 
```

Check that you have duplicate entries (matching `Description`, `task_call_module` and `task_call_func`)

Delete the duplicates.

:warning: not tested in every scenario, may break.
```sql
delete from authentik_events_systemtask a
using authentik_events_systemtask b
where
a.uid < b.uid and a.task_call_module = b.task_call_module and a.task_call_func = b.task_call_func and a.task_call_args = b.task_call_args and
a.task_call_kwargs = b.task_call_kwargs;
```

**Comment by jaredcat** [comment]
I had to change `a.uid < b.uid` to `a.uuid < b.uuid` for the script to work

**Comment by flammable** [comment]
Thanks, @Fymyte! Your script (and @jaredcat's modification) allowed me to successfully update to 2024.6 (and PostgreSQL 16).

**Comment by azapater** [comment]
thanks! this was driving me mad!
