### ISSUE TITLE
Can't login with Apple OAuth after update to 2024.4.0

### ISSUE THREAD

**Issue by dlhall111** [goauthentik/authentik#9402]
**Describe the bug**
After updating to 2024.4.0 there is no login fields shown as the page immediately renders to the "Something went wrong! Please try again later." error message.

**To Reproduce**
1. Have Apple OAuth source enabled in default-authentication-identification
2. Go to URL (local or via reverse proxy address) for Authentik site
3. See error
4. Disable Apple OAuth source in default-authentication-identification
5. Error is gone (Google OAuth remains enabled and works)

**Expected behavior**
To see the usual login screen for Authentik

**Screenshots**

**Logs**
<details>
    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
  File "/authentik/flows/views/executor.py", line 290, in get
    stage_response = self.current_stage_view.dispatch(request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/flows/stage.py", line 95, in get
    challenge = self._get_challenge(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/flows/stage.py", line 172, in _get_challenge
    challenge = self.get_challenge(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/identification/stage.py", line 243, in get_challenge
    source_challenge.is_valid()
  File "/ak-root/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 220, in is_valid
    assert hasattr(self, 'initial_data'), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
builtins.AssertionError: Cannot call `.is_valid()` as no `data=` keyword argument was passed when instantiating the serializer instance.
```
</details>

**Version and Deployment (please complete the following information):**
- authentik version: 2024.4.0
- Deployment: [docker-compose (MacOS Docker Desktop)]

**Additional context**

**Comment by dlhall111** [comment]
After disabling both Apple and Google OAuth sources I can now access the login page and successfully login with a built-in user.  So it seems I have something busted with the OAuth sources.  I did add the "offline_access" scope to both, so I'm not sure what I'm missing.
