### ISSUE TITLE
Failed to export blueprints

### ISSUE THREAD

**Issue by m00nyONE** [goauthentik/authentik#9430]
**Describe the bug**
authentik fails exporting blueprints

**To Reproduce**

run `ak export_blueprint` on a worker

**Expected behavior**

get blueprints

**Screenshots**

**Logs**
```
Switching to schema 'public'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/manage.py", line 46, in <module>
    execute_from_command_line(sys.argv)
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/tenants/management/__init__.py", line 38, in handle
    self.handle_per_tenant(*args, **options)
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/blueprints/management/commands/export_blueprint.py", line 19, in handle_per_tenant
    self.stdout.write(exporter.export_to_string())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/blueprints/v1/exporter.py", line 73, in export_to_string
    return dump(blueprint, Dumper=BlueprintDumper)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/yaml/__init__.py", line 253, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/yaml/__init__.py", line 241, in dump_all
    dumper.represent(data)
  File "/authentik/blueprints/v1/common.py", line 566, in represent
    data = asdict(data, dict_factory=factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dataclasses.py", line 1322, in asdict
    return _asdict_inner(obj, dict_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dataclasses.py", line 1338, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dataclasses.py", line 1366, in _asdict_inner
    return type(obj)(_asdict_inner(v, dict_factory) for v in obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dataclasses.py", line 1366, in <genexpr>
    return type(obj)(_asdict_inner(v, dict_factory) for v in obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dataclasses.py", line 1338, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dataclasses.py", line 1375, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dataclasses.py", line 1376, in <genexpr>
    _asdict_inner(v, dict_factory))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dataclasses.py", line 1375, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dataclasses.py", line 1376, in <genexpr>
    _asdict_inner(v, dict_factory))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dataclasses.py", line 1366, in _asdict_inner
    return type(obj)(_asdict_inner(v, dict_factory) for v in obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/rest_framework/utils/serializer_helpers.py", line 57, in __init__
    self.serializer = kwargs.pop('serializer')
                      ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'serializer'
```

**Version and Deployment:**

-   authentik version: 2024.4.0
-   Deployment: helm

**Comment by sherif-fanous** [comment]
Ditto

```console
authentik@authentik-worker-77d959b777-4pq9r:/$ ak export_blueprint
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1716555823.9567018, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1716555823.9573154, "count": 58}
{"event": "Starting authentik bootstrap", "level": "info", "logger": "authentik.lib.config", "timestamp": 1716555824.2237544}
{"event": "PostgreSQL connection successful", "level": "info", "logger": "authentik.lib.config", "timestamp": 1716555824.2426836}
{"event": "Redis Connection successful", "level": "info", "logger": "authentik.lib.config", "timestamp": 1716555824.2475262}
{"event": "Finished authentik bootstrap", "level": "info", "logger": "authentik.lib.config", "timestamp": 1716555824.2476652}
{"event": "Booting authentik", "level": "info", "logger": "authentik.lib.config", "timestamp": 1716555825.4792237, "version": "2024.4.2"}
{"event": "Enabled authentik enterprise", "level": "info", "logger": "authentik.lib.config", "timestamp": 1716555825.481191}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1716555825.4822297, "path": "authentik.enterprise.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1716555825.4834905, "path": "authentik.stages.authenticator_totp.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1716555825.4843266, "path": "authentik.sources.ldap.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1716555825.4878428, "path": "authentik.enterprise.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1716555825.4887524, "path": "authentik.blueprints.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1716555825.4896207, "path": "authentik.policies.reputation.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1716555825.4900823, "path": "authentik.sources.plex.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1716555825.4908414, "path": "authentik.providers.scim.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1716555825.4914482, "path": "authentik.outposts.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1716555825.4923337, "path": "authentik.sources.oauth.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1716555825.4928207, "path": "authentik.admin.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1716555825.4942803, "path": "authentik.events.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1716555825.4949172, "path": "authentik.crypto.settings"}
/ak-root/venv/lib/python3.12/site-packages/opencontainers/distribution/reggie/defaults.py:17: SyntaxWarning: invalid escape sequence '\('
  "http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+"
{"domain_url": null, "event": "Loaded MMDB database", "file": "/geoip/GeoLite2-ASN.mmdb", "last_write": 1715093837.0, "level": "info", "logger": "authentik.events.context_processors.mmdb", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:46.298984"}
{"domain_url": null, "event": "Loaded MMDB database", "file": "/geoip/GeoLite2-City.mmdb", "last_write": 1715093836.0, "level": "info", "logger": "authentik.events.context_processors.mmdb", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:46.300432"}
{"app_name": "authentik.tenants", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.tenants.checks", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.174511"}
{"app_name": "authentik.tenants", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.tenants.signals", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.175140"}
{"app_name": "authentik.admin", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.admin.tasks", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.223086"}
{"app_name": "authentik.admin", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.admin.signals", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.223704"}
{"app_name": "authentik.crypto", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.crypto.tasks", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.225208"}
{"app_name": "authentik.flows", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.flows.signals", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.265320"}
{"app_name": "authentik.outposts", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.outposts.tasks", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.301234"}
{"app_name": "authentik.outposts", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.outposts.signals", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.302270"}
{"app_name": "authentik.policies.reputation", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.policies.reputation.tasks", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.303257"}
{"app_name": "authentik.policies.reputation", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.policies.reputation.signals", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.304293"}
{"app_name": "authentik.policies", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.policies.signals", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.315894"}
{"app_name": "authentik.providers.proxy", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.providers.proxy.tasks", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.316665"}
{"app_name": "authentik.providers.proxy", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.providers.proxy.signals", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.317280"}
{"app_name": "authentik.providers.scim", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.providers.scim.tasks", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.555556"}
{"app_name": "authentik.providers.scim", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.providers.scim.signals", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.556467"}
{"app_name": "authentik.rbac", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.rbac.signals", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.557435"}
{"app_name": "authentik.sources.ldap", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.sources.ldap.tasks", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.565295"}
{"app_name": "authentik.sources.ldap", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.sources.ldap.signals", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.567536"}
/ak-root/venv/lib/python3.12/site-packages/facebook/__init__.py:99: SyntaxWarning: invalid escape sequence '\d'
  version_regex = re.compile("^\d\.\d{1,2}$")
{"app_name": "authentik.sources.oauth", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.sources.oauth.tasks", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.576958"}
{"app_name": "authentik.sources.saml", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.sources.saml.signals", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.577654"}
{"app_name": "authentik.sources.scim", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.sources.scim.signals", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.578422"}
{"app_name": "authentik.stages.authenticator_duo", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.stages.authenticator_duo.tasks", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.579151"}
{"app_name": "authentik.stages.authenticator_static", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.stages.authenticator_static.signals", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.579733"}
{"app_name": "authentik.stages.authenticator_webauthn", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.stages.authenticator_webauthn.tasks", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.620095"}
{"app_name": "authentik.stages.email", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.stages.email.tasks", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.620457"}
{"app_name": "authentik.core", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.core.tasks", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.622623"}
{"app_name": "authentik.core", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.core.signals", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.622764"}
{"app_name": "authentik.enterprise", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.enterprise.tasks", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.623287"}
{"app_name": "authentik.enterprise", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.enterprise.signals", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.623784"}
{"app_name": "authentik.enterprise.providers.rac", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.enterprise.providers.rac.signals", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.628787"}
{"app_name": "authentik.events", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.events.tasks", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.629136"}
{"app_name": "authentik.events", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.events.signals", "pid": 39961, "schema_name": "public", "timestamp": "2024-05-24T13:03:48.629249"}
Switching to schema 'public'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/manage.py", line 46, in <module>
    execute_from_command_line(sys.argv)
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/tenants/management/__init__.py", line 38, in handle
    self.handle_per_tenant(*args, **options)
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/blueprints/management/commands/export_blueprint.py", line 19, in handle_per_tenant
    self.stdout.write(exporter.export_to_string())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/blueprints/v1/exporter.py", line 73, in export_to_string
    return dump(blueprint, Dumper=BlueprintDumper)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/yaml/__init__.py", line 253, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/yaml/__init__.py", line 241, in dump_all
    dumper.represent(data)
  File "/authentik/blueprints/v1/common.py", line 566, in represent
    data = asdict(data, dict_factory=factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dataclasses.py", line 1322, in asdict
    return _asdict_inner(obj, dict_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dataclasses.py", line 1338, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dataclasses.py", line 1366, in _asdict_inner
    return type(obj)(_asdict_inner(v, dict_factory) for v in obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dataclasses.py", line 1366, in <genexpr>
    return type(obj)(_asdict_inner(v, dict_factory) for v in obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dataclasses.py", line 1338, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dataclasses.py", line 1375, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dataclasses.py", line 1376, in <genexpr>
    _asdict_inner(v, dict_factory))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dataclasses.py", line 1375, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dataclasses.py", line 1376, in <genexpr>
    _asdict_inner(v, dict_factory))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dataclasses.py", line 1366, in _asdict_inner
    return type(obj)(_asdict_inner(v, dict_factory) for v in obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/rest_framework/utils/serializer_helpers.py", line 57, in __init__
    self.serializer = kwargs.pop('serializer')
                      ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'serializer'
```

**Comment by JamesReynolds** [comment]
I also applied this patch just to 2024.4.2 and it fixed the issue for me.

**Comment by BeryJu** [comment]
Hmm I'm curious what authentik object causes this issue, since this discussion for a patch within DRF have been open since 2013 I would assume this would probably be cause by an authentik API schema change

**Comment by JamesReynolds** [comment]
@BeryJu I'll try a bisect on Monday if I've got time.

**Comment by sherif-fanous** [comment]
I have this issue on multiple deployments. Will happily share whatever is requested to help debug this issue.

**Comment by cfradewavecom** [comment]
I just bumped into the same error, using version 2024.4.2

**Comment by AsteroidOrangeJuice** [comment]
This is still a problem in 2024.6.0.

**Comment by TheAssassin** [comment]
This issue has _not_ been fixed, it should be reopened. Tested in [2024.12.3](https://goauthentik.io/docs/releases/2024.12), but none of the previous versions worked either.

**Comment by maykosiqueira** [comment]
This issue has not been fixed, I trying in version https://docs.goauthentik.io/docs/releases/2025.2 but has same error

**Comment by zmijunkie** [comment]
This issue can be reproduced without problem at my place by following the tutorial at https://docs.goauthentik.io/integrations/services/gitea/ ... but where exactly ?

**Comment by Disin** [comment]
2025.5 - same error

**Comment by dragonfleas** [comment]
Is there any workaround for this?

**Comment by IAMSolaara** [comment]
2025.6.4 and I still have this error aswell :/

**Comment by leopoldhub** [comment]
2025.6.4 too, same issue

**Comment by leopoldhub** [comment]
Ok, so while waiting for the issue to be resolved, I adapted #9930 to the latest release ([patch here](https://gist.github.com/leopoldhub/75e243b53d13d3e3ab4c11f552737aa9)).

You can patch your current worker with the following steps.

**⚠️ First of all, please make sure that you trust the above patch and understand the effects of the commands you execute.**

Then, use the followings commands to patch your worker:

```sh
AUTHENTIK_NAMESPACE=auth

kubectl -n "$AUTHENTIK_NAMESPACE" patch deployment authentik-worker --type=json -p '[{"op":"replace","path":"/spec/template/spec/containers/0/securityContext","value":{"runAsUser":0,"allowPrivilegeEscalation":true,"readOnlyRootFilesystem":false}}]'

kubectl -n "$AUTHENTIK_NAMESPACE" rollout status deployment/authentik-worker --timeout=300s

kubectl exec -it -n "$AUTHENTIK_NAMESPACE" $(kubectl get po -n "$AUTHENTIK_NAMESPACE" -l app.kubernetes.io/component=worker,app.kubernetes.io/instance=authentik | tail -1| awk '{print $1}') -c worker -- bash
```

Once done, execute the following inside the worker shell:

```sh
apt update && apt install -y nano git curl

curl --retry-all-errors -L https://gist.githubusercontent.com/leopoldhub/75e243b53d13d3e3ab4c11f552737aa9/raw/13bb15d0d9e5a97e334817e336925c85b9151295/fix.patch | git apply --check

ak export_blueprint
```

If you want to apply everything in a single command:

```sh
AUTHENTIK_NAMESPACE=auth kubectl -n "$AUTHENTIK_NAMESPACE" patch deployment authentik-worker --type=json -p '[{"op":"replace","path":"/spec/template/spec/containers/0/securityContext","value":{"runAsUser":0,"allowPrivilegeEscalation":true,"readOnlyRootFilesystem":false}}]' && kubectl -n "$AUTHENTIK_NAMESPACE" rollout status deployment/authentik-worker --timeout=300s && kubectl exec -it -n "$AUTHENTIK_NAMESPACE" $(kubectl get po -n "$AUTHENTIK_NAMESPACE" -l app.kubernetes.io/component=worker,app.kubernetes.io/instance=authentik | tail -1| awk '{print $1}') -c worker -- bash -c "apt update -y && apt install -y nano git curl && curl --retry-all-errors -L https://gist.githubusercontent.com/leopoldhub/75e243b53d13d3e3ab4c11f552737aa9/raw/13bb15d0d9e5a97e334817e336925c85b9151295/fix.patch | git apply && ak export_blueprint && bash"
```

**⚠️ Please patch the worker back to its original state when finished!**

```
kubectl -n "$AUTHENTIK_NAMESPACE" patch deployment authentik-worker --type=json -p '[{"op":"remove","path":"/spec/template/spec/containers/0/securityContext"}]'
```

**Comment by dragonfleas** [comment]
Might be a good idea to just get that working PR merged in, someone should fork the pull request branch and add some tests to it and push that up as a replacement for #9930

**Comment by leopoldhub** [comment]
@dragonfleas yes, this would be the best fix, but it seems that there is a bunch of unit test, and I sadly do not have the time to make sure everything meets requirements and see the PR through.

The above manipulation is here as a "one-time" quick dirty fix to ensure you can export your blueprints in the meantime.

If someone wants to do it, feel free to update the #9930 dev branch to HEAD (resolve simple conflicts) and open a new PR.

**Comment by dragonfleas** [comment]
I'll take it on this afternoon, haven't touched python in a long time but I'm sure I can hack it. I feel it's fairly obvious what the test cases should be from the behavior added.

**Comment by PeshekDotDev** [comment]
I believe I have found the cause of this and have made a PR. I can also provide a temporary fix:

Cause:
Any flow that uses the consent stage (OIDC/SAML providers set with explicit consent set) creates a UserConsent object containing a ReturnList that doesn't get converted during `ak export_blueprint`

Temporary fix:
1. Change the provider to implicit consent
2. Delete the application (NOT provider)
3. Create a new application (same name is fine) and connect the old provider

Your blueprint export will work fine after those steps

If anyone has this problem without explicit consent set, please let me know
