### ISSUE TITLE
GET /api/v3/flows/executor/default-authentication-flow/

### ISSUE THREAD

**Issue by stonecoldant316** [goauthentik/authentik#9469]
**Describe the bug**
unable to access login page after upgrade to 2024.4

**To Reproduce**
open browser to internal ip of server

**Expected behavior**
a login page should be presented

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/82961591/4f991fc8-a291-474e-96cc-3e2bf14eb31a)

**Logs**
<details>
    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
  File "/authentik/flows/views/executor.py", line 290, in get
    stage_response = self.current_stage_view.dispatch(request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/flows/stage.py", line 95, in get
    challenge = self._get_challenge(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/flows/stage.py", line 172, in _get_challenge
    challenge = self.get_challenge(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/identification/stage.py", line 243, in get_challenge
    source_challenge.is_valid()
  File "/ak-root/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 220, in is_valid
    assert hasattr(self, 'initial_data'), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
builtins.AssertionError: Cannot call `.is_valid()` as no `data=` keyword argument was passed when instantiating the serializer instance.
```
</details>

**Version and Deployment (please complete the following information):**
- authentik version: 2024.4.0
- Deployment: [e.g. docker-compose, helm]
- docker through unraid

**Additional context**
restoring to previous version via zfs snapshot is the current workaround

**Comment by BeryJu** [comment]
https://github.com/goauthentik/authentik/issues/9408#issuecomment-2076818201
