### ISSUE TITLE
prowlarr with authentik my other *arr can't contact the indexers

### ISSUE THREAD

**Issue by AblabiX** [goauthentik/authentik#9567]
**Describe the bug**
When I try to put the Prowlarr application in basic auth with Authentik, the other *arr applications can't reach Prowlarr anymore.

**To Reproduce**
To reproduce the error, put all *arr applications, including Prowlarr, in basic auth. When I put in basic auth or external, in indexer tests, it shows 'Prowlarr URL is invalid,' and 'Lidarr cannot connect to Prowlarr' like if the site definition is incorrect

**Logs**

**Prowlarr**

2024-05-04 10:04:56.1|Info|Auth|Auth-Success ip ******** username '*********'
2024-05-04 10:05:12.0|Warn|HttpClient|HTTP Error - Res: HTTP/2.0 [POST] https://lidarr**********/api/v1/indexer/test: 400.BadRequest (167 bytes)
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "Unable to connect to indexer, check the log for more details",
    "severity": "error"
  }
]
2024-05-04 10:05:12.0|Warn|Lidarr|Prowlarr URL is invalid

[v1.16.2.4435] NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [POST] at [https://lidarr*********/api/v1/indexer/test]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 128
   at NzbDrone.Common.Http.HttpClient.Post(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 423
   at NzbDrone.Core.Applications.Lidarr.LidarrV1Proxy.TestConnection(LidarrIndexer indexer, LidarrSettings settings) in ./Prowlarr.Core/Applications/Lidarr/LidarrV1Proxy.cs:line 131
   at NzbDrone.Core.Applications.Lidarr.Lidarr.Test() in ./Prowlarr.Core/Applications/Lidarr/Lidarr.cs:line 54
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "Unable to connect to indexer, check the log for more details",
    "severity": "error"
  }
]

2024-05-04 10:05:12.1|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- ProwlarrUrl: Prowlarr URL is invalid, Lidarr cannot connect to Prowlarr

**lidarr**

2024-05-04 10:01:28.0|Info|Auth|Auth-Success ip ********** username '*********'
2024-05-04 10:05:11.9|Warn|Newznab|Unable to connect to indexer

[v2.2.5.4141] System.Xml.XmlException: '>' is an unexpected token. The expected token is '='. Line 42, position 90.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(XmlReader reader)
   at NzbDrone.Core.Indexers.RssParser.LoadXmlDocument(IndexerResponse indexerResponse) in ./Lidarr.Core/Indexers/RssParser.cs:line 103
   at NzbDrone.Core.Indexers.Newznab.NewznabRssParser.PreProcess(IndexerResponse indexerResponse) in ./Lidarr.Core/Indexers/Newznab/NewznabRssParser.cs:line 61
   at NzbDrone.Core.Indexers.RssParser.ParseResponse(IndexerResponse indexerResponse) in ./Lidarr.Core/Indexers/RssParser.cs:line 56
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Lidarr.Core/Indexers/HttpIndexerBase.cs:line 288
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Lidarr.Core/Indexers/HttpIndexerBase.cs:line 332
RequestUri: https://authentik.***************/if/flow/default-authentication-flow/?next=%2Fapplication%2Fo%2Fauthorize%2F%3Fclient_id%************j%26redirect_uri%3Dhttps%253A%252F%252Fprowlarr.***********%252Foutpost.goauthentik.io%252Fcallback%253FX-authentik-auth-callback%253Dtrue%26response_type%3Dcode%26scope%3Dprofile%2Bemail%2Bopenid%2Bak_proxy%26state%3D*************************;StatusCode: OK;ContentType: text/html; charset=utf-8;ContentLength: 2993;ContentSample: 

<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <title>authentik</title>
        <link rel="icon" href="/static/dist/assets/icons/icon.png">
        <link rel="shortcut icon" href="/static/dist/assets/icons/icon.png">
        

        
<link rel="prefetch" href="/static/dist/assets/images/flow_background.jpg" />

<script>
    window.authentik = {
        locale: "en-us",
        config: JSON.parse('{\u0022error_reporting\u0022: {\u0022enabled\u0022: true, \u0022sentry_dsn\u0022: \u0022https://151ba72610234c4c97c5bcff4e1cffd8@authentik.error\u002Dreporting.a7k.io/4504163677503489\u0022, \u0022environment\u0022: \u0022customer\u0022, \u0022send_pii\u0022: false, \u0022traces_sample_rate\u0022: 0.1}, \u0022capabilities\u0022: [\u0022can_save_media\u0022, \u0022can_asn\u0022, \u0022can_geo_ip\u0022, \u0022can_impersonate\u0022, \u0022is_enterprise\u0022], \u0022cache_timeout\u0022: 300, \u0022cache_timeout_flows\u0022: 300, \u0022cache_timeout_policies\u0022: 300, \u0022cache_timeout_reputation\u0022: 300}'),
        brand: JSON.parse('{\u0022matched_domain\u0022: \u0022authentik\u002Ddefault\u0022, \u0022branding_title\u0022: \u0022authentik\u0022, \u0022branding_logo\u0022: \u0022/static/dist/assets/icons/icon_left_brand.svg\u0022, \u0022branding_favicon\u0022: \u0022/static/dist/assets/icons/icon.png\u0022, \u0022ui_footer_links\u0022: [], \u0022ui_theme\u0022: \u0022automatic\u0022, \u0022flow_authentication\u0022: \u0022default\u002Dauthentication\u002Dflow\u0022, \u0022flow_invalidation\u0022: \u0022default\u002Dinvalidation\u002Dflow\u0022, \u0022flow_user_settings\u0022: \u0022default\u002Duser\u002Dsettings\u002Dflow\u0022, \u0022default_locale\u0022: \u0022\u0022}'),
        versionFamily: "2024.4",
        versionSubdomain: "version-2024-4",
        build: "",
    };
    window.addEventListener("DOMContentLoaded", () => {
        
    });
</script>

<script>
window.authentik.flow = {
    "layout": "stacked",
};
</script>

        <link rel="stylesheet" type="text/css" href="/static/dist/authentik.css">
        <link rel="stylesheet" type="text/css" href="/static/dist/custom.css" data-inject>
        <script src="/static/dist/poly.js?version=2024.4.1" type="module"></script>
        <script src="/static/dist/standalone/loading/index.js?version=2024.4.1" type="module"></script>
        
<script src="/static/dist/flow/FlowInterface.js?version=2024.4.1" type="module"></script>
<style>
:root {
    --ak-flow-background: url("/static/dist/assets/images/flow_background.jpg");
}
</style>

        <meta name="sentry-trace" content="ea65b90ecd28449e9b9751a0be277138-9451b92eb577bd61-1" />
    </head>
    <body>
        
<ak-message-container></ak-message-container>
<ak-flow-executor flowSlug="default-authentication-flow">
    <ak-loading></ak-loading>
</ak-flow-executor>

        
        
    </body>
</html>

2024-05-04 10:05:12.0|Warn|LidarrErrorPipeline|FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details

[v2.2.5.4141] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
   at Lidarr.Api.V1.ProviderControllerBase`4.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in ./Lidarr.Api.V1/ProviderControllerBase.cs:line 276
   at Lidarr.Api.V1.ProviderControllerBase`4.Test(TProviderDefinition definition, Boolean includeWarnings) in ./Lidarr.Api.V1/ProviderControllerBase.cs:line 267
   at Lidarr.Api.V1.ProviderControllerBase`4.Test(TProviderResource providerResource) in ./Lidarr.Api.V1/ProviderControllerBase.cs:line 212
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Lidarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Lidarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Lidarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Lidarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Lidarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Lidarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

**Version and Deployment:**

-   authentik version: [2024.4.1]
-   Deployment: docker-compose
-  Traefik v3.0

**Additional info**
Middleware in use

    middleware-authentik:
      forwardAuth:
        address: "http://****************/outpost.goauthentik.io/auth/traefik"
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version
          - authorization

**Comment by hwwilliams** [comment]
@AblabiX what was the fix for this?

**Comment by AblabiX** [comment]
> [@AblabiX](https://github.com/AblabiX) what was the fix for this?

I’ve configured the paths under _authenticated paths_ in app provider on authentik
