### ISSUE TITLE
OIDC Error - POST default-provider-authorization-explicit-consent -  duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by masterwishx** [goauthentik/authentik#9780]
**Describe the bug**
When trying to auth headscale /tailscale client by OIDC have error ::
 duplicate key value violates unique constraint

**To Reproduce**
1. `tailscale up --login-server https://headscale.mysite.com`
2. open in chrome browser :  `https://headscale.mysite.com/oidc/register/mkey:xxxxxxxxxxxxxxxxxxxxxx`
3. got error

**Screenshots**

![image](https://github.com/goauthentik/authentik/assets/28630321/a7245cbc-1eb9-47f9-8dc3-9f450d3986bd)

![image](https://github.com/goauthentik/authentik/assets/28630321/c3917eb9-cbef-4f37-a03d-90a491191149)

![image](https://github.com/goauthentik/authentik/assets/28630321/899d4992-bc7d-42a4-b17d-526d16f8993a)

**Logs**
<details>
    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
  File "/authentik/flows/views/executor.py", line 341, in post
    stage_response = self.current_stage_view.dispatch(request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/flows/stage.py", line 145, in post
    return self.challenge_valid(challenge)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/consent/stage.py", line 148, in challenge_valid
    consent.save()
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "/ak-root/venv/lib/python3.12/site-packages/sentry_sdk/integrations/django/__init__.py", line 644, in execute
    result = real_execute(self, sql, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "authentik_stages_consent_user_id_application_id_p_e44c6458_uniq"
DETAIL:  Key (user_id, application_id, permissions)=(1, 8399ec93-xxx-xxx-xxx-ea7, ak_proxy email openid profile) already exists.
```
</details>

**Version and Deployment (please complete the following information):**
- authentik version: 2024.4.2
- Deployment: [docker-compose in Ubuntu server in oracle vps]

**Additional context**
Also tryed reauth ,same error

** Config from headscale**

`oidc:
  only_start_if_oidc_is_available: true
  issuer: "https://auth.mysite.com/application/o/headscale/"
  client_id: "xxxxxxxxxxxx"
  client_secret: "xxxxxxxxxxxxxxxxxxxx"
  expiry: 180d
  scope: ["openid", "profile", "email"]
  allowed_groups:
    - headscale Users

`

**Comment by masterwishx** [comment]
Strange but after a couple of times got error ,even redirect to matomo.mysite.com after two days at end got connected ...

**Comment by masterwishx** [comment]
again have this error for new connection

**Comment by masterwishx** [comment]
after changed to default-provider-authorization-implicit-consent it seems fixed the issue
