### ISSUE TITLE
Creating application or provider via core API causes validation errors

### ISSUE THREAD

**Issue by cadeParade** [goauthentik/authentik#9787]
**Describe the bug**
I am trying to set up a clean authentik install with a script in my FastAPI app, including an application and an oauth2/OIDC provider. I am using [authentik-client](https://pypi.org/project/authentik-client/). 
So I need to create both an application and a provider object, but creating either one causes validation errors. It seems like the create call does work, ultimately, but the terminal output shows errors and I'm not sure it should. Additionally, the properties it complains about are not listed as required (or even mentioned at all?) on the core API doc pages ([application](https://docs.goauthentik.io/developer-docs/api/reference/core-applications-create) and [provider](https://docs.goauthentik.io/developer-docs/api/reference/providers-oauth-2-create))

**To Reproduce**

I run this:
```
    import authentik_client
    from authentik_client.rest import ApiException

    authentik_admin_access_token = settings.AUTHENTIK_BOOTSTRAP_TOKEN
    authentik_configuration = authentik_client.Configuration(
        host="http://localhost:9000/api/v3",
        access_token=authentik_admin_access_token,
    )

    with authentik_client.ApiClient(authentik_configuration) as api_client:
        application_api_instance = authentik_client.CoreApi(api_client)
        try:
            application_data = {
                "name": "Foo",
                "slug": "foo",
                "meta_launch_url": "http://127.0.0.1:3000",
            }
            api_application_response = application_api_instance.core_applications_create(
                application_data
            )
            print("The response of ApplicationsAPI->core_applications_create:\n")
            pprint(api_application_response)
            return api_application_response
        except ApiException as e:
            print("Exception when calling ApplicationsAPI->core_applications_create: %s\n" % e)
```
I get 

`pydantic_core._pydantic_core.ValidationError: 1 validation error for Application provider_obj  Input should be a valid dictionary or instance of Provider [type=model_type, input_value=None, input_type=NoneType]    For further information visit https://errors.pydantic.dev/2.7/v/model_type`
<details>

<summary>
Stack trace
</summary>

```
Traceback (most recent call last):
  File "/Users/lc/projects/foo/api/bin/first_time_setup", line 38, in <module>
    setup_authentik.do_it()
  File "/Users/lc/projects/foo/api/bin/setup_authentik.py", line 43, in do_it
    create_foo_application()
  File "/Users/lc/projects/foo/api/bin/setup_authentik.py", line 56, in create_foo_application
    api_application_response = application_api_instance.core_applications_create(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lc/projects/foo/api/.venv/lib/python3.12/site-packages/pydantic/validate_call_decorator.py", line 59, in wrapper_function
    return validate_call_wrapper(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lc/projects/foo/api/.venv/lib/python3.12/site-packages/pydantic/_internal/_validate_call.py", line 81, in __call__
    res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lc/projects/foo/api/.venv/lib/python3.12/site-packages/authentik_client/api/core_api.py", line 428, in core_applications_create
    return self.api_client.response_deserialize(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lc/projects/foo/api/.venv/lib/python3.12/site-packages/authentik_client/api_client.py", line 316, in response_deserialize
    return_data = self.deserialize(response_text, response_type)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lc/projects/foo/api/.venv/lib/python3.12/site-packages/authentik_client/api_client.py", line 392, in deserialize
    return self.__deserialize(data, response_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lc/projects/foo/api/.venv/lib/python3.12/site-packages/authentik_client/api_client.py", line 439, in __deserialize
    return self.__deserialize_model(data, klass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lc/projects/foo/api/.venv/lib/python3.12/site-packages/authentik_client/api_client.py", line 761, in __deserialize_model
    return klass.from_dict(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lc/projects/foo/api/.venv/lib/python3.12/site-packages/authentik_client/models/application.py", line 148, in from_dict
    _obj = cls.model_validate({
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/lc/projects/foo/api/.venv/lib/python3.12/site-packages/pydantic/main.py", line 551, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Application
provider_obj
  Input should be a valid dictionary or instance of Provider [type=model_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.7/v/model_type
```

</details>

Ok fine so maybe I need a provider first. So I run (after deleting the application): 
```
    with authentik_client.ApiClient(authentik_configuration) as api_client:
        provider_api_instance = authentik_client.ProvidersApi(api_client)
        flows_api_instance = authentik_client.FlowsApi(api_client)

        try:
            authorization_flow = flows_api_instance.flows_instances_retrieve(
                "default-provider-authorization-implicit-consent"
            )
            authetication_flow = flows_api_instance.flows_instances_retrieve(
                "default-authentication-flow"
            )
            provider_data = {
                "name": "FooProvider",
                "authorization_flow": authorization_flow.pk,
                "authentication_flow": authetication_flow.pk,
                "client_id": "authentik_client_id2",
                "client_secret": "authentik_client_secret",
                "redirect_uris": "http://127.0.0.1:9090/auth/authentik/callback",
                "assigned_application_slug": "foo",
                "assigned_application_name": "Foo",
                "assigned_backchannel_application_slug": "foo",
                "assigned_backchannel_application_name": "foo",
            }

            api_provider_response = provider_api_instance.providers_oauth2_create(provider_data)
            print("The response of ProvidersApi->core_providers_create:\n")
            pprint(api_provider_response)
            return api_provider_response
        except ApiException as e:
            print("Exception when calling ProvidersApi->core_providers_create: %s\n" % e)
```
And again I get validation errors: 
```
pydantic_core._pydantic_core.ValidationError: 4 validation errors for OAuth2Provider
assigned_application_slug
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.7/v/string_type
assigned_application_name
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.7/v/string_type
assigned_backchannel_application_slug
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.7/v/string_type
assigned_backchannel_application_name
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.7/v/string_type
```

First of all -- all the validation error properties have a string provided, so I'm pretty confused about this error. Second, none of these properties are mentioned in the request_body section of the [`providers_oauth2_create` documentation](https://docs.goauthentik.io/developer-docs/api/reference/providers-oauth-2-create).

It seems like there are two issues:
1. Some type validation is acting weird or incorrect -- I am providing strings for properties but it is saying it is wrong because it expects a string
2. Creating a provider requires an application. Creating an application requires a provider. So I can't create either.

**Expected behavior**
Ability to create an application or a provider.

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.4.2.post1715271061
-   Deployment: docker-compose

Thanks for any advice or help!

**Comment by BeryJu** [comment]
The intended use for the generated API client would be using this
```python
from authentik_client.models.application import Application
from authentik_client.models.o_auth2_provider import OAuth2Provider

Application()
```

instead of just passing a dictionary to the API calls

**Comment by cadeParade** [comment]
Thanks for your reply. I have been continuing to run into this problem after using `authentik_client` provided models. I think I have narrowed down the problem.
When I create an OAuth Provider via the API, it throws validation errors for `assigned_application_slug`, `assigned_application_name`, `assigned_backchannel_application_slug`, `assigned_backchannel_application_name`. 

I am using [this package](https://pypi.org/project/authentik-client/), as linked from the [authentik documentation](https://docs.goauthentik.io/developer-docs/api/clients). FYI, the links to the documentation on the pypi page go to 404s (ex: https://pypi.org/project/authentik-client/docs/ProvidersApi.md#providers_oauth2_create). I cannot find a python version of `authentik_client` open source on github, although maybe it is all generated [by this schema.yml](https://github.com/goauthentik/authentik/blob/main/schema.yml)?)

To create a new provider, we call: `provider_api_instance.providers_oauth2_create([some data])`.

`providers_oauth2_create` expects an argument of type `OAuth2ProviderRequest` ([maybe defined here](https://github.com/goauthentik/authentik/blob/main/schema.yml#L18105-L18113)).

An `OAuth2ProviderRequest` has [these properties](https://github.com/goauthentik/authentik/blob/main/schema.yml#L38866-L38947), which does _not_ include `assigned_application_slug`, `assigned_application_name`, `assigned_backchannel_application_slug`, `assigned_backchannel_application_name`. 
So to me, it seems impossible to send the properties it is expecting since even if you put the `assigned_application_slug` etc in the data object to construct `OAuth2ProviderRequest`,  properties that aren't in the `OAuth2ProviderRequest` schema are ignored.

Please let me know if I am misunderstanding something and how I can successfully create an OAuth provider with `authentik-client`

Here is the actual code I am using if it helpful:
<details>

<summary>expand...</summary>

```
    with ApiClient(authentik_configuration) as api_client:
        provider_api_instance = ProvidersApi(api_client)
        flows_api_instance = FlowsApi(api_client)
        property_mappings_api_instance = PropertymappingsApi(api_client)

        try:
            print("[authentik_setup] Creating oauth provider...")
            authorization_flow = flows_api_instance.flows_instances_retrieve(
                "default-provider-authorization-implicit-consent"
            )
            authetication_flow = flows_api_instance.flows_instances_retrieve(
                "default-authentication-flow"
            )

            mappings = property_mappings_api_instance.propertymappings_scope_list()
            scope_mappings = [
                mapping.pk
                for mapping in mappings.results
                if mapping.managed
                in [
                    "goauthentik.io/providers/oauth2/scope-openid",
                    "goauthentik.io/providers/oauth2/scope-profile",
                    "goauthentik.io/providers/oauth2/scope-email",
                ]
            ]

            provider_data = {
                "name": PROVIDER_NAME,
                "authorization_flow": authorization_flow.pk,
                "authentication_flow": authetication_flow.pk,
                "client_id": settings.AUTHENTIK_CLIENT_ID,
                "client_secret": settings.AUTHENTIK_CLIENT_SECRET,
                "redirect_uris": "http://127.0.0.1:9090/auth/authentik/callback",
                "property_mappings": scope_mappings,
            }

            provider_request = OAuth2ProviderRequest.model_construct(**provider_data)
            api_provider_response = provider_api_instance.providers_oauth2_create(provider_request)
```

</details>

**Comment by BeryJu** [comment]
The `assigned_*` properties are read_only and are mainly used by the frontend when the provider is connected with an application. In the backend this is defined correctly (and in theory so is it in the schema), however some client generators don't interpret this correctly

The python client is indeed generated from that schema (https://github.com/goauthentik/authentik/blob/main/.github/workflows/api-py-publish.yml) hence there currently isn't a source for it available. 

Which line exactly is throwing the exception you posted above?

**Comment by ekoyle** [comment]
The [generated API docs](https://docs.goauthentik.io/developer-docs/api/reference/providers-saml-create) show `assigned_application_name`, `assigned_application_slug`, etc as "required" in the response, so I think the problem may actually be with the `schema.yml` file (or whatever generates it) rather than the openapi generator.

**Comment by ekoyle** [comment]
For reference, adding `nullable` to these fields in `schema.yml` and regenerating the python client bindings was enough to get past this (not sure whether that is correct, I didn't look at the returned json to determine whether these were actually null values or just not present):

```
diff --git a/schema.yml b/schema.yml
index baa970150..8b301609b 100644
--- a/schema.yml
+++ b/schema.yml
@@ -45767,18 +45767,22 @@ components:
         assigned_application_slug:
           type: string
           description: Internal application name, used in URLs.
+          nullable: true
           readOnly: true
         assigned_application_name:
           type: string
           description: Application's display Name.
+          nullable: true
           readOnly: true
         assigned_backchannel_application_slug:
           type: string
           description: Internal application name, used in URLs.
+          nullable: true
           readOnly: true
         assigned_backchannel_application_name:
           type: string
           description: Application's display Name.
+          nullable: true
           readOnly: true
         verbose_name:
           type: string
```

**Comment by ekoyle** [comment]
I am also seeing similar issues trying to create a provider via the API.

It looks like DRF doesn't honor `required=False` for `ReadOnlyField`s. Even though these fields have `required=False` in their ModelSerializer class, they are still showing up under the `required:` field list for the response object in `schema.yml` . There was a similar problem with `allow_null` which appears to have been resolved by https://github.com/encode/django-rest-framework/pull/8536 . It doesn't seem like adding `"required": False` for the field in extra_kwargs  in the serializer Meta makes any difference on these. I think changes may be needed in DRF for `required` so that drf_spectacular gets the metadata it needs.

A possible workaround would be to set `allow_null=True` for these fields. That solves the python openapi binding issue, at least (not sure whether other libraries/bindings validate the responses the same way... it still seems like having the field not be required in the spec would be ideal).

See also: https://github.com/tfranzel/drf-spectacular/issues/383

**Comment by mpaxson** [comment]
Can we bump this

**Comment by txj-xyz** [comment]
following for updates

**Comment by dtomasi** [comment]
Any update on this?
It seems to not be possible to get even a list of providers in ´2025.2.1.post1740858304´

> pydantic_core._pydantic_core.ValidationError: 4 validation errors for ProxyProvider
assigned_application_slug
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
assigned_application_name
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
assigned_backchannel_application_slug
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
assigned_backchannel_application_name
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type

>   File "/app/packages/automation/common/helper/authentik.py", line 274, in create_or_update_proxy_provider
    api_response = providers_api.providers_proxy_list(name__iexact=provider_request.name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/pydantic/_internal/_validate_call.py", line 38, in wrapper_function
    return wrapper(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/pydantic/_internal/_validate_call.py", line 111, in __call__
    res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/authentik_client/api/providers_api.py", line 17966, in providers_proxy_list
    return self.api_client.response_deserialize(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/authentik_client/api_client.py", line 316, in response_deserialize
    return_data = self.deserialize(response_text, response_type)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/authentik_client/api_client.py", line 392, in deserialize
    return self.__deserialize(data, response_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/authentik_client/api_client.py", line 437, in __deserialize
    return self.__deserialize_model(data, klass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/authentik_client/api_client.py", line 759, in __deserialize_model
    return klass.from_dict(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/authentik_client/models/paginated_proxy_provider_list.py", line 98, in from_dict
    "results": [ProxyProvider.from_dict(_item) for _item in obj["results"]] if obj.get("results") is not None else None
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/authentik_client/models/proxy_provider.py", line 157, in from_dict
    _obj = cls.model_validate({
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/pydantic/main.py", line 627, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by sclu1034** [comment]
The issue is still relevant. I'm trying to start using the Python package with an existing Authentik installation.

Attempting to call `CoreApi.core_applications_retrieve(slug)` fails when retrieving the connected provider:

```
pydantic_core._pydantic_core.ValidationError: 2 validation errors for Provider
assigned_backchannel_application_slug
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/string_type
assigned_backchannel_application_name
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/string_type
```

I can verify via cURL that these two fields are indeed _not_ returned when retrieving the corresponding provider, despite the [docs](https://api.goauthentik.io/reference/providers-oauth-2-retrieve/) claiming that they are required and supposedly returned.

**Comment by poodle64** [comment]
Confirming this still applies on Authentik **2026.2.2**. The same `ReadOnlyField` + `required` mismatch surfaces on a wider set of fields than what the original report covers, so noting them here for anyone else hitting validation errors against the generated client.

Read-only fields the API can return as `null` but the schema marks `required` (and does not mark `nullable: true`):

- `Application.provider_obj`
- `Application.launch_url`
- `Outpost.service_connection_obj`
- `Group.users_obj`, `Group.roles_obj`
- `PolicyBinding.policy_obj`, `PolicyBinding.group_obj`, `PolicyBinding.user_obj`
- `OAuth2Provider` (and other provider variants): `assigned_application_slug`, `assigned_application_name`

Some related fields *have* been corrected since the original report (e.g. `assigned_backchannel_application_slug`/`_name` and `Application.meta_icon` are now `nullable: true` in 2026.2.2), so the fix pattern is clearly understood; it just hasn't been applied to all of the affected serializers yet.

As @ekoyle noted [above](https://github.com/goauthentik/authentik/issues/9787#issuecomment-2197234262), DRF doesn't honour `required=False` for `ReadOnlyField`, so the fix needs to set `allow_null=True` on the serializer field (or the equivalent in `extend_schema_field`) rather than rely on `required`.

Happy to open a PR if it would help.
