### ISSUE TITLE
Error sending recovery link via Mail von Display Name has "," in it

### ISSUE THREAD

**Issue by d-schiffner** [goauthentik/authentik#9996]
**Describe the bug**
Trying to send a password recovery mail to a user. The django mailer seems to only expect plain emails, but gets fully qualified ones instead.

**To Reproduce**
1. User clicks on password-recovery / Go into admin overview -> click "Email recovery"
2. Go to Logs

**Expected behavior**
The mail is being sent successfully

**Logs**
<details>
    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
  File "/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/celery/app/autoretry.py", line 38, in run
    return task._orig_run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/email/tasks.py", line 89, in send_mail
    backend.send_messages([message_object])
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/mail/backends/smtp.py", line 136, in send_messages
    sent = self._send(message)
           ^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/mail/backends/smtp.py", line 151, in _send
    sanitize_address(addr, encoding) for addr in email_message.recipients()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/mail/message.py", line 92, in sanitize_address
    raise ValueError(
builtins.ValueError: Invalid address; only <surname> could be parsed from "<surname>, <givenname> <redacted@mail.com>"
```
</details>

**Version and Deployment (please complete the following information):**
- authentik version: 2024.4.2
- Deployment: [e.g. docker-compose, helm]

**Comment by d-schiffner** [comment]
I shortly checked with python3.12:

```
>>> parser.get_mailbox('Surname, Givenname <mailbox@mail.com>')
(Mailbox([AddrSpec([LocalPart([DotAtom([DotAtomText([ValueTerminal('Surname')])])])])]), ', Givenname <mailbox@mail.com>')
>>> parser.get_mailbox('"Surname, Givenname" <mailbox@mail.com>')
(Mailbox([NameAddr([DisplayName([QuotedString([BareQuotedString([ValueTerminal('Surname,'), WhiteSpaceTerminal(' '), ValueTerminal('Givenname')]), CFWSList([WhiteSpaceTerminal(' ')])])]), AngleAddr([ValueTerminal('<'), AddrSpec([LocalPart([DotAtom([DotAtomText([ValueTerminal('mailbox')])])]), ValueTerminal('@'), Domain([DotAtom([DotAtomText([ValueTerminal('mail'), ValueTerminal('.'), ValueTerminal('com')])])])]), ValueTerminal('>')])])]), '')
```

I found the source here:

https://github.com/goauthentik/authentik/blob/main/authentik/stages/email/utils.py#L37

If source line is replaced with the according quotes, the problem should be fixed
