### ISSUE TITLE
Error During Example Enrollment Flow

### ISSUE THREAD

**Issue by dylanjamesdev** [goauthentik/authentik#9997]
**Describe the bug**
Register flow is not working as expected-- was working previously.

**To Reproduce**
Create flow
Collect Name, Username, Email, Password
Step: default-enrollment-user-write
Step: default-enrollment-user-login

**Expected behavior**
The user is registered and logged in.

**Inspector**
https://i.imgur.com/UAdju7A.png

**Used flow**
https://files.catbox.moe/eaa6k1.yaml (I also tried to use the example register flow on the Authentik website, it has the same outcome. The same stages are used in mine, in addition to the same fields that we collect data from)

**Logs**
Why is there LDAP errors? This should be creating the user within Authentik...?

<details>
    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
  File "/authentik/flows/views/executor.py", line 341, in post
    stage_response = self.current_stage_view.dispatch(request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/flows/stage.py", line 108, in post
    valid = challenge.is_valid()
            ^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/prompt/stage.py", line 174, in password_single_clean
    password_validate.send(sender=self, password=value, plan_context=self.plan.context)
  File "/ak-root/venv/lib/python3.12/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/sources/ldap/signals.py", line 49, in ldap_password_validate
    changer = LDAPPasswordChanger(source)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/sources/ldap/password.py", line 55, in __init__
    self._connection = source.connection()
                       ^^^^^^^^^^^^^^^^^^^
  File "/authentik/sources/ldap/models.py", line 188, in connection
    successful = conn.bind()
                 ^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/ldap3/core/connection.py", line 607, in bind
    response = self.post_send_single_response(self.send('bindRequest', request, controls))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/ldap3/strategy/sync.py", line 160, in post_send_single_response
    responses, result = self.get_response(message_id)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/ldap3/strategy/base.py", line 403, in get_response
    raise LDAPOperationResult(result=result['result'], description=result['description'], dn=result['dn'], message=result['message'], response_type=result['type'])
ldap3.core.exceptions.LDAPInvalidCredentialsResult: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - None - bindResponse - None
```
</details>

**Version and Deployment (please complete the following information):**
- authentik version: 2024.4.2
- Deployment: [e.g. docker-compose, helm]

**Additional context**

**Comment by aaw3** [comment]
You are getting an LDAP error that prevents enrollment due to having an LDAP source with writebacks that is having errors. Either fix the issues of the LDAP Source, disable writebacks or delete the source.
I had the same issues with the LDAP Source disabled and I am currently trying to get a PR merged to fix that issue.
